### PR TITLE
CI: configure Coverity Scan with debug flag

### PR DESCRIPTION
**Pull request by nilason**
Configure and build for Coverity Scan with debug flag set. Also run `cov-build` directly with `make` as argument.

In addition some style fixes to pass pre-commit.

Attempt to fix (still broken?) Coverity Scan.

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
I'll let you see if the scans work as expected

**Comment by nilason** [comment]
Now we’ll see…

**Comment by nilason** [comment]
Appears to work fine:

```
GRASS GIS 8.4.0dev afce9ea compilation log
--------------------------------------------------
Started compilation: Wed Apr 10 05:51:50 UTC 2024
--
Errors in:
No errors detected.
--
Finished compilation: Wed Apr 10 05:58:49 UTC 2024
Emitted 2551 C/C++ compilation units (100%) successfully

2551 C/C++ compilation units (100%) are ready for analysis
The cov-build utility completed successfully.

...

100 45.0M    0   113  100 45.0M     42  17.0M  0:00:02  0:00:02 --:--:-- 17.0M
Build successfully submitted.
```

but still no update on Coverity Scan.
I tested with my fork and the analysis was ready in less than an hour, I received email and my own Coverity project was updated.
@wenzeslaus Did you receive any mail and what is there to see at scan.coverity.com?

**Comment by echoix** [comment]
I logged to the coverity account I created when I got invited to the coverity project. I do not see it either. In fact last scan in 2022.

The only thing I see is at the end of uploading the results, it mentions to make sure cov-build version matches 2023.6.2 or 2022.12.2, but at the top of the build, we have 2023.6.2 written, so they should match.

**Comment by nilason** [comment]
> but still no update on Coverity Scan. I tested with my fork and the analysis was ready in less than an hour, I received email and my own Coverity project was updated. @wenzeslaus Did you receive any mail and what is there to see at scan.coverity.com?

@wenzeslaus In case you missed this, do you have any info on why the Coverity fails?

**Comment by wenzeslaus** [comment]
> > but still no update on Coverity Scan. I tested with my fork and the analysis was ready in less than an hour, I received email and my own Coverity project was updated. @wenzeslaus Did you receive any mail and what is there to see at scan.coverity.com?
> 
> @wenzeslaus In case you missed this, do you have any info on why the Coverity fails?

Unfortunately, I don't. I just see what others (with access) see in the Coverity scan tool online. There is no log of failed uploads or anything like that. I suggested to @jadenabrams100 yesterday to create an artifact in the workflow which we can manually upload as something which can be done in the short time the team has left. @jadenabrams100 will also try to contact Coverity about that.

**Comment by nilason** [comment]
I have this working, with https://github.com/nilason/grass/commit/f01b89a488f2294c549f0e6b502ee69c9416d632 on my fork.
I disabled the cron, but that also worked. I always receive a mail when the analysis is finished.

**Comment by wenzeslaus** [comment]
@nilason I changed your role on scan.coverity.com to Maintainer/Owner (aka Admin).

In the past, the an email was triggered by a successful upload and analysis, there is no successful upload here as far as the project on the website is concerned, so no email makes sense.

**Comment by nilason** [comment]
> @nilason I changed your role on scan.coverity.com to Maintainer/Owner (aka Admin).

Thanks!

> In the past, the an email was triggered by a successful upload and analysis, there is no successful upload here as far as the project on the website is concerned, so no email makes sense.

Yes, I get an email for each successful upload (so far all of them were, so I don't know what will happen by failure).

**Comment by nilason** [comment]
> I have received an update back from an admin at Synopsys. The admin said that the fault is likely due to scanning results being over the 500MB limit, so the standard submission process won't cut it. Fortunately, @wenzeslaus and I discovered instructions for how to run automated scans for projects over 500MB. I will get to work on implementing the new method as soon as I can in addition to saving the scans as an artifact.

How do they count the size? The uploaded package is about 45 MB.
If it would help, setting cron on once-a-week could be an alternative.

**Comment by jadenabrams100** [comment]
> > I have received an update back from an admin at Synopsys. The admin said that the fault is likely due to scanning results being over the 500MB limit, so the standard submission process won't cut it. Fortunately, @wenzeslaus and I discovered instructions for how to run automated scans for projects over 500MB. I will get to work on implementing the new method as soon as I can in addition to saving the scans as an artifact.
> 
> How do they count the size? The uploaded package is about 45 MB. If it would help, setting cron on once-a-week could be an alternative.

According to the admin, they count the size as the size of the resulting `cov-int` directory.

I have completed the changes and submitted them in #3606.

**Pull request merged**
