### PR TITLE
r.to.vect: break line when value changes

### PR DESCRIPTION
**Pull request by byronbest**
https://trac.osgeo.org/grass/attachment/ticket/2649/lines.c.patch

### CODE REVIEW

**Comment by byronbest** [comment]
[wnwo.zip](https://github.com/OSGeo/grass/files/3603090/wnwo.zip)

zip of resulting kml, with and without patch. Test in 7.9-dev.
Drag them into Google Earth. Witness "missing" bit where line class changes in a diagonal segment.

Also, there is a single point line segment generated; the line actually does touch at one point, but the routine fails here with or without the patch. How do we represent "kiss"? Line length is not significant, so I'm okay leaving it for now. I styled the kml to show the problem more clearly.

**Comment by byronbest** [comment]
[wonw.zip](https://github.com/OSGeo/grass/files/3611124/wonw.zip)

This zip includes a tiny EDWG grid, with and without patch runs, with summary of results, showing without patch misclassifies segments, stretching the diagonal run when it should be two segments.

Note r.to.vect scans row by row, from bottom to top in this representation. Rotate the orientation 180, and the without patch would instead stretch the class 2 over the tiny class 1. With patch works in both cases.

**Comment by byronbest** [comment]
[path.txt](https://github.com/OSGeo/grass/files/3611213/path.txt)

ascii tiny grid ready to pass to r.to.vect for testing

**Comment by byronbest** [comment]
Test procedure: in Albers Equal Area, 500m resolution.
Without patch, line with class 2 is changed to class 1 along the diagonal run.
With patch, class 1 is exactly one 500m grid cell.
```grass
g.region -d
r.in.ascii input=path.txt output=p
g.region -a rast=p
r.to.vect -sv input=p output=p type=line
v.clean input=p type=line output=cp tool=rmline

v.out.ascii input=cp output=- format=standard type=line
```

Results in 7.4.1 (without patch)
```
L  2 1
 -2051750     1857250     
 -2054250     1859750     
 1     1         
L  11 1
 -2054250     1859750     
 -2054250     1860250     
 -2054750     1860750     
 -2054750     1861250     
 -2055250     1861750     
 -2055250     1862250     
 -2055750     1862750     
 -2055750     1863250     
 -2056250     1863750     
 -2056250     1864250     
 -2056750     1864750     
 1     2         
```

Results in 7.9.dev (with patch)
```
L  12 1
 -2052250     1857750     
 -2054250     1859750     
 -2054250     1860250     
 -2054750     1860750     
 -2054750     1861250     
 -2055250     1861750     
 -2055250     1862250     
 -2055750     1862750     
 -2055750     1863250     
 -2056250     1863750     
 -2056250     1864250     
 -2056750     1864750     
 1     2         
L  2 1
 -2051750     1857250     
 -2052250     1857750     
 1     1         
```

**Comment by neteler** [comment]
Would you mind to expand raster/r.to.vect/testsuite/test_r_to_vect.py with your test described above?

**Comment by byronbest** [comment]
bbest@stockholm-ubuntu:~/GitHub/grass/demolocation$
```
GISDBASE=`pwd` grass79 PERMANENT
GISDBASE=`pwd` grass74 PERMANENT
g.region -d
r.in.ascii input=- output=p <<++EOF++
north: 59
south: 56
east: -54
west: -63
rows: 6
cols: 9
* * * * * * * * *
* * * * * * * * *
* * * * * * 1 * *
* * * * * 1 * * *
* * * * 2 * * * *
* * * * * * * * *
++EOF++
g.region -a rast=p
r.to.vect -sv input=p output=p type=line
v.out.ascii input=p output=- format=standard type=line
g.remove -f name=p type=all
exit
```

**Comment by byronbest** [comment]
What happened to "make test"?
```
docker run -it --rm --user=$(id -u):$(id -g) --volume /tmp/:/data --env HOME=/data/ -w /code/grass grassgis79 grass /data/nc_basic_spm_grass7/PERMANENT --exec python -m grass.gunittest.main --location nc_basic_spm_grass7 --location-type nc

Executing <python -m grass.gunittest.main --location nc_basic_spm_grass7 --location-type nc> ...
/usr/bin/python: No module named six
Execution of <python -m grass.gunittest.main --location nc_basic_spm_grass7 --location-type nc> finished.
```
Over to you, Markus.

**Comment by neteler** [comment]
> What happened to "make test"?
> 
> ```
> docker run -it --rm --user=$(id -u):$(id -g) --volume /tmp/:/data --env HOME=/data/ -w /code/grass grassgis79 grass /data/nc_basic_spm_grass7/PERMANENT --exec python -m grass.gunittest.main --location nc_basic_spm_grass7 --location-type nc

Which docker image did you use? Self-built?

> Executing <python -m grass.gunittest.main --location nc_basic_spm_grass7 --location-type nc> ...
> /usr/bin/python: No module named six

^-- python3-six is missing in your docker image.

> Execution of <python -m grass.gunittest.main --location nc_basic_spm_grass7 --location-type nc> finished.
> ```
> 
> ```
> Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages
> Requirement already satisfied: six in /usr/lib/python3/dist-packages
> ```
> 
> Over to you, Markus.

I don't fully understand which image you use (and where the "Requirement already satisfied" comes from).

**Comment by neteler** [comment]
> I first reported this fix 25 years ago, only to have "original contributor" veto it -- I recall he worked for ESRI.
> I fixed it again 5 years ago. After relying on my local grass copy for decades, surprised to find nothing had been changed. Who knew?

So, time to revisit it :-)

> SO yeah, I'll look into it. Oh, the unit testing fails.
> **ERROR: Location </data/nc_spm_08_grass7> doesn't exist**
> Lovely.

Well, that error message is rather non-exhaustive... we may work better with reproducible examples.

**Comment by byronbest** [comment]
To show that I have six installed already, the test python does not
docker image is faulty
I made it according to the only instructions there are-- Readme.md
From current clone, only change is my patch!

**Comment by metzm** [comment]
I regard this PR as well tested and opt to merge it as it is.

The docker issues are not relevant for this PR.

**Comment by neteler** [comment]
Backported in 33fdda72e2d8898b085b9c14da5f4f53ac5a9ab8

**Comment by neteler** [comment]
Thanks for the r.to.vect update.

**Comment by byronbest** [comment]
Awesome! I no longer have to explain why DOE cannot use the standard
unmodified GRASS install in their analysis!
Thanks so much!

**Pull request merged**
