### PR TITLE
wxGUI: fix inconsistent layer sizes during rendering

### PR DESCRIPTION
**Pull request by petrasovaa**
Passes environment with width and height throughout the rendering process
to ensure consistent size.

Before rendering, checks already rendered layers have consistent size with
new size, if not, forces them to rerender.

After g.pnmcomp during checking vector legend changes, only render when
there is an actual vector legend overlay present.

### CODE REVIEW

**Comment by petrasovaa** [comment]
May solve #530. 
Also related to #500.

**Comment by nilason** [comment]
Great job! This solves the issue #530 on mac for me. Thanks!

**Comment by landam** [comment]
@petrasovaa Time to merge + backport?

**Comment by petrasovaa** [comment]
Well, given the imminent release of 7.8.3 I don't feel confident in backporting this, it impacts rendering and I would like to get this tested more. The bug it fixes is not very serious.

**Comment by nilason** [comment]
Maybe now is the time to throw this at master and see what comes out?
And hold on with the backport to 7.8.4.

**Pull request merged**
