### PR TITLE
wxGUI/history: enable run special command e.g. d.rast, d.vect etc., as well as from the wxGUI Console

### LINKED ISSUE #3301: [Bug] wxGUI/history: d.rast and others "special" commands runned from the History tab (page) tree, fails
**Describe the bug**
`d.rast` and others "special" commands runned from the History tab (page) tree, fails.

**To Reproduce**

1. Apply PR #3300 first, please
2. Launch wxGUI
3. Run `d.rast elevation` command from the wxGUI Console (raster map layer is displayed)
4. Switch to the History tab (page) and double click on the tree item `d.rast elevation`
5. See error

```
Neither MONITOR (managed by d.mon command)
nor GRASS_RENDER_IMMEDIATE (used for direct rendering)
defined
```

**Expected behavior**
`d.rast` and others "special" commands should be run from the History tab (page) tree, **as well as from the wxGUI Console**

**System description:**

- Operating System: all
- GRASS GIS version: 8.4.dev

```
GRASS nc_basic_spm_grass7/PERMANENT:~ > python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.11.6 (main, Dec  2 2023, 19:38:08) [GCC 13.2.1 20230826]
4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
```

### PR DESCRIPTION
**Pull request by tmszi**
Fixes #3301.

https://github.com/OSGeo/grass/assets/50632337/fd7433ed-bb15-4c78-b84f-85f7295aa808

### CODE REVIEW

**Comment by petrasovaa** [comment]
Didn't test yet, but what happens when you rerun r.mapcalc command from history?

**Comment by tmszi** [comment]
> Didn't test yet, but what happens when you rerun r.mapcalc command from history?

`r.mapcalc` use cases:

1. `r.mapcalc --overwrite expression="foo = 1"` or with expression param arg with single quotes successfully executed from the wxGUI Console and reran from the history tree (`r.mapcalc --overwrite expression="foo = 1"`), print error message **Unable to parse command 'r.mapcalc --overwrite expression="foo = 1"'**.
2. `r.mapcalc --overwrite expression="foo=1"` or with expression param arg with single quotes successfully executed from wxGUI Console and reran from the history tree (`r.mapcalc --overwrite expression="foo=1"` ), invoke `r.mapcalc` **module GUI** dialog but expression param arg contains double or single quotes and run module GUI dialog fails with error message 
```
(Thu Dec 14 05:32:52 2023)                                                      
r.mapcalc --overwrite expression="foo=1"                                       
syntax error
Parse error
ERROR: parse error
```
3. `r.mapcalc --overwrite "foo = 1"` or with expression arg with single quotes successfully executed from the wxGUI Console and reran from the history tree (`r.mapcalc --overwrite "foo = 1"`), print error message **Unable to parse command 'r.mapcalc --overwrite "foo = 1"'**.
4. `r.mapcalc` without parameters and arguments successfully executed from wxGUI Console invoke `r.mapcalc` **wxGUI dialog** which write to the history tree following command `r.mapcalc --overwrite expression=foo = 1` and reran command from the history tree, print error message **Unable to parse command 'r.mapcalc --overwrite expression=foo1 = 1'**.

These use cases not related with PR changes.

The change concerns the display of the `r.mapcalc` dialog type either the GUI dialog module or the wxGUI dialog, if only one `r.mapcalc` command without parameters and arguments is written in the history.

**Comment by tmszi** [comment]
Issue #3304 related to execution of the `r/r3.mapcalc` module command is fixed by PR #3305.

**Review by petrasovaa — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
