### PR TITLE
v.in.ogr: Get layer name without definition initialization

### LINKED ISSUE #2738: [Bug] GRASS reads all the layers when using v.in.ogr with WFS3/OAIPIF
**Describe the bug**
I noticed that importing a layer from a WFS3/OAIPIF source using `v.in.ogr` takes more time when the server has more layers. I analyzed the network traffic and figured out that GRASS was fetching data from all the layers.
I suppose this happens because `v.in.ogr` tries to get all the schemas of the layers, and since a WFS3/OAIPIF layers has no schema (it is just a GeoJSON), GDAL tries to read some data to define a schema. The schema is used to get the name of each available layer.

https://github.com/OSGeo/grass/blob/8e2504c5888540e4e78802189b8ba49703df0bcf/vector/v.in.ogr/main.c#L653-L658

Wouldn't be more appropriate to use `OGR_L_GetName` to get the name of the layer, instead of using `OGR_L_GetLayerDefn` first and `OGR_FD_GetName` later? The layer definition is not used anywhere else.

> const char *OGR_L_GetName(OGRLayerH)
>
>    Return the layer name.
>    This returns the same content as OGR_FD_GetName(OGR_L_GetLayerDefn(hLayer)), but for a few drivers, calling OGR_L_GetName() directly can avoid lengthy layer definition initialization.

-- https://gdal.org/api/vector_c_api.html#_CPPv413OGR_L_GetName9OGRLayerH

**To Reproduce**

1. v.in.ogr gdal_doo="PAGE_SIZE=100" input="WFS3:$server" layer="$layer"
2. Look at the web server logs (or use mitmproxy to check your network traffic)

**Expected behavior**
GRASS should not flood the OGC API server with requests related to other layers.

**System description (please complete the following information):**

- Operating System: GNU/Linux, Ubuntu 20.04.5
- GRASS GIS version: 8.2.0, 7.8.5

### PR DESCRIPTION
**Pull request by frafra**
Fix #2738.

Tested. No regression found.

### CODE REVIEW

**Comment by frafra** [comment]
Is this patch eligible to be backported to `OSGeo:releasebranch_7_8`?

**Comment by frafra** [comment]
`clang-format` complained about my code style, but I was just using the previous convention. I fixed the style error.

**Comment by nilason** [comment]
> `clang-format` complained about my code style, but I was just using the previous convention. I fixed the style error.

Your changes only shortened the code, thus now fits in one line (80 col).
There is nowadays (only recently added and accompanying updated submitting guides are still missing [note to myself!]) only one formatting "convention" and that is *clang-format*.

**Comment by frafra** [comment]
> Your changes only shortened the code, thus now fits in one line (80 col). There is nowadays (only recently added and accompanying updated submitting guides are still missing [note to myself!]) only one formatting "convention" and that is _clang-format_.

Oh, right, got it, thank you :)

**Comment by nilason** [comment]
This looks like a reasonable change to me.
Considering GRASS GIS 7.8.8RC3 has been released, only breaking fixes should go to 7.8.8 at this time, this doesn't seem like such...

**Review by metzm — APPROVED** [review]
Looks good to me. This is what the GDAL API documentation actually recommends: https://gdal.org/doxygen/ogr__api_8h.html#a88facf4f8e8b32278101d52ae094255c

**Comment by nilason** [comment]
@frafra  Thanks very much!

**Pull request merged**
