### PR TITLE
raster: Fixed PEP8 - E721 for category.py

### PR DESCRIPTION
**Pull request by arohanajit**
Used `isinstance()` instead of `==` for type instance checks

### CODE REVIEW

**Review by echoix — APPROVED** [review]
You might want to look if these issues are also ignored by ruff with the following rule : https://docs.astral.sh/ruff/rules/type-comparison/

Using ruff might help you find these faster too, and then use flake8 for the exhaustive checking of the unhandled cases from ruff.

**Comment by echoix** [comment]
See here: https://github.com/echoix/grass/pull/305, there's only 23 instances of E721 detected by ruff, and you're already fixing 2 of them. Are some of them easily fixable too?

For this particular rule, they are usually quite easy to review, once the choice on whether using an `isinstance` check is appropriate vs an `is` / `is not` check.

**Comment by echoix** [comment]
@arohanajit Is there something else to do here, after verifications? Otherwise we could go forward with this one

**Comment by arohanajit** [comment]
> @arohanajit Is there something else to do here, after verifications? Otherwise we could go forward with this one

No, for the flake8 errors in this particular case there is nothing more to be done

**Pull request merged**
