### PR TITLE
CodeQL add security checks

### PR DESCRIPTION
**Pull request by naidneelttil**

### CODE REVIEW

**Comment by echoix** [comment]
I wouldn’t be closed to this though. 

I have explored it sometimes on my fork, and found interesting issues. And I started trying out running also for the JavaScript language, which includes checking for GitHub actions.
But overall it might be needed to find a good balance between time taken to check and the benefits. Maybe running the extended queries only on the scheduled runs?

**Comment by naidneelttil** [comment]
> I wouldn’t be closed to this though.
> 
> I have explored it sometimes on my fork, and found interesting issues. And I started trying out running also for the JavaScript language, which includes checking for GitHub actions. But overall it might be needed to find a good balance between time taken to check and the benefits. Maybe running the extended queries only on the scheduled runs?

that doesn't sound like a bad idea, but I was trying on my own to see what this might do to the security checks and it balloons up the amount of errors to 5,000 -- even as a one time check on scheduled runs that would be quite overwhelming, nevermind the amount of false positives to sort though. I am considering possibly replacing that with a scheduled run of the security-extended codeQL query checks, which checks for expanded security issues, which is a bit more reasonable,  however it is still quite extensive with an additional 1,200 issues. I don't want to overwhelm the developers like that, I feel like it might be reasonable to see if I can pair down obvious false positives in the security-extended queries before making the PR

**Comment by echoix** [comment]
Oh, I didn't remember that it went to that much at the time I tried it in the Christmas break, probably just with security-extended maybe. Is it C/C++ or Python that flags that much?
What I like and is tolerable with CodeQL alerts, is that they don't bother you as much with older issues, but they flag it in PRs when something new is introduced. That's a good approach.

**Comment by echoix** [comment]
In the Christmas break I tested out by clearing the config to see what the default configs were like now, about 2 years after it has started to be used here. The automatic configuration didn't work, so I still had to set up an advanced configuration for it to accept our build setup. I started from a blank config, and rebuilt the necessary changes. Then the PR was made to simplify it a bit, and is what is used now.

An exemple of what changed since, was their Python handling. They don't need as much as what was needed 2 years ago. They now default to simply not install any other dependencies.


There's also the threat model options I'd like to see one day what can come out of it. As for now, the default I think is external, assuming some things that are from the inside are correct. I'd have to learn a bit more about this concept first, and then try to find out if some parts of our software would be good candidates for inspecting it from a different threat model perspective. But it's not my domain yet, I've only finished my robotic engineering degree (mechanical, electrical, and informatic/computer science), not cybersec..

**Pull request closed without merging**
