### PR TITLE
docs: add openssf Scorecard and Best Practices Badge to README.md

### PR DESCRIPTION
**Pull request by gregorywaynepower**
image

### CODE REVIEW

**Review by neteler — APPROVED** [review]
Thanks for your contribution!

**Comment by gregorywaynepower** [comment]
Thanks for accepting it! Y'all be interested in a pull request implementing the [Open Source Security Foundation's Github Action](https://github.com/ossf/scorecard-action)?

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
Just changed the title to have it categorized in the release notes ;)

**Comment by gregorywaynepower** [comment]
Thanks @echoix for the correction!

**Comment by echoix** [comment]
And yes, I’d be glad to see a PR for this. Do you know about how much time it runs? And is it triggered on schedule, or per PR?

**Comment by gregorywaynepower** [comment]
@echoix I haven't spent time benchmarking how long it takes to run, I haven't found it to be a hassle.. The [GitHub Action](https://github.com/ossf/scorecard-action) can be set to run on a schedule and on pushes to the repo. Pull Requests are currently experimental. It provides the same checks as the CLI tool, but it also automates configuration of YML files to provide minimum permissions provided by [StepSecurity](https://www.stepsecurity.io/) which is pretty snazzy and automates a huge chunk of the Github Action configuration.

I'm currently working on this for QGIS (https://github.com/qgis/QGIS/pull/55748), once I'm done with them I'll have time to work with y'all.

**Pull request merged**
