### PR TITLE
Misleading lock symbol icon in the in the Data tab toolbar

### PR DESCRIPTION
**Pull request by lindakladivova**
**Describe the bug**

The toolbar of Data tab uses lock/unlock symbol for allowing and disallowing edits in mapsets other than the current one. However, the locking refers to something else in GRASS GIS and that it locking of mapsets by a GRASS GIS process/session. That terminology is actually in line with other software where a file is locked when used by another process or instance of the same program.

**Expected behavior**

A new icon is needed. It may have the allowed and restricted states like now or it could be just one symbol relying on the toggle state of the button to convey the change of state. A common icon for editing in GIS, including GRASS GIS, is a pen/pencil, so that's at least a good starting point.

**Suggestion:**

Editing mode allowed:

allow_edits

No edits allowed:

disallow_edits

What are your suggestions?

### CODE REVIEW

**Comment by mlennert** [comment]
> **Describe the bug**
> 
> The toolbar of Data tab uses lock/unlock symbol for allowing and disallowing edits in mapsets other than the current one. However, the locking refers to something else in GRASS GIS and that it locking of mapsets by a GRASS GIS process/session. That terminology is actually in line with other software where a file is locked when used by another process or instance of the same program.
> 
> **Expected behavior**
> 
> A new icon is needed. It may have the allowed and restricted states like now or it could be just one symbol relying on the toggle state of the button to convey the change of state. A common icon for editing in GIS, including GRASS GIS, is a pen/pencil, so that's at least a good starting point.
> 
> **Suggestion:**
> 
> Editing mode allowed:
> 
> allow_edits
> 
> No edits allowed:
> 
> disallow_edits
> 
> What are your suggestions?

I don't have any strong feelings, but if forced to choose,I probably would prefer the suggestion of a simple pencil showing whether the button is pushed or not, instead of a change of icon.

**Comment by lindakladivova** [comment]
> 
> 
> > **Describe the bug**
> > The toolbar of Data tab uses lock/unlock symbol for allowing and disallowing edits in mapsets other than the current one. However, the locking refers to something else in GRASS GIS and that it locking of mapsets by a GRASS GIS process/session. That terminology is actually in line with other software where a file is locked when used by another process or instance of the same program.
> > **Expected behavior**
> > A new icon is needed. It may have the allowed and restricted states like now or it could be just one symbol relying on the toggle state of the button to convey the change of state. A common icon for editing in GIS, including GRASS GIS, is a pen/pencil, so that's at least a good starting point.
> > **Suggestion:**
> > Editing mode allowed:
> > allow_edits
> > No edits allowed:
> > disallow_edits
> > What are your suggestions?
> 
> I don't have any strong feelings, but if forced to choose,I probably would prefer the suggestion of a simple pencil showing whether the button is pushed or not, instead of a change of icon.

Do you think something like that?
No edits allowed:
disallow_edits2

Editing mode allowed:
allow_edits2
allow_edits3

**Comment by mlennert** [comment]
Yes, or the editing mode button in QGIS.

But I'm definitely neither a UX expert, nor up to date in modern design, so I might not be the best to ask. You could send a mail to the dev and/or user list and ask...

**Comment by neteler** [comment]
It might be worth checking if the red/green colors are colorblind safe.

**Comment by petrasovaa** [comment]
> Yes, or the editing mode button in QGIS.

I agree, we already that editing icon available. Probably we don't need a special icon for toggled state. Let's keep it simple and see later if people will find it misleading.

**Comment by lindakladivova** [comment]
> > Yes, or the editing mode button in QGIS.
> 
> I agree, we already that editing icon available. Probably we don't need a special icon for toggled state. Let's keep it simple and see later if people will find it misleading.

I used this icon mActionToggleEditing.svg avaliable in QGIS:
toggleEditing

**Comment by petrasovaa** [comment]
> > > Yes, or the editing mode button in QGIS.
> > 
> > 
> > I agree, we already that editing icon available. Probably we don't need a special icon for toggled state. Let's keep it simple and see later if people will find it misleading.
> 
> I used this icon mActionToggleEditing.svg available in QGIS:
> toggleEditing

We already have the edit.png in grass, so just add the svg to have both, I think they match.

**Comment by petrasovaa** [comment]
This works. One thing we probably should do is to keep the changing tooltip depending on the state (the icon would be the same).
The tooltip itself may need to be changed but I am not sure how. It says "Allow editing other mapsets", do users know what we mean with other mapsets? Should we add "and locations"? Or we could say "Do not restrict edits to current mapset only" and "Restrict edits to current mapset only". Or something else, any suggestions @mlennert, @wenzeslaus, @lindakladivova  ?

**Comment by mlennert** [comment]
Am 6. August 2020 22:36:49 MESZ schrieb Anna Petrasova <notifications@github.com>:
>This works. One thing we probably should do is to keep the changing
>tooltip depending on the state (the icon would be the same).
>The tooltip itself may need to be changed but I am not sure how. It
>says "Allow editing other mapsets", do users know what we mean with
>other mapsets? Should we add "and locations"? Or we could say "Do not
>restrict edits to current mapset only" and "Restrict edits to current
>mapset only". Or something else, any suggestions @mlennert,
>@wenzeslaus, @lindakladivova  ? 

I think "Allow editing other mapsets and locations" is the clearest.

**Comment by lindakladivova** [comment]
> 
> Am 6. August 2020 22:36:49 MESZ schrieb Anna Petrasova <notifications@github.com>:
> This works. One thing we probably should do is to keep the changing tooltip depending on the state (the icon would be the same). The tooltip itself may need to be changed but I am not sure how. It says "Allow editing other mapsets", do users know what we mean with other mapsets? Should we add "and locations"? Or we could say "Do not restrict edits to current mapset only" and "Restrict edits to current mapset only". Or something else, any suggestions @mlennert, @wenzeslaus, @lindakladivova ?
> I think "Allow editing other mapsets and locations" is the clearest.

I like this "Allow editing other mapsets and locations" the most as well.

**Comment by wenzeslaus** [comment]
The _current_ mapset will be something explicitly mentioned in the tree after #849 is in, so I think centering the message around _current mapset_ would be good. Here are the two tooltips for the two states. Both are formulated without using a negative and the first one is also trying for a positive tone.

* Allow edits outside of the current mapset
* Restrict edits to the current mapset only

**Comment by lindakladivova** [comment]
> 
> 
> The _current_ mapset will be something explicitly mentioned in the tree after #849 is in, so I think centering the message around _current mapset_ would be good. Here are the two tooltips for the two states. Both are formulated without using a negative and the first one is also trying for a positive tone.
> 
>     * Allow edits outside of the current mapset
> 
>     * Restrict edits to the current mapset only

Ready for review.

**Pull request merged**
