### PR TITLE
Use Codecov uploader in Travis CI instead of deprecated and broken bash uploader

### PR DESCRIPTION
**Pull request by echoix**
Use Codecov uploader in Travis CI instead of deprecated and broken bash uploader
Codecov bash uploader is deprecated and fully sunset since February 2022

See the top in: https://github.com/codecov/codecov-bash/blob/1817ab23d6b35ff6596e48d15db366b71f17ada3/readme.md
They also link to their blog: https://about.codecov.io/blog/introducing-codecovs-new-uploader/

When we look at the Travis CI build logs, we see that this step is broken, since there is an error in the syntax. (See full details at the end of the PR)

image

My first guess at fixing the original syntax error would have been to remove the space between `<` and `(` (see [Process Substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html#Process-Substitution)), since I assume the example followed was like this, but without the `-Z`:
https://github.com/codecov/example-bash/blob/16036e813e65e633cbcc2814ad28eda0c728e57e/.github/workflows/ci.yml

```yaml
      - name: Upload reports to Codecov
        run: bash <(curl -s https://codecov.io/bash) -Z
```

<details><summary>Excerpt of a recent Travis CI run and full log</summary>
<p>

```shell
$ bash < (curl -s https://codecov.io/bash)
/home/travis/.travis/functions: eval: line 109: syntax error near unexpected token `('
/home/travis/.travis/functions: eval: line 109: `bash < (curl -s https://codecov.io/bash) '
Done. Your build exited with 0.
```

The run is https://app.travis-ci.com/github/OSGeo/grass/jobs/592397008
The full log is here: [log.txt](https://github.com/OSGeo/grass/files/10347187/log.txt)

</p>
</details>

Next question is: What does Codecov upload and check?

### CODE REVIEW

**Comment by echoix** [comment]
At least we know now that there isn't any code coverage info to upload...
image

Was there a tool run before?

**Comment by neteler** [comment]
> At least we know now that there isn't any code coverage info to upload...

As far as I know the code coverage info has not been generated so far.

**Comment by neteler** [comment]
Close/reopen to wake up CI

**Comment by echoix** [comment]
Is this something we would want ready to fix?

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
The new code is better than ending up with an error which is the current state, but removing it seems like a better solution.

The Codecov comes from pre-GitHub pre-GitHub Action times (fe269335977504783d9e3b6ec5fe24237d2cf127). At this point, it is missing anything to feed that. Travis-CI does not even run the tests, just a build if I recall correctly, so you can also just remove the code from here. I don't know if Codecov can do more than coverage, but even if that's the case, GitHub Action would be likely a better integration for PRs.

**Comment by wenzeslaus** [comment]
> Is this something we would want ready to fix?

It would be good to have in general. I don't know if it needs to start with Codecov or something else. I also don't know what it would take at this point to integrate Codecov.

Determining the coverage might be tricky across two languages and command line tools, but maybe the tooling can handle that at this point. In _grass.gunittest_, I tried to do it on tool-level by collecting which tools are running (that seemed important for GRASS GIS and not covered by other frameworks). The _grass.gunittest_ work is kind of pre-everything with a lot of custom approaches. Anyway, it generates images like this one:

image

**Comment by echoix** [comment]
Fixed in #3002

**Pull request closed without merging**
