### PR TITLE
docker: update actions (G78)

### PR DESCRIPTION
**Pull request by neteler**
This PR hopefully fixes the currently broken docker action:

* selective sync to workflow in `main`

TODO: not sure about the change in line 43

### CODE REVIEW

**Comment by echoix** [comment]
I know it's not exactly on the good PR, as it is for grass 7.8, but I was wondering why the Docker latest tag is pushed on changes to main. Isn't it a convention that the :latest tag in Docker is the default tag when nothing is specified, and usually the latest release, the image that most people should want to use. Currently, the commits on main would be mapped more appropriately on a :beta tag, as it is between releases.

**Comment by nilason** [comment]
The yaml error in https://github.com/OSGeo/grass/blob/2b82dad3d6e71675368ceece8f8a5c4f557a6e98/.github/workflows/docker.yml was probably because of two instances of name (L2 and L19) tag, not the starting `---`.

**Comment by neteler** [comment]
> The yaml error in https://github.com/OSGeo/grass/blob/2b82dad3d6e71675368ceece8f8a5c4f557a6e98/.github/workflows/docker.yml was probably because of two instances of name (L2 and L19) tag, not the starting `---`.

My fix attempt was 12435e1e432b6f1944e353519f4a411ad4a0f6e5, like this it mainly corresponds to the respective file in G82.

**Comment by nilason** [comment]
> My fix attempt was [12435e1](https://github.com/OSGeo/grass/commit/12435e1e432b6f1944e353519f4a411ad4a0f6e5), like this it mainly corresponds to the respective file in G82.

That's what I just happened to see and thought it was curious.
It would have been enough to only remove one of the "name" lines, the `---` could just as well have stayed (linters would error or warn on its absence). But no big deal, works without anyway, as it is optional (if you're interested see https://yaml.org/spec/1.2.2/#22-structures).

**Comment by neteler** [comment]
I have fixed  the "name" lines and the `---` in 22840d7c163d1c49a676da76e13acb74b630cd88.

**Comment by nilason** [comment]
https://github.com/actions/runner-images/issues/6002

**Comment by neteler** [comment]
> Looking at the runners, it hit me the ubuntu-18.04 is deprecated:

Isn't that a separate problem, i.e. to update all the other actions, in a new PR (like what we used renovate bot for)?

**Comment by nilason** [comment]
> > Looking at the runners, it hit me the ubuntu-18.04 is deprecated:
> 
> Isn't that a separate problem, i.e. to update all the other actions, in a new PR (like what we used renovate bot for)?

Oh yes, sorry, forgot to add that that's a matter for another issue/PR.

**Pull request merged**
