### PR TITLE
allow larger maps in r.terraflow

### PR DESCRIPTION
**Pull request by ninsbl**
Replaces #31
patch with a fix provided by @metzm

### CODE REVIEW

**Comment by ninsbl** [comment]
Unfortunately, also memory seems to be Limited by some sort of type definition.

If I allocate a lot of the sytem memory (100GB) on a large map, so out-of-memory computation is still necessary, I get the following error message:

```
terminate called after throwing an instance of
'std::bad_array_new_length'
  what():  std::bad_array_new_length
```

**Comment by wenzeslaus** [comment]
Slightly off topic:

> patch with a fix provided by @metzm

For co-authors, I suggest using Co-authored-by at the end of the commit message:

```

Co-authored-by: name <name@example.com>
```

I think empty line (i.e., two new lines) is necessary and sufficient (GitHub documentation is little confusing there, but the generally that's what's accepted).

**Comment by wenzeslaus** [comment]
According to [cppreference.com](https://en.cppreference.com/w/cpp/memory/new/bad_array_new_length), `std::bad_array_new_length` happens when *array length is negative* (the other two options don't look likely in our case). Since number of rows and columns seems to be (always?) defined as `dimension_type` which is a typedef for `short` (types.h:29), I would guess that it overflows, becomes negative, and if that eventually goes to `new` in one way or the other, the exception is thrown. Although, there is `if ((nr > dimension_type_max) || (nc > dimension_type_max))` test in main.cpp:486 which is trying to fail fast there.

**Comment by metzm** [comment]
dimension_type has been changed in this PR from short to int, but this is only part of the solution. In order to support large maps, all instances where rows * cols is computed must cast to long, or better some portable 64 integer type.

I guess I overlooked an instance where rows * cols is computed, I will check again.

**Comment by neteler** [comment]
> Slightly off topic:
> For co-authors, I suggest using Co-authored-by at the end of the commit message:
> 
> ```
> 
> Co-authored-by: name <name@example.com>
> ```

(added to https://trac.osgeo.org/grass/wiki/HowToGit#Citingco-authorsinagitcommitmessage )

**Comment by ninsbl** [comment]
Desired functionality is also available in [r.hydrodem](https://grass.osgeo.org/grass76/manuals/addons/r.hydrodem.html), which is able to handle large rasters.

The question is how to proceed with this PR.
We can close it without merging, since other options exist. Or - if we consider the changes still relevant - we merge the PR as an improvement of the current code, though not perfect (memory is limited to 32GB).
If we decide not to merge, we should probably consider removing r.terraflow from core and adding/prommoting r.hydrodem instead?

In either case we should close the related trac ticket...

**Comment by metzm** [comment]
Memory in r.terraflow is limited to 32 GB? Interesting. This must come from the GRASS iostream library and would also affect r.viewshed. We do not have an alternative for r.viewshed, therefore the memory limit should be fixed.
I opt to merge this PR and create a new issue/ticket for the memory limit.

**Comment by neteler** [comment]
> I opt to merge this PR and create a new issue/ticket for the memory limit.

@ninsbl will you merge this PR?

**Pull request merged**
