### PR TITLE
r.geomorphon: Fix shape calculations

### PR DESCRIPTION
**Pull request by infrastation**
This bugfix solves an issue with my project data, please review, you might want it in the release branches too. I found it whilst working on something else in this plugin, which I would like to mention as well.

There are 6 (so far) commits with code cleanups in my working copy. They would not add value in the release branches, so I am going to open a separate pull request for the cleanups after the bugfix is sorted.

The cleanups prepare the plugin code for a new feature, which is still a work in progress, and which would make sense in the master branch and eventually in the 2021 Q1 release, although unlikely in the release branches. If everything goes well, it should be ready in time for that.

Would that fit with your development plans?

### CODE REVIEW

**Comment by infrastation** [comment]
It seems to me, the Windows build is broken due to unrelated reasons.

**Comment by wenzeslaus** [comment]
> (...) Would that fit with your development plans?

Sounds very reasonable to me. Thank you.

> the Windows build is broken due to unrelated reasons.

Sometimes that happens. I restarted the build to see if that was just something temporary.

**Review by wenzeslaus — APPROVED** [review]
This looks straightforward and correct.

I'll merge later if there no objections.

**Review by marisn — APPROVED** [review]
Looks good to me. If we have the same code in 7.x branch, it is a safe backport.

**Comment by neteler** [comment]
> Looks good to me. If we have the same code in 7.x branch, it is a safe backport.

Yes, the r.geomorphone related files master and relbranch78 are identical.

**Pull request merged**
