### PR TITLE
wxGUI/datacalog: distinguish vector map layer type by icon

### PR DESCRIPTION
**Pull request by tmszi**
**Describe the solution you'd like**

Distinguish vector map layer type by icon (quick and clear visual orientation in vector map layers in the data catalog tree):

* vector3d 3D vector map layer ('vector3d.png' icon). Modified original vector map layer icon with 3D char.

* vector_db_disconnect Vector map layer (geometry) is stored in the db, but db connection is refused, db service isn't running ('vector_db_disconnect.png' icon). Modified original vector map layer icon with DB char (DB -> Database), and x char (x -> connection is refused).
 
* vector_link_without_src Link external vector map layer, but source path changed/deleted ('vector_link_without_src.png' icon). Modified original vector map layer icon with LK char (LK -> Link), and x char (x -> source path changed/deleted).

Source files (*.xcf format):

[vector_icons.tar.gz](https://github.com/OSGeo/grass/files/5078286/vector_icons.tar.gz)

**Disadvantage of the current implementation of this solution**

Slowing down of loading the catalog data tree.

It's up to the discussion to see if such functionality is needed and useful or not.

### CODE REVIEW

**Comment by petrasovaa** [comment]
I am not sure vector_db_disconnect and vector_link_without_src make too much sense, it seems like very specific and uncommon case. Showing 3D/2D makes sense, and if we decide to show that, we could also add the geometry type (points, lines, areas, mixed). But I am concerned about loading, so not sure whether to recommend certain version of this at all.

**Comment by tmszi** [comment]
> I am not sure vector_db_disconnect and vector_link_without_src make too much sense, it seems like very specific and uncommon case. 

At first I thought only of distinguishing these two types 2D and 3D. However, the problem is with vector map layers that have a stored topology in the database and if the database service is not available, it is not possible to obtain information about whether the vector map layer is 3D or not, topology information ([coor](https://grass.osgeo.org/programming7/vlibFormat.html#vlibHeadFileFormat) file which hold info about 2D/3D, is stored in db). That's why I distinguished the vector layer with icons `vector_link_without_src` and `vector_link_without_src` (however 3D information is available for the link vector map layer even if the source is changed or removed, but it is also appropriate inform the user that the resource has changed or deleted and that was the reason why I also distinguished this type).

**Comment by echoix** [comment]
Solved conflicts

**Comment by petrasovaa** [comment]
Given the number of open PRs, I will take the liberty to close this one. To me, the disadvantage of slowing down the loading is bigger than the advantage of being to able to visually distinguish 3D vector. That said, I didn't actually measure the slow down and how significant it is, so feel free to reopen if you feel like that wouldn't be an issue.

**Pull request closed without merging**
