### PR TITLE
v.voronoi for areas

### PR DESCRIPTION
**Pull request by metzm**
Incomplete fix for skeletons and voronoi diagrams for areas.
The skeletons are sometimes still a mess, but this is due to numerical instability in v.voronoi.
The voronoi diagrams for areas need more cleaning up, thus this is an incomplete fix.

### CODE REVIEW

**Comment by mlennert** [comment]
I've just tested with the same commands as the original bug report, i.e.:

`v.voronoi -s census_wake2000 out=census_skel`

This gives pretty much nonsense as you can see in the attached image:

v_voronoi_skeleton

However, when generalizing the polygons first, using:

`v.generalize census_wake2000 method=douglas_reduction out=census_red threshold=100`

and then running the same v.voronoi command, I now get pretty nice results:

v_voronoi_skeleton_reduced_input

Trying the same generalization in grass7.6 doesn't lead to better results, so your changes really have a very positive effect.

Changing the threshold in the generalizing leads to slightly different center lines. I guess this is due to the numerical instability.

So, probably the man page should include some info about generalization before creating skeletons.

**Comment by metzm** [comment]
> I've just tested with the same commands as the original bug report, i.e.:
> 
> `v.voronoi -s census_wake2000 out=census_skel`
> 
> This gives pretty much nonsense as you can see in the attached image:
> 
> v_voronoi_skeleton

Good news: I managed to improve numerical stability, no more nonsense results in this example. I tested a few other maps and settings and results seem to be much more stable.

[Sorry for the git commit mess, no idea why rebase did not work]

**Comment by landam** [comment]
So it means that this PR can be closed?

**Comment by mlennert** [comment]
> So it means that this PR can be closed?

Looks very good to me at least. Thanks a lot !

I just tested with urbanarea as well. After generalization with douglas_reduction reduction=30 I get pretty good results (without reduction it takes ages, so I haven't had the time to try yet). 

So, yes, I think the PR can be merged.

**Comment by pmav99** [comment]
Maybe adding a test case would be a good idea?

**Comment by metzm** [comment]
@landam @mlennert I want to fix Voronoi diagrams for adjacent areas (areas with a common boundary), they don't look yet how they should look like: common boundaries must be part of the Voronoi diagrams: If two areas do not have a common boundary but are very close to each other, a part of the Voronoi diagram must be in between these two areas. Now if you reduce the gap between the two areas successively, the Voronoi diagrams will approximate the boundaries. That means when the gap is finally closed, the Voronoi diagrams for the two areas must follow the common boundary. That's maybe worth a new PR, but as long as I am on it, I could continue to use this PR.

@pmav99 Yes, test cases would be a good idea, one for classical Voronoi diagrams for points, one for Voronoi diagrams for areas, and one for skeletons of areas.

**Comment by metzm** [comment]
Voronoi diagrams for adjacent areas are now fixed. There are still some small artefacts here and there, but for the time being these won't fix. I suggest to merge this PR and create a new one for test cases.

**Pull request merged**
