### PR TITLE
lib config: create dynamic library of C++ libraries (2nd attempt)

### PR DESCRIPTION
**Pull request by nilason**
Up till now linking C++ based libraries (at this point only the **iostream** library) was forced into creating a static library. This PR enables the possibility to create a dynamic library with the new configure flag 'SHLIB_LDX', which could use CXX instead of CC.

`IS_CXX = yes` must be set before including the 'Lib.make' file in the library's Makefile.

(retry of #2611 )

### CODE REVIEW

**Comment by wenzeslaus** [comment]
Maybe one of the [GCC matrix configs](https://github.com/OSGeo/grass/blob/main/.github/workflows/gcc.yml#L20) should test this.

BTW, I see an email from GitHub for ab9a3d269fe5822cae05378ede783fa532768cad for the other PR, but I don't know what went wrong on the web.

**Comment by nilason** [comment]
> Maybe one of the [GCC matrix configs](https://github.com/OSGeo/grass/blob/main/.github/workflows/gcc.yml#L20) should test this.

I believe all will create dynamic libs by default, e.g.:

```
...
g++ -shared -o /home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/lib/libgrass_iostream.8.3.so -L/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/lib -L/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/lib -Wl,--export-dynamic -Wl,-rpath-link,/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/lib -Wl,-rpath,/home/runner/install/grass83/lib -Wl,-soname,libgrass_iostream.8.3.so OBJ.x86_64-pc-linux-gnu/ami_stream.o OBJ.x86_64-pc-linux-gnu/mm.o OBJ.x86_64-pc-linux-gnu/mm_utils.o OBJ.x86_64-pc-linux-gnu/rtimer.o  -lgrass_gis.8.3 -lm 
...
```

> BTW, I see an email from GitHub for [ab9a3d2](https://github.com/OSGeo/grass/commit/ab9a3d269fe5822cae05378ede783fa532768cad) for the other PR, but I don't know what went wrong on the web.

I have no clue what happened, or rather why nothing happened, I did what I always do.

**Comment by nilason** [comment]
This is what the previously mentioned log line looked like before:

```
ar cr /home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/lib/libgrass_iostream.8.2.a OBJ.x86_64-pc-linux-gnu/ami_stream.o OBJ.x86_64-pc-linux-gnu/mm.o OBJ.x86_64-pc-linux-gnu/mm_utils.o OBJ.x86_64-pc-linux-gnu/rtimer.o; ranlib /home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/lib/libgrass_iostream.8.2.a
```

**Comment by nilason** [comment]
@lbartoletti If you have the possibility to test if this PR causes any regression on BSD systems, I'd be grateful.

**Comment by lbartoletti** [comment]
> @lbartoletti If you have the possibility to test if this PR causes any regression on BSD systems, I'd be grateful.

I successfully build your branch.

Thanks!

**Comment by nilason** [comment]
> > @lbartoletti If you have the possibility to test if this PR causes any regression on BSD systems, I'd be grateful.
> 
> I successfully build your branch.
> 
> Thanks!

I figured it would work, but one never knows... Thanks for taking the time!!

**Comment by nilason** [comment]
To summarise the results from testing:
The configure flag `--enable-shared` which is set by default, now works also for creating C++ GRASS libraries like *libgrass_iostream*.
There are two modules (r.terraflow and r.viewshed) linking to the *libgrass_iostream* library, which are both built and tested successfully on the CI Windows, CI Ubuntu, MacOS, and BSD.

**Comment by nilason** [comment]
@sebastic Do you have any thoughts or objections to this?

**Comment by sebastic** [comment]
No. As long as GRASS doesn't adhere to FHS, all libraries are installed outside the ld search paths and considered private.

**Pull request merged**
