### PR TITLE
packaging: Update Vagrantfile to Ubuntu 24.04

### PR DESCRIPTION
**Pull request by landam**
This PR updates Vagrantfile to use Ubuntu 24.04 LTS.

## Notes

- unofficial Ubuntu image is used (https://app.vagrantup.com/alvistack/boxes/ubuntu-24.04 which is one of the most popular on [Vagrant Cloud](https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=ubuntu+24.04) and has X Windows system activated) Reason: Canonical no longer publish Vagrant image ([source](https://documentation.ubuntu.com/public-images/en/latest/public-images-explanation/vagrant/))
- PDAL support not included since UbuntuGIS doesn't provide any package for Ubuntu 24.04 yet ([link](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+packages?field.name_filter=pdal&field.status_filter=published&field.series_filter=))

## How to test

```sh
vagrant up
vagrant ssh -c grass
```

### CODE REVIEW

**Review by wenzeslaus — APPROVED** [review]
The PR implements what the description promised.

Although there was the outdated libLAS support, the PDAL support was not there before, so no discussion is needed on including it. The change from sh to Bash likely reflects the general expectation and the file targets specific distro.

**Comment by wenzeslaus** [comment]
Do you want this in 8.4.0 or 8.4.1? This might be fine to do backport between 8.4.0RC1 and 8.4.0.

**Comment by landam** [comment]
I can do backport today.

**Comment by landam** [comment]
@neteler Thanks for backporting.

**Pull request merged**
