### PR TITLE
wxGUI/dbmgr: fix show attribute table for vector map from another mapset

### LINKED ISSUE #3078: [Bug] opening attribute table in empty mapset freezes GUI
**Describe the bug**
This is a weird bug but it could be a confusing problem for many. If you try to open the attribute table manager from an empty mapset, it freezes the GUI with a 'loading attribute table' message.  

**To Reproduce**
1. Switch to the sc_spm_08_grass7 demo location
2. Create a new mapset ("new") in the data manager
3. Switch to the mapset "new"
4. Make sure that "new" has access to PERMANENT (g.mapsets)
5. Add the firestations vector map from PERMANENT to the layer manager
6. Try to open the attribute table manager window

**Expected behavior**
Instead of the table manager window, there is a 'loading attribute table' message displayed that never goes away. 

**System description (please complete the following information):**

- Operating System: MacOS 13.4.1 (ARM)
- GRASS GIS version: 8.3.0

**Work Around
Copy a vector map to the empty mapset. Then everything works fine and the table manager opens. For some reason, not having the support folders/files for vectors in the current mapset is probably what is causing the freezing. But it shouldn't freeze like that. 

If you then delete the vector you've copied into the empty mapset and try to open the attribute table from another mapset, it works fine. So it definitely has something to do with setting up the support for vectors. Either this needs to happen when mapsets are created or the table manager needs to ignore the lack of vector support when opening a table of a vector in a different mapset.

### PR DESCRIPTION
**Pull request by tmszi**
Fixes #3078.

### CODE REVIEW

**Review by petrasovaa — CHANGES_REQUESTED** [review]
GUI shouldn't be temporarily changing mapsets. The way to do it is to use `gs.create_environment` and pass that environment to db.connect.

**Comment by tmszi** [comment]
> GUI shouldn't be temporarily changing mapsets. The way to do it is to use `gs.create_environment` and pass that environment to db.connect.

Yes you are right, thanks for your explanation. Fixed with https://github.com/OSGeo/grass/pull/3081/commits/6d6c7418f1a8e3404883533697da70bbb79a9f28.

**Comment by tmszi** [comment]
#3086 solve issue #3078.

**Comment by petrasovaa** [comment]
I think this could still be useful if the mapset is created manually without initialization. The only thing I would perhaps modify is relying on vectname to include mapset, using find_file may be a good idea.

**Comment by tmszi** [comment]
> I think this could still be useful if the mapset is created manually without initialization. The only thing I would perhaps modify is relying on vectname to include mapset, using find_file may be a good idea.

Ok, I'm reopening this PR and have incorporated your suggestion.

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
