### PR TITLE
Update r.carve.html

### PR DESCRIPTION
**Pull request by YannChemin**
Modified the example code of r.carve to be more attractive on launch

### CODE REVIEW

**Comment by echoix** [comment]
Will the sleep command work when used on Windows (at least through OSGeo4W install)?

**Comment by wenzeslaus** [comment]
There is also echo with pipe (does that work?). Maybe just specifying that the language is Bash is appropriate. We do that elsewhere.

**Comment by wenzeslaus** [comment]
The sentence before the example could be:

> Do X and Y using North Carolina sample dataset (Bash script):

**Comment by echoix** [comment]
> There is also echo with pipe (does that work?). Maybe just specifying that the language is Bash is appropriate. We do that elsewhere.

Agreed, I didn't see that it was already not compatible. So it's good like this :)

**Comment by echoix** [comment]
Was there some parts of this PR that are relevant to keep.

**Pull request closed without merging**
