### PR TITLE
configure: Improve OpenMP detection

### PR DESCRIPTION
**Pull request by nilason**
Add detection of link flag `-lomp` in addition to the gcc `-lgomp`, this also adds detection of Clang on Apple with `-Xclang -fopenfp`.

This adds the configure flag `--disable-openmp` which (if set) overrides `--with-openmp`. This comes with the use of (locally modified) `AC_OPENMP`.

### CODE REVIEW

**Comment by petrasovaa** [comment]
I just merged r.resamp.interp #1771, could you please update this PR for this module as well? Thanks

**Comment by nilason** [comment]
It would be good if someone could test this PR. Configure should work as before: no configure settings should need to be changed.

I had hoped for this to go to 8.2, but having the RC1 out already makes that doubtful... However, needs testing.

**Comment by neteler** [comment]
> I had hoped for this to go to 8.2, but having the RC1 out already makes that doubtful... However, needs testing.

We may schedule 8.2.2 (as it will take many months that the future 8.3.0 hits the Linux distros...).

**Comment by nilason** [comment]
> > I had hoped for this to go to 8.2, but having the RC1 out already makes that doubtful... However, needs testing.
> 
> We may schedule 8.2.2 (as it will take many months that the future 8.3.0 hits the Linux distros...).

Yes, it will have to be 8.2.2 (at the earliest) for this. This is probably a needed change for Homebrew dist, but has unfortunately not been tested yet even if I notified of this PR a month ago.

**Comment by nilason** [comment]
If there are no objections, I will merge this shortly. Needs testing.

**Pull request merged**
