### PR TITLE
wingrass standalone installer: update msvcrt packages

### PR DESCRIPTION
**Pull request by landam**

### CODE REVIEW

**Comment by hellik** [comment]
regarding the not starting GUI GUI issue of 7.8.5 , I thought about updating runtimes in the standalone installer. Though not sure because OSGeo4W winGRASS 7.8.5 starts

**Comment by landam** [comment]
> regarding the not starting GUI GUI issue of 7.8.5 , I thought about updating runtimes in the standalone installer. Though not sure because OSGeo4W winGRASS 7.8.5 starts

BTW, I haven't updated to `msvcrt2015-2.0-1`, it would need another fix in the installer since this file doesn't contain exe binary file.

**Comment by landam** [comment]
it's probably not related to #1218

**Comment by hellik** [comment]
> 
> 
> > regarding the not starting GUI GUI issue of 7.8.5 , I thought about updating runtimes in the standalone installer. Though not sure because OSGeo4W winGRASS 7.8.5 starts
> 
> BTW, I haven't updated to `msvcrt2015-2.0-1`, it would need another fix in the installer since this file doesn't contain exe binary file.

according to http://download.osgeo.org/osgeo4w/x86_64/release/msvcrt/setup.hint

```
sdesc: "Microsoft Visual C/C++ Runtimes"
ldesc: "Microsoft Visual C/C++ Runtimes"
category: Libs
requires: msvcrt2008 msvcrt2010
```

is **msvcrt2015-2.0-1** needed?

**Comment by hellik** [comment]
> 
> 
> > regarding the not starting GUI GUI issue of 7.8.5 , I thought about updating runtimes in the standalone installer. Though not sure because OSGeo4W winGRASS 7.8.5 starts
> 
> BTW, I haven't updated to `msvcrt2015-2.0-1`, it would need another fix in the installer since this file doesn't contain exe binary file.

```
D:\temp\msvcrt2015-2.0-2.tar\msvcrt2015-2.0-2\bin>dir /b
concrt140.dll
msvcp140.dll
msvcp140_1.dll
msvcp140_2.dll
msvcp140_codecvt_ids.dll
vccorlib140.dll
vcomp140.dll
vcruntime140.dll
vcruntime140_1.dll
```

these files are living in **C:\OSGeo4W64\bin**

**Comment by landam** [comment]
>   these files are living in C:\OSGeo4W64\bin

Note that currently all `msvcrt` files are removed by packager script.

**Comment by neteler** [comment]
Hi, is this ticket relevant for the upcoming 7.8.6 release?

**Comment by landam** [comment]
> Hi, is this ticket relevant for the upcoming 7.8.6 release?

Yes, but it's not blocker for 7.8.6.

**Comment by ninsbl** [comment]
Is this now replaced by #1904 ?

**Comment by neteler** [comment]
> Is this now replaced by #1904 ?

@landam Do we still want this in the upcoming G7.8.8?

**Comment by hellik** [comment]
> > Is this now replaced by #1904 ?
> 
> @landam Do we still want this in the upcoming G7.8.8?

AFAIU this PR is mentioned for OSGeo4W Ver 1; which is not recommended and not heavily maintained anymore.

recommended and maintained is now OSGeo4W Ver 1.

**Comment by hellik** [comment]
@landam I guess, this PR can be closed?

**Pull request closed without merging**
