### PR TITLE
g.region: Fix the flat flag

### PR DESCRIPTION
**Pull request by HuidaeCho**
This PR prints `projection=` and `zone=` in the same one line for the flat `-f` flag.

Before:
```bash
$ g.region -pgf
projection=3
zone=0
n=37.0625 s=31.375 w=-109.0625 e=-103 nsres=0.03125 ewres=0.03125 rows=182 cols=194 cells=35308 
```

After:
```bash
$ g.region -pgf
projection=3 zone=0 n=37.0625 s=31.375 w=-109.0625 e=-103 nsres=0.03125 ewres=0.03125 rows=182 cols=194 cells=35308 
```

### CODE REVIEW

**Comment by HuidaeCho** [comment]
Maybe later for a new release in a separate PR, it would be better to imply `-g` when `-f` is used. Currently, both `-g` and `-f` are needed and `-f` without `-g` has no effect. Just using `-f` should replace `-gf` IMO.

**Comment by petrasovaa** [comment]
There are print flags that add information (`-l, -e, -c, -n, -3, -b`). I don't think all of them are printed in flat format on 1 line with this PR yet. 

I agree the `-f' flag should stand on its own in the same way you don't have to use `-g` flag together with `-p` flag. Ultimately we could introduce some kind of format method to include json format and get rid of all these flags?

There are some flags that don't seem to be behaving consistently, e.g. `-t` (no key printed), `-w` (always key=value format) and maybe some others.

**Review by wenzeslaus — COMMENTED** [review]
+1 for making flat really one line. This strangeness was there for a while and it prevents use in shell scripting without addition of a grep filter.

A test for `-gf` and `-f` would be nice, e.g., testing that `-f` really yields one line only which was apparently missing. There is already `general/g.region/testsuite/` so it should be relatively easy to add a new test.

**Comment by wenzeslaus** [comment]
> There are print flags that add information (`-l, -e, -c, -n, -3, -b`). I don't think all of them are printed in flat format on 1 line with this PR yet.

I think that falls into the general revision of all output formats below.

> I agree the `-f` flag should stand on its own in the same way you don't have to use `-g` flag together with `-p` flag.

I also expect that. `-g` usually means "key=value" line by line in other tools and there are no modifications to the format.

> Ultimately we could introduce some kind of format method to include json format and get rid of all these flags?

That would be ideal.

**Comment by HuidaeCho** [comment]
> There are print flags that add information (`-l, -e, -c, -n, -3, -b`). I don't think all of them are printed in flat format on 1 line with this PR yet.

Done.

**Comment by HuidaeCho** [comment]
> > There are print flags that add information (`-l, -e, -c, -n, -3, -b`). I don't think all of them are printed in flat format on 1 line with this PR yet.
> 
> I think that falls into the general revision of all output formats below.
> 
> > I agree the `-f` flag should stand on its own in the same way you don't have to use `-g` flag together with `-p` flag.
> 
> I also expect that. `-g` usually means "key=value" line by line in other tools and there are no modifications to the format.
> 
> > Ultimately we could introduce some kind of format method to include json format and get rid of all these flags?
> 
> That would be ideal.

Agreed, but I think that's for another PR.

**Comment by HuidaeCho** [comment]
> There are some flags that don't seem to be behaving consistently, e.g. `-t` (no key printed), `-w` (always key=value format) and maybe some others.

Yep, GMT and WMS styles don't support shell printing.

**Review by petrasovaa — APPROVED** [review]
I tested it and added a test for the f flag.

I tested the standalone -f flag, here is the code for it, but probably you are right this should be a separate PR.
```diff
diff --git a/general/g.region/main.c b/general/g.region/main.c
index 06c33a2e8c..33ad06f383 100644
--- a/general/g.region/main.c
+++ b/general/g.region/main.c
@@ -361,7 +361,7 @@ int main(int argc, char *argv[])
     G_option_required(
         flag.dflt, flag.savedefault, flag.print, flag.lprint, flag.eprint,
         flag.center, flag.gmt_style, flag.wms_style, flag.dist_res, flag.nangle,
-        flag.z, flag.bbox, flag.gprint, flag.res_set, flag.noupdate,
+        flag.z, flag.bbox, flag.gprint, flag.flprint, flag.res_set, flag.noupdate,
         parm.region, parm.raster, parm.raster3d, parm.vect, parm.north,
         parm.south, parm.east, parm.west, parm.top, parm.bottom, parm.rows,
         parm.cols, parm.res, parm.res3, parm.nsres, parm.ewres, parm.tbres,
@@ -371,7 +371,6 @@ int main(int argc, char *argv[])
                       flag.eprint, flag.center, flag.gmt_style, flag.wms_style,
                       flag.dist_res, flag.nangle, flag.z, flag.bbox,
                       flag.gprint, parm.save, NULL);
-    G_option_requires(flag.flprint, flag.gprint, NULL);
 
     if (G_parser(argc, argv))
         exit(EXIT_FAILURE);
@@ -383,7 +382,7 @@ int main(int argc, char *argv[])
     if (flag.print->answer)
         print_flag |= PRINT_REG;
 
-    if (flag.gprint->answer)
+    if (flag.gprint->answer || flat_flag)
         print_flag |= PRINT_SH;
 
     if (flag.lprint->answer)

```

**Review by echoix — APPROVED** [review]
I read the changes and they make sense for what it says it does ;)

**Comment by echoix** [comment]
Created issues to not forget about the other points, so this PR should be good to merge, it was already reviewed and approved, and I took another look at it.

**Pull request merged**
