### PR TITLE
r3.in.v5d: Remove unused variables

### PR DESCRIPTION
**Pull request by ShubhamDesai**
This pull request removes unused variables identified by cppcheck.

### CODE REVIEW

**Comment by echoix** [comment]
I've done a screening yesterday, but I'd like someone to check a little more with the complete context of the multiple `#ifdef` and `#else`, around. Cppcheck is most probably right, but the declarations are defined differently in the conditional compilation symbols.

**Comment by nilason** [comment]
> I've done a screening yesterday, but I'd like someone to check a little more with the complete context of the multiple `#ifdef` and `#else`, around. Cppcheck is most probably right, but the declarations are defined differently in the conditional compilation symbols.

Indeed. @ShubhamDesai  you need to make sure all cases (SIMPLE_COMPRESSION, KLUDGE) passes both cppcheck and compiler for these changes in `compute_ga_gb()`.
Start by looking at `cppcheck --check-level=exhaustive  --enable=all ./raster3d/r3.in.v5d/v5d.c`.

**Comment by ShubhamDesai** [comment]
> cppcheck --check-level=exhaustive --enable=all

I am using this command and it gives the following error
["--check-level=exhaustive".](cppcheck: error: unrecognized command line option: "--check-level=exhaustive".)


i used to use this command previously
cppcheck --enable=all --force . 2> cppcheck_report.txt


also regarding compilation do you mean the following commands
./configure
make
make install

i am recently done with the setup just trying to see how each command works

**Comment by nilason** [comment]
> > cppcheck --check-level=exhaustive --enable=all
> 
> I am using this command and it gives the following error ["--check-level=exhaustive".](cppcheck: error: unrecognized command line option: "--check-level=exhaustive".)

I use:
```
cppcheck --version
Cppcheck 2.14.2
```

**Comment by nilason** [comment]
> also regarding compilation do you mean the following commands ./configure make make install
> 
> i am recently done with the setup just trying to see how each command works

Yes. If you are working in one specific directory, you can then re-compile just a part with, eg.:

```sh
cd raster3d/r3.in.v5d
make clean
make
```

**Comment by ShubhamDesai** [comment]
> Cppcheck 2.14.2

ok i will try this one

**Comment by ShubhamDesai** [comment]
> > also regarding compilation do you mean the following commands ./configure make make install
> > i am recently done with the setup just trying to see how each command works
> 
> Yes. If you are working in one specific directory, you can then re-compile just a part with, eg.:
> 
> ```shell
> cd raster3d/r3.in.v5d
> make clean
> make
> ```

thanks for the guidance

**Comment by ShubhamDesai** [comment]
> > I've done a screening yesterday, but I'd like someone to check a little more with the complete context of the multiple `#ifdef` and `#else`, around. Cppcheck is most probably right, but the declarations are defined differently in the conditional compilation symbols.
> 
> Indeed. @ShubhamDesai you need to make sure all cases (SIMPLE_COMPRESSION, KLUDGE) passes both cppcheck and compiler for these changes in `compute_ga_gb()`. Start by looking at `cppcheck --check-level=exhaustive --enable=all ./raster3d/r3.in.v5d/v5d.c`.

I used the following cppcheck command
cppcheck --check-level=exhaustive --enable=all v5d.c 2> cppcheck_issuesafter.txt

Following was the output :
**Before** 
v5d.c:548:13: style: The scope of the variable 'nrncnl' can be reduced. [variableScope]
        int nrncnl = nrnc * nl;
            ^
**v5d.c:552:19: style: Unused variable: min [unusedVariable]
            float min, max;
                  ^
v5d.c:552:24: style: Unused variable: max [unusedVariable]
            float min, max;
                       ^
v5d.c:470:12: style: Unused variable: lev [unusedVariable]
    int i, lev, allmissing, num;
           ^**
v5d.c:673:16: style: Variable 'compdata2' can be declared as pointer to const [constVariablePointer]
    V5Dushort *compdata2 = (V5Dushort *)compdata;

**After:**
v5d.c:548:13: style: The scope of the variable 'nrncnl' can be reduced. [variableScope]
        int nrncnl = nrnc * nl;
            ^
v5d.c:672:16: style: Variable 'compdata2' can be declared as pointer to const [constVariablePointer]
    V5Dushort *compdata2 = (V5Dushort *)compdata;
    
  
Also i used the following make commands inside the raster3d/r3.in.v5d directory
before and after doing the changes

make clean 
make

there was no error thrown.

**Comment by nilason** [comment]
> there was no error thrown.

And if either of SIMPLE_COMPRESSION or KLUDGE is defined?

**Comment by ShubhamDesai** [comment]
> I used the following cppcheck command cppcheck --check-level=exhaustive --enable=all v5d.c 2> cppcheck_issuesafter.txt
> 
> Following was the output : **Before** v5d.c:548:13: style: The scope of the variable 'nrncnl' can be reduced. [variableScope] int nrncnl = nrnc * nl; ^ **v5d.c:552:19: style: Unused variable: min [unusedVariable] float min, max; ^ v5d.c:552:24: style: Unused variable: max [unusedVariable] float min, max; ^ v5d.c:470:12: style: Unused variable: lev [unusedVariable] int i, lev, allmissing, num; ^** v5d.c:673:16: style: Variable 'compdata2' can be declared as pointer to const [constVariablePointer] V5Dushort *compdata2 = (V5Dushort *)compdata;
> 
> **After:** v5d.c:548:13: style: The scope of the variable 'nrncnl' can be reduced. [variableScope] int nrncnl = nrnc * nl; ^ v5d.c:672:16: style: Variable 'compdata2' can be declared as pointer to const [constVariablePointer] V5Dushort *compdata2 = (V5Dushort *)compdata;
> 
> Also i used the following make commands inside the raster3d/r3.in.v5d directory before and after doing the changes
> 
> make clean make
> 
> there was no error thrown.

do you mean using this command
cppcheck --check-level=exhaustive --enable=all -DSIMPLE_COMPRESSION -DKLUDGE ./raster3d/r3.in.v5d/v5d.c > cppcheck_issues.txt 2>&1
make clean
make CFLAGS="-DSIMPLE_COMPRESSION -DKLUDGE"

**Comment by ShubhamDesai** [comment]
> > there was no error thrown.
> 
> And if either of SIMPLE_COMPRESSION or KLUDGE is defined?

do you mean using this command
cppcheck --check-level=exhaustive --enable=all -DSIMPLE_COMPRESSION -DKLUDGE ./raster3d/r3.in.v5d/v5d.c > cppcheck_issues.txt 2>&1
make clean
make CFLAGS="-DSIMPLE_COMPRESSION -DKLUDGE"

**Comment by nilason** [comment]
> > > there was no error thrown.
> > 
> > 
> > And if either of SIMPLE_COMPRESSION or KLUDGE is defined?
> 
> do you mean using this command cppcheck --check-level=exhaustive --enable=all -DSIMPLE_COMPRESSION -DKLUDGE ./raster3d/r3.in.v5d/v5d.c > cppcheck_issues.txt 2>&1 make clean make CFLAGS="-DSIMPLE_COMPRESSION -DKLUDGE"

Yep, of the head I can’t tell if it will work without re-configuring but try along that line.

**Comment by ShubhamDesai** [comment]
> > > > there was no error thrown.
> > > 
> > > 
> > > And if either of SIMPLE_COMPRESSION or KLUDGE is defined?
> > 
> > 
> > do you mean using this command cppcheck --check-level=exhaustive --enable=all -DSIMPLE_COMPRESSION -DKLUDGE ./raster3d/r3.in.v5d/v5d.c > cppcheck_issues.txt 2>&1 make clean make CFLAGS="-DSIMPLE_COMPRESSION -DKLUDGE"
> 
> Yep, off the head I can’t tell if it will work without re-configuring but try along that line.

ok i used it no error was thrown 

but if in case of reconfigure should i use these commands below
make clean
./configure
cppcheck --check-level=exhaustive --enable=all -DSIMPLE_COMPRESSION -DKLUDGE ./raster3d/r3.in.v5d/v5d.c > cppcheck_issues.txt 2>&1
make clean
make CFLAGS="-DSIMPLE_COMPRESSION -DKLUDGE"


also should all of this be done from root grass directory or just specific to the directory working on in this case raster3d/r3.in.v5d

**Comment by nilason** [comment]
> also should all of this be done from root grass directory or just specific to the directory working on in this case raster3d/r3.in.v5d

configure is always done in root, but it is good practice to do a `make distclean` before (also in root).

**Comment by ShubhamDesai** [comment]
> make CFLAGS="-DSIMPLE_COMPRESSION -DKLUDGE"

i ran this command on entire project the error.logs showed lot of issues
so i went inside again the directory and ran `make clean` and this command make `CFLAGS="-DSIMPLE_COMPRESSION -DKLUDGE"`
it did not throw any error

**Review by nilason — APPROVED** [review]

**Pull request merged**
