### PR TITLE
GUI: use %d instead of %s for integers

### PR DESCRIPTION
**Pull request by HuidaeCho**
Why `%s` for `len()`? Just this case?

### CODE REVIEW

**Comment by HuidaeCho** [comment]
Line 849 in `dialogs.py` is the same string with `%d`.

**Comment by neteler** [comment]
Please consider also to update with a simple search/replace also all .po files

**Comment by HuidaeCho** [comment]
> Please consider also to update with a simple search/replace also all .po files

What about Transifex? Just the .po files in our repo?

**Comment by neteler** [comment]
> > Please consider also to update with a simple search/replace also all .po files
> 
> What about Transifex? Just the .po files in our repo?

We have a sync procedure for that, which is outlined here:

https://github.com/OSGeo/grass/blob/master/locale/README#L117

**Pull request merged**
