### PR TITLE
r.geomorphon misc cleanups

### PR DESCRIPTION
**Pull request by infrastation**
These changes make existing code easier to follow and to work with, please review. It will be great if you do not squash these commits together, as they are quite unrelated to each other, and in one of them the credit goes to another contributor, who is not a developer.

I have a few more cleanup commits ready for a separate pull request later, where it would be fine to squash as you usually do.

### CODE REVIEW

**Comment by infrastation** [comment]
Forgot to move a `typedef` in the last commit, will push an updated revision soon.

**Comment by wenzeslaus** [comment]
From a rough look, this looks very good. Thank you.

I can enable _rebase and merge_ temporarily to preserve the commits. (We have this disabled because individual commits on branches in PRs are usually too messy to be useful for anything else than review.) I agree that there is a value in having most of these separate. BTW, you may want to look at GitHub CLI which makes creating PR really easy (although you still need to create branches). Smaller PRs are generally easier to review compared to larger PRs even when PR is well organized. Anyway, we can rebase here since it is already done and since we are not going to backport this, right?

Not squashing and rebasing makes sense only when the individual commits compile and pass the tests. Is that the case for these commits? (Esp. failing compilation would make later git bisect harder.)

You mentioned a co-author: There is a `Co-authored-by: name <name@example.com>` text you can add at the end of a commit message ([GitHub doc](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors)).

**Comment by infrastation** [comment]
Thank you for looking. I can rebase on the current master to make the merge fast-forward if that helps. Each commit compiles and works as expected in my working copy, I am not sure about the CI tests if that's what you mean, but it should be fine because these changes do not cause any difference in behaviour as far as I can tell (famous last words). Let me ask the other contributor about `Co-authored-by` and get back to you in about 12 hours.

**Comment by infrastation** [comment]
Rebased on the master branch. The other contributor is fine with the current revision of the commit message.

**Review by wenzeslaus — COMMENTED** [review]
Thank you. This is what the code needed!

**Pull request merged**
