### PR TITLE
d.rast.num: Constrain rendering within the current display extent in the wx monitor

### PR DESCRIPTION
**Pull request by HuidaeCho**
This PR uses #3482 to allow displaying raster numbers for a smaller **display extent** (not computational region) than the suggested 200x200. Do we still want this limitation when `d.rast.arrow` doesn't have any or should we add the same limit to `d.rast.arrow`?

### CODE REVIEW

**Review by echoix — APPROVED** [review]
It seems the same pattern as #3491 and #3492 that I understood, but here the logic is done a bit earlier, but after calling the parser. I don't see an obvious reason why it should work: it is shortcircuiting extra validation steps if it will be entered again in a second pass.

**Comment by wenzeslaus** [comment]
> Do we still want this limitation when `d.rast.arrow` doesn't have any or should we add the same limit to `d.rast.arrow`?

The limitation works very poorly in GUI and it does not makes sense in number of cells because what really matters is the size of a cell in rendered pixes. We probably don't what to go that direction and we don't want to keep increasing the limit based on available hardware. Overall, it would be great if you can remove it as part of this update.

**Comment by HuidaeCho** [comment]
> It seems the same pattern as #3491 and #3492 that I understood, but here the logic is done a bit earlier, but after calling the parser. I don't see an obvious reason why it should work: it is shortcircuiting extra validation steps if it will be entered again in a second pass.

All three PRs have the same pattern: `D_open_driver()` after `G_parser()` and before `G_get_window()`, in `d.rast.(arrow|num)`, to grab `GRASS_REGION`.
1. `d.*` modules run from the terminal (no `GRASS_REGION` defined)
2. `D_open_driver()` spawns the same module and exits if `GRASS_RENDER_IMMEDIATE` is not defined (not defined in the terminal) and either (not both) `GRASS_RENDER_COMMAND` or `MONITOR` is defined. In this case, `MONITOR` is defined so the display module will be spawned.
3. That spawned module still cannot see `GRASS_REGION` because it was spawned from the terminal, but this time, the monitor's `render.py` read in `env` file which contains `GRASS_RENDER_IMMEDIATE`. Now because `GRASS_RENDER_IMMEDIATE` and `MONITOR` are defined, `D_open_driver()` doesn't spawn the module and goes on to check `GRASS_REGION` and return `-1` (`GRASS_REGION` not available in the terminal yet)
4. In step 3, when `render.py` was called, it added the command line for the display module to the `cmd` file, which the monitor GUI (`gui/wxpython/mapdisp/main.py`) checks in its `watcher` every 0.5 second and triggers an event for rendering all layers in `GetLayersFromCmdFile()`.
5. `GetLayersFromCmdFile()` above executes all display commands in the `cmd` file, but now with the display extent defined in `GRASS_REGION`.
6. Every display module calls `D_open_driver()`, which will now return `0` because `GRASS_REGION` is defined from the GUI.
7. Rendering occurs happily and quickly only within `GRASS_REGION`.
8. Any further changes to `GRASS_REGION` within the monitor GUI will move to step 5.

**Comment by echoix** [comment]
> > It seems the same pattern as #3491 and #3492 that I understood, but here the logic is done a bit earlier, but after calling the parser. I don't see an obvious reason why it should work: it is shortcircuiting extra validation steps if it will be entered again in a second pass.


I'm so sorry, I thought I wrote: 

I don't see an obvious reason why it _**shouldn't**_ work. Probably an autocorrect thing.

**Comment by HuidaeCho** [comment]
> > > It seems the same pattern as #3491 and #3492 that I understood, but here the logic is done a bit earlier, but after calling the parser. I don't see an obvious reason why it should work: it is shortcircuiting extra validation steps if it will be entered again in a second pass.
> 
> I'm so sorry, I thought I wrote:
> 
> I don't see an obvious reason why it _**shouldn't**_ work. Probably an autocorrect thing.

No problem. Now we have more detail documentation about how `D_open_driver()` works. ;-).

**Comment by echoix** [comment]
Thanks for the very detailed and simple explanations! It'll take some time until I master a bit of every part of GRASS, but it's a good start, and way easier in words like this, I'm lucky for it!

**Comment by neteler** [comment]
> Now we have more detail documentation about how `D_open_driver()` works. ;-).

Thanks for writing it up! Would it make sense to move it to the doxygen section as it is easily lost in a PR discussion?
Like here: https://grass.osgeo.org/programming8/displaylib.html

**Comment by HuidaeCho** [comment]
> > Now we have more detail documentation about how `D_open_driver()` works. ;-).
> 
> Thanks for writing it up! Would it make sense to move it to the doxygen section as it is easily lost in a PR discussion? Like here: https://grass.osgeo.org/programming8/displaylib.html

Now with #3500, it's much simpler from the developer's perspective. No special consideration is necessary.

**Review by wenzeslaus — APPROVED** [review]
I agree. Opening the driver should happen right after the parser given the monitor architecture.

**Comment by HuidaeCho** [comment]
> > Do we still want this limitation when `d.rast.arrow` doesn't have any or should we add the same limit to `d.rast.arrow`?
> 
> The limitation works very poorly in GUI and it does not makes sense in number of cells because what really matters is the size of a cell in rendered pixes. We probably don't what to go that direction and we don't want to keep increasing the limit based on available hardware. Overall, it would be great if you can remove it as part of this update.

Actually, the `-a` flag uses the number of raster cells always and "Constrain display resolution to computational settings" does a similar thing with computational resolution without this flag. Based on my test, the only time it uses the number of pixels is without these two, but then you'll just see a black (or green) rectangle because `d.rast.num` (or `d.rast.arrow`) just draws numbers (or arrows) per **pixel**, which doesn't make sense.

Without https://github.com/OSGeo/grass/blob/9c3b67ec82ff1d5db64f6a2baba98390bfe9406c/display/d.rast.num/main.c#L207-L222
```bash
# in NC sample dataset
d.mon wx0
g.region rast=elevation
d.rast elevation
d.rast.num elevation
```
produces
image
and is slow.

I think this limitation can be useful **if** it is customizable using either a module parameter or an environment variable. For example, if a raster map is large with a lot of cells, it will automatically not render at a scale closer to its full region and will start rendering when the map is zoomed in closely. Like min and max visibility scales.

**Pull request merged**
