### PR TITLE
switch environment: also change mapset

### PR DESCRIPTION
**Pull request by metzm**
WIP because this exposes a bug in r.import: a temp region with WIND_OVERRIDE can not be used with r.proj/v.proj because the location and mapset need to be switched during reprojection, and the env var WIND_OVERRIDE applies only to the location/mapset where it was established -> unable to find the region def given with WIND_OVERRIDE in the source location/mapset.

### CODE REVIEW

**Comment by metzm** [comment]
The bug in r.import is avoided with the second commit, as long as r.proj does not use G_get_window() in the source (input) location + mapset.

**Comment by metzm** [comment]
@neteler @landam This PR fixes an important bug in r.proj which also affects r.import. I recommend a new bugfix release of GRASS 7.8.

**Comment by neteler** [comment]
@metzm Thanks for catching this!

I searched for further candidates with
`ag 'G_setenv_nogisrc\("LOCATION_NAME"'` - so I found more

Question: is this fix also needed in 
 * imagery/i.rectify/target.c
 * vector/v.rectify/target.c
 * ...
?

**Comment by metzm** [comment]
I checked all occurrences of `G_create_alt_env()`, including i.rectify and v.rectify. These modules are not affected, i.e. `G_create_alt_env()` is used correctly.

**Comment by wenzeslaus** [comment]
To clarify this for anybody who would get the r.import issue: The error message from r.import with default parameters (i.e., extent=input) is:

```
ERROR: Unable to open element file <windows> for <tmp.r.import.py.4004@PERMANENT>
ERROR: Unable to get reprojected map extent
```

This is present in 7.8.2 and happens only when r.import really needs to reproject. The PR is merged and the r.import will be fixed in future releases (now available using the development version). Thanks @metzm for the fix!

**Comment by neteler** [comment]
> To clarify this for anybody who would get the r.import issue: The error message from r.import with default parameters (i.e., extent=input) is:
> 
> ```
> ERROR: Unable to open element file <windows> for <tmp.r.import.py.4004@PERMANENT>
> ERROR: Unable to get reprojected map extent
> ```
> 
> This is present in 7.8.2 and happens only when r.import really needs to reproject. 

Do you mean that there are still open issues in 7.8.2? The fix was backported AFAIK...

**Comment by wenzeslaus** [comment]
This PR is from January, but 7.8.2 is from December, so I assume the fix is not there, although it might be in the 7.8 branch, but maybe I'm missing something.

**Pull request merged**
