### PR TITLE
CI: update macOS runner dependencies

### PR DESCRIPTION
**Pull request by nilason**
The single most important change to enable newest available version of most packages is the change from `jpeg` to `libjpeg-turbo` package.

This is put in draft mode until #4116, #4117 and #4118 are solved.

### CODE REVIEW

**Comment by echoix** [comment]
Is it possible to change the package names to their updated names (I think gdal conda packaging changed recently), but limit the version of the (single) package that causes the doctests to fail. In other words, if only Python or numpy makes the build fail, we could add a constraint for now.

**Comment by nilason** [comment]
Added commit with pre-version 2 of Numpy to see what regression Numpy 2 causes by itself.

**Comment by echoix** [comment]
> Added commit with pre-version 2 of Numpy (v 1.26.4) to see what regression Numpy 2 causes by itself.

Do we know what Python version we get with this and the changes of the PR? (To investigate Python 3.12 vs numpy 2 failures at the same time)

**Comment by nilason** [comment]
> Do we know what Python version we get with this and the changes of the PR? (To investigate Python 3.12 vs numpy 2 failures at the same time)

It all in the log: Python version under "Check installed version", packages under "Setup Mamba > micromamba list".

**Comment by nilason** [comment]
> Added commit with pre-version 2 of Numpy (v 1.26.4) to see what regression Numpy 2 causes by itself.

Seems only #4116 is caused by Numpy 2.

Will try with Python 3.11 and Numpy 2.

**Comment by nilason** [comment]
> Will try with Python 3.11 and Numpy 2.

With that setting all three files errors.

**Comment by nilason** [comment]
Interesting, with Python 3.11.9 with Numpy 1.26.4 the two issues #4117 and #4118 also fails. Some other dependency upgrade(s) is causing them...

**Comment by nilason** [comment]
> Interesting, with Python 3.11.9 with Numpy 1.26.4 the two issues #4117 and #4118 also fails. Some other dependency upgrade(s) is causing them...

Could it be the change of GEOS from 3.11 to 3.12?

**Comment by nilason** [comment]
> > Interesting, with Python 3.11.9 with Numpy 1.26.4 the two issues #4117 and #4118 also fails. Some other dependency upgrade(s) is causing them...
> 
> Could it be the change of GEOS from 3.11 to 3.12?

Sure it must be, https://libgeos.org/posts/2023-06-27-geos-3-12-released/:

> Change WKTWriter defaults output dimension to 4 and trim to ‘on’ (GH-915, Mike Taves)

**Comment by echoix** [comment]
I was just about to write it back here:
At the end of
https://libgeos.org/posts/2023-06-27-geos-3-12-released/
> Change WKTWriter defaults output dimension to 4 and trim to ‘on’ (GH-915, Mike Taves)

https://github.com/libgeos/geos/pull/915

And also https://github.com/libgeos/geos/pull/903 might be of concern. Maybe that's why (dimensions changed) some windows tests try to allocate an array of couple terabytes.

**Comment by nilason** [comment]
This is ready for review. And mergeable after #4123 is merged.

(I'm not familiar enough with the pygrass lib to address the Numpy 2 issue #4116, so for the time being I'm pinning the version to 1.x).

**Review by echoix — APPROVED** [review]

**Comment by nilason** [comment]
Backported with 926cf21.

**Pull request merged**
