### PR TITLE
nix: fix build by using libxml2 with http support

### PR DESCRIPTION
**Pull request by imincik**
- CI(deps): Lock file maintenance
- nix: fix build by using libxml2 with http support

Related nixpkgs PR:
https://github.com/NixOS/nixpkgs/pull/331118

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by imincik** [comment]
> Would this build error happen eventually on non-nix builds? Would there be an adaptation that we would need to apply to all of our other builds for this?

This issue is caused by [removal of default support of http in libxml2](https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/NEWS#L58) . GRASS must be using it somewhere.

**Comment by echoix** [comment]
> > Would this build error happen eventually on non-nix builds? Would there be an adaptation that we would need to apply to all of our other builds for this?
> 
> 
> 
> This issue is caused by [removal of default support of http in libxml2](https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/NEWS#L58) . GRASS must be using it somewhere. 

@neteler is there something to do about this?

**Comment by neteler** [comment]
> This issue is caused by [removal of default support of http in libxml2](https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/NEWS#L58) . GRASS must be using it somewhere.

I wonder how to look for it:

```
ag libxml2 
mswindows/osgeo4w/liblas-config
46:LIBXML2_INCLUDE_DIR=""
47:if test -n "$LIBXML2_INCLUDE_DIR" ; then 
48:    INCLUDES="$INCLUDES -I$LIBXML2_INCLUDE_DIR"
50:LIBXML2_LIBRARIES=""
51:if test -n "$LIBXML2_LIBRARIES" ; then 
52:    LIBS="$LIBS $LIBXML2_LIBRARIES"

mswindows/crosscompile.sh
302:	libxml2-2.dll \

package.nix
23:, libxml2
82:    libxml2
```

In my view liblas isn't relevant at all any more (since we support PDAL) and could be dropped.

**Comment by echoix** [comment]
Is it a transitive dependency then?

**Comment by hellik** [comment]
That's may be the reason for liblas.

**Pull request merged**
