### PR TITLE
i.pansharpen: Fix encode string

### PR DESCRIPTION
**Pull request by tmszi**
Fix bug in the reopened issue #737.

### CODE REVIEW

**Comment by neteler** [comment]
Thanks but I still get `TypeError: a bytes-like object is required, not 'str'` with this PR:

```
i.pansharpen red=lsat7_2002_30 \
>   green=lsat7_2002_20 blue=lsat7_2002_10 \
>   pan=lsat7_2002_80 method=ihs \
>   output=lsat7_2002_15m_ihs -l
dUsing 8bit image channels
.erPerforming pan sharpening with hi res pan image: 14.250000
Transforming to IHS color space...
as 100%
Histogram matching...
e 100%

 100%
Transforming back to RGB color space and sharpening...
 100%
Assigning grey equalized color tables to output images...
setting pan-sharpened channels to equalized grey scale
Adjusting blue channel color table...
Traceback (most recent call last):
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 632, in <module>
    main()
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 280, in main
    bc.stdin.write('\n'.join(blue_colors))
TypeError: a bytes-like object is required, not 'str'
```

Or does it address something else?

**Comment by tmszi** [comment]
>   File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 280, in main
> bc.stdin.write('\n'.join(blue_colors))

This PR [fix](https://github.com/OSGeo/grass/pull/745/commits/642bc6d322d1ab0a1f89a805595197c84afcc32a) row above. Could you check if you updated your source code correctly, please?

**Comment by neteler** [comment]
> This PR [fix](https://github.com/OSGeo/grass/pull/745/commits/642bc6d322d1ab0a1f89a805595197c84afcc32a) row above. Could you check if you updated your source code correctly, please?

You are right, I apologize: while patching master I tested with g78... of course it works.
I'll merge and backport it. Thanks again!

**Comment by tmszi** [comment]
> > This PR [fix](https://github.com/OSGeo/grass/pull/745/commits/642bc6d322d1ab0a1f89a805595197c84afcc32a) row above. Could you check if you updated your source code correctly, please?
> 
> You are right, I apologize: while patching master I tested with g78... of course it works.
> I'll merge and backport it. Thanks again!

That's okay, sometimes it happens. You are welcome.

**Pull request merged**
