### PR TITLE
utils: Small fixes of Bash util scripts

### PR DESCRIPTION
**Pull request by wenzeslaus**
A selection of small fixes by Mega-Linter (combination of bash-exec, shellcheck, and esp. shfmt).

### CODE REVIEW

**Comment by neteler** [comment]
Portability question:
the scripts might have been bourne shell scripts originally. Is the change to bash-style safe, even on systems which offer e.g. dash instead of bash?

**Comment by wenzeslaus** [comment]
> the scripts might have been bourne shell scripts originally. Is the change to bash-style safe, even on systems which offer e.g. dash instead of bash?

The scripts have shebangs, so that should define what they are actually written in. One has `bash`, the other two have `sh`, so the language should be resolved by the shebang even for the linter (and checked) AFAIU and definitively when running. The `$(pwd)` syntax works in Dash too if you are asking that.

**Comment by wenzeslaus** [comment]
> Portability question...

See [ShellCheck > Portability](https://github.com/koalaman/shellcheck#portability):

> ShellCheck will warn when using features not supported by the shebang. For example, if you set the shebang to #!/bin/sh, ShellCheck will warn about portability issues similar to checkbashisms.

**Comment by wenzeslaus** [comment]
None of these is used by complication, so I think there is low risk in merging this.

**Pull request merged**
