### PR TITLE
Convert REQUIREMENTS.html contents to REQUIREMENTS.md

### PR DESCRIPTION
**Pull request by echoix**
This replaces #2726 and is a followup of #2729 that was just merged.
Closes #2726

### CODE REVIEW

**Comment by echoix** [comment]
@nilason Could you set this PR to close another PR, the "closes" keywords don't seem to work for a PR.

**Comment by echoix** [comment]
I think we can open an issue to talk about improving the contents of the page. For now, it only needs to be merged since the current file isn't Markdown yet.

**Comment by nilason** [comment]
> @nilason Could you set this PR to close another PR, the "closes" keywords don't seem to work for a PR.

It had to be done manually.

**Comment by echoix** [comment]
> > @nilason Could you set this PR to close another PR, the "closes" keywords don't seem to work for a PR.
> 
> It had to be done manually.

Thanks!

**Comment by nilason** [comment]
@echoix Thanks for your contribution and patience!

**Comment by echoix** [comment]
You're welcome! I didn't realise that the project was finalizing its release in the beginning of January, so waiting for the new merge window is totally correct once understood ;)

**Pull request merged**
