### PR TITLE
mkhtml: check for addon_path

### PR DESCRIPTION
**Pull request by mmacata**
This PR suggests to add a check for an empty addon_path.
The default value is set to `addon_path = None` in [L889](https://github.com/osgeo/grass/blob/main/utils/mkhtml.py#L889) and there are circumstances where it is not overwritten. As far as I see it, this would prevent the code from requesting a wrong path in the [following method](https://github.com/osgeo/grass/blob/main/utils/mkhtml.py#L297) returning the latest commit of the whole addon repository instead of the latest commit for the addon.

Manual page generation here is really new to me so I am not sure about all the different variations in which this script might be called and if I oversee something. Background is that I am using the script to generate manual pages for addons not in the official addon repository and this PR would prevent multiple unneccessary requests to the github API.

### CODE REVIEW

**Review by tmszi — CHANGES_REQUESTED** [review]
Condition `if addon_path is not None:` should be inside body of `get_git_commit_from_rest_api_for_addon_repo()` function, line 294. See the code line comment on the line 291, please.

https://github.com/OSGeo/grass/blob/afce9eadb5bc95165efdc39f00ec365e311f36df/utils/mkhtml.py#L278-L294


Because if addon **is not official addon**, func must return date (access date of addon directory) with `git_log` variable, example `{'commit': 'unknown', 'date': 'Wednesday Apr 10 11:48:39 2024'}`, line 293.

And date and time inside manual page looks like 

_Accessed: Wednesday Apr 10 11:48:39 2024_

instead of 

_Latest change: Wednesday Mar 01 21:08:00 2023 in commit:1a96f69ccf430caa03bec8dbfc990c07c81f3164_ 

Attached patch file:
[patch.zip](https://github.com/OSGeo/grass/files/14931421/patch.zip)

Apply patch with:

```
git am < 0001-utils-do-not-make-unnecessary-request-to-addons-repo.patch
```

**Comment by mmacata** [comment]
Thanks for the feedback, I applied it. But this way there is no chance the information can be retrieved from the `get_git_commit_from_file` method in that case?

**Comment by tmszi** [comment]
> But this way there is no chance the information can be retrieved from the `get_git_commit_from_file` method in that case

**Comment by tmszi** [comment]
> But this way there is no chance the information can be retrieved from the `get_git_commit_from_file` method in that case?

Only official addons are supported now (during addon compilation is downloaded source code without Git repo, and getting commit is done by request/response from the official GitHub GRASS GIS Addons repository) . 

Else branch with `get_git_commit_from_file()` function retrieve commits from file (if core_modules_with_last_commit.json file exists) during compilation GRASS GIS **core modules** but not addons.

https://github.com/OSGeo/grass/blob/49e135301716013af9a32fb1d68afa8ed25ea60d/utils/mkhtml.py#L407-L409


I apologize for close/reopen PR. I accidentally hit Close with comment button.

**Comment by mmacata** [comment]
Ok thanks for clarification!
I tested my use case with these changes and everything runs well.

I am not sure about the failing Python Code Quality Checks though. The error there doesn't seem to be related to linting:
> Error: Failed to FinalizeArtifact: Received non-retryable error: Failed request: (403) Forbidden: Error from intermediary with HTTP status code 403 "Forbidden"

@tmszi is it possible to retry the failing check? I don't have access rights to do so.

**Comment by echoix** [comment]
It seemed like an intermittent failure..

**Review by tmszi — APPROVED** [review]

**Comment by mmacata** [comment]
That could be the cause, yes, now it runs through :)

May someone with merge rights merge this?

**Pull request merged**
