### PR TITLE
Translations update from OSGeo Weblate

### PR DESCRIPTION
**Pull request by osgeoweblate**
Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [GRASS GIS/grasslibs](https://weblate.osgeo.org/projects/grass-gis/grasslibs/).

It also includes following components:

* [GRASS GIS/grasswxpy](https://weblate.osgeo.org/projects/grass-gis/grasswxpy/)

* [GRASS GIS/grassmods](https://weblate.osgeo.org/projects/grass-gis/grassmods/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by neteler** [comment]
@HuidaeCho again `Files changed 0`...

**Comment by HuidaeCho** [comment]
> @HuidaeCho again `Files changed 0`...

Worse, the last two commits didn't seem to work.
```bash
git diff fa3b3d3dd6907d9d5ad5796264ad915d188ab9d3 69dd32429a8c53e9e72011332cbf30e09e53ccf7

git diff dc84b8650a191e697bfaa0c7076adaf187a47ca5 69dd32429a8c53e9e72011332cbf30e09e53ccf7
```
I think we have to try that lossy hack. Either way, we're loosing translations, it seems... What do you think?

**Comment by neteler** [comment]
Before trying it the hard way, shall we download the few changed files from weblate and manually merge them in later?

**Comment by HuidaeCho** [comment]
> Before trying it the hard way, shall we download the few changed files from weblate and manually merge them in later?

@neteler I downloaded
* grass-gis-grasslibs.zip
* grass-gis-grassmods.zip
* grass-gis-grasswxpy.zip

Weblate was already locked by failed rebases. Do we need anything else before the "hammer"? Let me know if I'm missing anything.

**Comment by neteler** [comment]
Does @robe2 have any further recommendations?

**Comment by HuidaeCho** [comment]
I'll go ahead and reset it.

**Comment by HuidaeCho** [comment]
Just reset the Weblate repo and unlocked it. Interestingly, there were no new translations in backups from 50 minutes ago.

**Pull request merged**
