### PR TITLE
Added global dataset to download location in startup

### PR DESCRIPTION
**Pull request by baharmon**
Added the natural earth dataset (207MB) to the download list in the startup menu  #509 
Tested on a local installation of GRASS 7.8.

### CODE REVIEW

**Comment by baharmon** [comment]
The checklist sounds good. Should there be an upper limit to file size? If the file size is posted, then users could decide whether it is larger than they want themselves. I think including info for users such as download size, disk size, license, and maintainer name and contact would be very helpful. A short description of the dataset would also help.

**Comment by wenzeslaus** [comment]
> ...download size, disk size, license, and maintainer name and contact would be very helpful. A short description of the dataset would also help.

Sorry for a late answer. You can just add these as additional keys in the dictionary. Nothing will read it yet and we may change the keys in the future (for now they are purely internal), but it would be a good start. That's totally optional, but it would nice to have that before the merge.

**Comment by baharmon** [comment]
Added dictionary keys for size, license, epsg code, and maintainer.

**Comment by wenzeslaus** [comment]
Thank you. Sorry, this took a long time. It would be great to have a more stable URL for the future such as Zenodo. So, please consider that. This will be more prominent in the main GUI as this will be part of the Data tab, so likely there will be even more users using this.

**Pull request merged**
