### PR TITLE
added missing architecture drawing

### PR DESCRIPTION
**Pull request by neteler**
Source: https://trac.osgeo.org/grass/browser/grass-web/trunk/images?rev=49702

### CODE REVIEW

**Comment by kikislater** [comment]
Nice schema ! 
Grass map storage is isolated from any other part. Seems strange to me ! Isn't Sql database reference file based raster or vector ?

**Comment by neteler** [comment]
Do you mean why the "SQL Database" box is on the right side? 
The attributes are managed by default in a SQLite database.

**Comment by kikislater** [comment]
No sorry ! Above "SQL Database", "GRASS MAP STORAGE" has no relation with others boxes. So if attributes are managed in SQLite there should be a relation between this and grass map storage, no ?

**Comment by neteler** [comment]
Good point! Fixed in https://github.com/OSGeo/grass/pull/38

**Pull request merged**
