### PR TITLE
docs: fixed E265 from image2target/

### PR DESCRIPTION
**Pull request by arohanajit**
Just removed extra `#` which fixed all `E265` from `image2target/`

### CODE REVIEW

**Comment by echoix** [comment]
Did the double `#` prevent them to be recognized by the parser? These are what is used to generate the interface, the docs, and validate the arguments given to a module

**Comment by arohanajit** [comment]
Yeah, I think its coded to look for `# ` at start hence it generates an error for anything else. I thought that should be fine since its pretty much in line with format of all other docs i've seen in other files till now.

**Comment by petrasovaa** [comment]
> Did the double `#` prevent them to be recognized by the parser before? These are what is used to generate the interface, the docs, and validate the arguments given to a module

Yes, it was not working, but in the current code, the parser part is commented out anyway. @arohanajit I suggest to remove that part instead of fixing it.

**Comment by arohanajit** [comment]
I've removed the parser code. Could you please have a quick look at it? That's a lot of lines removed and I want to make sure I've not removed that might be reqd in future

**Comment by echoix** [comment]
Looks fine, don't worry. It doesn't look like you removed something that was used

**Review by echoix — APPROVED** [review]

**Pull request merged**
