### PR TITLE
misc: fix indentation for r.series and r.patch

### PR DESCRIPTION
**Pull request by aaronsms**
- Reformat r.series
- Reformat r.patch

### CODE REVIEW

**Review by marisn — APPROVED** [review]

**Comment by aaronsms** [comment]
I have added the two commits above to .git-blame-ignore-revs.

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
Please remove the commits from .git-blame-ignore-revs. Squashing the commits during merge will create a different commit (with a different hash). This is something which needs to be done separately after the merge, hence the need for the label.

**Comment by wenzeslaus** [comment]
I have clarified the label description.

**Comment by aaronsms** [comment]
I have reverted the last commit.

**Pull request merged**
