### PR TITLE
Changed the source code links in HTML manual pages to point to the git repositories.

### PR DESCRIPTION
**Pull request by aghisla**
It's more a test for the pull request workflow than a meaningful addition :)

As discussed with Martin, changing the last modified date will likely be a post commit hook, but I need more time to figure out how to write something good. I'll add it to this pull request, unless you merge it before I can update it.

### CODE REVIEW

**Comment by aghisla** [comment]
Ah I forgot to mention that the edit in mkhtml.py doesn't recompile the HTML pages, so a make clean (or manual removal of html pages) is needed to update the links to the source code.

**Comment by neteler** [comment]
Thanks, would you mind to update the copyright year to 2019 in the file header?

In addition as being related, it would be cool to expand this PR with updates to these files:
```
# using the silver searcher "ag":
ag trac.osgeo.org/grass/browse
scripts/g.extension/g.extension.html
213:g.extension r.local.relief url="https://trac.osgeo.org/grass/browser/grass-addons/grass7/raster/r.local.relief?rev=57854&amp;format=zip"

scripts/g.extension/g.extension.py
1224:    source_url = "https://trac.osgeo.org/grass/browser/grass-addons/grass7/"
1766:        trac_url = 'https://trac.osgeo.org/grass/browser/grass-addons/' \

doc/howto_release.txt
119:# Tag release (http://trac.osgeo.org/grass/browser/grass/tags):

doc/vector/TODO
252:	http://trac.osgeo.org/grass/browser/grass-addons/grass7/vector/v.pack
254:	http://trac.osgeo.org/grass/browser/grass-addons/grass7/vector/v.unpack

doc/infrastructure.txt
148:* https://trac.osgeo.org/grass/browser
219:* Adding contributor: https://trac.osgeo.org/grass/browser/grass-addons/contributors.csv (via SVN commit)

display/d.mon/main.c
21: [1] https://trac.osgeo.org/grass/browser/grass/trunk/display/d.mon/render_cmd.py
22: [2] https://trac.osgeo.org/grass/browser/grass/trunk/lib/display/r_raster.c#L107

man/parser_standard_options.py
142:    URL = ('https://trac.osgeo.org/grass/browser/grass/'

grasslib.dox
41:  http://trac.osgeo.org/grass/browser/grass-web/trunk/images/grass7_arch.odp
188:  http://trac.osgeo.org/grass/browser/grass-web/trunk/images/loc_struct.odg

lib/python/gunittest/reporters.py
113:    tracurl = 'http://trac.osgeo.org/grass/browser/'

vector/v.qcount/v.qcount.html
13:     https://trac.osgeo.org/grass/browser/grass/branches/releasebranch_5_4/src/sites/s.qcount/tutorial
108:     https://trac.osgeo.org/grass/browser/grass/branches/releasebranch_5_4/src/sites/s.qcount/tutorial
```
... then all trac refs would be properly updated.

**Comment by neteler** [comment]
> Thanks, would you mind to update the copyright year to 2019 in the file header?
> 
> In addition as being related, it would be cool to expand this PR with updates to these files:
> 
> ```
> # using the silver searcher "ag":
> ag trac.osgeo.org/grass/browse

Most of them addressed in https://github.com/OSGeo/grass/pull/36

Open

- copyright year update
- man/parser_standard_options.py
- lib/python/gunittest/reporters.py

**Comment by neteler** [comment]
Still open:

```
ag trac.osgeo.org/grass/browse

lib/python/gunittest/reporters.py
113:    tracurl = 'http://trac.osgeo.org/grass/browser/'

scripts/g.extension/g.extension.py
1255:    source_url = "https://trac.osgeo.org/grass/browser/grass-addons/grass7/"
1802:        # trac_url = 'https://trac.osgeo.org/grass/browser/grass-addons/' \

scripts/g.extension/g.extension.html
213:g.extension r.local.relief url="https://trac.osgeo.org/grass/browser/grass-addons/grass7/raster/r.local.relief?rev=57854&amp;format=zip"

man/parser_standard_options.py
142:    URL = ('https://trac.osgeo.org/grass/browser/grass/'
```

**Comment by landam** [comment]
Already solved by 278501c2268970e010d13c06175e98f02777a7bc

**Pull request closed without merging**
