### PR TITLE
Docker alpine image patch to work with py3.8

### PR DESCRIPTION
**Pull request by mmacata**
Currently, some extensions cannot be installed. With these Dockerfile patches for alpine and python3.8, they can be installed again.

### CODE REVIEW

**Comment by neteler** [comment]
Related discussion: https://trac.osgeo.org/grass/ticket/3880#comment:5

**Comment by neteler** [comment]
To remain operative, I'll merge this now.

**Comment by neteler** [comment]
Backported to relbr78 in 00afb784791727cdf2edf0a34d86c0810f9018b8

**Comment by metzm** [comment]
Note that the patch for gisinit.c is not needed, actually it is doing more harm than good. The real bug is in the generated ctypes when using Python 3.8 where not a full string is returned but only the first character of a string. That means, instead of comparing "$Revision$" with "$Revision$", the string "$" is compared to "$Revision$".

**Pull request merged**
