### PR TITLE
Happy new year 2024

### PR DESCRIPTION
**Pull request by landam**
`g.version` / wxGUI About dialog still points to 2023:

VirtualBox_MS Windows_05_02_2024_14_59_45

### CODE REVIEW

**Comment by neteler** [comment]
There are many more files to be updated. I can do that later tonight.

**Comment by neteler** [comment]
> There are many more files to be updated. I can do that later tonight.

Done in d803960

**Comment by echoix** [comment]
And is this supposed to be updated too ?
https://github.com/OSGeo/grass/blob/ae869f5aaabbb48387f986abeee812c1af2b2afe/include/VERSION

**Comment by nilason** [comment]
> And is this supposed to be updated too ? https://github.com/OSGeo/grass/blob/ae869f5aaabbb48387f986abeee812c1af2b2afe/include/VERSION

It was the first commit.

**Comment by echoix** [comment]
> > And is this supposed to be updated too ? https://github.com/OSGeo/grass/blob/ae869f5aaabbb48387f986abeee812c1af2b2afe/include/VERSION
> 
> 
> 
> It was the first commit.

That's right. The page I opened from the email notification was only the extra commit, not the whole PR. I noticed that version file in the weekend.

**Review by echoix — APPROVED** [review]
If it's all the places to update, it's alright for me. Does the other grass repos have some similar tasks to do each year?

**Comment by neteler** [comment]
> If it's all the places to update, it's alright for me.

I used the diff from last year's PR and updated it accordingly. And that one was based on the previous years (lovingly manually searched).

> Does the other grass repos have some similar tasks to do each year?

Not really, just this repo.

**Comment by neteler** [comment]
Backported to G83 in 5c5f3c147d940b0e8b988f6ff6039bd19bf2af1f

**Comment by veroandreo** [comment]
> lovingly manually searched

:hand_over_mouth:

**Pull request merged**
