### PR TITLE
WIP: init: Parse more version of library version with --config

### PR DESCRIPTION
**Pull request by wenzeslaus**
Try to parse more version format and places with --config revision (libgis version).
Print a message when not found or the format was not recognized.
Fails with traceback when format was recognized, but not parsed correctly.

Fixes https://trac.osgeo.org/grass/ticket/4001. Note that since bfdb74d2d2, it does not fail if you ask for something which does not need the files and the files are not there, so assuming the dev files are all or nothing, it gives a proper message if you don't have the development part/package.

### CODE REVIEW

**Comment by metzm** [comment]
Note that GIS_H_VERSION is currently not really usable, because it no longer contains the svn revision number of the latest change to gis.h.
I would like to move GIS_H_VERSION to version.h.in and generate it at configure time just like e.g. GRASS_VERSION_STRING. The idea is that GIS_H_VERSION will consist of the GRASS_VERSION_NUMBER and the git hash tag of the latest commit to include.

**Comment by ninsbl** [comment]
Is here anything left after #405 and #532 have been merged?

**Comment by ninsbl** [comment]
Can this be closed?

**Comment by wenzeslaus** [comment]
Closing. A completely different approach is now used to define and get revisions/versions, perhaps even the need for greater robustness is not as big as it was with the old system.

**Pull request closed without merging**
