### PR TITLE
wxGUI: Fix scrolling the layertree to the right when adding items

### PR DESCRIPTION
**Pull request by lindakladivova**
After adding layers to the layer tree, the whole tree is scrolled to the right. If we do that again, the scrollbar is even more expanded.

This PR adjusts the scrollbars at the moment when the new item is added.

Screenshot from 2023-06-05 09-57-28

### CODE REVIEW

**Comment by landam** [comment]
@lindakladivova Can you please provide more details how to reproduce this issue? I am unable to reproduce it:

[Screencast from 2023-11-19 12-08-16.webm](https://github.com/OSGeo/grass/assets/5683186/94cfa6d9-0e8a-44fb-a815-609668ad7a78)

**Comment by neteler** [comment]
To reproduce:

load:
`nc_spm_08_grass7/landsat/`

Then display one/some landsat scenes, then click the right mouse button on the legend and the text will be shifted to the left which is not helpful:

image

**Comment by landam** [comment]
@neteler I tried to reproduce it, but I am still failing:

[Screencast from 2024-03-23 00-54-02.webm](https://github.com/OSGeo/grass/assets/5683186/f5d4520d-9543-428c-9f6c-129a76763ff8)

**Comment by veroandreo** [comment]
> @neteler I tried to reproduce it, but I am still failing:
> 
>  Screencast.from.2024-03-23.00-54-02.webm

I think you need to try with maps with longer map names, see what happens when I unclick a map:

[Screencast from 2024-03-22 21-12-31.webm](https://github.com/OSGeo/grass/assets/20075188/96ed64b0-4541-40b3-8146-b338db8ee112)

**Review by petrasovaa — APPROVED** [review]
It's a small change, I think it's fine to merge it.

**Pull request merged**
