### PR TITLE
wxGUI: New toolbar icon for accessing Map Display settings dialog

### PR DESCRIPTION
**Pull request by lindakladivova**
The new icon for Map Display Settings:
monitor-settings

The "old-new" icon for Map Display creation (adapted according to the first one):
monitor-create

--------------------------------------------------------------------------------
The old icon for Map Display creation (for comparison):
monitor-create

### CODE REVIEW

**Comment by veroandreo** [comment]
The new one looks nice! :+1:

**Comment by petrasovaa** [comment]
Looks good! Just keep the size to minimum:
 * for SVGs use File -> Cleanup document in Inkscape
 * for pngs use the pngnq and optipng tools in https://trac.osgeo.org/grass/wiki/Submitting/Docs#Images

**Comment by petrasovaa** [comment]
Sorry to bug you about this again, but looking at the optimized monitor-create.png it looks like the result is slightly different, worse I would say. Probably the pngnq has not done a great job on this, so it may be better to skip it or set higher number of colors.

**Comment by lindakladivova** [comment]
> Sorry to bug you about this again, but looking at the optimized monitor-create.png it looks like the result is slightly different, worse I would say. Probably the pngnq has not done a great job on this, so it may be better to skip it or set higher number of colors.

I have tried to use a higher number of colors (192) and the png sizes were greater than without pngnq  (1.0kB (create) 1.1 kB (settings)). So I would probably skip the pngnq altogether.. The same for optipng because then it had no efect - icons were already optimized. 

BTW, I've looked at other image sizes and I think it is entirely okay, we are below 1.0kB. There are many above.

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
