### PR TITLE
t.rast.algebra/testsuite: split file test_raster_algebra.py

### PR DESCRIPTION
**Pull request by neteler**
In order to address the frequent CI timeout during execution of the `test_raster_algebra.py` file this file is split into two parts with roughly similar test duration.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
Alternatively, we could increase the time out if you think it is really this one test hitting the time limit as opposed to hanging forever. The limit was set in 89fe85cbad9f77d23e1e8c4a1b1efc1b897f2cf9 (#2172).

While the temporal timeouts are a long-term issue (#2185), the recent flood of failures is due to various network issues (OSGeo for sample data and others for dependencies). A series of failures is also due to g.extension like [this run](https://github.com/OSGeo/grass/actions/runs/5032142475/jobs/9025625792) on main for #2966 which timed out and gave:

```
Running ./scripts/g.extension/testsuite/test_addons_download.py...
========================================================================
WARNING: Bug in UI description. Missing module description
.......========================================================================
FAILED ./scripts/g.extension/testsuite/test_addons_download.py - Timeout >300.0s
```  

[This run](https://github.com/OSGeo/grass/actions/runs/4961270814/jobs/8885333141) for #2955 fails with just like [the first attempt of runs](https://github.com/OSGeo/grass/actions/runs/5034026068/jobs/9028600476) for this PR:

```
Running ./temporal/t.rast.what/testsuite/test_what.py...
========================================================================
..............========================================================================
FAILED ./temporal/t.rast.what/testsuite/test_what.py - Timeout >300.0s
```

In grass-addons, the CI jobs are often canceled by GitHub automation after exceeding 6 hours with the following as the last line (like [this one](https://github.com/OSGeo/grass-addons/actions/runs/4747482610/jobs/8453686941) for https://github.com/OSGeo/grass-addons/pull/606): 

```
Running ./temporal/t.rast.what.aggr/testsuite/test_whataggr.py...
Error: The operation was canceled. 
```

**Comment by ninsbl** [comment]
If you run the t.rast.algebra test locally, it clocks in just around the timeout value. So, for this particular test, increasing the timeout threshold will help...

**Comment by neteler** [comment]
> If you run the t.rast.algebra test locally, it clocks in just around the timeout value. 

Confirmed also here, that's why I have split it (thematically) into two files with runtime of ~ 50% timeout each.
Personally I prefer shorter files anyway.

> So, for this particular test, increasing the timeout threshold will help...

Since the timeout now happened elsewhere, we might consider that in addition.

**Comment by wenzeslaus** [comment]
## Timing

These are times coming directly from the test report generated in the CI.

### The main branch

Test | test_raster_algebra
-- | --
Testsuite | ./temporal/t.rast.algebra
Test file | ./temporal/t.rast.algebra/testsuite/test_raster_algebra.py
Status | succeeded
Return code | 0
Number of tests | 43
Successful tests | 43
Failed tests | 0
Percent successful | 100%
Test duration | 0:03:48.910987
Tested modules | t.rast.algebra

### This PR

Test | test_raster_algebra_part1
-- | --
Testsuite | ./temporal/t.rast.algebra
Test file | ./temporal/t.rast.algebra/testsuite/test_raster_algebra_part1.py
Status | succeeded
Return code | 0
Number of tests | 20
Successful tests | 20
Failed tests | 0
Percent successful | 100%
Test duration | 0:02:41.177489
Tested modules | t.rast.algebra


Test | test_raster_algebra_part2
-- | --
Testsuite | ./temporal/t.rast.algebra
Test file | ./temporal/t.rast.algebra/testsuite/test_raster_algebra_part2.py
Status | succeeded
Return code | 0
Number of tests | 23
Successful tests | 23
Failed tests | 0
Percent successful | 100%
Test duration | 0:02:42.036689
Tested modules | t.rast.algebra

Total: 5 min 23 sec (setup happens once for each test)

**Comment by wenzeslaus** [comment]
> ...I have split it (thematically) into two files...Personally I prefer shorter files anyway.

Since you were able to split them thematically can you please name them that way. Splitting the long file thematically is actually best regardless of the times.

**Comment by neteler** [comment]
Files renamed:

- `test_raster_algebra_part1.py` --> `test_raster_algebra_arithmetic.py`
- `test_raster_algebra_part2.py` --> `test_raster_algebra_operators.py`

**Review by wenzeslaus — APPROVED** [review]
I can't really evaluate the names, but the names and shorter files are nice. Let's merge it.

**Pull request merged**
