### PR TITLE
make: Add support for Makefile variable DESTDIR

### PR DESCRIPTION
**Pull request by nilason**
This PR adds support for staged installs with the addition of the Makefile variable `DESTDIR`.

Support of `DESTDIR` is "strongly recommended"  for packages support  by [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/DESTDIR.html). See also automake documentation [2.2.10 Building Binary Packages Using DESTDIR](https://www.gnu.org/software/automake/manual/html_node/DESTDIR.html) and [12.4 Staged Installs](https://www.gnu.org/software/automake/manual/html_node/Staged-Installs.html).

This addresses [trac ticket 764 (open)](https://trac.osgeo.org/grass/ticket/764) and [trac ticket 1839 (closed)](https://trac.osgeo.org/grass/ticket/1839), regarding issues with MacPorts build of GRASS GIS.

The problem with missing `DESTDIR` support was also discussed in [Red Hat Bugzilla – Bug 1739908](https://bugzilla.redhat.com/show_bug.cgi?id=1739908).

Using `DESTDIR` in packaging systems is mentioned in e.g. [MacPorts Documentation: 5.3. Port Phases](https://guide.macports.org/chunked/reference.phases.html) and Fedora Packaging Guidelines [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/) and [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_why_the_makeinstall_macro_should_not_be_used).

This is a modification of https://github.com/macports/macports-ports/blob/4e2a26e42de94067ac78b3f26dbb54d5931158e0/gis/grass7/files/patch-Install_make.diff
originally created by @Veence.

I have successfully tested this locally with an ordinary `./configure | make | make install` kind of build, as well as a MacPorts port on Mac.

#### How to use and test `DESTDIR`

In short: e.g. `make DESTDIR=/home/stagedir install` will install GRASS GIS into `/home/stagedir`, not into `$prefix`. Compiling and linking will not be affected, the files will only be "copied" into `DESTDIR` in the end.
:exclamation: If `DESTDIR` is **not** defined as in `make install`, installation will proceed as expected to `$prefix`.

Test:
```sh
# given default prefix=/usr/local
./configure [...]
make
make install                              # should not give (unexpected) errors 
make DESTDIR=/home/stagedir install       # should not give (unexpected) errors and similar log as previous command
diff -rq /usr/local/grass79 /home/stagedir/usr/local/grass79     # should show no difference
diff /usr/local/bin/grass79 /home/stagedir/usr/local/bin/grass79 # should show no difference

# remove installed
rm /usr/local/bin/grass79
rm -rf /usr/local/grass79

# undo this PR, i.e. revert the `include/Make/Install.make` file
# then install again and diff against previous staged version
make install
diff -rq /usr/local/grass79 /home/stagedir/usr/local/grass79     # should show no difference
diff /usr/local/bin/grass79 /home/stagedir/usr/local/bin/grass79 # should show no difference
```

### CODE REVIEW

**Comment by neteler** [comment]
> This PR adds support for staged installs with the addition of the Makefile variable `DESTDIR`.
> ...
> The problem with missing `DESTDIR` support was also discussed in [Red Hat Bugzilla – Bug 1739908](https://bugzilla.redhat.com/show_bug.cgi?id=1739908).

Once accepted, then this related packaging patch can be removed: https://src.fedoraproject.org/rpms/grass/blob/rawhide/f/grass-7.8.0-buildroot.diff

**Comment by neteler** [comment]
Tests on Linux (Fedora):

```
# this should fail, expectedly:
cd grass78/
mkdir /tmp/grass78/

make DESTDIR=/tmp/grass78 install
/home/mneteler/software/grass78/bin.x86_64-pc-linux-gnu/grass78
make install-check-built
make[1]: Entering directory '/home/mneteler/software/grass78'
make[1]: Leaving directory '/home/mneteler/software/grass78'
make install-check-parent
make[1]: Entering directory '/home/mneteler/software/grass78'
ERROR: Directory /usr/local is a parent directory of your
  install directory /usr/local/grass78 and is not writable.
  Perhaps you need root access.
  Installation aborted, exiting Make.
make[1]: *** [include/Make/Install.make:53: install-check-parent] Error 1
make[1]: Leaving directory '/home/mneteler/software/grass78'
make: *** [include/Make/Install.make:36: install] Error 2
```

Test of PR:

```
cd grass_master/
mkdir /tmp/grass79/

make DESTDIR=/tmp/grass79 install
/home/mneteler/software/grass_master/bin.x86_64-pc-linux-gnu/grass79
make install-check-built
make[1]: Entering directory '/home/mneteler/software/grass_master'
...
make real-install
make[1]: Entering directory '/home/mneteler/software/grass_master'
mkdir -p -m 755 /tmp/grass79/usr/local/grass79
mkdir -p -m 755 /tmp/grass79/usr/local/bin
tar cBCf /home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu - . | tar xBCf /tmp/grass79/usr/local/grass79 - 2>/dev/null
rm /tmp/grass79/usr/local/grass79/grass79.tmp
make /tmp/grass79/usr/local/bin/grass79
make[2]: Entering directory '/home/mneteler/software/grass_master'
sed -e 's#'@GISBASE@'#'/usr/local/grass79'#g' \
    -e 's#'@LD_LIBRARY_PATH_VAR@'#'LD_LIBRARY_PATH'#g' \
    -e 's#'@CONFIG_PROJSHARE@'#'/usr/share/proj'#g' \
    /home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/grass79.tmp > /tmp/grass79/usr/local/bin/grass79
chmod a+x /tmp/grass79/usr/local/bin/grass79
make[2]: Leaving directory '/home/mneteler/software/grass_master'
rm /tmp/grass79/usr/local/grass79/etc/fontcap
...
sed -e 's#^\(GRASS_HOME.[^=]*\).*#\1= /usr/local/grass79#g' -e 's#/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu#/usr/local/grass79#g' /home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/include/Make/Platform.make > /tmp/grass79/usr/local/grass79/include/Make/Platform.make
make[2]: Leaving directory '/home/mneteler/software/grass_master'
rm /tmp/grass79/usr/local/grass79/include/Make/Grass.make
make /tmp/grass79/usr/local/grass79/include/Make/Grass.make
make[2]: Entering directory '/home/mneteler/software/grass_master'
sed -e 's#^\(ARCH_DISTDIR.[^=]*\).*#\1= /usr/local/grass79#g' -e 's#^\(ARCH_BINDIR.[^=]*\).*#\1= /usr/local/bin#g' /home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/include/Make/Grass.make > /tmp/grass79/usr/local/grass79/include/Make/Grass.make
make[2]: Leaving directory '/home/mneteler/software/grass_master'
chmod -R a+rX /tmp/grass79/usr/local/grass79 2>/dev/null
make[1]: Leaving directory '/home/mneteler/software/grass_master'

```

Note that an endless loop occurs if `DESTDIR` does not exist yet. A _does-DESTDIR-exist_ test would be helpful.

However, I cannot start it:

```
/tmp/grass79/usr/local/bin/grass79 
Starting GRASS GIS...
Traceback (most recent call last):
  File "/tmp/grass79/usr/local/bin/grass79", line 2497, in <module>
    main()
  File "/tmp/grass79/usr/local/bin/grass79", line 2371, in main
    last_mapset_usable = can_start_in_gisrc_mapset(
  File "/tmp/grass79/usr/local/bin/grass79", line 1186, in can_start_in_gisrc_mapset
    from grass.grassdb.checks import can_start_in_mapset
ModuleNotFoundError: No module named 'grass'
```

Probably due to
https://github.com/OSGeo/grass/blob/13f85ff6d77d30d31541ef6f4d6f9ee1542ded94/lib/init/grass.py#L90

which still results in my installation in

```
grep /usr/local /tmp/grass79/usr/local/bin/grass79
    GISBASE = os.path.normpath("/usr/local/grass79")
```
?

**Comment by nilason** [comment]
Thanks for testing this. I will take a look at the issues re. non-existing directory you mentioned.
For now, only a brief note on:

> However, I cannot start it:
> 
> ```
> /tmp/grass79/usr/local/bin/grass79 
> Starting GRASS GIS...
> Traceback (most recent call last):
>   File "/tmp/grass79/usr/local/bin/grass79", line 2497, in <module>
>     main()
>   File "/tmp/grass79/usr/local/bin/grass79", line 2371, in main
>     last_mapset_usable = can_start_in_gisrc_mapset(
>   File "/tmp/grass79/usr/local/bin/grass79", line 1186, in can_start_in_gisrc_mapset
>     from grass.grassdb.checks import can_start_in_mapset
> ModuleNotFoundError: No module named 'grass'
> ```

It not supposed to work from this staging place, which is only an intermediate directory (as opposed to running from source dir, like `./bin.xxxx/grass79`). All linking are made to whatever install path ($prefix) is used. But if you move/copy the content from DESTDIR to $prefix it should work from that point.
For example, move:
 `/tmp/grass79/usr/local/grass79 ` to `/usr/local/grass79` and
`/tmp/grass79/usr/local/bin/grass79` to `/usr/local/bin/grass79`
and *then* try to start `/usr/local/bin/grass79`.
This is also the way packaging systems use this staging dir.

**Comment by nilason** [comment]
> Note that an endless loop occurs if DESTDIR does not exist yet. A does-DESTDIR-exist test would be helpful.

This is now addressed with added commit. DESTDIR is created if it doesn't exist.

**Comment by neteler** [comment]
> It not supposed to work from this staging place, which is only an intermediate directory (as opposed to running from source dir, like `./bin.xxxx/grass79`). All linking are made to whatever install path ($prefix) is used.

Ah, got it now, thanks!

**Review by neteler — APPROVED** [review]
Works nicely!

**Comment by nilason** [comment]
> Works nicely!

Great!

**Comment by nilason** [comment]
If there are no objections I will merge this soon.

May be a candidate for backporting, but let's wait and see if there are any unintended side effects.

**Comment by nilason** [comment]
@neteler Thank you for the review!

**Comment by nilason** [comment]
This has been in the wild on master for some time now. It appears to cause no problems.
Any objection to backport this for 7.8.6? Anyone, @neteler ?

Would be good to get rid of the MacPorts patch (to this effect) with next release.

**Comment by neteler** [comment]
No objection from my side (just to keep in mind that the related patch in the Fedora build process must be removed from the SPEC file - maybe likewise for other distros).

**Comment by nilason** [comment]
> No objection from my side (just to keep in mind that the related patch in the Fedora build process must be removed from the SPEC file - maybe likewise for other distros).

Good. Now I backported to 7.8. Thanks!

**Pull request merged**
