### PR TITLE
utils: module HTML man page use hamburger menu TOC for screen width < 1024 px

### PR DESCRIPTION
**Pull request by tmszi**
Module HTML man page use hamburger menu TOC https://github.com/OSGeo/grass/issues/2589#issuecomment-1265416989 for screen width < 1024 px.

### CODE REVIEW

**Comment by tmszi** [comment]
How to test this PR:

Core module HTML man page:
 
1. Compile GG with this branch
2. Launch GG
3. `GRASS nc_spm_08_grass7/landsat:~ > firefox-bin $GISBASE/docs/html/v.surf.rst.html`
4. Switch to responsive design in the Mozilla Firefox by Ctrl + Shift + M the keyboard shortcut
5. Change responsive design screen size < 1024 px
6. Test hamburger menu

Addon HTML man page:

3. `g.extension db.join`
4. `GRASS nc_spm_08_grass7/landsat:~ > firefox-bin $GRASS_ADDON_BASE/docs/html/db.join.html `
5. Switch to responsive design in the Mozilla Firefox by Ctrl + Shift + M the keyboard shortcut
6. Change responsive design screen size < 1024 px
7. Test hamburger menu

**Comment by neteler** [comment]
I tested it locally, the menu looks good (incl. submenus!):
- it seems that ```docs/html/hamburger_menu*.svg``` files aren't installed yet via Makefile.

**Comment by tmszi** [comment]
>     * it seems that `docs/html/hamburger_menu*.svg` files aren't installed yet via Makefile.

Yes, you are right. I had these files copied manually. Thanks for the tip. Fixed with https://github.com/OSGeo/grass/pull/2606/commits/6eb28565183d2cea141eec48fcc19353ab22db50.

**Comment by neteler** [comment]
image

... looks good to me!

**Review by neteler — APPROVED** [review]

**Comment by neteler** [comment]
@tmszi:  I just realize it now: the SVG also need to be installed in the `manuals/addons/` subdir:

https://grass.osgeo.org/grass82/manuals/addons/hamburger_menu.svg -> 404

**Comment by tmszi** [comment]
> @tmszi: I just realize it now: the SVG also need to be installed in the `manuals/addons/` subdir:
> 
> https://grass.osgeo.org/grass82/manuals/addons/hamburger_menu.svg -> 404

When I tested it locally (addon installation), these two lines https://github.com/OSGeo/grass/pull/2606/commits/15d5178e8b6b2e157e13285e5f5df688b7861b24 fixed this issue.

**Comment by tmszi** [comment]
@neteler We need add these two images here https://github.com/OSGeo/grass-addons/blob/grass8/utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh#L303.

**Comment by tmszi** [comment]
I found these pages doesn't have hamburger menu TOC:

https://grass.osgeo.org/grass82/manuals/full_index.html

https://grass.osgeo.org/grass82/manuals/keywords.html

**Pull request merged**
