### PR TITLE
Add GitHub Actions with build, test, and Python static code analysis

### PR DESCRIPTION
**Pull request by wenzeslaus**
This simply cherry picks 4bb3a3ad and 39415e87bf from master.

It runs Flake8, but ignores most of the errors. It is still helpful for catching some very serious ones like syntax errors.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
For the tests to be at least somewhat useful without checking the result manually, this will require backport of 6962e31 (`grass.gunittest.main ... --min-success`).

**Comment by wenzeslaus** [comment]
To make running tests even more useful, it would be good to include or subsequently backport also #585.

**Comment by neteler** [comment]
> To make running tests even more useful, it would be good to include or subsequently backport also #585.

Since 7.8.3 is out, pls backport as needed.

**Comment by ninsbl** [comment]
Currently builds with Ubuntu 16.04 fail while 18.04 works.
Problems are with Python dependencies. Amongst others I found the error message:
ModuleNotFoundError: No module named 'six'
 E.g. line 10415 here: https://github.com/ninsbl/grass/runs/652446206

Apart from this, it is really cool to have these checks in place, so many thanks for your effort with that!

**Comment by wenzeslaus** [comment]
> Currently builds with Ubuntu 16.04 fail while 18.04 works.

Yes, the Ubuntu 16.04 job sometimes fails, emphasis on the sometimes. Look around on different branches and repos. It has never failed on the [master](https://github.com/OSGeo/grass/commits/master) (*yet*) and, for example, it runs just fine in this PR or in #596 which is from master. Nevertheless, it happened several times already (@neteler was the first one to notice). I even got it for another repo which is compiling GRASS. Re-running the job helped in my case, so you can try that just to get the green checkbox.

> ModuleNotFoundError: No module named 'six'

Right, that's the error and we were not able to find anything more in the logs yet. Something bad is happening somewhere, so it would be good to get that resolved. You can see this specific problem to a lot in different repos, questions, and issues not related to GitHub Actions or GRASS GIS with both pip and apt. Reinstalling six helped according to the internet, but that seems like a strange solution for CI. From our experience, it seems it is specific to Ubuntu 16.04, but I did not follow that lead. 

Anyway, this is not directly related to this PR. Please, open a new issue if needed. I'm merging this now.

> ...it is really cool to have these checks in place...

Thanks!

**Comment by wenzeslaus** [comment]
Just for the record: There seems to be a consistent pattern of two more test files succeeding on Ubuntu 16.04 in comparison to Ubuntu 18.04.

Ubuntu 16.04:

```
Executed 235 test files in 0:32:45.178398.
From them 214 files (91%) were successful and 21 files (9%) failed.
```

Ubuntu 18.04:

```
Executed 235 test files in 0:38:49.221152.
From them 212 files (90%) were successful and 23 files (10%) failed.
```

The tests are set in 7.8 branch to consider <90% as a failure.

**Comment by mlennert** [comment]
Is there actually a specific reason why we need to support Ubuntu 16.04 ?

**Comment by wenzeslaus** [comment]
Ubuntu 16.04 is one of the two Linux VMs available in GitHub Actions and it is still an active [LTS](https://wiki.ubuntu.com/Releases). If the errors start happening in the main repo or the noise prevents us from reviewing PRs and we still don't know how to fix it, then I would say let's remove it.

**Pull request merged**
