### PR TITLE
wxGUI/datacatalog: enable lazy loading of maps

### PR DESCRIPTION
**Pull request by petrasovaa**
Lazy loading (#1403) can be enabled in settings (General page). When lazy loading is used, only current mapset's content is loaded. Any db/location/mapset node have option in context menu to reload the content, alternatively double click on mapset reloads content.

If loading takes too long (> 5 s), infobar with suggestion to change the settings shows up.

### CODE REVIEW

**Comment by HuidaeCho** [comment]
Thanks for the PR. Just tested it. By default without the lazyLoading setting in `$HOME/.grass7/wx` (?), it was still slow, so the default is full loading, I think. I added `datacatalog;lazyLoading;enabled;True` to `$HOME/.grass7/wx`, but still the same. Not the right place for this setting? So I tried to open Preferences, but it didn't open anymore. Without this PR, Preferences works fine. I force returned True from `_useLazyLoading()` and voila! 5 seconds from typing `g.gui` to ready! Awesome!

I found `$HOME/.grass7/wx.json` and added the lazyLoading to datacatalog. That worked! Is `$HOME/.grass7/wx` obsolete now and can I safely delete it?

I think once the Preferences window is fixed, this PR is good to go. Maybe, default to lazy loading without this setting, but that's not critical.

**Comment by petrasovaa** [comment]
> Thanks for the PR. Just tested it. By default without the lazyLoading setting in `$HOME/.grass7/wx` (?), it was still slow, so the default is full loading, I think. I added `datacatalog;lazyLoading;enabled;True` to `$HOME/.grass7/wx`, but still the same. Not the right place for this setting? So I tried to open Preferences, but it didn't open anymore. Without this PR, Preferences works fine. I force returned True from `_useLazyLoading()` and voila! 5 seconds from typing `g.gui` to ready! Awesome!
> 
Could you post the error you get when opening Preferences? I don't think I was having any problem.

Have you tested the on-demand loading of layers (right click on mapset/location/db)?

> I found `$HOME/.grass7/wx.json` and added the lazyLoading to datacatalog. That worked! Is `$HOME/.grass7/wx` obsolete now and can I safely delete it?

Yes.
> 
> I think once the Preferences window is fixed, this PR is good to go. Maybe, default to lazy loading without this setting, but that's not critical.

The idea is to default to full loading to make things easier for new users who don't have many maps. One other thing is to automatically track how long it takes to load it and if it takes too long (e.g. 5 or 10 s?) it would suggest you to apply this setting.

This is also draft because there are still some issues to solve (e.g. when you drag a map to unloaded mapset, it needs to load etc).

**Comment by HuidaeCho** [comment]
> > Thanks for the PR. Just tested it. By default without the lazyLoading setting in `$HOME/.grass7/wx` (?), it was still slow, so the default is full loading, I think. I added `datacatalog;lazyLoading;enabled;True` to `$HOME/.grass7/wx`, but still the same. Not the right place for this setting? So I tried to open Preferences, but it didn't open anymore. Without this PR, Preferences works fine. I force returned True from `_useLazyLoading()` and voila! 5 seconds from typing `g.gui` to ready! Awesome!
> 
> Could you post the error you get when opening Preferences? I don't think I was having any problem.

I didn't get any errors. Now, it works after setting the setting manually.

> 
> Have you tested the on-demand loading of layers (right click on mapset/location/db)?
>

`Reload maps` and double clicking work fine.

> > I found `$HOME/.grass7/wx.json` and added the lazyLoading to datacatalog. That worked! Is `$HOME/.grass7/wx` obsolete now and can I safely delete it?
> 
> Yes.
> 
> > I think once the Preferences window is fixed, this PR is good to go. Maybe, default to lazy loading without this setting, but that's not critical.
> 
> The idea is to default to full loading to make things easier for new users who don't have many maps. One other thing is to automatically track how long it takes to load it and if it takes too long (e.g. 5 or 10 s?) it would suggest you to apply this setting.
> 
> This is also draft because there are still some issues to solve (e.g. when you drag a map to unloaded mapset, it needs to load etc).

I see.

**Comment by petrasovaa** [comment]
> > The idea is to default to full loading to make things easier for new users who don't have many maps. One other thing is to automatically track how long it takes to load it and if it takes too long (e.g. 5 or 10 s?) it would suggest you to apply this setting.
> > This is also draft because there are still some issues to solve (e.g. when you drag a map to unloaded mapset, it needs to load etc).
> 
Should be resolved now, it should suggest setting the lazy loading in an infobar (if loading takes more than 5 s). If you get some issues with settings/preferences window, try to remove the 'datacatalog' part in the wx.json. I tried to ensure it works, but there still might be some issues.

**Comment by lindakladivova** [comment]
Do we need to show infobar? It seems to me very likely that a user would prefer to use lazy loading (when loading takes more than 5 sec)... I am not sure if the infobar cannot be rather confusing (with very long description and button titles)... but not sure. Generally, I like this PR. :-)

**Comment by petrasovaa** [comment]
> Do we need to show infobar? It seems to me very likely that a user would prefer to use lazy loading (when loading takes more than 5 sec)... I am not sure if the infobar cannot be rather confusing (with very long description and button titles)... but not sure. Generally, I like this PR. :-)

There are couple options. Lazy loading could be the default, I am not sure that's best for newcomers. If full loading is default, automatically switching to lazy loading without informing users could be confusing, so that's how I ended up with the infobar. But this is certainly open for discussion.

**Comment by veroandreo** [comment]
Ok, I got the info bar

image

but clicking over any of the options has no effect and I get this in the Console tab:

```
Traceback (most recent call last):
  File
"/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-
gnu/gui/wxpython/core/settings.py", line 1228, in Set

settings[group][key][subkey] = value
KeyError
:
'lazyLoading'
During handling of the above exception, another exception
occurred:
Traceback (most recent call last):
  File
"/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-
gnu/gui/wxpython/datacatalog/catalog.py", line 113, in
_saveLazyLoadingOnSettings

UserSettings.Set(group='datacatalog',
  File
"/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-
gnu/gui/wxpython/core/settings.py", line 1230, in Set

raise GException("%s '%s:%s:%s'" %
core.gcmd
.
GException
:
Unable to set  'datacatalog:lazyLoading:enabled'
```

and when I close the info bar and go to Preferences, I get nothing (i.e., no window with the settings) and this error in the console tab:

```
Traceback (most recent call last):
  File
"/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-
gnu/gui/wxpython/core/settings.py", line 1228, in Set

settings[group][key][subkey] = value
KeyError
:
'lazyLoading'
During handling of the above exception, another exception
occurred:
Traceback (most recent call last):
  File
"/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-
gnu/gui/wxpython/datacatalog/catalog.py", line 113, in
_saveLazyLoadingOnSettings

UserSettings.Set(group='datacatalog',
  File
"/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-
gnu/gui/wxpython/core/settings.py", line 1230, in Set

raise GException("%s '%s:%s:%s'" %
core.gcmd
.
GException
:
Unable to set  'datacatalog:lazyLoading:enabled'
```

**Comment by petrasovaa** [comment]
@veroandreo thanks for catching this, could you please try again?

**Comment by veroandreo** [comment]
Works fine now, no errors in the console tab and I can enable lazy loading both from the info bar and settings-->preferences

**Review by veroandreo — APPROVED** [review]

**Comment by petrasovaa** [comment]
> Works fine now, no errors in the console tab and I can enable lazy loading both from the info bar and settings-->preferences

Thanks, I will merge now and we can discuss any changes to the behavior when more people get to test it.

**Pull request merged**
