### PR TITLE
README: fix link in travis-ci badge

### PR DESCRIPTION
**Pull request by veroandreo**

### CODE REVIEW

**Comment by petrasovaa** [comment]
Looks like the binder badge in Description is not working either, would you mind fixing it?

**Comment by veroandreo** [comment]
> Looks like the binder badge in Description is not working either, would you mind fixing it?

Should be fixed now

**Review by petrasovaa — APPROVED** [review]

**Comment by nilason** [comment]
This line also could be fixed while you're there:

```md
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](code_of_conduct.md)
```

to:
```md
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](CODE_OF_CONDUCT.md)
```

**Comment by nilason** [comment]
@veroandreo You will need to "Update branch" to include the [fix for Windows CI runner](https://github.com/OSGeo/grass/commit/0ec833ce53f7227dab55cb0f7d9090af7ebe898d) to be able to merge this.

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
