### PR TITLE
g.proj: Fix Cannot find proj.db

### PR DESCRIPTION
**Pull request by HuidaeCho**
```
proj_get_authorities_from_database: Cannot find proj.db
make: *** [../../include/Make/Html.make:14: g.proj.tmp.html] Error 1
```

Proj >= 6 requires proj.db in PROJ_LIB.

### CODE REVIEW

**Comment by neteler** [comment]
@HuidaeCho which operating system do you use?
@metzm apparently it worked for you without this change on Fedora?

**Comment by hellik** [comment]
How to test in winGRASS? winGRASS already switched to Proj >= 6  as default. Dailys are built.

**Comment by HuidaeCho** [comment]
I had this problem with winGRASS. If you already have PROJ_LIB set outside GRASS, you won't see this issue.

**Comment by HuidaeCho** [comment]
This is how I compile winGRASS:
```
sed -e 's/-lproj/-lproj_6_2/g' configure > myconfigure
OSGEO4W_ROOT_MSYS=/c/osgeo4w64 \
./myconfigure \
--host=$MINGW_CHOST \
--with-nls \
--with-includes=/c/osgeo4w64/include \
--with-libs='/c/osgeo4w64/lib /c/osgeo4w64/bin' \
--with-proj-share=/c/osgeo4w64/share/proj \
--with-gdal=$HOME/usr/grass/grass/mswindows/osgeo4w/gdal-config \
--with-opengl=windows \
--with-freetype-includes=/c/osgeo4w64/include/freetype2 \
--with-geos=$HOME/usr/grass/grass/mswindows/osgeo4w/geos-config \
--with-netcdf=$HOME/usr/grass/nc-config \
--with-liblas=$HOME/usr/grass/grass/mswindows/osgeo4w/liblas-config

make
```
I don't have the PROJ_LIB environment variable outside GRASS. Maybe, you could replicate this issue by running
```
PROJ_LIB= make
```
from general/g.proj?

**Comment by HuidaeCho** [comment]
I don't think it's a problem with GRASS_PROJSHARE. https://proj.org/faq.html#why-am-i-getting-the-error-cannot-find-proj-db Proj>=6 uses PROJ_LIB to find proj.db. When the user doesn't have this environment variable defined when compiling GRASS (winGRASS or not), I think we'll encounter this issue. The only place we set this variable is mswindows/env.bat and mswindows/osgeo/env.bat.tmpl. I don't think we run any of these batch files when building winGRASS. That basically requires either (1) this commit or (2) PROJ_LIB defined by the compiling user.

**Comment by hellik** [comment]
https://github.com/OSGeo/grass/blob/master/mswindows/osgeo4w/package.sh#L66

```fetchenv $OSGEO4W_ROOT_MSYS/bin/o4w_env.bat```

package.sh calls _o4w_env.bat_ for winGRASS compilation, which does 

```for %%f in ("%OSGEO4W_ROOT%\etc\ini\*.bat") do call "%%f"```

and calls C:\OSGeo4W64\etc\ini\proj.bat and set:

```SET PROJ_LIB=%OSGEO4W_ROOT%\share\proj```

> I don't think we run any of these batch files when building winGRASS. That basically requires either (1) this commit or (2) PROJ_LIB defined by the compiling user.

at least for winGRASS builds on Martin's build server and other compiling user following the [instructions](https://trac.osgeo.org/grass/wiki/CompileOnWindows), _PROJ_LIB_ is correctly set.

**Comment by hellik** [comment]
> I don't have the PROJ_LIB environment variable outside GRASS. Maybe, you could replicate this issue by running

here in the OSGeo4W shell, outside a winGRASS session:

```
C:\>echo %PROJ_LIB%
C:\OSGEO4~1\share\proj
```

**Comment by hellik** [comment]
> That basically requires either (1) this commit or (2) PROJ_LIB defined by the compiling user.

not sure this PR is really needed, as PROJ_LIB is correctly set when compiling user follow the [instructions](https://trac.osgeo.org/grass/wiki/CompileOnWindows).

if compiling users do another way to compile winGRASS, it's up to them to define PROJ_LIB.

**Comment by HuidaeCho** [comment]
> https://github.com/OSGeo/grass/blob/master/mswindows/osgeo4w/package.sh#L66
> 
> `fetchenv $OSGEO4W_ROOT_MSYS/bin/o4w_env.bat`
> 
> package.sh calls _o4w_env.bat_ for winGRASS compilation, which does
> 
> `for %%f in ("%OSGEO4W_ROOT%\etc\ini\*.bat") do call "%%f"`
> 
> and calls C:\OSGeo4W64\etc\ini\proj.bat and does:
> 
> `SET PROJ_LIB=%OSGEO4W_ROOT%\share\proj`
> 
> > I don't think we run any of these batch files when building winGRASS. That basically requires either (1) this commit or (2) PROJ_LIB defined by the compiling user.
> 
> at least for winGRASS builds on Martin's build server and other compiling user following the [instructions](https://trac.osgeo.org/grass/wiki/CompileOnWindows), _PROJ_LIB_ is correctly set.

Ah! o4w_env.bat sets PROJ_LIB. OK, using package.sh should be fine and I agree that it's the user's responsibility to set it. Do we have a similar mechanism for non-winGRASS?

**Comment by HuidaeCho** [comment]
> > I don't have the PROJ_LIB environment variable outside GRASS. Maybe, you could replicate this issue by running
> 
> here in the OSGeo4W shell, outside a winGRASS session:
> 
> ```
> C:\>echo %PROJ_LIB%
> C:\OSGEO4~1\share\proj
> ```

I thought that the instructions say we should use MSYS2 to compile it, not the OSGeo4W shell.

**Comment by HuidaeCho** [comment]
> > That basically requires either (1) this commit or (2) PROJ_LIB defined by the compiling user.
> 
> not sure this PR is really needed, as PROJ_LIB is correctly set when compiling user follow the [instructions](https://trac.osgeo.org/grass/wiki/CompileOnWindows).
> 
> if compiling users do another way to compile winGRASS, it's up to them to define PROJ_LIB.

I agree with you if we require the user to set PROJ_LIB properly in non-windows environments (package.sh does it for winGRASS). Maybe, that's a reasonable assumption when they have Proj 6 installed already and it should just work without this commit. I'll take care of it on my side ;-).

**Comment by hellik** [comment]
>I thought that the instructions say we should use MSYS2 to compile it, not the OSGeo4W shell.

yes, following the instructions, MSYS2 is the way to go. 

it was just an example, that PROJ_LIB is set correctly when OSGeo4W is used as a kind of subsystem when compiling winGRASS via MSYS2. ;-)

**Comment by hellik** [comment]
>Do we have a similar mechanism for non-winGRASS?

I would say yes; when linux distros switch to proj6/gdal6, every env variable should be set correctly.

**Comment by HuidaeCho** [comment]
> > Do we have a similar mechanism for non-winGRASS?
> 
> I would say yes; when linux distros switch to proj6/gdal6, every env variable should be set correctly.

Agreed!

**Comment by HuidaeCho** [comment]
mswindows/osgeo4w/package.sh calls /c/osgeo4w64/bin/o4w_env.bat to set PROJ_LIB. For non-winGRASS, it's the system's or user's responsibility to correctly set up Proj 6. This commit is not necessary.

**Pull request closed without merging**
