### PR TITLE
wxGUI/datacatalog: flatten mapset-layer hierarchy, add icons for types, highlight current

### PR DESCRIPTION
**Pull request by petrasovaa**
Changes:

* instead of dividing layers by type (e.g. PERMANENT -> raster -> elevation) have all layers together, now distinguished  by icons
* added icons for all items
* highlight by bold font current db, location and mapset

GRASS GIS Data Catalog_018

### CODE REVIEW

**Comment by petrasovaa** [comment]
@mlennert, @landam I don't need code review necessarily, just general feedback.

**Comment by mlennert** [comment]
> @mlennert, @landam I don't need code review necessarily, just general feedback. 

I really like the idea !

**Comment by ninsbl** [comment]
Yes, sounds like a good idea. Maybe out of scope for this PR, but could you add the number of maps  after the mapset name?
Background: I have some mapsets with time series containing >25000 maps in a multiuser environment. If colleagues expand them they have to wait for some time ...

BTW, does the data catalogue support STDS?

**Comment by petrasovaa** [comment]
> Yes, sounds like a good idea. Maybe out of scope for this PR, but could you add the number of maps after the mapset name?
> Background: I have some mapsets with time series containing >25000 maps in a multiuser environment. If colleagues expand them they have to wait for some time ...
> 

Sounds like a new feature request. Please create an issue and we should probably discuss how it should behave. E.g., it could ask you if you really want to see all the maps.

> BTW, does the data catalogue support STDS?

Please create a new issue. Again, there are couple options how it should behave. Neither of these issues are directly related to GSoC, so it would depend if we (or somebody else) have time for this.

**Pull request merged**
