### PR TITLE
wxGUI: add dark mode support for command output

### PR DESCRIPTION
**Pull request by nilason**
This PR adds dark mode support for command output.

Tested with `Python 3.8.3 + wxPython 4.0.7.post2` and `Python 3.7.3 + wxPython 4.1.0` on mac.

Known limitations:
- selected text highlight color doesn't change on-the-fly, need to restart gui
- dark mode on pre-wxPython 4.1 might give difficulties to read warning and error text (by not being able to adapt custom colours)
- output does not change on-the-fly, layout will change on next render (command)

Please, do give it a thorough testing.

### CODE REVIEW

**Comment by petrasovaa** [comment]
Relates to #591 dark theme issue.

**Comment by petrasovaa** [comment]
Looks good, except the output of command. wx.SYS_COLOUR_WINDOW and wx.SYS_COLOUR_BACKGROUND are the same for me (even when tested with default and customized themes on Ubuntu). So the output looks little bit confusing since you can't easily tell the difference between the command output and the rest like this:
Selection_025

Is this different on Mac/Windows?

**Comment by nilason** [comment]
> except the output of command. wx.SYS_COLOUR_WINDOW and wx.SYS_COLOUR_BACKGROUND are the same for me 

This is what I was a bit afraid of. They are different on mac.
The system colours may be viewed conveniently in `wxdemo > System Settings`.

**Comment by nilason** [comment]
How about wx.SYS_COLOUR_DESKTOP?

**Mac default colours:**
mac-colours-default

**Mac dark mode:**
mac-colours-darkmode

**Comment by petrasovaa** [comment]
To correct myself, the default Adwaita theme on Ubuntu, is fine, but only in the light mode. The dark mode has the same color and that seems to be the case for other dark versions of themes I experimented with.
I don't see any which would be greyish and semantically fit. Maybe we can keep the value hardcoded? Alternatively, we could get the sys_color_window and make it darker/lighter depending if the dark mode is active with function https://wxpython.org/Phoenix/docs/html/wx.Colour.html?highlight=changelightness#wx.Colour.ChangeLightness
Selection_026

**Comment by nilason** [comment]
> To correct myself, the default Adwaita theme on Ubuntu, is fine, but only in the light mode. The dark mode has the same color and that seems to be the case for other dark versions of themes I experimented with.
I don't see any which would be greyish and semantically fit. Maybe we can keep the value hardcoded? Alternatively, we could get the sys_color_window and make it darker/lighter depending if the dark mode is active with function https://wxpython.org/Phoenix/docs/html/wx.Colour.html?highlight=changelightness#wx.Colour.ChangeLightness

Let's try hardcoded, after all we want grey. Only font colour will change. Hopefully there will be broader system colour support in the future.

**Pull request merged**
