### PR TITLE
update base_url to current server layout

### PR DESCRIPTION
**Pull request by neteler**
Addresses https://trac.osgeo.org/grass/ticket/3455 for relbranch76

### CODE REVIEW

**Comment by hellik** [comment]
this PR is for relbranch_76;

following [dev ML](https://lists.osgeo.org/pipermail/grass-dev/2019-July/092972.html)

_*grass76

https://wingrass.fsv.cvut.cz/grass76/x86_64/addons/

[DIR]	grass-7.6.svn/	2019-07-25 09:06 	- 	 
[DIR]	latest/	2019-07-25 09:06 	- 	 

https://wingrass.fsv.cvut.cz/grass76/latest/addons/

[DIR]	grass-7.6.svn/	2019-07-25 09:06 	- 	 
[DIR]	latest/	2019-07-25 09:06 	-_ 	

as it a releasebranch, we don't deliver a daily winGRASS 7.6.svn, only a point release like e.g. winGRASS 7.6.1.

so it's not clear, to which directory g.extension should look, _grass-7.6.svn_ or _latest_ ?

a quick comparison of the content of these 2 directories, it seems there are no differences in the hash. thus, both directories may be the same?

**Comment by neteler** [comment]
I believe they are the same (@landam knows) - I suspect them to be a link from one to the next which isn't visible here.
The MD5 sums are the same.

For now we need a workaround, we can beautify it later.

**Comment by hellik** [comment]
tested it with the change of _svn_, the download works.

though, binary/exe doesn't work because of a library mismatch:

_C:\>r.flip --help
FEHLER: Das Module wurde mit Version $Revision$ gebaut, aber versucht
        Version $Revision: 72327 $ zu verwenden. Sie müssen GRASS erneut
        bauen oder verschiedene Installationen entwirren._

**Comment by neteler** [comment]
Yeah, the revision check no longer works. I suppose it needs to be dropped since git does not provide anything similar (AFAIK).

**Comment by hellik** [comment]
so it may need a new ticket for removing revision check?

**Comment by hellik** [comment]
> 
> 
> so it may need a new ticket for removing revision check?

see [trac ticket](https://trac.osgeo.org/grass/ticket/3880) for adapting the revision check.

**Comment by neteler** [comment]
While incomplete I have merged it now - at least the Python scripts should install again.

**Pull request merged**
