### PR TITLE
configure: use pkg-config for FreeType 2

### PR DESCRIPTION
**Pull request by infrastation**
@marisn: as requested and discussed on grass-dev

### CODE REVIEW

**Comment by metzm** [comment]
Thanks for this PR! I always needed to add `--with-freetype-includes=`, this PR solves it.

**Review by nilason — APPROVED** [review]
Nice little improvement! Successfully tested on Mac.

**Comment by nilason** [comment]
> ... as requested and discussed on grass-dev

For the record: https://lists.osgeo.org/pipermail/grass-dev/2021-June/095244.html

**Comment by infrastation** [comment]
Rebased on the latest master branch with a bit more detailed commit message.

**Comment by infrastation** [comment]
Rebased on the latest master branch.

**Review by marisn — APPROVED** [review]

**Comment by nilason** [comment]
@infrastation Could you please rebase against main branch again? There seems to be a hiccup in the Flake8 CI checks, which need to pass before being able to merge. That check is not directly relevant for this particular PR, but nevertheless needed.
This is caused, if I'm not mistaken, by changes in GH settings and GH workflow postdating you last rebase.

**Comment by nilason** [comment]
Thanks @infrastation !
I will merge this in a couple of days if there are no objections.

**Comment by nilason** [comment]
I assume there are no objections to this improvement. Will take the liberty to merge. Thanks @infrastation !

**Pull request merged**
