### PR TITLE
wxGUI: Fix F405 error by explicitly importing required modules in iscatt/

### PR DESCRIPTION
**Pull request by arohanajit**
Fixed all `F405` and `F403` by explicitly importing all the functions. I had to import `ctypes` separately as well since explicit import of `ctypes.c_void_p` wasn't working for some reason. Also updated `ctypes.POINTER` to `POINTER` since its being imported.

### CODE REVIEW

**Review by petrasovaa — DISMISSED** [review]

**Review by echoix — COMMENTED** [review]
While you're at it, would you try to have these new imports following the order of what the tool "isort" would do? But please only keep the changes on like new lines, not reordering existing ones too much.

I already tried to change everywhere, but I didn't manage to have a perfectly tuned config. And made hard to read diffs. But we are still tending towards this.

Using `isort the/file/path.py`, without any config, does a correct enough job to the new lines+their placement, and will greatly reduce the diff of when we will be applying isort everywhere (I hope in the 1-1.5 year timeframe)

**Comment by echoix** [comment]
Remember to run black too after choosing the lines to commit.

**Comment by arohanajit** [comment]
I ran `isort` which sorted the imports and subsequently the `black` which again rearranged them😅. Do you want me to do this for all the files I modify in future or only the ones where I work on `F405`?

**Comment by echoix** [comment]
> I ran `isort` which sorted the imports and subsequently the `black` which again rearranged them😅. Do you want me to do this for all the files I modify in future or only the ones where I work on `F405`?

When adding new imports, or when changing from `*` to explicit imports (so that sub list is sorted).

For this PR, there were two "unexpected" changes where imports not related to this PR got changed. But since they are simple enough, let's just keep it. These changes were the `import numpy as np` that got replaced with the `from ctypes import `, and the `from grass.lib.imagery import * ` that got moved down.

Keep it like this, it's clean that way :)

**Review by echoix — APPROVED** [review]

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
