### PR TITLE
make: remove __pycache__ directories with distclean

### PR DESCRIPTION
**Pull request by nilason**
as reported with https://github.com/OSGeo/grass-addons/pull/740.

### CODE REVIEW

**Review by neteler — APPROVED** [review]
Works nicely, thanks.

**Comment by nilason** [comment]
Should also be backported to 8.2.1.

**Comment by neteler** [comment]
> Should also be backported to 8.2.1.

Done.

**Comment by nilason** [comment]
> > Should also be backported to 8.2.1.
> 
> Done.

Thanks!

**Pull request merged**
