### PR TITLE
r.in.pdal: Fix use of PDAL 2.4 deprecated api

### LINKED ISSUE #2638: [Bug] r.in.pdal uses deprecated declarations from PDAL
**Describe the bug**

Use of `<<` for LasHeader is deprecated (triggers `-Wdeprecated-declarations`) with PDAL 2.4.1 (May 19, 2022).

The `[[deprecated]]` attribute was added in https://github.com/PDAL/PDAL/pull/3682, but only after previous removal (e.g., https://github.com/PDAL/PDAL/pull/3677), but I don't see an announcement or discussion of the removal. The relevant file in PDAL is [LasHeader.hpp](https://github.com/PDAL/PDAL/blob/master/io/LasHeader.hpp#L68).

**To Reproduce**

1. Get PDAL 2.4.0 or higher.
2. Compile r.in.pdal.
4. See the warning.

**Expected behavior**

No compilation warning, but what the code should do, that's up for discussion.

**Screenshots**

Compilation output:

```
info.cpp: In function ‘void print_lasinfo(StringList*)’:
info.cpp:103:22: warning: ‘std::ostream& pdal::operator<<(std::ostream&, const pdal::LasHeader&)’ is deprecated [-Wdeprecated-declarations]
  103 |         std::cout << las_header;
      |                      ^~~~~~~~~~
In file included from info.h:20,
                 from info.cpp:12:
/usr/local/usrapps/geospatial/grass-8.3.0-dev.2022-11-08/include/pdal/io/LasHeader.hpp:288:26: note: declared here
  288 |     friend std::ostream& operator<<(std::ostream& ostr, const LasHeader& h);
      |                          ^~~~~~~~
info.cpp:103:22: warning: ‘std::ostream& pdal::operator<<(std::ostream&, const pdal::LasHeader&)’ is deprecated [-Wdeprecated-declarations]
  103 |         std::cout << las_header;
      |                      ^~~~~~~~~~
In file included from info.h:20,
                 from info.cpp:12:
/usr/local/usrapps/geospatial/grass-8.3.0-dev.2022-11-08/include/pdal/io/LasHeader.hpp:288:26: note: declared here
  288 |     friend std::ostream& operator<<(std::ostream& ostr, const LasHeader& h);
      |                          ^~~~~~~~
```

**System description (please complete the following information):**

- Operating System: [e.g. Windows, Linux, ..., incl. version]
- GRASS GIS version [e.g. 7.8.4]

**Additional context**

This is not currently tested in the CI.

### PR DESCRIPTION
**Pull request by nilason**
Re-used code from PDAL 2.3:

https://github.com/PDAL/PDAL/blob/2.3.0/io/LasHeader.cpp#L524

Fixes #2638

### CODE REVIEW

**Comment by nilason** [comment]
Seems to work fine, only one call:
`h.pointCountByReturn()`
needs to casted somehow...?

**Comment by neteler** [comment]
If possible, could this be backported? In various distros G8.2 will stay for a while...

**Comment by nilason** [comment]
> If possible, could this be backported? In various distros G8.2 will stay for a while...

Shouldn't be any problem!

**Review by marisn — APPROVED** [review]
Didn't run, but code looks OK.

**Comment by nilason** [comment]
Merged and backported.

Thanks @marisn !

**Comment by nilason** [comment]
> Merged and backported.
> 
That is backported to 8.2

**Pull request merged**
