### PR TITLE
wxGUI/xml: update GUI tools toolbox items

### PR DESCRIPTION
**Pull request by tmszi**
gui_tools_toolbox_items

### CODE REVIEW

**Review by petrasovaa — COMMENTED** [review]
Thank you! I am not sure about the data catalog, currently it opens the catalog, however it blocks the console. I am not sure how useful opening the catalog from GUI is since it's already there in the first tab, however it should not block the GUI. So I would suggest maybe writing a simple handler (in lmgr/frame.py) which opens the catalog frame, instead of calling g.gui.datacatalog directly.

**Comment by tmszi** [comment]
> Thank you! I am not sure about the data catalog, currently it opens the catalog, however it blocks the console. I am not sure how useful opening the catalog from GUI is since it's already there in the first tab, however it should not block the GUI. So I would suggest maybe writing a simple handler (in lmgr/frame.py) which opens the catalog frame, instead of calling g.gui.datacatalog directly.

I'm using multiple monitors, and having a Data Catalog (wxGUI component) as a separate window I find it useful (but it isn't common use case).

**Review by petrasovaa — APPROVED** [review]
Looks good, thank you!

**Comment by wenzeslaus** [comment]
> I'm using multiple monitors, and having a Data Catalog (wxGUI component) as a separate window I find it useful (but it isn't common use case).

That's a good point. Multiple screens is actually a use case we want to cover, but perhaps here it should be covered in a different way (e.g., more flexible tabs/detachable windows) and if it is for advanced users, g.gui.datacatalog from command line may be the solution for many. Anyway, let's see how the current implementation works in the wild.

**Pull request merged**
