### PR TITLE
t.rast.accumulate: Remove check of non-existing `range` option

### PR DESCRIPTION
**Pull request by echoix**
Seems like a copy-paste artifact from another module like t.rast.accdetect

See https://github.com/OSGeo/grass/pull/4137#discussion_r1707325256 and the thread

### CODE REVIEW

**Comment by echoix** [comment]
@ninsbl Please check if I understood the same thing as you. I’m not 100% sure if I did it correctly. But I’m sure that it won’t have an impact on the code flow compared to now, as it currently doesn’t do what is expected.

**Comment by veroandreo** [comment]
t.rast.accumulate has upper and lower strds as options. That's for the case when instead fixed limits, users want to pass strds of upper and lower limits for accumulation. It seems however that the message part that you suggest to remove is indeed from t.rast.accdetect and it is not doing anything in t.rast.accumulate.

**Comment by echoix** [comment]
> t.rast.accumulate has upper and lower strds as options. That's for the case when instead fixed limits, users want to pass strds of upper and lower limits for accumulation. It seems however that the message part that you suggest to remove is indeed from t.rast.accdetect and it is not doing anything in t.rast.accumulate.

Do you mean it should be checking another option instead, or removing it is correct? (You can look at the screenshots in the related comment thread)

**Comment by veroandreo** [comment]
> Do you mean it should be checking another option instead, or removing it is correct? (You can look at the screenshots in the related comment thread)

Removing seems correct, as far as I understand.

**Review by veroandreo — APPROVED** [review]

**Pull request merged**
