### PR TITLE
style: Revert "style: Fixes some unnecessary-lambda (PLW0108) (#3956)"

### LINKED ISSUE #4124: [Bug] GUI: all tools are inaccessible from the GUI - main menu, tool tree or console not working
## Describe the bug
Trying to open any tool dialog with double click from the Tool tree pane yields the following error in the console:

```
Traceback (most recent call last):
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/gui_core/treeview.py", line 67, in
<lambda>

lambda evt: self._emitSignal(evt.GetItem(),
self.selectionChanged),


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/gui_core/treeview.py", line 197, in
_emitSignal

signal.emit(node=node, **kwargs)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/signal.py", line 232,
in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/dispatcher.py", line
344, in send

response = robustapply.robustApply(


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/robustapply.py", line
61, in robustApply

return receiver(*arguments, **named)


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/gui_core/menu.py", line 345, in
OnItemSelected

self.showNotification.emit(message=label)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/signal.py", line 232,
in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/dispatcher.py", line
344, in send

response = robustapply.robustApply(


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/main_window/frame.py", line 324, in
SetStatusText

self.statusbar.SetStatusText(*args)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/lmgr/statusbar.py", line 67, in
SetStatusText

self.GetWidget().SetStatusText(*args)
TypeError
:
StatusBar.SetStatusText(): not enough arguments
```

## To reproduce

1. Go to Tools pane in the GUI
2. Double click on any tool, eg. Vector > Topology Maintenance > v.build
3. See error in the Console pane

## System description

```                                                                    
GRASS version: 8.5.0dev                                                         
Code revision: e56c7cddd7                                                       
Build date: 2024-07-30                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.7.1                                                                     
PROJ: 9.2.1                                                                     
GEOS: 3.12.0                                                                    
SQLite: 3.42.0                                                                  
Python: 3.11.6                                                                  
wxPython: 4.2.1                                                                 
Platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.38                          
```

### PR DESCRIPTION
**Pull request by echoix**
This reverts commit 0cc7cbf610e889075b8f465eecb0f319737b7456.

Fixes #4124

### CODE REVIEW

**Review by nilason — APPROVED** [review]

**Comment by echoix** [comment]
@wenzeslaus what should the title prefix be? Can we merge it with an incorrect prefix?

**Comment by wenzeslaus** [comment]
> @wenzeslaus what should the title prefix be? Can we merge it with an incorrect prefix?

Or we allow "Revert " to be a prefix. However, it looks like the revert should be in the same category as the original commit so that you can spot that in the change when reviewing the changes (e.g. in change log).

**Comment by echoix** [comment]
I agree that the default title can be programmatically matched to the reverted PR. But in either case, we (in fact you or a few others with appropriate rights) need to adjust the branch naming restrictions to allow the revert branches to be made in the repo. It was cumbersome to remake that PR manually from a fork, while there is a button in the interface for that already.

**Comment by neteler** [comment]
> I agree that the default title can be programmatically matched to the reverted PR

This would be nice, so original title with "Revert: " prefix.

**Comment by wenzeslaus** [comment]
If we count on programmatic matching rather than human one, then it would make sense to write that logic into the script for generating release notes.

**Comment by echoix** [comment]
> If we count on programmatic matching rather than human one, then it would make sense to write that logic into the script for generating release notes.

But until it becomes a too long of a chore, it can stay manual. It seems quite rare for now.

**Comment by wenzeslaus** [comment]
> ...it can stay manual. It seems quite rare for now.

Then the choice is between having it the corresponding category (with specific prefixes, e.g.,  `style:`, or in the Other category). With `Revert ` it falls to Other which needs to be manually reviewed anyway for other reasons, but it may be far from the reverted change.

**Pull request merged**
