### PR TITLE
howto_release.md: update wingrass notes

### PR DESCRIPTION
**Pull request by landam**
See #2406

### CODE REVIEW

**Comment by landam** [comment]
@wenzeslaus Please review if possible.

**Comment by hellik** [comment]
Shouldn't we in mid/long term move to build winGRASS in GitHub, once cmake building is ready? ;-)

**Review by wenzeslaus — APPROVED** [review]
Looks perfect, thanks!

**Comment by wenzeslaus** [comment]
> Shouldn't we in mid/long term move to build winGRASS in GitHub, once cmake building is ready? ;-)

Yes, but no need to wait for CMake. The compilation already works in CI. The missing pieces are the packaging and addon compilation. Anyway, the purpose of this PR and related issue is to document the current procedure, so it is clear what should be migrated to GitHub.

**Pull request merged**
