### PR TITLE
packaging: improve nix development environment

### PR DESCRIPTION
**Pull request by imincik**
* inherit build dependencies from grass package
* add `dev-help` function

### CODE REVIEW

**Comment by imincik** [comment]
@echoix , I am not sure about commit message prefix. 

Maybe, we can add `nix` prefix to [Packaging, ... category](https://github.com/OSGeo/grass/blob/5d25c53517ab6eb339ad07177cfc8ec9d79f0df8/utils/release.yml#L36)

**Comment by echoix** [comment]
> @echoix , I am not sure about commit message prefix. 
> 
> 
> 
> Maybe, we can add `nix` prefix to [Packaging, ... category](https://github.com/OSGeo/grass/blob/5d25c53517ab6eb339ad07177cfc8ec9d79f0df8/utils/release.yml#L36)

Yes, I think it's good to add it, you could add it in this PR if it this PR won't be backported or cause problems with backporting. In that case, the check will stay failed until merged, since it is using pull_request_target trigger.

**Comment by imincik** [comment]
> > @echoix , I am not sure about commit message prefix.
> > Maybe, we can add `nix` prefix to [Packaging, ... category](https://github.com/OSGeo/grass/blob/5d25c53517ab6eb339ad07177cfc8ec9d79f0df8/utils/release.yml#L36)
> 
> Yes, I think it's good to add it, you could add it in this PR if it this PR won't be backported or cause problems with backporting. In that case, the check will stay failed until merged, since it is using pull_request_target trigger.

Done is [separate PR](https://github.com/OSGeo/grass/pull/3925) to avoid conflicts and failed tests.

**Comment by imincik** [comment]
This PR can be merged now.

**Review by echoix — APPROVED** [review]

**Pull request merged**
