### PR TITLE
releasebranch_8_2: Update grass80 to grass82

### PR DESCRIPTION
**Pull request by neteler**
Update various mentions of grass80 and grass81 -> grass82

### CODE REVIEW

**Review by wenzeslaus — APPROVED** [review]
In the scope of version eighty and eighty one to eighty two, this is good.

I have found some potential candidates with `grep -IrnE "[^0-9]8\.[01][^0-9]"` in INSTALL, `g.version.html`, `rpm/grass.spec`, and Docker readme, but only the last one really needs an update; no sure about the rpm.

**Comment by neteler** [comment]
> I have found some potential candidates with `grep -IrnE "[^0-9]8\.[01][^0-9]"` in INSTALL, `g.version.html`, `rpm/grass.spec`, and Docker readme, but only the last one really needs an update; no sure about the rpm.

Thanks, I could catch a few more items to be updated, done in 02248ff.

**Comment by neteler** [comment]
(I missed to update https://github.com/OSGeo/grass/blob/releasebranch_8_2/include/VERSION, done separately)

**Comment by neteler** [comment]
For the record: Additional Windows related changes in #2338

**Pull request merged**
