### PR TITLE
r.li manual: Update reference to fragstat paper

### PR DESCRIPTION
**Pull request by ecodiv**
updated dead URL to fragstat paper by McGarigal et al.

### CODE REVIEW

**Comment by veroandreo** [comment]
@echoix I edited the original title to match the style we use, why does the test fail?

**Comment by echoix** [comment]
> @echoix I edited the original title to match the style we use, why does the test fail?

@veroandreo because the regex used doesn't expect a space between r.li and manual before the colon.

**Comment by neteler** [comment]
> the regex used doesn't expect a space between r.li and manual before the colon.

(I'd love to see `xxx manual:` to be identified as an entry for the manual section in the release notes.)

**Comment by echoix** [comment]
> > the regex used doesn't expect a space between r.li and manual before the colon.
> 
> 
> 
> (I'd love to see `xxx manual:` to be identified as an entry for the manual section in the release notes.)

@wenzeslaus ?

**Comment by echoix** [comment]
Let's keep on going, and don't wait for the regex to be adjusted. It will need to be done for a next release, shoving it for later. I opened an issue to track this.

**Pull request merged**
