### PR TITLE
r.in.wms: Fix Access window out of range in RasterIO() error (raster tile size)

### PR DESCRIPTION
**Pull request by tmszi**
Fix bug introduced in the issue #688.

### CODE REVIEW

**Comment by nilason** [comment]
With this fix I cannot reproduce the issue reported in #688. Seems to me to solve the issue.
Thanks!

**Comment by petrasovaa** [comment]
I was trying to understand the fix and noticed there is a float division instead of integer division (change in Python 3):

```
diff --git a/scripts/r.in.wms/wms_drv.py b/scripts/r.in.wms/wms_drv.py
index cbad15b4a..cc53c410e 100644
--- a/scripts/r.in.wms/wms_drv.py
+++ b/scripts/r.in.wms/wms_drv.py
@@ -425,7 +425,7 @@ class WMSRequestMgr(BaseRequestMgr):
         rows = int(region['rows'])
 
         # computes parameters of tiles
-        self.num_tiles_x = cols / self.tile_cols
+        self.num_tiles_x = cols // self.tile_cols
         self.last_tile_x_size = cols % self.tile_cols
         self.tile_length_x = float(
             self.tile_cols) / float(cols) * (self.bbox['maxx'] - self.bbox['minx'])
@@ -435,7 +435,7 @@ class WMSRequestMgr(BaseRequestMgr):
             self.last_tile_x = True
             self.num_tiles_x = self.num_tiles_x + 1
 
-        self.num_tiles_y = rows / self.tile_rows
+        self.num_tiles_y = rows // self.tile_rows
         self.last_tile_y_size = rows % self.tile_rows
         self.tile_length_y = float(
             self.tile_rows) / float(rows) * (self.bbox['maxy'] - self.bbox['miny'])
```

This seems to fix the issue, could you please test?

**Comment by tmszi** [comment]
> This seems to fix the issue, could you please test?

I tested it and it works properly.

**Comment by petrasovaa** [comment]
> > This seems to fix the issue, could you please test?
> 
> I tested it and it works properly.

Since this  seems to be the source of the issue, would you mind replacing the changes in this PR with the suggested fix?

**Comment by tmszi** [comment]
> Since this seems to be the source of the issue, would you mind replacing the changes in this PR with the suggested fix?

All right, I updated it.

**Comment by petrasovaa** [comment]
Thanks!

**Pull request merged**
