### PR TITLE
v.in.dwg: Retire v.in.dwg infavor of v.in.redwg

### PR DESCRIPTION
**Pull request by ymdatta**
v.in.dwg is linked to proprietary library 'OpenDWG toolkit'. One needs to become a member of OpenDWG Alliance to get the needed libraries and headers in order to compile this module.

However, OpenDWG webpage went offline around 2011 and we have 'v.in.redwg' as replacement for it. Hence retire 'v.in.dwg' module.

### CODE REVIEW

**Comment by echoix** [comment]
You also need to remove the entry in the Makefile of the parent folder, https://github.com/OSGeo/grass/blob/95c123d4b8ce740cefa2fcbc23f649ba25454807/vector/Makefile#L105

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
Hm, this is even more complicated. Changes in `configure.ac` `include/Make/Platform.make.in` are needed. @ymdatta please do that and regenerate `configure` if you feel up to it or open an issue for it (and we merge this PR without the change).

**Comment by HamishB** [comment]
Why not rename v.in.redwg as v.in.dwg and v.in.dwg as v.in.opendwg? The end user doesn't care what the backend library is, only that the name is self-documenting and it does what they want it to.

best,
Hamish

**Comment by wenzeslaus** [comment]
> Why not rename v.in.redwg as v.in.dwg and v.in.dwg as v.in.opendwg?

Yes, that possible. v.in.redwg is currently in grass-addons, so it an independent discussion from this PR and may include discussion about moving it to the core (perhaps you want to open a GitHub Discussion or grass-dev thread for that). v.in.opendwg is not bad in general, but I don't see someone actually maintaining the code, so keeping in active code base (in core or addons) does not seem good.

**Comment by echoix** [comment]
Renaming a module is kinda disruptive for anyone having scripted workflows. If the backend library changes, (thus keeping this module), and has somewhat a similar behavior as before, why would we need to rename the module?
The interface (options) might be similar.

It's reasonable to say like : _this module now uses a new library, and might have some differences, but is more recent/accepts newer files types_

Rather than: oh oh, that module doesn't exist anymore at all, change to use that same module with another name and library.

**Comment by ymdatta** [comment]
@wenzeslaus : Made the necessary changes.

1. Removed `opendwg` remnants from configure.ac file.
2. Regenerated configure script.
3. Removed `opendwg` entry from `include/Platform.make.in` file.

Minor testing done: able to configure with current [configuration](https://grasswiki.osgeo.org/wiki/Compile_and_Install_Ubuntu#Compilation) and compile without any issues. When configure was run, didn't see any indication of dwg in the support section of config.

Earlier: (Indicated with asteriks around, Line 5)

```
  BLAS support:               no
  BZIP2 support:              no
  C++ support:                yes
  Cairo support:              yes
  **DWG support:                no**
  FFTW support:               yes
  FreeType support:           yes
  GDAL support:               yes
  GEOS support:               yes
  LAPACK support:             no
  Large File support (LFS):   yes
  libLAS support:             no
  LIBSVM support:             no
  MySQL support:              no
  NetCDF support:             no
  NLS support:                yes
  ODBC support:               no
  OGR support:                yes
  OpenCL support:             no
  OpenGL support:             yes
  OpenMP support:             yes
  PDAL support:               yes
  PNG support:                yes
  POSIX thread support:       no
  PostgreSQL support:         yes
  Readline support:           no
  Regex support:              yes
  SQLite support:             yes
  TIFF support:               yes
  X11 support:                yes
  Zstandard support:          yes
```

After the change:

```
  BLAS support:               no
  BZIP2 support:              no
  C++ support:                yes
  Cairo support:              yes
  FFTW support:               yes
  FreeType support:           yes
  GDAL support:               yes
  GEOS support:               yes
  LAPACK support:             no
  Large File support (LFS):   yes
  libLAS support:             no
  LIBSVM support:             no
  MySQL support:              no
  NetCDF support:             no
  NLS support:                yes
  ODBC support:               no
  OGR support:                yes
  OpenCL support:             no
  OpenGL support:             yes
  OpenMP support:             yes
  PDAL support:               yes
  PNG support:                yes
  POSIX thread support:       no
  PostgreSQL support:         yes
  Readline support:           no
  Regex support:              yes
  SQLite support:             yes
  TIFF support:               yes
  X11 support:                yes
  Zstandard support:          yes
```

**Review by wenzeslaus — APPROVED** [review]
Looks great. I can't find any other remains of OpenDWG.

**Pull request merged**
