### PR TITLE
Docker: Sync main Dockerfile to docker/ubuntu/Dockerfile

### PR DESCRIPTION
**Pull request by echoix**
Closes https://github.com/OSGeo/grass/issues/3204 

I copied over the ubuntu dockerfile edited in #3170 to the dockerfile in the root of the repo, and added a note at the top for future edits to the file (in both files).

This should allow the additional checks to pass again.

### CODE REVIEW

**Comment by ninsbl** [comment]
Thanks @echoix

**Comment by echoix** [comment]
Travis failing is unexpected, it didn't fail up to yesterday, and it errors out at the https://github.com/OSGeo/grass/blob/0bc5039dd372684562b13f85ae087418a1add8a4/.travis/linux.before_install.sh file

**Comment by ninsbl** [comment]
Failure of the Ubuntu minimum Test seems an unrelated, random time out of a temporal test.

**Comment by ninsbl** [comment]
Failure of the Ubuntu minimum Test seems an unrelated, random time out of a temporal test.

**Comment by neteler** [comment]
> Travis failing is unexpected, it didn't fail up to yesterday, and it errors out at the https://github.com/OSGeo/grass/blob/0bc5039dd372684562b13f85ae087418a1add8a4/.travis/linux.before_install.sh file

See #3202

**Comment by echoix** [comment]
The Pylint failure, even if I'm certain that it's not this PR that caused it, intrigues me since there are still 111 failures and 180 passed, 98 deselected, and the three other steps didn't run (compiling example module and building and deploying sphinx doc)

**Comment by echoix** [comment]
I hoped it would be merged last weekend ;)

**Comment by neteler** [comment]
We are trapped: "Required statuses must pass before merging".. :(

**Comment by echoix** [comment]
Do you want me to just temporarily ou the old version in this PR or a new one (which would have the additional checks failing)?

**Comment by echoix** [comment]
I pinned the version of pytest-pylint like suggested by https://github.com/OSGeo/grass/pull/3203#issuecomment-1761771118

It should allow to pass the tests. The errors should still be fixed, they seem legitimate (by the looks of it without looking in a complete IDE). Thus I made sure to leave a note in the action in order to remove it very shortly after.

Feel free to cherry pick the first commit only for back porting, or reverting anything else later. But it unlocks everybody else for now.

**Review by wenzeslaus — APPROVED** [review]
This is great. I just changed the subject since it is more about the Docker files than CI. CI is just checking the requirements here.

I'll mention the pytest-pylint hot fix in the final commit message when merging.

**Pull request merged**
