### PR TITLE
CI: add expat dependency to macOS runner

### PR DESCRIPTION
**Pull request by nilason**

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by neteler** [comment]
To be backported to G8.4, @nilason ?

**Comment by echoix** [comment]
Most probably, as the macOS builds should fail too as the conda environment would resolve the same

**Comment by nilason** [comment]
> To be backported to G8.4, @nilason ?

Yes.

**Comment by neteler** [comment]
Mhh, the file versions differ too much and git cherry-picking fails.

**Comment by nilason** [comment]
> Mhh, the file versions differ too much and git cherry-picking fails.

I can take look tomorrow.

**Comment by nilason** [comment]
Backported with 64fece0 (together with 926cf21).

**Pull request merged**
