### PR TITLE
g.extension: improve way how to parse module name from makefile

### LINKED ISSUE #1136: [Bug] g.extension: cutting off addon module name: WARNING: No metadata available for module 'r.sample.categor'.
**Describe the bug**

g.extension cuts off addon module name in extensions.xml and doesn't add the module to the _Layer manager_ -> _Modules_ -> _Addons_

**To Reproduce**

```
g.extension extension=r.sample.category 
```

addon and manual html are installed, though not added to the GUI and following message pops up:

```
g.extension extension=r.sample.category                                         
Downloading precompiled GRASS Addons <r.sample.category>...
Updating extensions metadata file...
Updating extension modules metadata file...
WARNING: No metadata available for module 'r.sample.categor'.
ERROR: Unable to read manual page: [Errno 2] No such file or directory: 'C:\\Users\\xxxx\\AppData\\Roaming\\GRASS7\\addons\\docs\\html\\r.sample.categor.html'
```

note: **r.sample.categor.html** vs. module name **r.sample.category** 

looking into _C:\Users\xxxxx\AppData\Roaming\GRASS7\addons\extensions.xml_ 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE task SYSTEM "grass-addons.dtd">
<addons version="7">
    <task name="r.sample.category">
        <binary>
            <file>C:\Users\xxxxx\AppData\Roaming\GRASS7\addons\bin\r.sample.category.bat</file>
            <file>C:\Users\xxxxx\AppData\Roaming\GRASS7\addons\docs\html\r.sample.category.html</file>
            <file>C:\Users\xxxxx\AppData\Roaming\GRASS7\addons\docs\html\r.sample.category.png</file>
            <file>C:\Users\xxxxx\AppData\Roaming\GRASS7\addons\docs\man\man1\r.sample.category.1</file>
            <file>C:\Users\xxxxx\AppData\Roaming\GRASS7\addons\scripts\r.sample.category.py</file>
        </binary>
        <modules>
            <module>r.sample.categor</module>
        </modules>
        <libgis revision="d8fbd49af" />
    </task>
</addons>
```

note:  _<module>_**r.sample.categor**_</module>_ within the modules tag

**Expected behavior**

addon is installed without this message and added to the GUI as all other addons

**System description (please complete the following information):**

```
System Info                                                                     
GRASS Version: 7.8.4                                                            
Code revision: d8fbd49af                                                        
Build date: 2020-10-05                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.2                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.19041-SP0 (OSGeo4W) 
```

### PR DESCRIPTION
**Pull request by tmszi**
**To Reproduce:**

1. `g.extension r.sample.category`
2. Check if module is registred
 ```
GRASS nc_basic_spm_grass7/PERMANENT:~ > g.extension -a
No extension (module) installed
```
Problematic are Add-Ons which has defined PGM variable without space around '=' in the makefile. 

```
MODULE_TOPDIR = ../..

PGM=r.sample.category

include $(MODULE_TOPDIR)/include/Make/Script.make

default: script
```

List of problematic Add-Ons:

```
general/g.isis3mt/Makefile:3:PGM=g.isis3mt
general/g.copyall/Makefile:3:PGM=g.copyall
raster3d/r3.what/Makefile:3:PGM=r3.what
raster/r.green/r.green.hydro/Makefile:3:PGM=r.green.hydro
raster/r.green/r.green.biomassfor/Makefile:3:PGM=r.green.biomassfor
raster/r.green/Makefile:3:PGM=r.green
raster/r.green/r.green.gshp/Makefile:3:PGM=r.green.gshp
raster/r.vect.stats/Makefile:3:PGM=r.vect.stats
raster/r.bioclim/Makefile:3:PGM=r.bioclim
raster/r.sun.hourly/Makefile:3:PGM=r.sun.hourly
raster/r.landscape.evol/Makefile:3:PGM=r.landscape.evol
raster/r.stream.watersheds/Makefile:3:PGM=r.stream.watersheds
raster/r.surf.nnbathy/Makefile:3:PGM=r.surf.nnbathy
raster/r.out.kde/Makefile:3:PGM=r.out.kde
raster/r.landscape.evol.old/Makefile:3:PGM=r.landscape.evol.old
raster/r.out.ntv2/Makefile:3:PGM=r.out.ntv2
raster/r.lake.series/Makefile:3:PGM=r.lake.series
raster/r.local.relief/Makefile:3:PGM=r.local.relief
raster/r.stream.variables/Makefile:3:PGM=r.stream.variables
raster/r.sample.category/Makefile:3:PGM=r.sample.category
raster/r.shaded.pca/Makefile:3:PGM=r.shaded.pca
raster/r.connectivity/Makefile:3:PGM=r.connectivity
raster/r.slope.direction/Makefile:3:PGM=r.slope.direction
raster/r.sun.daily/Makefile:3:PGM=r.sun.daily
raster/r.sim.water.mp/Makefile:4:PGM=r.sim.water.mp
gui/wxpython/wx.mwprecip/Makefile:3:PGM= g.gui.mwprecip
gui/wxpython/wx.metadata/g.gui.cswbrowser/Makefile:3:PGM= g.gui.cswbrowser
gui/wxpython/wx.metadata/g.gui.metadata/Makefile:3:PGM= g.gui.metadata
display/d.vect.thematic2/Makefile:3:PGM=d.vect.thematic2
display/d.explanation.plot/Makefile:3:PGM=d.explanation.plot
vector/v.in.redwg/Makefile:3:PGM=v.in.redwg
vector/v.area.stats/Makefile:4:PGM=v.area.stats
vector/v.tin.to.rast/Makefile:3:PGM=v.tin.to.rast
vector/v.area.weigh/Makefile:3:PGM=v.area.weigh
vector/v.convert/Makefile:4:PGM=v.convert
vector/v.surf.nnbathy/Makefile:3:PGM=v.surf.nnbathy
vector/v.concave.hull/Makefile:3:PGM=v.concave.hull
imagery/i.fusion.brovey/Makefile:3:PGM=i.fusion.brovey
```

Fixes #1136.

### CODE REVIEW

**Comment by hellik** [comment]
>Problematic are Add-Ons which has defined PGM variable without space around '=' in the makefile.

what about change these makefiles in our addons repo?

**Comment by neteler** [comment]
> > Problematic are Add-Ons which has defined PGM variable without space around '=' in the makefile.
> 
> what about change these makefiles in our addons repo?

Could be done but that's only a workaround since AFAIK the Makefile syntax isn't invalid.

**Comment by tmszi** [comment]
> > Problematic are Add-Ons which has defined PGM variable without space around '=' in the makefile.
> 
> what about change these makefiles in our addons repo?

Yes I agree. I opened [PR](https://github.com/OSGeo/grass-addons/pull/358).

**Review by neteler — APPROVED** [review]
Looks good to me

**Pull request merged**
