### PR TITLE
update base_url to current server layout

### PR DESCRIPTION
**Pull request by neteler**
Addresses https://trac.osgeo.org/grass/ticket/3455 for master

### CODE REVIEW

**Comment by hellik** [comment]
as this PR is for master, tested with

`System Info                                                                     
GRASS Version: 7.7.dev                                                          
Code revision: 5249e44ac                                                        
Build date: 2019-07-24                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 2.4.1                                                                     
PROJ.4: 5.2.0                                                                   
GEOS: 3.7.2                                                                     
SQLite: 3.26.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.3                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W)  `

and locally adapted g.extension.py

`    if build_platform == 'x86_64':
        platform = build_platform
    else:
        platform = 'x86'
    base_url = "http://wingrass.fsv.cvut.cz/" \
               "grass%(major)s%(minor)s/%(platform)s/addons/" \
               "grass-%(major)s.%(minor)s.%(patch)s" % \
               {'platform': platform,
                'major': version[0], 'minor': version[1],
                'patch': 'dev'}`

I get following error:

`g.extension extension=r.euro.ecosystem                                          
Downloading precompiled GRASS Addons <r.euro.ecosystem>...
Traceback (most recent call last):
  File
"C:\OSGEO4~1\apps\grass\grass77/scripts/g.extension.py",
line 1933, in <module>
    sys.exit(main())
  File
"C:\OSGEO4~1\apps\grass\grass77/scripts/g.extension.py",
line 1913, in main
    install_extension(source=source, url=url, xmlurl=xmlurl)
  File
"C:\OSGEO4~1\apps\grass\grass77/scripts/g.extension.py",
line 693, in install_extension
    if source == 'official' and len(installed_modules) <=
len(mlist):
UnboundLocalError: local variable 'installed_modules'
referenced before assignment`

**Comment by hellik** [comment]
although this error message, the addon is correctly installed in

`C:\Users\myuser\AppData\Roaming\GRASS7\addons`

**Comment by hellik** [comment]
downloaded a python addon and a binary/exe addon; both are working in winGRASS7.7.dev

**Comment by neteler** [comment]
While incomplete I have merged it now - at least the Python scripts should install again.

**Pull request merged**
