### PR TITLE
wxGUI/mapdisp: Replace CRLF by LF in properties.py

### PR DESCRIPTION
**Pull request by wenzeslaus**
Replace CRLF (dos) by LF (unix) line endings. See also #2144 and #2147.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
@lindakladivova Please let me know when would be a good time for you to merge this. Don't worry about a merge conflict, I can just redo this PR and you can finish whatever you need. Just let me know when you don't have any PRs or local changes yourself.

**Comment by lindakladivova** [comment]
> @lindakladivova Please let me know when would be a good time for you to merge this. Don't worry about a merge conflict, I can just redo this PR and you can finish whatever you need. Just let me know when you don't have any PRs or local changes yourself.

I think you can merge It now 😊. I have some local changes but never mind.

**Comment by lindakladivova** [comment]
> > @lindakladivova Please let me know when would be a good time for you to merge this. Don't worry about a merge conflict, I can just redo this PR and you can finish whatever you need. Just let me know when you don't have any PRs or local changes yourself.
> 
> I think you can merge It now 😊. I have some local changes but never mind.

I worked on my sister's computer when we were in Bulgaria on a tennis tournament.. so that's probably the reason...

**Comment by wenzeslaus** [comment]
No worries, now we will have it checked #2144.

**Pull request merged**
