### PR TITLE
docker: update simple.laz

### PR DESCRIPTION
**Pull request by neteler**
Reformatted [docker/testdata/simple.laz](https://github.com/OSGeo/grass/blob/main/docker/testdata/simple.laz) with  `las2las -i simple.laz -o simple_new.laz` to avoid read "error in LAZ chunk table" when using PDAL/laz-perf by updating to LAZ > 1.0.

(original file: https://github.com/PDAL/PDAL/blob/master/test/data/laz/simple.laz)

### CODE REVIEW

**Comment by nilason** [comment]
With PDAL 2.4.2 I get the following error:
```
r.in.pdal resolution=0.00037 type=CELL method=percentile pth=95 input=~/Downloads/simple.laz output=simple_perc -o 
Reading data...
libc++abi: terminating with uncaught exception of type pdal::pdal_error: readers.las: Invalid file signature. Was expecting 'LASF', Check the first four  bytes of the file.
zsh: abort      r.in.pdal resolution=0.00037 type=CELL method=percentile pth=95   -o
```

**Comment by neteler** [comment]
I suppose that `pdal` also fails for you?
I had success also with PDAL 2.5.1.

Probably to be reported upstream?

**Comment by nilason** [comment]
> I suppose that `pdal` also fails for you? I had success also with PDAL 2.5.1.

Yes.

> Probably to be reported upstream?

Maybe, will investigate a bit first.

**Comment by nilason** [comment]
I had the same problem using 2.5.1.
But it worked and I could reproduce the #2840 issue with
https://github.com/PDAL/PDAL/blob/master/test/data/las/simple.las

**Comment by nilason** [comment]
Reported this upstreams: https://github.com/PDAL/PDAL/issues/3978.

Converting the file with `las2las` produced a file even I could read.

**Comment by neteler** [comment]
> Converting the file with `las2las` produced a file even I could read.

Cool, I have update the file accordingly in this PR.

**Review by nilason — APPROVED** [review]
Great!

```
pdal info  docker/testdata/simple.laz 
{
  "file_size": 18233,
  "filename": "docker/testdata/simple.laz",
  "now": "2023-02-21T17:47:35+0100",
  "pdal_version": "2.5.1 (git-version: Release)",
  "reader": "readers.las",
  "stats":
  {
    "bbox":
    {
      "native":
      {
        "bbox":
        {
          "maxx": 638982.55,
          "maxy": 853535.43,
...
```

**Comment by neteler** [comment]
Thanks, @nilason for your support!

**Comment by neteler** [comment]
FWIW: PDAL also updated the `simple.laz` file in https://github.com/PDAL/PDAL/pull/3985

**Pull request merged**
