### PR TITLE
grass.app: Move ISIS integration to the library

### PR DESCRIPTION
**Pull request by wenzeslaus**
Path setup for ISIS was lost in GIS variable setup. This moves it to the library where other paths and integrations are initialized.

This is untested. I'm leaving the variables as is.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
@YannChemin I think you are the original author here. Do you want to take this opportunity to review the current state?

**Comment by neteler** [comment]
@afrigeri please take a look as well.

**Comment by wenzeslaus** [comment]
As far as the proposed code change, anyone please review and let's get this merged. I can get back to this when there are any followup changes proposed by @afrigeri or @YannChemin.

**Review by echoix — APPROVED** [review]

**Review by echoix — APPROVED** [review]
I don't understand why it was lost, but moving that same code around looks ok (inside a function).

Was the original function not always called when using new methods of starting grass in scripts?

**Comment by afrigeri** [comment]
Wow!  Thanks @wenzeslaus and all

**Comment by echoix** [comment]
With no other responses for the week, and the fact that I see @afrigeri 's thumbs up on last month's comment and his reponse, I'm moving this forward

**Pull request merged**
