### PR TITLE
docker: update of Debian image

### PR DESCRIPTION
**Pull request by neteler**
- Debian docker base image update
- new versions:

| Base image   | GRASS GIS  | PROJ  | GDAL  | PDAL  | Python | Image size |
|--------------|------------|-------|-------|-------|--------|------------|
| Debian 11    | 8.3.dev    | 7.2.1 | 3.2.2 | 2.4.3 | 3.9.2  | 2.93 GB    |

LAZ-perf is enabled in PDAL, hence both LAS and LAZ files can be imported into GRASS GIS.

TODO in a separate PR: reduce image size

### CODE REVIEW

**Comment by neteler** [comment]
I hoped that the docker.yml would be triggered by it isn't...

**Review by tmszi — APPROVED** [review]
The image is created and the container is started.

**Comment by tmszi** [comment]
> I hoped that the docker.yml would be triggered by it isn't...

Because the trigger is enabled when pushing to a branch, not PR.

https://github.com/OSGeo/grass/blob/f76b2674319d8d4bc7d98bf269c5b4f23831e590/.github/workflows/docker.yml#L19-L29

**Comment by neteler** [comment]
> Because the trigger is enabled when pushing to a branch, not PR.

I see - should hat be changed? (in another PR)

**Comment by nilason** [comment]
> > Because the trigger is enabled when pushing to a branch, not PR.
> 
> I see - should hat be changed? (in another PR)

Discussed here:

https://github.com/OSGeo/grass/pull/1790#issuecomment-900950686

**Comment by nilason** [comment]
> > > Because the trigger is enabled when pushing to a branch, not PR.
> > 
> > 
> > I see - should hat be changed? (in another PR)
> 
> Discussed here:
> 
> [#1790 (comment)](https://github.com/OSGeo/grass/pull/1790#issuecomment-900950686)

A tip. When I need to test something I'm not able to do locally, I temporally change in the relevant .yml file the following lines:

```yaml
on:
  push:
    branches:
      - main
      - releasebranch_*
  pull_request:
    branches:
      - main
      - releasebranch_*
```

to:

```yaml
on:
  - push
  - pull_request
```

and push it to a test fork (without creating PR).

**Comment by nilason** [comment]
> and push it to a test fork (without creating PR).

I meant to say: "push to a test **branch** on my fork  (without creating PR)".

**Pull request merged**
