### PR TITLE
configure: upgrade to autoconf 2.69

### PR DESCRIPTION
**Pull request by nilason**
Updates the configure system to autoconf 2.69 (of 2012) from the rather outdated version 2.13 (1999).

Apart from general modernisation this also fixes problems (at least for me) with iconv as reported in #513.

### CODE REVIEW

**Comment by nilason** [comment]
Now I have no more planned changes to this PR. Please go ahead and test!

This apparently doesn't cause any regression as I can see, succeeds on all CIs too. I would be good to get this change to 8.0 for future ease of maintenance on that line of releases. But I don't want this to be a blocker, hence I put this on 8.2 milestone.

Some notes:
* The choice of autoconfig version 2.69, was based on the fact that it is the latest release with a few years on its neck. Later releases 2.70 and 2.71 are from 2020 and 2021 respectively.

* This includes a rename of `configure.in` to `configure.ac`, the previous name has long been deprecated and became obsolete with 2.70. Now is as good occasion as ever to do this change.

* Updated `config.h.in` with `autoreconf --install` (kept manually added code).

* Updated with latest `config.guess` and `config.sub`

**Review by metzm — APPROVED** [review]
The usage of autoconf 2.13 tools has caused headaches before, but nobody dared to tackle the task of upgrading to a newer version! Thanks a lot, great work!

There is a bit of custom code in the old configure setup, e.g. regarding LFS, that could be replaced by using predefined tests available with the autoconf 2.69 suite. That would be worth another PR. Inspiration for updating provides e.g. GDAL's configure system.

**Comment by petrasovaa** [comment]
Awesome, this should also fix #560. I am not sure whether to wait for 8.2 with this.

**Comment by marisn** [comment]
I did a simple compile/run test. Everything seems to be fine. I would +1 pushing this to 8.0.

**Review by marisn — APPROVED** [review]

**Comment by nilason** [comment]
> The usage of autoconf 2.13 tools has caused headaches before, but nobody dared to tackle the task of upgrading to a newer version! Thanks a lot, great work!

Thanks, that's nice to hear! :-)

> There is a bit of custom code in the old configure setup, e.g. regarding LFS, that could be replaced by using predefined tests available with the autoconf 2.69 suite. That would be worth another PR. Inspiration for updating provides e.g. GDAL's configure system.

Yes I noticed, and there are probably more things that may be fixed/improved later on when we have this initial upgrade working.


@ all 
I understand from the reactions that this is something many looked forward to, this includes me. In general I feel confident this will not break anything seriously, actually autoupdate did the bulk of the work (yes, pre- and post fixes were needed, but they were actually minor ones). I think it wouldn't be too much of a gamble to get this to 8.0.

Actually, we may also considerate bringing this back to 7.8. See #560. A short time 7.8.6RC3 for testing...? Just throwing the question for consideration.

**Comment by nilason** [comment]
I have now updated with fixes from release branch 7.8 (#1869, #1870, #1883).
If the [G78 Windows daily build](https://wingrass.fsv.cvut.cz/grass78/x86_64/) succeeds, I will merge this PR.

**Comment by nilason** [comment]
Now G78 configures, builds and runs (I did test) for Windows with autoconf 2.69 too, see [log](https://wingrass.fsv.cvut.cz/grass78/x86_64/logs/log-r7388b3f2f-649/):

```
GRASS GIS 7.8.6dev 7388b3f2f compilation log
--------------------------------------------------
Started compilation: Tue Sep 21 12:57:44     2021
--
Errors in:
No errors detected.
--
Finished compilation: Tue Sep 21 13:36:43     2021
```

Merging this to main branch (G8) too.

**Pull request merged**
