### PR TITLE
t.vect.algebra: modified html doc

### PR DESCRIPTION
**Pull request by nobeeakon**
removed a paragraph talking about raster dataset types, which is not an option in this module

### CODE REVIEW

**Comment by wenzeslaus** [comment]
This probably got lost in the community sprint traffic. @veroandreo can you please review this or suggest somebody else?

**Review by veroandreo — APPROVED** [review]
AFAICT, removing the sentence is fine. This is a module to perform operations among STVDS only and there's no type parameter whatsoever. The sentence was maybe a remaining from other temporal module

**Comment by wenzeslaus** [comment]
@nobeeakon Your GitHub account and local Git configuration are not in sync in regard to author/committer identity (another name and user_name@computer_name instead of email show as an author of the commit). Do you want to sync it?

If it doesn't matter to you, that's fine. I can just merge the PR as is which would link it to your GitHub account, but I wanted to check with you if that's want you expect.

**Comment by nobeeakon** [comment]
Thanks for that @wenzeslaus . I have updated github config, but anyway, it's fine as it is.

**Comment by wenzeslaus** [comment]
Thank you both, @nobeeakon and @veroandreo. Merged.

**Pull request merged**
