### PR TITLE
Add POT files for Weblate Template for new translations

### PR DESCRIPTION
**Pull request by HuidaeCho**

### CODE REVIEW

**Comment by neteler** [comment]
This PR requires changes in the following cronjobs, if I am not mistaken:

https://github.com/OSGeo/grass-addons/blob/9745a4114c39c212c1e56eee36d6bda7f1c77538/utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh#L179

https://github.com/OSGeo/grass-addons/blob/9745a4114c39c212c1e56eee36d6bda7f1c77538/utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh#L201

https://github.com/OSGeo/grass-addons/blob/9745a4114c39c212c1e56eee36d6bda7f1c77538/utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh#L200

The script lines around `$MYMAKE pot` aren't needed any more, right? At least in G8, unless the files are also added to G7.

**Comment by veroandreo** [comment]
Just out of curiosity: how do translations via weblate work, i.e., how do they get integrated? I was translating some remaining strings in Spanish, but how/where to see that?

**Comment by neteler** [comment]
Unless this PR isn't backported, only this applies:

> This PR requires changes in the following cronjobs, if I am not mistaken:
> 
> https://github.com/OSGeo/grass-addons/blob/9745a4114c39c212c1e56eee36d6bda7f1c77538/utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh#L201

Needed change implemented in https://github.com/OSGeo/grass-addons/pull/737

**Comment by HuidaeCho** [comment]
> Just out of curiosity: how do translations via weblate work, i.e., how do they get integrated? I was translating some remaining strings in Spanish, but how/where to see that?

Check [this overall workflow](https://docs.weblate.org/en/weblate-4.11.2/admin/continuous.html#translation-consistency). As of now, steps 1, 2, and 3 are missing without [the Weblate app on GitHub](https://docs.weblate.org/en/weblate-4.11.2/admin/continuous.html#github-setup), so it's not encouraged to update translations outside Weblate.

This PR is required to provide [*new* strings for translation](https://docs.weblate.org/en/weblate-4.11.2/devel/translations.html#adding-translation).

**Pull request merged**
