### PR TITLE
wxGUI: more Python 3.10 fixes

### PR DESCRIPTION
**Pull request by petrasovaa**
Addresses #2047, #2048, #2049, also includes other problematic places.

Wait with merging, more fixes are needed.

### CODE REVIEW

**Comment by neteler** [comment]
Thanks for fixing so many issues with Python 3.10 here. I'd like to see this merged for G8.0.0RC1 which is scheduled still for 2021. Maybe we do not catch all issues but this PR is already fixing a lot!

**Comment by petrasovaa** [comment]
This is good to go I think, not sure if @tmszi wants to do more changes.

**Comment by tmszi** [comment]
> This is good to go I think, not sure if @tmszi wants to do more changes.

I agree, we can move on. The remaining bugs will be resolved in the new PRs.

**Comment by neteler** [comment]
OK, so I'll now merge this PR so that we can prepare G8.0.0RC1.

If all possible, please backport it to G7.8.

**Comment by petrasovaa** [comment]
Merged to 7.8. Note that I didn't test it in 7.8.

**Comment by neteler** [comment]
> 

Excellent, it now also works in G78! 
(I fixed a small glitch in #2056)

**Pull request merged**
