### PR TITLE
CI for MS Windows: Switch to OSGeo4W V2

### PR DESCRIPTION
**Pull request by ninsbl**
This brings back CI on MS Windows. It replaces #1873

@HuidaeCho do you have any objections to merge this now, and adress packaging in another PR?

### CODE REVIEW

**Review by wenzeslaus — APPROVED** [review]

**Comment by hellik** [comment]
thanks for bring back windows CI.

PR looks good.

**Comment by neteler** [comment]
@ninsbl May this be merged? Would be nice to see the CI completely running again!

**Comment by hellik** [comment]
> @ninsbl May this be merged? Would be nice to see the CI completely running again!

would be good to have win CI back before 8.0 release.

**Comment by ninsbl** [comment]
> @ninsbl May this be merged? Would be nice to see the CI completely running again!

From my perspective, yes.
We can fix the packaging issue with a separate (new) script in the mswindows directory, what do you think @HuidaeCho ...?

**Comment by neteler** [comment]
Please let's go ahead and merge. We need the Windows CI back.

**Comment by ninsbl** [comment]
Should we backport to 8.0 releasebranch? It does not (should not) affect the sofyware / packages delivered to endusers, so it should be safe...

**Comment by neteler** [comment]
> Should we backport to 8.0 releasebranch? It does not (should not) affect the sofyware / packages delivered to endusers, so it should be safe...

Yes - I have just done that.

**Pull request merged**
