### PR TITLE
wxGUI/main_window: increase datacatalog pane min width to display the datacatalog toolbar SearchCtrl widget

### PR DESCRIPTION
**Pull request by tmszi**
**Describe the bug**
Datacatalog toolbar SearchCtrl widget (filter) isn't visible by default in single window mode.

**To Reproduce**

1. Launch wxGUI with single window mode
2. Check if Datacatalog toolbar SearchCtrl widget (filter) is visible

**Expected behavior**
Datacatalog toolbar SearchCtrl widget (filter) should be visible by default in single window mode.

**Screenshots**

Default:

wxgui_single_window_mode_def_datatcatalog_pane_min_width

Expected:

wxgui_single_window_mode_exp_datatcatalog_pane_min_width

**System description (please complete the following information):**

- GRASS GIS version main git branch

**Additional context**
wxGUI single window mode. Another solution would be to add a new toolbar with the SearchCtrl widget if we wanted to keep the current  Datacatalog pane widget minimum width as it is now.

### CODE REVIEW

**Comment by veroandreo** [comment]
It looks pretty wide to me, I'd go with a different solution: maybe a second row as suggested, but what about an arrow down as in the Layers pane? I'm inclined to the latter if possible.

**Comment by tmszi** [comment]
> It looks pretty wide to me, 
I agree with you.

> I'd go with a different solution: ... but what about an arrow down as in the Layers pane? 

Arrow down menu with wx.SearchCtrl widget seems is not possible, because it is standalone widget not toolbar tool widget and allowed toolbar tool type according wxPython [wx.Toolbar widget docs AddTool() method  with kind paramater ](https://wxpython.org/Phoenix/docs/html/wx.ToolBar.html#wx.ToolBar.AddTool) are: "_May be ITEM_NORMAL for a normal button (default), ITEM_CHECK for a checkable tool (such tool stays pressed after it had been toggled) or ITEM_RADIO for a checkable tool which makes part of a radio group of tools each of which is automatically unchecked whenever another button in the group is checked. ITEM_DROPDOWN specifies that a drop-down menu button will appear next to the tool button (only GTK+ and MSW)_".

I think this widget should be visible.

Suggested change:

wxgui_single_win_mode_datacalog_pane_exp

**Comment by lindakladivova** [comment]
I like the way how it looks like

> > It looks pretty wide to me,
> 
> I agree with you.
> 
> > I'd go with a different solution: ... but what about an arrow down as in the Layers pane?
> 
> Arrow down menu with wx.SearchCtrl widget seems is not possible, because it is standalone widget not toolbar tool widget and allowed toolbar tool type according wxPython [wx.Toolbar widget docs AddTool() method with kind paramater ](https://wxpython.org/Phoenix/docs/html/wx.ToolBar.html#wx.ToolBar.AddTool) are: "_May be ITEM_NORMAL for a normal button (default), ITEM_CHECK for a checkable tool (such tool stays pressed after it had been toggled) or ITEM_RADIO for a checkable tool which makes part of a radio group of tools each of which is automatically unchecked whenever another button in the group is checked. ITEM_DROPDOWN specifies that a drop-down menu button will appear next to the tool button (only GTK+ and MSW)_".
> 
> I think this widget should be visible.
> 
> Suggested change:
> 
> wxgui_single_win_mode_datacalog_pane_exp

@tmszi I like the way how it looks like. :-) Definitely better to have the Search as the second row! But I am not sure about the implementation. Maybe I would prefer to have two toolbars for Multi-Window as well and then just say for Single-Window mode put the Search box below and for the Multi-Window on the right.  In terms of code, it could be significantly clearer, but I realize that we then a bit change the Multi-GUI, so to be honest I am not sure if it is actually better. @petrasovaa , any opinion on that?

**Comment by petrasovaa** [comment]
I don't have a strong opinion on that, I thought having 2 toolbars might be better, but it may take up more space.

**Comment by wenzeslaus** [comment]
Even with 1600x900, it seems to me that there is enough space for the search box to be in the same row as the toolbar buttons (when made wider).

However, moving it to next row may allow to make it bigger by default (so more text can be, e.g., copy-pasted, and still visible - I don't expect to type a long map name) and perhaps there can be more search-related functionality there as well similarly to the Tools tab with search and advanced search. I think spending more vertical space is an issue, but in this case it might be worth it because it also makes the search more prominent.

**Review by lindakladivova — APPROVED** [review]

**Comment by petrasovaa** [comment]
Trying to incorporate some points from the discussion here, what do you think about #2207?

**Comment by tmszi** [comment]
Better implementation with #2207.

**Pull request closed without merging**
