### PR TITLE
style: Fixes if-stmt-min-max (PLR1730)

### PR DESCRIPTION
**Pull request by echoix**
Concerns Pylint rules ["consider-using-min-builtin / R1730"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-min-builtin.html) and ["consider-using-max-builtin / R1731"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-max-builtin.html)

Using `ruff check --output-format=concise --select PLR1730 --preview --fix`.

Part of the effort to introduce Pylint 3.x for https://github.com/OSGeo/grass/issues/3921

Uses the fixes provided for ruff rule [if-stmt-min-max (PLR1730)](https://docs.astral.sh/ruff/rules/if-stmt-min-max/) to fix part of Pylint's ["consider-using-min-builtin / R1730"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-min-builtin.html) and ["consider-using-max-builtin / R1731"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-max-builtin.html).

It also happens to reduce the number of branches and number of lines, where multiple places still exceeds some (already raised) limits, so its a good thing.

### CODE REVIEW

**Review by ninsbl — APPROVED** [review]
Nice, do you plan to apply such improvement to addons too?

**Comment by echoix** [comment]
If it is wanted, I could. But the goal now is to have less than the couple thousand Pylint violations only for `python/grass` and `gui/wxpython`.

I made sure to leave the command used in each commit/PR. So it's really a matter of milliseconds to fix. What is longer is my manual review that I do, file by file, before committing. The PRs I submitted one after the other were the accumulation of this morning and half the afternoon. It's all from one branch, then I cherry-pick individual changed to new branches created from main, hoping that the changes were completely independent to not have any conflicts. Then I wrote the PRs.

In between the changes, I review what changed in the Pylint run, and find a new issue that ruff can easily fix.

**Comment by ninsbl** [comment]
Great!

The addons repo would benefit from such an effort for sure, and IMHO code style in the core and addons repo should be as similar as possible...

But of course I understand that it is a matter of priorities...

**Comment by echoix** [comment]
I did a little bit the other weekend on the addons-repo, as I was blocked without any reviews here, and their pre-commit config is in a better shape than here. There is still https://github.com/OSGeo/grass-addons/pull/1134 that is waiting for discussions.

If you were talking about this specific fix, you can apply `ruff check --output-format=concise --select PLR1730 --preview --fix` right away on that repo.

**Pull request merged**
