### PR TITLE
make: Update DB.make for markdown support

### PR DESCRIPTION
**Pull request by landam**
This PR fixes https://github.com/OSGeo/grass/pull/4740#issuecomment-2493971349

Note that links remain broken if GRASS is not built with specific driver support. See broken MySQL links in https://grass.osgeo.org/grass84/manuals/databaseintro.html#creating-a-database. This issue should be addressed by separated PR or at least reported as GitHub issue.

### CODE REVIEW

**Review by neteler — APPROVED** [review]
Thanks, it solves the problem.

**Comment by neteler** [comment]
Seems we have a chicken-egg problem here (need to have the `.md` files in place to make the CI happy):

CI log:
```
make[3]: Entering directory '/home/runner/work/grass/grass/db/drivers'
make -C dbf || echo /home/runner/work/grass/grass/db/drivers/dbf >> /home/runner/work/grass/grass/error.log
make -C sqlite || echo /home/runner/work/grass/grass/db/drivers/sqlite >> /home/runner/work/grass/grass/error.log
make -C ogr || echo /home/runner/work/grass/grass/db/drivers/ogr >> /home/runner/work/grass/grass/error.log
make[4]: Entering directory '/home/runner/work/grass/grass/db/drivers/sqlite'
test -d OBJ.x86_64-pc-linux-gnu || mkdir -p OBJ.x86_64-pc-linux-gnu
make[4]: *** No rule to make target '/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/docs/mkdocs/source/grass-sqlite.md', needed by 'db_html'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Entering directory '/home/runner/work/grass/grass/db/drivers/ogr'
test -d OBJ.x86_64-pc-linux-gnu || mkdir -p OBJ.x86_64-pc-linux-gnu
make[4]: Entering directory '/home/runner/work/grass/grass/db/drivers/dbf'
test -d OBJ.x86_64-pc-linux-gnu || mkdir -p OBJ.x86_64-pc-linux-gnu
make[4]: *** No rule to make target '/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/docs/mkdocs/source/grass-ogr.md', needed by 'db_html'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/runner/work/grass/grass/db/drivers/sqlite'
make[4]: *** No rule to make target '/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/docs/mkdocs/source/grass-dbf.md', needed by 'db_html'.  Stop.
make[4]: *** Waiting for unfinished jobs....
```

**Comment by landam** [comment]
> Seems we have a chicken-egg problem here (need to have the `.md` files in place to make the CI happy):

Yes, we have to comment it similarly as we did for other markdown-related rules: https://github.com/OSGeo/grass/commit/6743f1ae78dfbe7bd45f1cdc1ec5afcbb7610a00. They can be enabled in PR which adds markdown files.

**Review by neteler — APPROVED** [review]
Thanks!

**Pull request merged**
