### PR TITLE
totools/mkhtml.py: fix replacing keywords (no keywords) html pages path if add-on html man page stored on the server

### PR DESCRIPTION
**Pull request by tmszi**
Fixes replacing keywords (Add-On without keywords) html pages path if add-on html man page stored on the server.

Fixes GRASS GIS Add-Ons [issue](https://github.com/OSGeo/grass-addons/issues/337).

### CODE REVIEW

**Comment by neteler** [comment]
Thanks - I have tested it on the server and the list of broken manual pages shrinks from

```
neteler@grasslxd:/var/www/code_and_data/grass78/manuals/addons$ l | grep '   0'
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 i.ann.maskrcnn.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 m.eigensystem.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.futures.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.edm.eval.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.denoise.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.cpt2grass.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.agent.rand.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.agent.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.agent.aco.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.learn.ml2.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.structure.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.financial.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.delplants.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.gshp.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.biomassfor.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.pi.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.out.ntv2.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.object.activelearning.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.maxent.lambdas.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.vector.ruggedness.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.tri.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 v.sort.points.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 v.mrmr.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 v.feature.algebra.html
```

to now

```
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 i.ann.maskrcnn.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 m.eigensystem.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.agent.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.green.hydro.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.green.gshp.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.green.biomassfor.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.futures.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.learn.ml2.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.pi.html
-rw-rw-r-- 1 neteler users       0 Dec 13 20:14 v.feature.algebra.html
```

The related build log: 
[build.log](https://github.com/OSGeo/grass/files/5685437/build.log) which shows `FAILED` for all of them:
```

grep FAILED build.log 
Compiling g.isis3mt... FAILED
Compiling wx.mwprecip... FAILED
Compiling wx.stream... FAILED
Compiling wx.wms... FAILED
Compiling i.ann.maskrcnn... FAILED
Compiling m.eigensystem... FAILED
Compiling r.agent... FAILED
Compiling r.futures... FAILED
Compiling r.learn.ml2... FAILED
Compiling r.le.patch... FAILED
Compiling r.le.setup... FAILED
Compiling r.le.trace... FAILED
Compiling r.modis... FAILED
Compiling r.pi... FAILED
Compiling r.sentinel... FAILED
Compiling r.sun.mp... FAILED
Compiling v.delaunay3d... FAILED
Compiling v.feature.algebra... FAILED
Compiling v.in.redwg... FAILED
Compiling v.in.survey... FAILED
Compiling v.stream.profiler... FAILED
```

So, probably remaining is to simply remove the 0 byte HTML files in case of the related `FAILED` status?

Related Linux log: https://grass.osgeo.org/addons/grass7/logs/

**Comment by wenzeslaus** [comment]
I'm not sure if I understand the context here, but if this is about normal build failing: *r.futures.html* is a plain page. A main page for a group of modules. Not co-generated by a module. That used work.

Other cases, like v.feature.algebra, used to work even though they are programs, but not with the GRASS module interface. (_v.feature.algebra_ should/will be dropped from the list for v8, but that's unrelated.)

**Comment by tmszi** [comment]
> Thanks - I have tested it on the server and the list of broken manual pages shrinks from
> 
> to now
> 
> ```
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 i.ann.maskrcnn.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 m.eigensystem.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.agent.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.green.hydro.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.green.gshp.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.green.biomassfor.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.futures.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.learn.ml2.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 r.pi.html
> -rw-rw-r-- 1 neteler users       0 Dec 13 20:14 v.feature.algebra.html
> ```

Fixed in the [0e9eb30](https://github.com/OSGeo/grass/pull/1172/commits/0e9eb30f00b0fc56584f5d429654d267f9eb9769) and tested locally and worked as expected.

Current list of Add-Ons that failed to compile (I checked them manually and the compilation error is not related to the mkhtml tool):

```
Compiling g.isis3mt... FAILED
Compiling wx.stream... FAILED
Compiling wx.wms... FAILED
Compiling i.points.auto... FAILED
Compiling i.pr... FAILED
Compiling i.spec.sam... FAILED
Compiling i.spec.unmix... FAILED
Compiling m.eigensystem... FAILED
Compiling r.learn.ml2... FAILED
Compiling r.le.setup... FAILED
Compiling r.le.trace... FAILED
Compiling r.modis... FAILED
Compiling r.object.activelearning... FAILED
Compiling r.pi... FAILED
Compiling r.sentinel... FAILED
Compiling v.in.redwg... FAILED
Compiling v.in.survey... FAILED
Compiling v.kriging... FAILED
```

> So, probably remaining is to simply remove the 0 byte HTML files in case of the related `FAILED` status?

This is not necessary because the compilation error was caused by an bug in the mkhtml tool, and I've fixed that. No 0 byte HTML files  should be created.

**Review by neteler — APPROVED** [review]
:100: % success, no more 0 byte files on the server.

**Comment by tmszi** [comment]
> 100 % success, no more 0 byte files on the server.

Thanks Markus.

**Pull request merged**
