### PR TITLE
Add pre-commit hook file

### PR DESCRIPTION
**Pull request by nilason**
This adds [pre-commit](https://pre-commit.com) hook file, which runs and checks black, flake8 and clang-format on staged files.

```bash
cd grass-source-dir
python -m pip install pre-commit
# following step once per repo
pre-commit install

# edit files ...

git add <modified_files>

# following step triggers the hook
git commit
```

This is by far the simplest way to keep the files in a good shape. Also it will save **a lot** of CI builds, with no need for correcting pushed and failed commits.

The black and flake8 part may be backported to 8.2.

### CODE REVIEW

**Comment by nilason** [comment]
I accidentally hit the return key and posted this PR before I even started. Now I have updated the description.

**Comment by nilason** [comment]
Just added `trailing-whitespace` and `end-of-file-fixer` hooks, which both check all types of files. I also added `markdownlint` hook.

**Comment by nilason** [comment]
Any objections on merging this `.pre-commit-config.yaml` file?
I think it is a very convenient workflow, I find myself manually putting it in while working on other PRs.

Note: if `pre-commit` is **not** installed, this addition  will not in any way affect present workflow.

**Comment by neteler** [comment]
> This is by far the simplest way to keep the files in a good shape. Also it will save **a lot** of CI builds, with no need for correcting pushed and failed commits.

This sounds very good! And it will speed up things.

**Pull request merged**
