### PR TITLE
Fix v.in.pdal compilation on mac, #475

### PR DESCRIPTION
**Pull request by nilason**
This fix addresses compilation failure of pdal on mac #475.

Implemented already as a patch for macports (https://github.com/macports/macports-ports/commit/1ed7c203f3075283309edac1a7595640d0ba9f06), credit to @Veence.

Not tested on Linux, Windows.

### CODE REVIEW

**Comment by cmbarton** [comment]
Thanks much. I'll recompile and test soon. Is this backported to RB7.8 yet?

**Comment by neteler** [comment]
> Thanks much. I'll recompile and test soon. Is this backported to RB7.8 yet?

It has not even been merged (note the "open" of this PR)...

**Comment by neteler** [comment]
I have `git apply`ed this PR to master and it compiles on Linux (Fedora 32, gcc 9.3.1).

**Comment by wenzeslaus** [comment]
Thanks @neteler for testing on Linux. I would just assume this will work on Windows. Please merge at will.

@rkanavath something to keep in mind for CMake build.

**Pull request merged**
