### PR TITLE
wxGUI: preparation for single and multi layout for Data Catalog

### PR DESCRIPTION
**Pull request by lindakladivova**
This PR prepares Data Catalog for different layout options (depends of chosen layout - multi or single). It does not implement the concrete solution.

### CODE REVIEW

**Comment by petrasovaa** [comment]
What problem is this trying to solve? I thought we planned to keep the toolbar together with the tree anyway, so the layout would stay the same with the possible exception of the infobar, but that's a decision for later. Not sure if the base class isn't an overkill.

**Comment by lindakladivova** [comment]
> 
> 
> What problem is this trying to solve? I thought we planned to keep the toolbar together with the tree anyway, so the layout would stay the same with the possible exception of the infobar, but that's a decision for later. Not sure if the base class isn't an overkill.

I think we will need to look for a different solution than the one used for multi layout because of the toolbar which is too long now... . The question is how to do it. I think that smaller icons (as in QGIS) are not a suitable solution, from my own experience - I noticed them after quite a long time working with QGIS, probably because they are too small :-). 
So, I would prefer either two toolbars below each other OR one horizontal (for reloading and search stuff) and one vertical toolbar (for the creation of data hierarchy items).
But I agree that it is a decision for later. :-)

(The same thing will probably have to be addressed for the Display tab whose toolbar is too long as well.)

**Comment by petrasovaa** [comment]
> > What problem is this trying to solve? I thought we planned to keep the toolbar together with the tree anyway, so the layout would stay the same with the possible exception of the infobar, but that's a decision for later. Not sure if the base class isn't an overkill.
> 
> I think we will need to look for a different solution than the one used for multi layout because of the toolbar which is too long now... . The question is how to do it. I think that smaller icons (as in QGIS) are not a suitable solution, from my own experience - I noticed them after quite a long time working with QGIS, probably because they are too small :-).
> So, I would prefer either two toolbars below each other OR one horizontal (for reloading and search stuff) and one vertical toolbar (for the creation of data hierarchy items).
> But I agree that it is a decision for later. :-)
> 
> (The same thing will probably have to be addressed for the Display tab whose toolbar is too long as well.)

That's a good point. We can discuss this further but I think making the toolbar vertical would work well for both layouts. The search would still stay on top (not in a toolbar but similarly to Modules tab). The display tab toolbar could be similar.

**Comment by petrasovaa** [comment]
If you don't mind I will close this PR now and we can reopen it if we find it relevant later.

**Pull request closed without merging**
