### PR TITLE
style: Modernize Python syntax, resolves Python 3.12 `\.` Syntax warning

### PR DESCRIPTION
**Pull request by echoix**
Follow up from #3251.
Contributes to #3285.

This is a bit more varied than the previous PR, but also smaller to review.
To help the review, I made each type of changes in a separate commit with an explanation of each issue in the commit message.

The last commit is the only one that really addresses the Python 3.12 SyntaxWarning of using an unescaped sequence.

As the previous PR, this one is also conservative: I excluded the `python/libgrass_interface_generator` directory altogether, and excluded all changes that I couldn't assure myself they were really safe. As such, there are some remaining items to address. (I searched the history of the files to understand the context of when the now-problems were introduced, but some were new lines at the time without info to understand why it was like that)

Including this PR will help reduce the diff of adding/changing Python linters, since more problems would be already fixed.

- [x] 1. [Fix unnecessary future import](https://github.com/OSGeo/grass/commit/a3d92fb9a711cf112ebaa7cb73ae4176de36aacb)

   - See 
https://docs.astral.sh/ruff/rules/unnecessary-future-import/ and https://github.com/asottile/pyupgrade?tab=readme-ov-file#__future__-import-removal
   - `from __future__ import absolute_import` and `from __future__ import print_function`
- [x] 2. [python: Fix remaining useless object inheritance](https://github.com/OSGeo/grass/commit/260908b6b6db5b23e32579d8ebe5357ad55e2a8a)

   - Missed or merged back, but fixed here.
- [x] 3. [Fix some checks of type, where the type is already a primitive.](https://github.com/OSGeo/grass/commit/2db950c1a33487fa6b3d8f5f4e5685e6aeb8a296)

   - Changes like 
     ```diff
     -if isinstance(self.epsgCodeDict, type("")):
     +if isinstance(self.epsgCodeDict, str):
     ```
   - See https://docs.astral.sh/ruff/rules/type-of-primitive/
- [ ] 4. [Fix remaining check of type of primitive.](https://github.com/OSGeo/grass/commit/f4ad3dc5dab75ae0d164725e139a8bef340b6e8d)

    -  [ ]  - I want a closer review on this one change (in `python/grass/pygrass/messages/__init__.py`), as it seems to be like a message protocol where the lengths of the data is important, but I'm not certain the code really protects a maximum size. In Python 2, bytes and string were essentially the same (8 bits) (a bit like C-style chars I think), but Python 3 strings are stored as Unicode by default. So is there a possibility that a string with special characters (multibyte characters) are over the allowed size of 2000? Does this interact with a C code, that could cause an overflow or incomplete string?

- [x] 5. [Fix unnecessary calls to functions instead of native literals](https://github.com/OSGeo/grass/commit/bb2640c4fe6125e44e882d657ec24a9bbcaaf66f)

   - See https://docs.astral.sh/ruff/rules/native-literals/
- [x] 6. [Use generator expressions when list comprehension is immediately unpacked](https://github.com/OSGeo/grass/commit/5864b76aef5ecc3dee4d59e5497998c837681f38) 

   - See https://docs.astral.sh/ruff/rules/unpacked-list-comprehension/
- [x] 7. [Use builtin open instead of python3' alias `io.open`](https://github.com/OSGeo/grass/commit/327305c74a4c0941dff7322c6ecd55e8efb4fc63)

   - See https://docs.astral.sh/ruff/rules/open-alias/
- [x] 8. [Use `yield from` when a simple `yield` in a `for` loop is used.](https://github.com/OSGeo/grass/commit/c9a00709e9b5035b91fa8333e51a21c07587ae53)

   - Supported since Python 3.3
   - See https://docs.astral.sh/ruff/rules/yield-in-for-loop/
- [x] 9. [Convert additional `yield` usage inside a list to a `yield from`](https://github.com/OSGeo/grass/commit/3b2bb8c8b60435f8163bebda23c255fad91876b7)

   - Manual fix of the same issue as above, since the comment above but in the loop prevented an automatic detection.
- [x] 10. [Removed extra parentheses where obviously unneeded](https://github.com/OSGeo/grass/commit/31ac7cda92706e2b36fc9b9faa5350fa2d08fdbd)

    - Some other cases were flagged and could have been automatically fixed, but I wasn't confident enough to apply them now.
      - This file had a lot of them that looked like these: https://github.com/OSGeo/grass/blob/44e7ebc46dd83dbb48e9e469a6aa7b0d5a12645c/python/grass/pygrass/modules/grid/grid.py#L350-L351
         The tool was confident it was the same as the others, but didn't remember the specifics of what happens when you extend/append a list depending on the type of the argument (if it is a value, another list, another tuple, a generator).
    - See https://docs.astral.sh/ruff/rules/extraneous-parentheses/
- [x] 11. [Removed extra parentheses in .BestSize((self.xx.GetBestSize())) calls](https://github.com/OSGeo/grass/commit/0e5a31cf71b1b4071dc8f99f2d58dc2dc962166e)

    - Some existing calls already called it without the extra parentheses. From the wxPython docs, I understand that `GetBestSize()` returns a `wx.Size` object, and the `BestSize()` can accept `wx.Size`, a tuple of `(x, y)`, or two arguments, like `x` and `y` separately (at least for https://docs.wxpython.org/wx.lib.agw.aui.framemanager.AuiPaneInfo.html?highlight=bestsize#wx.lib.agw.aui.framemanager.AuiPaneInfo.BestSize). So, once I found the existing usages, I convinced myself that it was possible to use it the other places too.
    - [x] - One particular detection that I found problematic was with this line https://github.com/OSGeo/grass/blob/44e7ebc46dd83dbb48e9e469a6aa7b0d5a12645c/gui/wxpython/iclass/frame.py#L499 in this function https://github.com/OSGeo/grass/blob/44e7ebc46dd83dbb48e9e469a6aa7b0d5a12645c/gui/wxpython/iclass/frame.py#L489-L500
      - [x] - I'm not sure that the current code does what is expected. `SetActiveMap` has some signatures that are `SetActiveMap(self, index)`. Here, we seem to call it with the result of a boolean expression, so `True` or `False`? (assuming only pure-python behaviour, no NumPy-like indexing or something like that). Then, if like some other languages, `True` and `False` are considered like `1` or `0` when numbers are expected, this would mean that only indexes 0 or 1 work properly? Do I understand the full situation? Obviously the "extra" parentheses weren't removed here because of my interrogations.
- [x] 12. [Removed a Python 2.6 version block for json.loads kwargs](https://github.com/OSGeo/grass/commit/9821bacef65d2cdf7ab68b6d61e1aee21ca01208)

    - I won't explain that a special handling for Python 2.6 is not needed anymore.
- [x] 13. [Use raw strings when using `\.`](https://github.com/OSGeo/grass/commit/aa8951a1ac7eddb0e65b672fad5184c4ae825e88)

    - The sequence `\.` is an undefined escape sequence, but can be found in regex-strings. In regex strings, we usually want the backslash character and the dot character, instead of escaping dot like if it was a tab character `\t`. This is what raw strings (strings prefixed with r) do: they treat backslashes as literal characters.
    - In Python 3.12, using `\.` in a string (not raw strings) raises `SyntaxWarning: invalid escape sequence '\.'`

### CODE REVIEW

**Comment by echoix** [comment]
To see the unfixed pyupgrade checks that remain, of the ones I included in this PR, you can use the pyupgrade rules implemented in ruff, using the following:
```python
pip install ruff
ruff --exclude python/libgrass_interface_generator --select UP --ignore UP032,UP031,UP015,UP022,UP030
```

This instantly gives:
```
gui/wxpython/animation/data.py:91:42: UP034 [*] Avoid extraneous parentheses
gui/wxpython/iclass/frame.py:499:32: UP034 [*] Avoid extraneous parentheses
gui/wxpython/iscatt/core_c.py:61:30: UP034 [*] Avoid extraneous parentheses
python/grass/benchmark/app.py:124:8: UP036 Version block is outdated for minimum Python version
python/grass/benchmark/app.py:140:8: UP036 Version block is outdated for minimum Python version
python/grass/benchmark/testsuite/test_benchmark_cli.py:33:8: UP036 Version block is outdated for minimum Python version
python/grass/jupyter/testsuite/interactivemap_test.py:65:16: UP036 Version block is outdated for minimum Python version
python/grass/jupyter/testsuite/map3d_test.py:76:16: UP036 Version block is outdated for minimum Python version
python/grass/jupyter/testsuite/map_test.py:64:16: UP036 Version block is outdated for minimum Python version
python/grass/pygrass/modules/grid/grid.py:349:16: UP034 [*] Avoid extraneous parentheses
python/grass/pygrass/modules/grid/grid.py:350:16: UP034 [*] Avoid extraneous parentheses
scripts/g.extension/g.extension.py:2235:36: UP034 [*] Avoid extraneous parentheses
Found 12 errors.
[*] 6 fixable with the `--fix` option (6 hidden fixes can be enabled with the `--unsafe-fixes` option).
``` 

The versions block issues are for a different behaviour for before Python 3.7 or before Python 3.8. Even if the main branch should only support Python 3.8 and newer, I didn't remove them yet.

**Comment by petrasovaa** [comment]
> * I'm not sure that the current code does what is expected. `SetActiveMap` has some signatures that are `SetActiveMap(self, index)`. Here, we seem to call it with the result of a boolean expression, so `True` or `False`? (assuming only pure-python behaviour, no NumPy-like indexing or something like that). Then, if like some other languages, `True` and `False` are considered like `1` or `0` when numbers are expected, this would mean that only indexes 0 or 1 work properly? Do I understand the full situation? Obviously the "extra" parentheses weren't removed here because of my interrogations.

Yes, it's meant only for 0 and 1 indices, there are only 2 items. So T/F works here. Removing the parentheses should be fine.

**Comment by echoix** [comment]
I added a checklist to the items that I included for review, so one could review and check one item at a time (that they are comfortable of)

**Comment by petrasovaa** [comment]
> As the previous PR, this one is also conservative: I excluded the `python/libgrass_interface_generator` directory altogether,

If I am not mistaken, number 9 is actually from there.

**Comment by echoix** [comment]
> > As the previous PR, this one is also conservative: I excluded the `python/libgrass_interface_generator` directory altogether,
> 
> 
> 
> If I am not mistaken, number 9 is actually from there.

It seems you aren't mistaken. It was changed "manually" by searching the occurrences of yield, and I manually checked if it was in a loop, with the same patterns as what could be transformed. That means that the filter I made was correctly applying, and it didn't flag me this file.

Do you want me to undo this commit, or keep it?

**Comment by petrasovaa** [comment]
> * [ ]   - I want a closer review on this one change (in `python/grass/pygrass/messages/__init__.py`), as it seems to be like a message protocol where the lengths of the data is important, but I'm not certain the code really protects a maximum size. In Python 2, bytes and string were essentially the same (8 bits) (a bit like C-style chars I think), but Python 3 strings are stored as Unicode by default. So is there a possibility that a string with special characters (multibyte characters) are over the allowed size of 2000? Does this interact with a C code, that could cause an overflow or incomplete string?

It turns out this was fixed in the C code a while ago: https://github.com/OSGeo/grass/commit/9b61d2e668c82bd32b28aa560d70707b39cd2426

So the entire check (and shortening the message) should be removed.

**Comment by petrasovaa** [comment]
> > > As the previous PR, this one is also conservative: I excluded the `python/libgrass_interface_generator` directory altogether,
> > 
> > 
> > If I am not mistaken, number 9 is actually from there.
> 
> It seems you aren't mistaken. It was changed "manually" by searching the occurrences of yield, and I manually checked if it was in a loop, with the same patterns as what could be transformed. That means that the filter I made was correctly applying, and it didn't flag me this file for this reason, and I overlooked the folder of the file.
> 
> Do you want me to undo this commit, or keep it?

Based on @nilason's comment in #3251, we should revert that, no?

**Comment by echoix** [comment]
> > * [ ]    - I want a closer review on this one change (in `python/grass/pygrass/messages/__init__.py`), as it seems to be like a message protocol where the lengths of the data is important, but I'm not certain the code really protects a maximum size. In Python 2, bytes and string were essentially the same (8 bits) (a bit like C-style chars I think), but Python 3 strings are stored as Unicode by default. So is there a possibility that a string with special characters (multibyte characters) are over the allowed size of 2000? Does this interact with a C code, that could cause an overflow or incomplete string?
> 
> It turns out this was fixed in the C code a while ago: [9b61d2e](https://github.com/OSGeo/grass/commit/9b61d2e668c82bd32b28aa560d70707b39cd2426)
> 
> So the entire check (and shortening the message) should be removed.

I'll make a PR just for that, since its quite unrelated and will be harder to go back in history, and the fix isn't "bad" per se. Since now all the changes are reviewed, it will be merged before (and will not conflict)

**Pull request merged**
