### PR TITLE
Add new splash screen as decided in #1716

### PR DESCRIPTION
**Pull request by veroandreo**
This PR replaces splash_screen.svg and splash_screen.png by the design proposed in #1716. The width is slightly larger than in the previous one and the height slightly smaller. Let me know what you think :) 

While on it... should we remove the startup_banner files?? Was there any instance in grass 8 in which the startup screen is still used? (I don't remember, sorry)

### CODE REVIEW

**Comment by petrasovaa** [comment]
I tweaked it slightly, there was a one pixel edge. I removed the banner files.

You probably know this, but for next time PRs are to be opened from a branch on your fork...

**Comment by veroandreo** [comment]
> I tweaked it slightly, there was a one pixel edge. I removed the banner files.

Great, thanks!

> You probably know this, but for next time PRs are to be opened from a branch on your fork...

Well, I thought I knew, seems not :)
I did `git checkout -b new-branch` in my local copy, then applied changes, add, commit and `git push upstream new-branch`. From there, I get the link to create the PR. Which is then the correct approach to follow?

**Comment by petrasovaa** [comment]
> I did `git checkout -b new-branch` in my local copy, then applied changes, add, commit and `git push upstream new-branch`. From there, I get the link to create the PR. Which is then the correct approach to follow?

The instructions say `origin`, not `upstream`, that's probably the issue.

**Comment by veroandreo** [comment]
> > I did `git checkout -b new-branch` in my local copy, then applied changes, add, commit and `git push upstream new-branch`. From there, I get the link to create the PR. Which is then the correct approach to follow?
> 
> The instructions say `origin`, not `upstream`, that's probably the issue.

Right! Now I realize. All previous occasions I have done it correctly, I just  confused remote branches names this time... Sorry about that

**Comment by wenzeslaus** [comment]
> All previous occasions I have done it correctly, I just confused remote branches names this time.

I often use _fork and upstream_ as names for my remotes. However, I'm hesitant to put it to the official guide since all guides I have seen online use _origin and upstream_ and it is easier to set it up that way.

**Pull request merged**
