### PR TITLE
script.core.Popen: do not show new window on MS Windows

### PR DESCRIPTION
**Pull request by landam**
See original #3457. When running Python script using GRASS Python API in third party environments (like QGIS) on MS Windows for every command triggered by `script.core.Popen` a new window pops up. This can be very frustrating when running multiple GRASS modules in sequence. See short example below:

[Screencast_02_27_2024_11:43:41_AM.webm](https://github.com/OSGeo/grass/assets/5683186/f3722036-9769-47ad-a60f-885a0b67b967)

And if you can really enjoy terminal windows poping-up. Than here is real example of [SMODERP2D](https://github.com/storm-fsv-cvut/smoderp2d) QGIS Plugin :-)

[Screencast_02_27_2024_11:44:43_AM.webm](https://github.com/OSGeo/grass/assets/5683186/a8cee2a2-4711-425b-b8e7-ac8398e80351)

# How to tests

Run script below in QGIS:

```py
import os

import grass.script.setup as gsetup
from grass.pygrass.modules import Module

gisdb = f"{os.environ['HOMEPATH']}\\Documents\\grassdata"
gsetup.init(gisdb, "world_latlong_wgs84", 'PERMANENT')

Module("g.region", n=90, s=0, w=0, e=100, res=0.02, flags="p")
Module("r.random.surface", output="x", overwrite=True)
print("done")
```

# New behaviour

The PR changes this behaviour. No pop-up windows are show.

[Screencast_02_27_2024_11:50:25_AM.webm](https://github.com/OSGeo/grass/assets/5683186/212fd082-e605-4308-bf82-8f14e03371e0)

### CODE REVIEW

**Comment by landam** [comment]
Note that QGIS is not using GRASS API for launching GRASS commands on background. QGIS hides windows on default: https://github.com/qgis/QGIS/blob/master/python/plugins/grassprovider/grass_utils.py#L420

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
Isn't this missing a "is Windows" condition?

**Comment by petrasovaa** [comment]
> Isn't this missing a "is Windows" condition?

No, see [line 47](https://github.com/OSGeo/grass/pull/3460/files#diff-4815fb3068aa191296cfc3394d441aeb6ae6af2c339930bca4c23544c254bb1dL47)

**Review by wenzeslaus — APPROVED** [review]
This looks good to me. Having a sentence in commit message why this particular combination of options is needed would be nice, but trying to search for it myself, I realize that may be unnecessarily complicated. I noticed it is different than what is in QGIS GRASS wrapper code you linked.

**Comment by wenzeslaus** [comment]
Off topic, but try (>=8.3):

```diff
- import os
- import grass.script.setup as gsetup
-
- gisdb = f"{os.environ['HOMEPATH']}\\Documents\\grassdata"
- gsetup.init(gisdb, "world_latlong_wgs84", 'PERMANENT')
+ import grass.script as gs
+
+gs.setup.init("~/Documents/grassdata/world_latlong_wgs84/PERMANENT")
```

**Review by hellik — APPROVED** [review]

**Comment by landam** [comment]
> Off topic, but try (>=8.3):
> 
> ```diff
> - import os
> - import grass.script.setup as gsetup
> -
> - gisdb = f"{os.environ['HOMEPATH']}\\Documents\\grassdata"
> - gsetup.init(gisdb, "world_latlong_wgs84", 'PERMANENT')
> + import grass.script as gs
> +
> +gs.setup.init("~/Documents/grassdata/world_latlong_wgs84/PERMANENT")
> ```

Works nicely.

**Comment by landam** [comment]
> I noticed it is different than what is in QGIS GRASS wrapper code you linked.

Right, I changed it in 427c00edd3cd30e35f78ca871e0a796d41949694 and tested on MS Windows.

**Pull request merged**
