### PR TITLE
i.segment: Fix uninitialized variable issue

### PR DESCRIPTION
**Pull request by ShubhamDesai**
This pull request address all the uninitialized variables for c files in imagery folder.

Issues:

region_growing.c:725:17: Uninitialized struct member: ngbr_rc.next [uninitStructMember]
    *pngbr_rc = ngbr_rc;
          
region_growing.c:1077:21: Uninitialized struct member: ngbr_rc.next [uninitStructMember]
        *pngbr_rc = ngbr_rc;
                 
region_growing.c:1555:21: Uninitialized struct member: ngbr_rc.next [uninitStructMember]
        *pngbr_rc = ngbr_rc;
                    
region_growing.c:1555:21: Uninitialized variable: ngbr_rc.next [uninitvar]
        *pngbr_rc = ngbr_rc;
                    
region_growing.c:899:10: Uninitialized variable: pl1 [uninitvar]
    pl = pl1 + pl2 - nshared;
         
region_growing.c:899:16: Uninitialized variable: pl2 [uninitvar]
    pl = pl1 + pl2 - nshared;
               
region_growing.c:916:13: Uninitialized variable: count1 [uninitvar]
    count = count1 + count2;
            
region_growing.c:916:22: Uninitialized variable: count2 [uninitvar]
    count = count1 + count2;

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
Just making sure, that was the remaining uninitialized variables issues for imagery modules? The other PR (https://github.com/OSGeo/grass/pull/4022) was for all C++ uninitialized variable issues in imagery, and this one for C in imagery too, so there shouldn't be any left

**Comment by ShubhamDesai** [comment]
> Just making sure, that was the remaining uninitialized variables issues for imagery modules? The other PR (#4022) was for all C++ uninitialized variable issues in imagery, and this one for C in imagery too, so there shouldn't be any left

yes i checked nothing left

**Comment by echoix** [comment]
Do you know if there's a way to enable a check to enforce this on the folders that are fixed? So, once fixed, it would stay fixed? (It's out of scope for this PR, but would prevent wasting all this effort by regressing in the future).

**Comment by echoix** [comment]
I renamed the title to mention only that module, as it is the only one, but we had the context in the PR. It might just help avoid confusion in release notes later on.

**Pull request merged**
