### PR TITLE
lib: Replaced __cmp__ method with compensating methods for Python3 functionality

### PR DESCRIPTION
**Pull request by arohanajit**
wrt to #1809 
This PR updates the  `__cmp__` method in `saferef.py` to be compatible with Python 3. Comparison methods `__eq__`
 and `__lt__` are implemented to maintain the same functionality without requiring changes elsewhere in the code.

**Changes:**

- Added `__eq__` method for equality comparison.
- Added `__lt__` method for less-than comparison.
- The `__cmp__` method now uses the rich comparison methods for its logic.

This shouldn't change overall behavior of `saferef` class.

### CODE REVIEW

**Comment by petrasovaa** [comment]
@echoix any suggestions here? Upstream has no fix for it. It's not used.

**Comment by echoix** [comment]
> @echoix any suggestions here? Upstream has no fix for it. It's not used. 

I'd need to have a deep look for this, as it might be impactful. I think we needed to revert one of my PRs that touched this if I remember well.

I'd be cautious and read well. Was it @wenzeslaus that has experience with this file?

**Review by petrasovaa — DISMISSED** [review]
I would remove the `__cmp__` (it is not used in Python3) and keep the rest.

**Comment by echoix** [comment]
Can you update the title too?

**Comment by echoix** [comment]
Great!

**Review by echoix — APPROVED** [review]

**Comment by nilason** [comment]
This has broken GUI.

**Comment by echoix** [comment]
> This has broken GUI.

Can you show a situation where it occurs?

**Comment by nilason** [comment]
GUI ”freezes” with an hourglass the end of startup.

**Comment by echoix** [comment]
> GUI ”freezes” with an hourglass the end of startup. 

In the meantime, I figured how to reproduce it. I'm almost finished validating the solution for it, and from what I understand, the implementation of eq isn't really the problem, it is its presence that has a problem. Let me finish debugging, after lunch

**Pull request merged**
