### PR TITLE
Python: Python2 removal

### PR DESCRIPTION
**Pull request by a-detiste**
Hi,

Here's some cleanup of the old python 2 versus 3 logic.

https://github.com/OSGeo/grass/discussions/2055

If you are please with this first batch I can proceed to do the remainder.

### CODE REVIEW

**Comment by a-detiste** [comment]
I see some long lines in the wx/ files. At another try I will use `black` there.

**Comment by tmszi** [comment]
Before you push your changes into remote branch use locally [pre-commit](https://github.com/OSGeo/grass/blob/main/doc/development/submitting/submitting.md#use-pre-commit) please.

**Comment by a-detiste** [comment]
Thanks for caring, I really want to get this right.

**Review by petrasovaa — APPROVED** [review]
This looks great, thanks!

**Pull request merged**
