### PR TITLE
CI: Updated parser doc in scripts/d.wms.py to fix E501

### PR DESCRIPTION
**Pull request by arohanajit**
Fixed `flake8: E501` in `scripts/d.wms.py`. I just split description into multiple lines to comply with `max-line-length`

### CODE REVIEW

**Comment by neteler** [comment]
Does the parser accept multiple description lines?

**Comment by arohanajit** [comment]
If I am being honest I don't really know. I was hoping to rely on github actions to highlight any potential errors. If you could tell me how can I check for this (I am new to this repo) that would be really helpful! Considering how common this error is

**Comment by wenzeslaus** [comment]
For now, just don't touch these #% lines. We need to figure out what we
actually want to do with them.

**Comment by neteler** [comment]
> I was hoping to rely on github actions to highlight any potential errors.

(In this case there is AFAIK no test implemented, hence the github actions can not catch any potential error.)

**Pull request closed without merging**
