### PR TITLE
i18n: Translation update of Latvian language

### PR DESCRIPTION
**Pull request by marisn**
As Latvian language translations live in git and not in Transifex, here is the latest translation update for master.
A reworked PR due to git fubar on my side.

### CODE REVIEW

**Comment by neteler** [comment]
Feel free to merge or indicate a reviewer :)

**Comment by marisn** [comment]
> Feel free to merge or indicate a reviewer :)

Unfortunately I can not merge or request a review. I can only kindly ask and hope for the best. Markus (@neteler), would you, please, merge this PR for me?

**Comment by neteler** [comment]
> > Feel free to merge or indicate a reviewer :)
> 
> Unfortunately I can not merge or request a review. 

Why is that? Let's fix it :)
Indeed: I see, that you are not yet listed here under [members](https://github.com/orgs/OSGeo/teams/grass-committers/members). But you should have received an invitation as core comitter to this repo, see

https://trac.osgeo.org/grass/wiki/GitMigration#Authorship:RecognizingtheGRASSGIScontributorsduringandaftermigration
- https://trac.osgeo.org/grass/browser/grass-addons/tools/svn2git/AUTHORS.txt

Maybe you need to enable in your GH profile also the email address mentioned in AUTHORS.txt?

**Comment by neteler** [comment]
FYIW, I have now generate a new invitation to you thru the GH interface

**Comment by marisn** [comment]
> Maybe you need to enable in your GH profile also the email address mentioned in AUTHORS.txt?

Strange. I had it done back then when migration to GH was announced. Still it is listed as a secondary address.

**Pull request merged**
