### PR TITLE
style: Fix yoda-conditions (SIM300)

### PR DESCRIPTION
**Pull request by echoix**
Ruff rule: https://docs.astral.sh/ruff/rules/yoda-conditions/

### CODE REVIEW

**Review by ninsbl — APPROVED** [review]
The changes in spatial_extent.py are less obvious yoda comparisons as both sides are variables... Do you know why the order is changed there? Just curios for future programing...

**Comment by echoix** [comment]
> The changes in spatial_extent.py are less obvious yoda comparisons as both sides are variables... Do you know why the order is changed there? Just curios for future programing...

I know, I double checked and was finding it weird at first. I was about to place an ignore directive. Yoda conditions are where the constants are at the left instead of right, and the single letter variables (W, E, N, S) are defined as literals (that is, a single constant value). Since the complete expressions were already complex enough for me to understand, I judged that it wasn't worse with it reversed, for anyone new that would need to read the code.

**Comment by echoix** [comment]
You're seeing that the changes are starting to be a bit more opinionated, as a lot of the big easy changes are already made.

There's also a big batch of single-violation fixes to do, (see the ruff tracking issue I made the other day) but I'm not sure how to combine them properly in a PR. Do you rather have a series of about 12-20 PRs that only have one violation to fix, but also helps tracking down what violations are enabled?

**Comment by ninsbl** [comment]
> Do you rather have a series of about 12-20 PRs that only have one violation to fix, but also helps tracking down what violations are enabled?

As you prefer. I am fine with either approach...

**Comment by echoix** [comment]
Thanks again for taking the time to read these PRs for me. I hope you don't mind that I assign to you these. At least the PRs gets a first answer in less than a week. Thanks again!

**Comment by echoix** [comment]
I need to solve conflicts now, and will probably have to re-approve

**Comment by ninsbl** [comment]
I am finally back at a PC and can do more efficient reviews, compared to reviewing on a mobile phone... Happy to do batches of PRs when I have some available time...

**Review by ninsbl — APPROVED** [review]

**Pull request merged**
