### PR TITLE
Jupyter: Bug fix for 3D renderer with KeyError: "GRASS_REGION" 

### PR DESCRIPTION
**Pull request by chaedri**
* Fixes bug. 

Bug description: When `render()` is called more than once in an instance of the `Grass3dRenderer` class, it raises `KeyError: 'GRASS_REGION'`.

Fix: I'm still not sure why exactly this occurs but I think it's because each time `render()` is called it copies the `os.environ` again. I created a new attribute `self._env` in the `__init__()` function and replaced all `os.environ.copy()`. Then, the code ran for me. Feedback and comments welcome.

### CODE REVIEW

**Comment by chaedri** [comment]
@wenzeslaus I may have fixed it! Here's a binder link to test. The binder link fails right now because I'm still working on it. It works when pyvirtualdisplay is not sured but it fails when it is.

https://mybinder.org/v2/gh/chaedri/grass/region-fix?labpath=doc%2Fnotebooks%2Fgrass_jupyter.ipynb

I'm not sure I fully understand why having multiple calls of `os.environ.copy` is problem but it's working for me now.

**Comment by veroandreo** [comment]
I still get the `'GRASS_REGION'` error in the last cell of the notebook

**Comment by petrasovaa** [comment]
`GRASS_REGION` is not guaranteed to be in the environment (e.g. when `use_region` is used), so I would set it only when it is there which will fix the error. Additionally, I removed `_region_set` attribute from `RegionManagerFor3D` because it doesn't work correctly now, since the `render` function always uses a new environment. It will always now take the region from the elevation raster (unless use_region/saved_region is specified), so 2 subsequent calls of `render` can display different extents (e.g. elevation and then elev_lid792_1m). This would not work for 2D, but for 3D it probably makes sense.

```
diff --git a/python/grass/jupyter/region.py b/python/grass/jupyter/region.py
index d7f2027da..979864213 100644
--- a/python/grass/jupyter/region.py
+++ b/python/grass/jupyter/region.py
@@ -124,7 +124,8 @@ class RegionManagerFor2D:
     def set_region_from_env(self, env):
         """Copies GRASS_REGION from provided environment
         to local environment to set the computational region"""
-        self._env["GRASS_REGION"] = env["GRASS_REGION"]
+        if "GRASS_REGION" in env:
+            self._env["GRASS_REGION"] = env["GRASS_REGION"]
 
     def set_region_from_command(self, module, **kwargs):
         """Sets computational region for rendering.
@@ -185,7 +186,6 @@ class RegionManagerFor3D:
         """
         self._use_region = use_region
         self._saved_region = saved_region
-        self._region_set = False
 
     def set_region_from_command(self, env, **kwargs):
         """Sets computational region for rendering.
@@ -199,17 +199,13 @@ class RegionManagerFor3D:
         """
         if self._saved_region:
             env["GRASS_REGION"] = gs.region_env(region=self._saved_region, env=env)
-            self._region_set = True
             return
         if self._use_region:
             # use current
             return
-        if self._region_set:
-            return
         if "elevation_map" in kwargs:
             elev = kwargs["elevation_map"].split(",")[0]
             try:
                 env["GRASS_REGION"] = gs.region_env(raster=elev, env=env)
-                self._region_set = True
             except CalledModuleError:
                 return
```

**Comment by chaedri** [comment]
@petrasovaa That worked! Thank you :)

**Pull request merged**
