### PR TITLE
CI: ugly hack to debug Windows builds in CI fail

### PR DESCRIPTION
**Pull request by neteler**
Attempt to see more (error) messages.

Related to bug #2454

### CODE REVIEW

**Comment by neteler** [comment]
It is weird...:

`
2022-06-28T08:25:24.7528731Z C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: --export-dynamic is not supported for PE+ targets, did you mean --export-all-symbols?
2022-06-28T08:25:24.8306939Z if [ "/d/a/grass/grass/dist.x86_64-w64-mingw32/bin/d.labels.exe" != "" ] ; then GISRC=/d/a/grass/grass/dist.x86_64-w64-mingw32/demolocation/.grassrc83 GISBASE=D:/a/grass/grass/dist.x86_64-w64-mingw32 PATH="/d/a/grass/grass/dist.x86_64-w64-mingw32/bin:/d/a/grass/grass/dist.x86_64-w64-mingw32/bin:/d/a/grass/grass/dist.x86_64-w64-mingw32/scripts:$PATH" PYTHONPATH="D:/a/grass/grass/dist.x86_64-w64-mingw32/etc/python;D:/a/grass/grass/dist.x86_64-w64-mingw32/gui/wxpython;$PYTHONPATH" PATH="/d/a/grass/grass/dist.x86_64-w64-mingw32/bin:/d/a/grass/grass/dist.x86_64-w64-mingw32/bin:/d/a/grass/grass/dist.x86_64-w64-mingw32/scripts:/d/a/grass/grass/dist.x86_64-w64-mingw32/lib:/d/a/grass/grass/dist.x86_64-w64-mingw32/lib:/c/OSGeo4W/bin:/usr/bin:/mingw64/bin" LC_ALL=C LANG=C LANGUAGE=C /d/a/grass/grass/dist.x86_64-w64-mingw32/bin/d.labels.exe --html-description | grep -v '</body>\|</html>' ; fi
2022-06-28T08:25:24.8990288Z make[3]: *** [../../include/Make/Html.make:14: d.labels.tmp.html] Error 1
`

**Comment by hellik** [comment]
there are 2 issues in the configure

```
checking whether to use Cairo... "yes"
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
Package 'cairo', required by 'virtual:world', not found
checking for location of cairo includes... /d/a/grass/grass/include
checking cairo.h usability... yes
checking cairo.h presence... yes
checking for cairo.h... yes
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
checking for location of cairo library... 
checking for cairo linking flags... -L/d/a/grass/grass/mswindows/osgeo4w/lib -lcairo -lfontconfig
Package 'cairo', required by 'virtual:world', not found
checking for cairo_create... yes
checking for cairo_xlib_surface_create_with_xrender_format... no
checking for cairo_xlib_surface_get_xrender_format... no
```



```
checking whether to use FreeType... "yes"
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
checking for location of FreeType includes... /mingw64/include/freetype2
Package 'freetype2', required by 'virtual:world', not found
checking ft2build.h usability... yes
checking ft2build.h presence... yes
checking for ft2build.h... yes
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
checking for location of FreeType library... 
Package 'freetype2', required by 'virtual:world', not found
checking for FT_Init_FreeType in -lfreetype... yes
```

not sure what  **virtual:world**  is for.

though, config seems to be ok

```
  Cairo support:              yes
  DWG support:                no
  FFTW support:               yes
  FreeType support:           yes
```

**Comment by hellik** [comment]
it seems to be an issue of the build environment (results of googling the error message)

**Comment by hellik** [comment]
maybe some hints in [a github issue](https://github.com/rust-lang/pkg-config-rs/issues/23)

 `fixed by installing mingw-w64-x86_64-pkg-config or mingw-w64-i686-pkg-config instead of pkg-config.`

**Comment by neteler** [comment]
Here is the full log (hopefully accessible):
https://github.com/OSGeo/grass/commit/6866c3fb6b065796ef7b5de71b5d8389c55db735/checks/7088374248/logs

Here also as a ZIP file: [ci_windows_mingw_errors.zip](https://github.com/OSGeo/grass/files/9005805/ci_windows_mingw_errors.zip)

**Comment by neteler** [comment]
> maybe some hints in [a github issue](https://github.com/rust-lang/pkg-config-rs/issues/23)
> 
> `fixed by installing mingw-w64-x86_64-pkg-config or mingw-w64-i686-pkg-config instead of pkg-config.`

As far as I see this is already used - see:
https://github.com/OSGeo/grass/blob/2af9d79abd626a6c3031bdebed5321048855a9e2/.github/workflows/osgeo4w.yml#L39

**Comment by hellik** [comment]
> > maybe some hints in [a github issue](https://github.com/rust-lang/pkg-config-rs/issues/23)
> > `fixed by installing mingw-w64-x86_64-pkg-config or mingw-w64-i686-pkg-config instead of pkg-config.`
> 
> As far as I see this is already used - see:
> 
> https://github.com/OSGeo/grass/blob/2af9d79abd626a6c3031bdebed5321048855a9e2/.github/workflows/osgeo4w.yml#L39

Though not sure mingw-w64-x86_64 is used for compiling

**Comment by neteler** [comment]
> Though not sure mingw-w64-x86_64 is used for compiling

This remark isn't clear to me...

**Comment by ninsbl** [comment]
Sorry for my silence n this. For some reasons I do not receive GH notifications any more although I am watching issues...

Probably the issue is really the PKG_CONFIG_PATH., see e.g. https://github.com/msys2/setup-msys2/issues/171

Will try to have a look at this the comming days...

**Comment by ninsbl** [comment]
The culprit is likely here:
https://github.com/OSGeo/grass/runs/7513175054?check_suite_focus=true#step:5:242

Using msys2-setup@v2 action seems to help (tests are currently running in my fork...)...

I suggest to abandon this PR in favor of #2508...

**Comment by neteler** [comment]
> I suggest to abandon this PR in favor of #2508...

Yes, it was just a test.
Closing.

**Pull request closed without merging**
