### PR TITLE
contributing: Update to Black 23.1.0

### PR DESCRIPTION
**Pull request by wenzeslaus**
This mostly removes empty lines after function definitions. It also removes some overcomplicated syntax. It changes formatting of some multi-line statements.

This also updates version in the pre-commit hook and CI.

### CODE REVIEW

**Comment by echoix** [comment]
Why don't we use the black that is included in the existing Super-Linter workflow (but explicitly disabled in our config)? It would remove one runner usage to the CI. There isn't really a specific OS/python config required for black to do its job correctly, only one that is supported.

**Comment by wenzeslaus** [comment]
> Why don't we use the black that is included in the existing Super-Linter workflow (but explicitly disabled in our config)?

We introduced Black before it was stable, so I wanted to have fine control over the version.

Given this PR, this might be a consideration even now, but I don't know.

Another reason was to give extra clear error messages in CI, but that's perhaps less needed as people are more accustomed to the tooling and CI and we have pre-commit hook.

> Black has a stable style that changes at the first release of the year...

If we use the one in Super-Linter or MegaLinter, the question is when they update.

> It could be processed in a next PR if it sounds appropriate

Alternatively, you can merge some of the Python checks. Neither Flake8 nor Black need compiled code.

**Comment by echoix** [comment]
> > Black has a stable style that changes at the first release of the year...
> 
> 
> 
> If we use the one in Super-Linter or MegaLinter, the question is when they update.

I see that Super-Linter didn't update it yet (even in their main branch) even if black has been released one month ago. There is a PR of their weekly Python update that contains the new version that isn't merged yet. Their last release was two months ago (Jan). For MegaLinter, we check for updates daily, and get merged to main (ie beta) quickly, and usually we release every week or two, but now it's been three weeks because we want to make sure it's stable. 




> 
> Alternatively, you can merge some of the Python checks. Neither Flake8 nor Black need compiled code.
Oh, I didn't remember that we had other checks that were in an independent PR.

**Comment by wenzeslaus** [comment]
> ...other checks that were in an independent workflow.

All checks which have different text before forward slash from a different workflow, or number of YAML files under workflow can tell the exact number. Additional checks could also be added after Black and Flake8, but naming it seems hard.

The independent checks and Super-Linter/MegaLinter checks give results from multiple checks. Simply appending them would end after the first failure which is another reason why they are separate.

Another piece here is that checks such as Black are relatively fast, so there are many queued checks, but once they run, they are done quickly allowing the queue to move again. The checks which the CI is waiting for to complete at this moment are all checks which build or build & test (macOS, Ubuntu, ...), not these quick checks, so perhaps separate Black is not really an issue. What do you think?

**Pull request merged**
