### PR TITLE
r.import: try to avoid failure after v.proj

### PR DESCRIPTION
**Pull request by lucadelu**

### CODE REVIEW

**Comment by lucadelu** [comment]
Yes you are right, but I have a problem running actual test, it return this error.

```
WARNING: Projection of dataset does not appear to match current location.

         Location PROJ_INFO is:
         name: Lambert Conformal Conic
         proj: lcc
         datum: nad83
         a: 6378137.0
         es: 0.006694380022900787
         lat_1: 36.16666666666666
         lat_2: 34.33333333333334
         lat_0: 33.75
         lon_0: -79
         x_0: 609601.22
         y_0: 0
         no_defs: defined

         Dataset PROJ_INFO is:
         name: Albers_Conical_Equal_Area
         datum: nad83
         ellps: grs80
         proj: aea
         lat_1: 29.5
         lat_2: 45.5
         lat_0: 23
         lon_0: -96
         x_0: 0
         y_0: 0
         no_defs: defined

         ERROR: proj
Importing raster map <test_r_import_imported>...
 100%
ERROR: Please check the 'extent' parameter
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/lucadelu/github/grass/dist.x86_64-pc-linux-gnu/scripts/r.import", line 147, in cleanup
    mapset=grass.gisenv()['MAPSET'])['fullname']:
KeyError: 'MAPSET'
```

but if I try from ipython console no error

```
In [1]: import grass.script as grass

In [2]: grass.gisenv()['MAPSET']
Out[2]: 'user1'
```

**Comment by pmav99** [comment]
You mean you added a test and when you try to run it, you get this error? if yes, could you push it?

**Comment by metzm** [comment]
Please use vector_info_topo from grass.script instead of pygrass (keep it simple)

**Comment by metzm** [comment]
Simpler solution:
```
diff --git a/scripts/r.import/r.import.py b/scripts/r.import/r.import.py
index 50df9df9c..00122422a 100755
--- a/scripts/r.import/r.import.py
+++ b/scripts/r.import/r.import.py
@@ -319,6 +319,9 @@ def main():
         try:
             grass.run_command('v.proj', input=vreg, output=vreg,
                               location=tgtloc, mapset=tgtmapset, quiet=True)
+	    # test if v.proj created a valid area
+	    if grass.vector_info_topo(vreg)['areas'] != 1:
+		grass.fatal(_("Please check the 'extent' parameter"))
         except CalledModuleError:
             grass.fatal(_("Unable to reproject to source location"))
```

**Comment by neteler** [comment]
@metzm will you apply your solution?

**Comment by metzm** [comment]
> @metzm will you apply your solution?

Done in [f4cab7c](https://github.com/OSGeo/grass/commit/f4cab7cc3f5a0a2c4cd355c7e4e768b12ccd0a86)

**Comment by neteler** [comment]
> > @metzm will you apply your solution?
> 
> Done in [f4cab7c](https://github.com/OSGeo/grass/commit/f4cab7cc3f5a0a2c4cd355c7e4e768b12ccd0a86)

I'd suggest a backport to 7.8

**Comment by lucadelu** [comment]
Thanks @metzm

**Comment by neteler** [comment]
> > > @metzm will you apply your solution?
> > 
> > 
> > Done in [f4cab7c](https://github.com/OSGeo/grass/commit/f4cab7cc3f5a0a2c4cd355c7e4e768b12ccd0a86)
> 
> I'd suggest a backport to 7.8

done in 6b643a33cb413125c5e1858da61bdc48f68549fe

**Pull request closed without merging**
