### PR TITLE
i.vi: support soil_line_slope for PVI

### LINKED ISSUE #2558: [Feat] i.vi: Support soil_line_slope parameter for PVI
`soil_line_parameter` is already implemented for MSAVI in i.vi. Although PVI uses the same variable, it computes with this value equal to 1. The user should have an option to set it to different values.

### PR DESCRIPTION
**Pull request by pesekon2**
fix #2558

### CODE REVIEW

**Comment by nilason** [comment]
Merged this to main with clang-formatting. Had to close/reopen as the CI runners didn't start.

**Comment by pesekon2** [comment]
@nilason: Great, thanks. The runners seem to finish correctly. Shall I merge then?

**Comment by nilason** [comment]
> @nilason: Great, thanks. The runners seem to finish correctly. Shall I merge then?

:-) 
I have personally not tested, I’ll leave that decision to more experienced fellows :).

**Comment by pesekon2** [comment]
> :-) I have personally not tested, I’ll leave that decision to more experienced fellows :).

Okay, okay.

**Comment by petrasovaa** [comment]
Since I am not familiar with this index, I was wondering @pesekon2, did you verify this fix is scientifically correct? I just find it weird there was 1 instead of the slope of the soil line (that's angle right?) and the note in the manual (which BTW would be good to update) didn't quite clarify this to me. I wonder whether the soil line intercept should be incorporated too? The formulas I found for PVI elsewhere looked quite different, which adds to my confusion.

**Comment by pesekon2** [comment]
> did you verify this fix is scientifically correct?  ... The formulas I found for PVI elsewhere looked quite different, which adds to my confusion.

Yes I did, but I understand the confusion. There are generally two forms around internet that are equivalent and the one in `i.vi` is one of them. Pretty good explanation of PVI and our formula (with the equivalence to the other one) can be found [here](https://forum.step.esa.int/t/pvi-index-which-formula-is-right/6416/2).

> I just find it weird there was 1 instead of the slope of the soil line (that's angle right?) and the note in the manual (which BTW would be good to update) didn't quite clarify this to me

I have to say that I also didn't get the note in the manual but had thought that it was just me. Even more, I found it suspicious as 1 seems just like a totally random number. Maybe @YannChemin (the original author) can elaborate on that?

**Comment by pesekon2** [comment]
As @YannChemin didn't object against merging and the formula is scientifically correct, I will merge the PR.

**Comment by petrasovaa** [comment]
@pesekon2 could you update the manual?

**Comment by pesekon2** [comment]
> @pesekon2 could you update the manual?

@petrasovaa Yes I could, please see #2903. 

However, I don't know what to do with the line ` for a isovegetation lines (lines of equal vegetation) would all be parallel to the soil line therefore a=1.` I have no idea what did the author mean, nor does it make sense to me syntax-wise.

**Comment by pesekon2** [comment]
> > However, I don't know what to do with the line ` for a isovegetation lines (lines of equal vegetation) would all be parallel to the soil line therefore a=1.` I have no idea what did the author mean, nor does it make sense to me syntax-wise.
> 
> I suggest removing it, no need for more confusion.


OK. Deleted in [62f5a3f](https://github.com/OSGeo/grass/pull/2903/commits/62f5a3fe209dfbe599d340ecf5e71bffbb35e7ab). 

The formula in the docs was always correct (but the code didn't correspond to that) so I didn't change that.

**Pull request merged**
