### PR TITLE
r.in.wms: fix get region extent for WMS query, if location is 'XY location (unprojected)'

### PR DESCRIPTION
**Pull request by tmszi**
**To Reproduce**

1. Create Location with XY coordinate system (not projected)
2. Launch `grass79 --gui`
3. Launch Add web service layer dialog
4. Add some layer from `http://ows.mundialis.de/services/service?` (OpenStreetMap WMS - by terrestris layer)
5. Check error message in the emulator terminal

**Error message**:

```
Traceback (most recent call last):
  File "/usr/lib64/grass79/scripts/m.proj", line 292, in <module>
    main()
  File "/usr/lib64/grass79/scripts/m.proj", line 164, in main
    if "XY location" in kv['+proj'] and (ll_in or ll_out):
KeyError: '+proj'
Traceback (most recent call last):
  File "/usr/lib64/grass79/gui/scripts/d.wms", line 214, in <module>
    sys.exit(main())
  File "/usr/lib64/grass79/gui/scripts/d.wms", line 207, in main
    temp_map = wms.GetMap(options, flags)
  File "/usr/lib64/grass79/etc/r.in.wms/wms_base.py", line 212, in GetMap
    self.bbox = self._computeBbox()
  File "/usr/lib64/grass79/etc/r.in.wms/wms_base.py", line 335, in _computeBbox
    quiet=True)  # TODO: stdin
  File "/usr/lib64/grass79/etc/python/grass/script/core.py", line 566, in read_command
    return handle_errors(returncode, stdout, args, kwargs)
  File "/usr/lib64/grass79/etc/python/grass/script/core.py", line 394, in handle_errors
    returncode=returncode)
grass.exceptions.CalledModuleError: Module run m.proj m.proj --q -d proj_out=+proj=longlat +no_defs +a=6378137 +rf=298.257223563 +towgs84=0.000,0.000,0.000 +type=crs  proj_in=XY location (unprojected) input=/home/tomas/grassdata/xy/PERMANENT/.tmp/gentoo-gnu-linux/16034.0 ended with error
Process ended with non-zero return code 1. See errors in the (error) output.
```

### CODE REVIEW

**Comment by neteler** [comment]
> **To Reproduce**
> 
>     1. Create Location with XY coordinate system (not projected)
> 
>     2. Launch `grass79 --gui`

2a: Select/create XY location

>     3. Launch Add web service layer dialog
> 
>     4. Add some layer from `http://ows.mundialis.de/services/service?` (OpenStreetMap WMS - by terrestris layer)
> 
>     5. Check error message in the emulator terminal
> 
> **Error message**:

I tried this today and no error messages appeared.
Of course also no map while it is listed in the "Display" tab.

Perhaps it would be enough to catch "XY location" and open a message that this won't work?

**Comment by tmszi** [comment]
> > **To Reproduce**
> > ```
> > 1. Create Location with XY coordinate system (not projected)
> > 
> > 2. Launch `grass79 --gui`
> > ```
> 
> 2a: Select/create XY location
> 
> > ```
> > 3. Launch Add web service layer dialog
> > 
> > 4. Add some layer from `http://ows.mundialis.de/services/service?` (OpenStreetMap WMS - by terrestris layer)
> > 
> > 5. Check error message in the emulator terminal
> > ```
> > 
> > 
> > **Error message**:
> 
> I tried this today and no error messages appeared.
> Of course also no map while it is listed in the "Display" tab.
> 
> Perhaps it would be enough to catch "XY location" and open a message that this won't work?

This is very interesting, I recompiled GRASS 7.9 with the latest code, and the error still shows up.

r_in_wms

```
GRASS xy/PERMANENT:~ > g.version -g
version=7.9.dev
date=2021
revision=96a65e10f
build_date=2021-05-09
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
```

**Comment by ninsbl** [comment]
Bumping up milestone as 8.0.1 is due in two days, while this has not been part of RC1 and there has not been activity for some time.

**Review by petrasovaa — APPROVED** [review]
I think this can be merged for now, but there should be a better solution for GUI to inform users.

**Pull request merged**
