### PR TITLE
CI: upgrade actions and runners (8.2)

### PR DESCRIPTION
**Pull request by neteler**
- actions are upgraded to latest
- partial sync to respective files in `main`

### CODE REVIEW

**Comment by neteler** [comment]
Mhh, how to fix this?

https://github.com/OSGeo/grass/actions/runs/4266568587/jobs/7427243120#step:5:15

```
Run $exe = 'osgeo4w-setup.exe' $url = 'http://download.osgeo.org/osgeo4w/v2/' + $exe (New-Object System.Net.WebClient).DownloadFile($url, $exe) Start-Process ('.\'+$exe) -ArgumentList '-A -g -k -q -s http://download.osgeo.org/osgeo4w/v2/ \
ParserError: D:\a\_temp\71d084f4-7d5f-4b2f-b425-5a98c762d7bc.ps1:2
Line |
   2 |  $exe = 'osgeo4w-setup.exe' $url = 'http://download.osgeo.org/osgeo4w/ …
     |                             ~~~~
     | Unexpected token '$url' in expression or statement.

Error: Process completed with exit code 1.
```

**Comment by nilason** [comment]
> Mhh, how to fix this?
> 
> https://github.com/OSGeo/grass/actions/runs/4266568587/jobs/7427243120#step:5:15
> 
> ```
> Run $exe = 'osgeo4w-setup.exe' $url = 'http://download.osgeo.org/osgeo4w/v2/' + $exe (New-Object System.Net.WebClient).DownloadFile($url, $exe) Start-Process ('.\'+$exe) -ArgumentList '-A -g -k -q -s http://download.osgeo.org/osgeo4w/v2/ \
> ParserError: D:\a\_temp\71d084f4-7d5f-4b2f-b425-5a98c762d7bc.ps1:2
> Line |
>    2 |  $exe = 'osgeo4w-setup.exe' $url = 'http://download.osgeo.org/osgeo4w/ …
>      |                             ~~~~
>      | Unexpected token '$url' in expression or statement.
> 
> Error: Process completed with exit code 1.
> ```

The empty lines are important:

https://github.com/OSGeo/grass/blob/b9f6c48a9c494c4d1a9f54dfc6de182de1c5fc53/.github/workflows/osgeo4w.yml#L43-L52

**Comment by neteler** [comment]
> The empty lines are important:

Ah, thanks!

**Comment by nilason** [comment]
> > The empty lines are important:
> 
> Ah, thanks!

:-) yaml multiline strings is a terrible field (see eg. https://yaml-multiline.info).

**Review by nilason — APPROVED** [review]

**Comment by nilason** [comment]
> Mhh, how to fix this?
> 
> https://github.com/OSGeo/grass/actions/runs/4266568587/jobs/7427243120#step:5:15
> 
> ```
> Run $exe = 'osgeo4w-setup.exe' $url = 'http://download.osgeo.org/osgeo4w/v2/' + $exe (New-Object System.Net.WebClient).DownloadFile($url, $exe) Start-Process ('.\'+$exe) -ArgumentList '-A -g -k -q -s http://download.osgeo.org/osgeo4w/v2/ \
> ParserError: D:\a\_temp\71d084f4-7d5f-4b2f-b425-5a98c762d7bc.ps1:2
> Line |
>    2 |  $exe = 'osgeo4w-setup.exe' $url = 'http://download.osgeo.org/osgeo4w/ …
>      |                             ~~~~
>      | Unexpected token '$url' in expression or statement.
> 
> Error: Process completed with exit code 1.
> ```

#2861 removes the need for empty lines for line break. Will be easier to maintain.

**Pull request merged**
