### PR TITLE
Fix -Wunused-result compiler warnings

### LINKED ISSUE #2128: [Bug] Warnings for -Wunused-result in GCC build
**Describe the bug**

A build with GCC can produce warnings _ignoring return value_ (`-Wunused-result`) coming from library functions declared with attribute `warn_unused_result` (such as _fgets_ and _fread_).

```
warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
```

This happens with the default setting on Ubuntu (so likely other systems too) and with the current development practices, today's warnings are tomorrow's errors.

**To Reproduce**

Compile with GGC with `-Wunused-result`, `-Werror=unused-result`, or default settings on Ubuntu 20.04. See also build in the _ubuntu-20.04 tests_ job in the CI (e.g., [run 4947257936](https://github.com/OSGeo/grass/runs/4947257936?check_suite_focus=true)) or a binder build ([link for main](https://mybinder.org/v2/gh/OSGeo/grass/main?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fbasic_example.ipynb), may not rebuild).

**Expected behavior**

No warnings. (Return values checked I guess.)

**Screenshots**

```
main.c: In function ‘update_reclass_maps’:
main.c:138:2: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  fgets(buf2, 255, fp);
  ^~~~~~~~~~~~~~~~~~~~
...
main.c:148:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(str, l, 1, fp);
  ^~~~~~~~~~~~~~~~~~~~
```

**System description**

- Operating System: Ubuntu 20.04
- GRASS GIS version: releasebranch_8_0, main

**Additional context**

Besides the potential of this being configures as an error in the future, the warning is currently visible in several places, namely in some of the CI builds and during a build on mybinder.org where end users may see it too.

### PR DESCRIPTION
**Pull request by nilason**
Fixes #2128.

Also reported in #2156.

**Affects:**

Modules
- d.mon
- g.proj
- g.rename
- ps.map
- r.fill.dir
- r.grow.distance
- r.in.ascii
- r.in.bin
- r.in.gridatb
- r.in.mat
- r.param.scale
- r.topmodel
- v.vol.rst

GRASS Library parts
- lib/bitmap
- lib/cairodriver
- lib/db/dbmi_driver
- lib/gis
- lib/rst/interp_float
- lib/vector/Vlib/

### CODE REVIEW

**Comment by wenzeslaus** [comment]
Please consider splitting this to modules and library would be helpful. Not only that it will be smaller PRs, but the `G_fatal...` calls are much more likely to be the correct solution for modules than for the library (although I assume that's what we will end up doing anyway). We can get one of the PRs in faster.

**Comment by wenzeslaus** [comment]
@BadAssassin opened similar PR to this one (#2232), but considers this one better, so that seems like +1 for merging this PR.

**Comment by nilason** [comment]
I just took a fresh look at this and corrected a regression on bitmap.c which happened during rebase.

Almost exclusively these fixes are file I/O related, handling return values from calls with read()/fread(), write()/fwrite(), fgets(), fscanf(), getcwd(). In general it can be said that what up till now silently failed will now at least be accompanied with a message. I believe this is ready to be merged.

**Comment by asimrp** [comment]
Looks good to me :+1:  

Not sure what the scope of this PR is but a quick grep through the main branch, after pulling commits from this PR, reveals some `read()` calls that need similar treatment.  That is, the return value is used without checking for error or ignored altogether.  For example, see `RTreeReadBranch()` and `RTreeReadNode()` from [rtree/io.c](https://github.com/OSGeo/grass/blob/main/lib/vector/rtree/io.c), the three `read()` calls in [r.drain/main.c](https://github.com/OSGeo/grass/blob/main/raster/r.drain/main.c), `read_block()` from [raster3d/r3.in.v5d/binio.c](https://github.com/OSGeo/grass/blob/main/raster3d/r3.in.v5d/binio.c), and several more...

The command I used is
```
git grep -A 3 '[^a-zA-Z_.(]read('
```

**Comment by nilason** [comment]
> Looks good to me 👍

👍

> Not sure what the scope of this PR is but a quick grep through the main branch, after pulling commits from this PR, reveals some `read()` calls that need similar treatment. That is, the return value is used without checking for error or ignored altogether. For example, see `RTreeReadBranch()` and `RTreeReadNode()` from [rtree/io.c](https://github.com/OSGeo/grass/blob/main/lib/vector/rtree/io.c), the three `read()` calls in [r.drain/main.c](https://github.com/OSGeo/grass/blob/main/raster/r.drain/main.c), `read_block()` from [raster3d/r3.in.v5d/binio.c](https://github.com/OSGeo/grass/blob/main/raster3d/r3.in.v5d/binio.c), and several more...

The aim of this PR is as the title suggests, to fix -Wunused-result compiler warnings. One step in a campaign eliminating all `-Wall` warnings (see eg. #2156).

**Pull request merged**
