### PR TITLE
r.viewshed: initialize struct member before using struct

### PR DESCRIPTION
**Pull request by ymdatta**
This was reported by cppcheck tool. Technically, we are not using the member in the struct variable in any of the subsequent functions, but it's a good practice to initialize all the struct members whenever possible.

Initial errors from cppcheck tool:

image

After applying the patch:

image

Additional information:

1. Machine used: Virtual Machine running Ubuntu 22.04.4 LTS.
2. Reproduction rate: 100%, reproducible every time.
3. Architecture: Not specific to any underlying architecture.

Testing done:

Ran the complete `test_r_viewshed.py` gunittest from the testsuite and it was successful.

### CODE REVIEW

**Comment by echoix** [comment]
What's the reasoning for using -1 as the initial value for angle? (I understand that 0 is a valid value that might cause confusion)

**Comment by ymdatta** [comment]
I wanted a value that's different from 0 and in the same module, I saw usage of `-1` in two places for initialization: [grass.cpp:L242](https://github.com/OSGeo/grass/blob/main/raster/r.viewshed/grass.cpp#L242) and [grass.cpp:L460](https://github.com/OSGeo/grass/blob/main/raster/r.viewshed/grass.cpp#L460). So, I went ahead with `-1`.

**Comment by echoix** [comment]
https://github.com/OSGeo/grass/blob/5719ba6fd51158a88fb7ce1850a4651e61c7e344/raster/r.viewshed/eventlist.h#L49-L60

I see here that the angle is double. Should the suggestion of using -1.0 (like using 0.0 instead of 0) be applied here too, even if you pointed out occurrences where -1 was used (without the dot zero)?

**Comment by ymdatta** [comment]
I agree with you, I think `-1.0` is the right literal to be used here. I have made the changes. Thanks!

**Review by echoix — APPROVED** [review]

**Pull request merged**
