### PR TITLE
Python scripts: remove UTF-8 coding line

### PR DESCRIPTION
**Pull request by neteler**
UTF-8 is the default with Python 3, no need for the coding line.

Ref: https://github.com/OSGeo/grass/pull/1449#discussion_r593748122

### CODE REVIEW

**Comment by neteler** [comment]
@nilason not sure what to do with the now empty files:

```
Run cd python/grass
./pygrass/__init__.py:1:1: W391 blank line at end of file

^
./pygrass/shell/__init__.py:1:1: W391 blank line at end of file

^
2     W391 blank line at end of file
2
Error: Process completed with exit code 1.
```

Keep a `# blank file` inside?

**Comment by nilason** [comment]
> @nilason not sure what to do with the now empty files:
> 
> ```
> # Flake 8 test:
> 
> Run cd python/grass
> ./pygrass/__init__.py:1:1: W391 blank line at end of file
> 
> ^
> ./pygrass/shell/__init__.py:1:1: W391 blank line at end of file
> 
> ^
> 2     W391 blank line at end of file
> 2
> Error: Process completed with exit code 1.
> ```
> 
> Keep a `# blank file` inside?

According to [Python docs](https://docs.python.org/3/tutorial/modules.html#packages) empty init files are perfectly valid. Maybe Flake needs to be configured for these cases? Will look into it.

**Comment by nilason** [comment]
If I’m not mistaken, only a couple of the files become empty. Solution could be either a Docstring added or if no meaningful description can be made the files can be added to `.flake8` file under `per-file-ignores` and W391.

**Comment by neteler** [comment]
Thanks, @nilason ! I have added Docstrings in the two files.

Guess the tests would have worked now but fatra.cnr.ncsu.edu currently doesn't respond:

```
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
Execution of <g.download.location url=http://fatra.cnr.ncsu.edu/data/nc_spm_full_v2alpha2.tar.gz
```

**Review by nilason — APPROVED** [review]
Test failure is not related to this PR. The server is down. Did a `ping fatra.cnr.ncsu.edu` with no success.

Ideally, at least a very brief summary of the packages `pygrass` and `pygrass.shell` would be preferable. Perhaps @wenzeslaus could help out with docstrings for:
```
python/grass/pygrass/__init__.py
python/grass/pygrass/shell/__init__.py
```
Other than that, I think this is good to go!

**Comment by wenzeslaus** [comment]
> Solution could be either a Docstring added or if no meaningful description can be made the files can be added to `.flake8` file under `per-file-ignores` and W391.

`__init__.py` files are indeed a special case, already in per-file-ignores in `./python/grass/.flake8` because of unused imports (F401). However, I think Flake8 requires that an empty file (which is fine for `__init__.py`) should be really empty, i.e., zero bytes - this fits with unix/Linux logic of line endings (as opposed to line separators): There is no line with content to end, so there should be no line ending, i.e., the line is blank and is at the end of the file. Isn't that the problem?

```
$ touch touched.py
$ ls -la touched.py
... 0 Mar 14 20:45 touched.py
$ flake8 touched.py
$ echo "" > echoed.py
$ ls -la echoed.py
... 1 Mar 14 20:45 echoed.py
$ flake8 echoed.py 
echoed.py:1:1: W391 blank line at end of file
```

**Comment by wenzeslaus** [comment]
> Test failure is not related to this PR. The server is down. Did a `ping fatra.cnr.ncsu.edu` with no success.

Well, that seems to be more than just a glitch. We need a better solution anyway. What about fixing that now? First, a better storage place is needed.

**Comment by nilason** [comment]
> `__init__.py` files are indeed a special case, already in per-file-ignores in `./python/grass/.flake8` because of unused imports (F401). However, I think Flake8 requires that an empty file (which is fine for `__init__.py`) should be really empty, i.e., zero bytes - this fits with unix/Linux logic of line endings (as opposed to line separators): There is no line with content to end, so there should be no line ending, i.e., the line is blank and is at the end of the file. Isn't that the problem?

Thanks! Logical but not overly documented.

```
rm python/grass/pygrass/shell/__init__.py && touch python/grass/pygrass/shell/__init__.py
rm python/grass/pygrass/__init__.py && touch python/grass/pygrass/__init__.py
```
solved this warning for me locally.

**Comment by neteler** [comment]
> > Test failure is not related to this PR. The server is down. Did a `ping fatra.cnr.ncsu.edu` with no success.
> 
> Well, that seems to be more than just a glitch. We need a better solution anyway. What about fixing that now? First, a better storage place is needed.

grass.osgeo.org comes to mind. @wenzeslaus can you pls provide me with the file(s) to upload there? I don't seem to have an original copy.

**Comment by neteler** [comment]
> > > Test failure is not related to this PR. The server is down. Did a `ping fatra.cnr.ncsu.edu` with no success.
> > 
> > 
> > Well, that seems to be more than just a glitch. We need a better solution anyway. What about fixing that now? First, a better storage place is needed.
> 
> grass.osgeo.org comes to mind. @wenzeslaus can you pls provide me with the file(s) to upload there? I don't seem to have an original copy.

Thanks to @nilason who answered in real time I have solved it by defining the new download URL for nc_spm_full_v2alpha2.tar.gz (see e04ef1a). It is now hosted at

https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz

(In a separate PR, the other usages and doc references to this dataset need to be updated)

**Pull request merged**
