### PR TITLE
Add list of commits for git blame to ignore

### PR DESCRIPTION
**Pull request by wenzeslaus**
This adds a list of commits which one may want to ignore when doing `git blame` (`git blame file.c --ignore-revs-file .git-blame-ignore-revs`).

Formatting changes of Python (with Black), the initial C formatting commit, and couple of other commits are included.

The ignore list is for investigating 'standard' code in common use cases. It won't work when an error was introduced by the formatting change (e.g., by fixing some additional lines manually) or when dealing with CI checks changed in the same commit. Notably, language syntax is often updated when formatting happens (removal of Python 2 unicode strings literals or replacement of backticks syntax in bourne-shells) and a change of formatting is connected to an update in automated checks if there are already in place.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
## Git in command line

The `.git-blame-ignore-revs` file is not picked up automatically (for good reasons). You either specificity it in the command line, [change your Git settings](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame), or add an alias.

### Plain git blame

```
git blame scripts/r.mask/r.mask.py
```

```
...
4f41347db9 (Martin Landa    2012-12-23 14:53:55 +0000 120)         # -> create
8c12304e44 (Markus Metz     2012-12-15 23:25:33 +0000 121)         if exists:
75838784d2 (Martin Landa    2010-11-25 09:01:09 +0000 122)             if not grass.overwrite():
0d9e966dd2 (Vaclav Petras   2021-02-18 11:35:13 -0500 123)                 grass.fatal(
0d9e966dd2 (Vaclav Petras   2021-02-18 11:35:13 -0500 124)                     _(
0d9e966dd2 (Vaclav Petras   2021-02-18 11:35:13 -0500 125)                         "MASK already found in current mapset. Delete first or overwrite."
0d9e966dd2 (Vaclav Petras   2021-02-18 11:35:13 -0500 126)                     )
0d9e966dd2 (Vaclav Petras   2021-02-18 11:35:13 -0500 127)                 )
...
```

### Ignore revs while git blame

```
git blame scripts/r.mask/r.mask.py --ignore-revs-file .git-blame-ignore-revs
```

```
...
4f41347db9 (Martin Landa    2012-12-23 14:53:55 +0000 120)         # -> create
8c12304e44 (Markus Metz     2012-12-15 23:25:33 +0000 121)         if exists:
75838784d2 (Martin Landa    2010-11-25 09:01:09 +0000 122)             if not grass.overwrite():
75838784d2 (Martin Landa    2010-11-25 09:01:09 +0000 123)                 grass.fatal(
75838784d2 (Martin Landa    2010-11-25 09:01:09 +0000 124)                     _(
75838784d2 (Martin Landa    2010-11-25 09:01:09 +0000 125)                         "MASK already found in current mapset. Delete first or overwrite."
75838784d2 (Martin Landa    2010-11-25 09:01:09 +0000 126)                     )
0d9e966dd2 (Vaclav Petras   2021-02-18 11:35:13 -0500 127)                 )
...
```

### GitHub

GitHub interface [does not allow](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame) to use that file, so this PR is not useful for that. However, it is easy to move over a revision by pressing "View blame prior to this change" which is the icon between commit info and line numbers.

**Comment by wenzeslaus** [comment]
Please suggest where to document usage and maintenance of this if it is even worth having.

**Comment by neteler** [comment]
> Please suggest where to document usage and maintenance of this if it is even worth having.

Perhaps in a new `doc/git.md` (or `doc/git_SOMETHING.md` to be more specific)?

**Comment by wenzeslaus** [comment]
Will need #1513 once it is in.

**Comment by wenzeslaus** [comment]
Will need #1527 once it is in.

**Review by neteler — APPROVED** [review]
Great idea!

**Comment by wenzeslaus** [comment]
- [ ] Will need #1605

**Comment by nilason** [comment]
I think this may be merged. Additional commits may be added to the ignore-file as needed.

**Pull request merged**
