### PR TITLE
docs: v.to.db.html fix manual typo

### PR DESCRIPTION
**Pull request by dhdeangelis**

### CODE REVIEW

**Review by echoix — APPROVED** [review]
I didn't catch anything else in the file too.

**Comment by neteler** [comment]
How about running https://github.com/OSGeo/grass/blob/main/utils/fix_typos.sh on (parts of) the source code? In the past I had good experience with it.

**Comment by echoix** [comment]
There's also cspell, but it is not co figured yet to not trigger to all the proper nouns we use, so maybe a lot of false positives. It will work for typos in words, not errors in syntax. Works well in code and variable names too (knows where to split words for each of the programming languages). 

There's also proselint that is suitable for more of text documents (not sure if support on markup works better now), and is more geared towards errors between words, higher level, like consistency, clichés, jargon, cursing, archaisms, sexism, uncomparables, etc. 


There's also vale, that is flexible too.


But cspell is kinda the most used, and IDE integrations, especially for VSCode makes it really easy to use.

**Comment by echoix** [comment]
Personally, when needing to correct documents, I use the (paid) Antidote tool, the reference spell checking software for decades developed in Québec, that for 10 years has an English module. It also supports filtering out markup, so works now also with Tex, markdown, html. But it's not that useful to use in code.

**Comment by dhdeangelis** [comment]
> How about running https://github.com/OSGeo/grass/blob/main/utils/fix_typos.sh on (parts of) the source code? In the past I had good experience with it.
> 
> (it is based on https://github.com/codespell-project/codespell)

I didn't know about that script but I basically did the same using hunspell. For another project I run spell check on many files, so I got inspired and did the same all GRASS html manual files (many of which contain typos). The result is text file with 'misspellings' for each file, most of them just technical nouns and abbreviations. Then it is a simple (and educative) matter to go one file at a time, identify the misspellings, correct them and submit a PR. Since this takes only a few minutes for one html file it can be done within the course of a normal day without having to set aside special time. I actually find it entertaining.

**Pull request merged**
