### PR TITLE
v.info: fix printing UTM zone (#892)

### PR DESCRIPTION
**Pull request by metzm**
print UTM zone <X> according to hemisphere as <X>N or <X>S
Fixes issue #892

### CODE REVIEW

**Comment by neteler** [comment]
The test case works fine.

However, I tested it with another location and still found a glitch (Indonesia UTM48S in this example):

```
GRASS utm48S_32748/indonesia:grass_master > g.proj -w
PROJCS["WGS 84 / UTM zone 48S",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",105],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32748"]]

GRASS utm48S_32748/indonesia_ciminyak:grass_master > v.info osm_natural_free_1
 +----------------------------------------------------------------------------+
 | Name:            osm_natural_free_1                                        |
 | Mapset:          indonesia_ciminyak                                        |
 | Location:        utm48S_32748                                              |
 | Database:        /home/mneteler/grassdata                                  |
 | Title:                                                                     |
 | Map scale:       1:1                                                       |
 | Name of creator: mneteler                                                  |
 | Organization:                                                              |
 | Source date:     Sat Jun 13 21:17:21 2020                                  |
 | Timestamp (first layer): none                                              |
 |----------------------------------------------------------------------------|
 | Map format:      native                                                    |
 |----------------------------------------------------------------------------|
 |   Type of map: vector (level: 2)                                           |
 |                                                                            |
 |   Number of points:       13941           Number of centroids:  0          |
...
 |                                                                            |
 |   Projection: UTM (zone 48N)                                               |
 |                                                                            |
 |               N:  9344976.75761371    S:  9149431.58461725                 |
 |               E:   924789.03771958    W:   611932.08918657                 |
...
 +----------------------------------------------------------------------------+
```

--> Projection: UTM (zone 48**N**)

**Comment by metzm** [comment]
I can't reproduce with
`grass79 -c EPSG:32748 /path/to/grassdb/indonesia_utm_32748`
create an empty vector with
`v.edit tool=create map=test_vector`
and get vector info with
```
> v.info test_vector
 +----------------------------------------------------------------------------+
 | Name:            test_vector                                               |
 | Mapset:          PERMANENT                                                 |
 | Location:        indonesia_utm_32748                                       |
 | Database:        /media/storage/GRASSdata_geosds                           |
 | Title:                                                                     |
 | Map scale:       1:1                                                       |
 | Name of creator: metz                                                      |
 | Organization:                                                              |
 | Source date:     Mon Sep 21 21:53:01 2020                                  |
 | Timestamp (first layer): none                                              |
 |----------------------------------------------------------------------------|
 | Map format:      native                                                    |
 |----------------------------------------------------------------------------|
 |   Type of map: vector (level: 2)                                           |
 |                                                                            |
 |   Number of points:       0               Number of centroids:  0          |
 |   Number of lines:        0               Number of boundaries: 0          |
 |   Number of areas:        0               Number of islands:    0          |
 |                                                                            |
 |   Map is 3D:              No                                               |
 |   Number of dblinks:      0                                                |
 |                                                                            |
 |   Projection: UTM (zone 48S)                                               |
 |                                                                            |
 |               N:                 0    S:                 0                 |
 |               E:                 0    W:                 0                 |
 |                                                                            |
 |   Digitization threshold: 0                                                |
 |   Comment:                                                                 |
 |                                                                            |
 +----------------------------------------------------------------------------+
```
-> Projection: UTM (zone 48**S**)

How did you create the vector osm_natural_free_1 in the location/mapset utm48S_32748/indonesia?
What are the contents of the text file "utm48S_32748/indonesia/vector/osm_natural_free_1/head"?

**Comment by neteler** [comment]
The content is:

```
cat utm48S_32748/indonesia_ciminyak/vector/osm_natural_free_1/head
ORGANIZATION: 
DIGIT DATE:   Jun 13 20
DIGIT NAME:   mneteler
MAP NAME:     
MAP DATE:     Sat Jun 13 21:17:21 2020
MAP SCALE:    1
OTHER INFO:   
PROJ:         1
ZONE:         48
MAP THRESH:   0.000000
```

And here the history:

(the map, if I recall correctly, from http://download.geofabrik.de/asia/indonesia.html)

```
cat utm48S_32748/indonesia_ciminyak/vector/osm_natural_free_1/hist 
COMMAND: v.in.ogr -r input="/vsizip/indonesia-latest-free.shp.zip" layer="gis_osm_natural_free_1" output="gis_osm_natural_free_1" min_area=0.0001 type="" snap=-1
GISDBASE: /home/mneteler/grassdata
LOCATION: latlong_wgs84 MAPSET: hermosa_indonesien USER: mneteler DATE: Sat Jun 13 21:17:21 2020
---------------------------------------------------------------------------------
COMMAND: v.proj location="latlong_wgs84" mapset="hermosa_indonesien" input="gis_osm_natural_free_1" smax=10000
GISDBASE: /home/mneteler/grassdata
LOCATION: utm48S_32748 MAPSET: PERMANENT USER: mneteler DATE: Sat Jun 13 22:39:07 2020
```

**Comment by metzm** [comment]
That was a bug in `v.proj`.
Since all data in a given GRASS location use the same CRS, it does not make sense to store parts of the CRS with the data. The vector lib has been modified accordingly to report the zone of the location, not of the vector (which was wrong anyway if created with `v.proj` and a UTM zone in the southern hemisphere):

**Comment by neteler** [comment]
Now it works also for me, thanks for the fixes!

**Pull request merged**
