### PR TITLE
WIP upgrade tgis db

### PR DESCRIPTION
**Pull request by landam**
This PR introduces ability to upgrade TGIS DB version, only upgrade from version 2 (before introducing band references support, see #63) to 3 (with band ref support) is supported. Please note that this is work-in-progress PR. Main open issues:

- [x] 1) new/existing module? - see https://github.com/OSGeo/grass-addons/pull/71/files

* introduce new module, eg. `t.upgrade` (*), or
* add upgrade flag to existing module (and which?) Originally I was planning to add `-u` flag to `t.connect`, but it's a C module. For implementation Python is required.

- [ ] 2) how to deal with raster views?

When upgrading db, 2 raster views must be recreated. 

Option 1: duplicate `raster_views.sql` content in `upgrade_db_2_to_3.sql` (ugly)

Option 2: execute `raster_views.sql` by `upgrade_temporal_database()` only when upgrading from 2 to 3 (less ugly, but still not nice)

Option 3:  `upgrade_temporal_database()` could drop and re-create all views regardless version upgrade

Option 4: your suggestions...

## (*) Minimalistic t.upgrade.py

```
#!/usr/bin/env python3

import grass.temporal as tgis

tgis.init(skip_db_version_check=True)
    
dbif = tgis.SQLDatabaseInterfaceConnection()
dbif.connect()

tgis.upgrade_temporal_database(dbif)
```

## Usage

Having TGIS DB created before introducing band reference support.

```
t.info -d
ERROR: Unsupported temporal database: version mismatch.
```

Do upgrade:

```
./t.upgrade.py
```

Now let's try `t.info` command again.

```
t.info -d
 +------------------- Temporal DBMI backend information ----------------------+
...
 | tgis_db_version .......... 3
...
```

Be aware that band references metadata are not magically introduced to existing datasets.

```
t.info test76
...
 | Number of registered bands:. None
```

```
t.info T33UVR_20181205T101401_B04 type=raster
...
 | Band reference:............. None
```

You need to create new register file containing band references and register raster maps by `t.register` again to rewrite existing metadata.

### CODE REVIEW

**Comment by neteler** [comment]
Can we pls merge? thanks...

**Comment by landam** [comment]
Before merging "(2) how to deal with raster views" should be solved.

**Comment by neteler** [comment]
> Before merging "(2) how to deal with raster views" should be solved.

Do you have a suggestion in which direction to think? Raster views = VRT?

**Comment by landam** [comment]
> > Before merging "(2) how to deal with raster views" should be solved.
> 
> Do you have a suggestion in which direction to think? Raster views = VRT?

No, I mean SQL views.

**Comment by landam** [comment]
Sorry for messing up this PR, I have created new #306

**Pull request closed without merging**
