### PR TITLE
i18n: sync from Transifex

### PR DESCRIPTION
**Pull request by HuidaeCho**

### CODE REVIEW

**Review by neteler — APPROVED** [review]

**Comment by neteler** [comment]
@HuidaeCho let me suggest to also update G78, but as a separate PR instead of a backport. I can do that if you prefer

**Comment by HuidaeCho** [comment]
> @HuidaeCho let me suggest to also update G78, but as a separate PR instead of a backport. I can do that if you prefer

@neteler Is there a reason for a separate PR? I guess conflicts?

**Comment by neteler** [comment]
We may give it a try but the message "pools" in the .po files differ a bit, that's why I went for separate syncs in the past.

**Comment by HuidaeCho** [comment]
> 
> 
> We may give it a try but the message "pools" in the .po files differ a bit, that's why I went for separate syncs in the past.

Makes sense. But isn't the source Transifex the same? Let me try it first. Working on it now...

**Comment by neteler** [comment]
> Makes sense. But isn't the source Transifex the same? Let me try it first. Working on it now...

Yes, the source Transifex is the same but perhaps (just guessing) the `gettext` merging part ends up differently.

**Pull request merged**
