### PR TITLE
i18n: Update POT and PO files

### PR DESCRIPTION
**Pull request by HuidaeCho**
Steps to create this PR:
```bash
cd locale
make pot
make update-po
```
Manually resolved conflicts for `de`.

### CODE REVIEW

**Review by neteler — APPROVED** [review]

**Comment by echoix** [comment]
Is this a manual job that has to be done periodically? Ie: checking this once a month with other maintenance tasks?

**Comment by HuidaeCho** [comment]
> Is this a manual job that has to be done periodically? Ie: checking this once a month with other maintenance tasks?

Yes, it's a manual task for now and sometimes we have to resolve conflicts manually (just did it myself for `de`). So I would say it's a necessary evil.

**Comment by neteler** [comment]
> Is this a manual job that has to be done periodically? Ie: checking this once a month with other maintenance tasks?

The technical part I have described here:
https://github.com/OSGeo/grass/blob/main/doc/infrastructure.md#how-weblate-works

**Comment by echoix** [comment]
> > Is this a manual job that has to be done periodically? Ie: checking this once a month with other maintenance tasks?
> 
> The technical part I have described here: https://github.com/OSGeo/grass/blob/main/doc/infrastructure.md#how-weblate-works

So does Weblate collect the new strings to update by itself? It is the POT files as I understand. If they don't update the POT files by itself, would we need to update it more frequently to reduce conflicts in the future?

**Comment by HuidaeCho** [comment]
> > > Is this a manual job that has to be done periodically? Ie: checking this once a month with other maintenance tasks?
> > 
> > 
> > The technical part I have described here: https://github.com/OSGeo/grass/blob/main/doc/infrastructure.md#how-weblate-works
> 
> So does Weblate collect the new strings to update by itself? It is the POT files as I understand. If they don't update the POT files by itself, would we need to update it more frequently to reduce conflicts in the future?

It's the PO files that Weblate collects and updates, not the POT.

**Comment by neteler** [comment]
> Yes, it's a manual task for now

@HuidaeCho would you mind to add the steps into the PR description?

**Comment by HuidaeCho** [comment]
> > Yes, it's a manual task for now
> 
> @HuidaeCho would you mind to add the steps into the PR description?

@neteler Just added the steps.

**Review by neteler — APPROVED** [review]

**Pull request merged**
