### PR TITLE
d.polar: fix launch module (py3) and write output EPS file

### PR DESCRIPTION
**Pull request by tmszi**
**To Reproduce:**

1. `d.polar map=aspect output=/tmp/polar.eps`

**Error message:**

```
Traceback (most recent call last):
  File "/usr/lib64/grass79/scripts/d.polar", line 536, in <module>
    main()
  File "/usr/lib64/grass79/scripts/d.polar", line 431, in main
    rawf = file(rawfile, 'w')
NameError: name 'file' is not defined
```
**Expected behavior:**

d.polar module should launch normally without error message.

### CODE REVIEW

**Comment by neteler** [comment]
I tested it and it now works when giving an absolute output path.

Yet it fails with a relative path:

```
d.polar map=aspect output=polar.eps
 100%
Calculating statistics for polar diagram... (be patient)
ERROR: EPS output file path <polar.eps>, doesn't exists. Set new output
       file path.
```

**Comment by neteler** [comment]
While at it, would you mind to also fix these two flake8-identified errors?
```

 ./d.polar/d.polar.py:516:17: E124 closing bracket does not match visual indentation
                ),
                ^
./d.polar/d.polar.py:524:17: E124 closing bracket does not match visual indentation
                ),
                ^
2     E124 closing bracket does not match visual indentation
```

**Comment by tmszi** [comment]
> I tested it and it now works when giving an absolute output path.
> 
> Yet it fails with a relative path:
> 
> ```
> d.polar map=aspect output=polar.eps
>  100%
> Calculating statistics for polar diagram... (be patient)
> ERROR: EPS output file path <polar.eps>, doesn't exists. Set new output
>        file path.
> ```

Fixed in the [c99de50](https://github.com/OSGeo/grass/commit/c99de50c0e33c56f26276a2f7a8773ad3c08f6b5).

**Comment by tmszi** [comment]
> While at it, would you mind to also fix these two flake8-identified errors?
> 
> ```
> 
>  ./d.polar/d.polar.py:516:17: E124 closing bracket does not match visual indentation
>                 ),
>                 ^
> ./d.polar/d.polar.py:524:17: E124 closing bracket does not match visual indentation
>                 ),
>                 ^
> 2     E124 closing bracket does not match visual indentation
> ```

Yes of course I fixed in the [c99de50](https://github.com/OSGeo/grass/commit/c99de50c0e33c56f26276a2f7a8773ad3c08f6b5).

**Review by neteler — APPROVED** [review]

**Pull request merged**
