### PR TITLE
infra: Add autogenerated documentation to gitignore

### LINKED ISSUE #3521: [Bug] Ensure doc compilation files are ignored in .gitignore
I'm filing an issue to add a work item to have a look at the .gitignore file, to make sure that generated docs are correctly ignored, as happened in this PR:

> Something went wrong and your PR has a bunch of unrelated files added. Perhaps `git add -A`? Try `git add -p` instead.

Huh! It seems that doc compilation files are missing from the `.gitignore`.

_Originally posted by @marisn in https://github.com/OSGeo/grass/pull/3516#issuecomment-2015736244_

### PR DESCRIPTION
**Pull request by marisn**
As long as we have in-tree build system, our `.gitignore` has to grow.
Fixes #3521

### CODE REVIEW

**Comment by neteler** [comment]
(please make the PR title compatible with an entry in https://github.com/OSGeo/grass/blob/main/utils/release.yml as the release notes are autogenerated)

**Comment by marisn** [comment]
> (please make the PR title compatible with an entry in https://github.com/OSGeo/grass/blob/main/utils/release.yml as the release notes are autogenerated)

I do not think this is something that should go to release notes.

**Comment by neteler** [comment]
Ok. Still I have to check line manually and, in this case, delete it from the extracted PR notes.

**Comment by echoix** [comment]
What about the "infra:" prefix?
Also, I'm not sure that it excludes everything either, except if I build it myself. Do we take the approach of merging this and having to complete afterwards when we figure out if the python docs create more files.

**Review by neteler — APPROVED** [review]
Looks good to me.

(Un)related: the "infra:" keyword needs to be added to https://github.com/OSGeo/grass/blob/main/utils/release.yml

**Pull request merged**
