### PR TITLE
GRASS_VERSION_SVN -> GRASS_VERSION_GIT + update g.version

### PR DESCRIPTION
**Pull request by landam**
This PR:

* changes `GRASS_VERSION_SVN` compilation variable to `GRASS_VERSION_GIT`
* changes `VERSION` from `7.7.svn` to more generic `7.7.dev`
* updates `g.version -g` in order to print git reference commit

```
> g.version --help
...
  -g   Print info in shell script style (including Git reference commit)
...
> g.version -g
...
revision=3ff058709
...
```

(`revision` tag not changed due to backward compatibility)

Note: this PR does not solve WinGRASS-related `GRASS_VERSION_SVN` issue (see `mswindows/GRASS-Installer.nsi.tmpl`). This should be fixed by separate PR.

### CODE REVIEW

**Comment by landam** [comment]
Also wxGUI System Info updated to more generic 'Code revision'.

Screenshot from 2019-05-19 18-11-14

**Comment by neteler** [comment]
Thanks, still a change here is needed:

```
lib/init/grass.py
383:    config_detail=_("options: arch,build,compiler,path,revision,svn_revision,version"),
1905:        elif arg == 'svn_revision':
```
I suggest to keep `svn_revision` for backwards compatibility but add also a new `code_revision` with the same output.

A new bug is there:
```
grass77 --config
--> IndexError: list index out of range

grass77 --config revision
--> IndexError: list index out of range
```

**Comment by landam** [comment]
`--config` problem is related to SVN keywords substitution, see https://github.com/OSGeo/grass/blob/master/include/gis.h#L41. See also #11.

**Comment by landam** [comment]
Since `--config` problem is an another issue (related to svn keyword substitution) I suggest to split the tasks. Let's finish (merge) this PR and open a new issue (trac) for svn keyword substitution. @neteler do you agree?

**Comment by landam** [comment]
See related open issues:

* https://trac.osgeo.org/grass/ticket/3855
* https://trac.osgeo.org/grass/ticket/3856

**Comment by landam** [comment]
For record: PR backported to relbr76 in 59225e796

**Pull request merged**
