### PR TITLE
v.db.connect: Replace -o flag with the standard --overwrite

### LINKED ISSUE #3149: [Bug] v.db.connect does not recognize --overwrite flag
**Describe the bug**
v.db.connect does not recognize --overwrite and equivalent to -o. Hence, it throws an error if you try to overwrite from the GUI, which uses the long form of --overwrite instead of -o. 

When modules were converted to also use --overwrite, somehow v.db.connect was missed. 

**System description (please complete the following information):**

- Operating System: Mac OS 13.5.1
- GRASS GIS version 8.3.0

### PR DESCRIPTION
**Pull request by HuidaeCho**
This PR fixes #3149 by using the standard `--overwrite` flag.

### CODE REVIEW

**Comment by marisn** [comment]
I'm sorry, but this shall not pass. You should not remove a flag in non-major release.
Please add a printf with warning whenever `-o` is used: "The -o flag is deprecated and will be removed in future releases. Use --o instead"
To future proof the code, wrap the old `-o` in a macro `#if GRASS_VERSION_MAJOR < 9`

**Review by landam — CHANGES_REQUESTED** [review]
@HuidaeCho It make sense to me to add `--overwrite` flag. On the other hand we cannot break backward compatibility in GRASS 8 releases. The `-o` flag could be removed in GRASS 9. I suggest to add depreciation warning that `-o` will be removed in GRASS 9.

**Comment by HuidaeCho** [comment]
This PR requires #3256.

**Comment by HuidaeCho** [comment]
@marisn, @landam Will this work with #3256?

**Review by marisn — APPROVED** [review]

**Comment by marisn** [comment]
> @marisn, @landam Will this work with #3256?

Yes. I tested together with #3256 and backwards compatibility is in place.

**Review by wenzeslaus — COMMENTED** [review]
Maybe a test to prove that both `-o` and `--overwrite` work? Probably using `gs.run_command(...)` (with `flags="o"` and `overwrite=True`) rather than the `assert*()` functions which rely on grass.pygrass Module interface which performs checks on its own and does not support `lib/gis/renamed_options`.

**Review by landam — APPROVED** [review]
I successfully tested:

```
v.db.connect map=voda_aoi table=VodniTok
ERROR: Use --overwrite to overwrite existing link for layer <1>

v.db.connect map=voda_aoi table=VodniTok --o
The table <VodniTok> is now part of vector map <voda_aoi> and may be
deleted or overwritten by GRASS modules

v.db.connect map=voda_aoi table=VodniTok --o
The table <VodniTok> is now part of vector map <voda_aoi> and may be
deleted or overwritten by GRASS modules
```

**Comment by landam** [comment]
@HuidaeCho Please feel free to merge (you have more than zero approvals)...

**Pull request merged**
