### PR TITLE
remove .setpdfwrite option on MS Windows

### PR DESCRIPTION
**Pull request by ninsbl**
.setpdfwrite is no longer supported with ghostscript 9.5 shipped with OSGeo4W
See: https://trac.osgeo.org/osgeo4w/ticket/697

### CODE REVIEW

**Comment by hellik** [comment]
taken from [gs 9.50 manual](https://www.ghostscript.com/doc/9.50/Language.htm)

```
.setpdfwrite
    This operator is now deprecated, and its use is discouraged

    This operator conditions the environment for the pdfwrite output device. It is a shorthand for setting parameters that have been deemed benificial. While not strictly necessary, it is usually helpful to set call this when using the pdfwrite device. For example, this is how the ps2pdf script calls Ghostscript:

        gs -q -dSAFER -dNOPAUSE -dBATCH -sOutputFile=file.pdf [more options] \
          -sDEVICE=pdfwrite -c .setpdfwrite -f source1.ps [more files] 

    Currently, the operator just sets a minimum 3 MB vmthreshold to allow for accumulating shared object data and to reduce the incidence of garbage collection as a performance improvement. Additional settings may be added in the future.
```

taken from [gs 9.26 manual](https://www.ghostscript.com/doc/9.26/Use.htm)

```
With some PDF files, or if you are using Chinese, Japanese, or other fonts with very large character sets, adding the following sequence of switches before the first file name may dramatically improve performance at the cost of an additional memory. For example, to allow use of 30Mb of extra RAM use: -c 30000000 setvmthreshold -f.

This can also be useful in processing large documents when using a high-level (vector) output device (like pdfwrite) that maintains significant internal state. In fact, the .setpdfwrite operator used by the ps2pdf script and others sets a vmthreshold value of 3 MB to account for this.
```
do we need to set **setvmthreshold** instead?

**Comment by neteler** [comment]
Since #1961 has been merged and backported, can this be, too?

**Comment by ninsbl** [comment]
> @ninsbl Since #1961 has been merged and backported, can this be, too?

This is actually the backport PR to the 7.8 releasebranch (as direct backport was not possible due to code formating (black)...

Shold be safe to merge...

**Comment by neteler** [comment]
Thanks, so I merge it.

**Pull request merged**
