### PR TITLE
r.neighbors: Add parallel support

### PR DESCRIPTION
**Pull request by aaronsms**
- Update Makefile
- Refactor inputs to use pointers
- Refactor to use segment libraries
- Add parallel region
- Add parallel test cases

All input and output variables are transformed into pointers to support parallel execution. There is no change in the underlying algorithm except of the introduction of segmented temporary files to allow for random access write. So the extra memory usage will be scaled according to the number of threads used plus a constant overhead from the usage of segmented files. I think we should introduce a memory parameter to allow users to control the how much memory to be used for the segment. Right now, it is just a fixed constant, which is to be changed.

This PR contains an addition of a test file which contains the parallel version of the original sequential test cases. Upon addition of benchmark script, this will be combined into the original test file to avoid code duplication. On my machine, there is some speedup of ~2x on 4 threads, though this is not accurate without the benchmark.

I am thinking to refactor my code to encapsulate the usage of Segments.

### CODE REVIEW

**Comment by ninsbl** [comment]
Nice!
Could this be coordinated with: #597
Sorry for not having committed before you started on r.neighbors...

**Comment by aaronsms** [comment]
> Nice!
> Could this be coordinated with: #597
> Sorry for not having committed before you started on r.neighbors...

No worries, yeap will incorporate the changes once #597 is merged.

**Comment by aaronsms** [comment]
- [ ] Fix CentOS build fail due to C98 incompatibility (will take note of this in the future)

test_pygrass_modules_interface_doctests.py was failing, I am guessing this has to do with the newly added test cases. 20.04 build fail is incidental, due to connection issues to repository.

**Comment by HuidaeCho** [comment]
@aaronsms Please consider using the standard option `G_OPT_M_NPROCS` introduced in #1644.

**Comment by aaronsms** [comment]
> @aaronsms Please consider using the standard option `G_OPT_M_NPROCS` introduced in #1644.

Noted! Will use that for future modules.

**Comment by aaronsms** [comment]
I will close this PR in favor of #1724.

**Pull request closed without merging**
