### PR TITLE
Indent most of C code

### PR DESCRIPTION
**Pull request by wenzeslaus**
Indents most of C and C++ code except for what is reported by indent as issues.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
How to deal with conflicts this creates in PRs with C code?

Indent your code:

```
./utils/grass_indent.sh db/drivers/mysql/create_table.c
```

Update upstream/main branch:

```
git fetch upstream/main
```

Merge into your branch upstream/main:

```
git merge --strategy=ours upstream/main
```

**Comment by wenzeslaus** [comment]
CodeQL fails with issues which already exist. The rest runs.

**Comment by wenzeslaus** [comment]
This leaves out all directories which indent reports errors for.

**Comment by neteler** [comment]
(discussed at https://grasswiki.osgeo.org/wiki/GRASS_GIS_at_OSGeo_Community_Sprint_2022)

**Pull request merged**
