### PR TITLE
grass_raster: remove GDAL_DYNAMIC (fixes #1872, reverts 26503976190 ff)

### LINKED ISSUE #1872: [Bug] GRASS misses GDAL dynamic library references on Windows
There are explicit references to GDAL DLL  that miss versions above GDAL 3.0 on Windows: https://github.com/OSGeo/grass/blob/75dd60a694198f7bca17b7e3d6387b6eefa9bb7a/lib/raster/gdal.c#L119

See also qgis/QGIS#45079

### PR DESCRIPTION
**Pull request by jef-n**
fixes #1872, reverts 26503976190 ff

### CODE REVIEW

**Comment by hellik** [comment]
Is r.external then still working?

**Comment by jef-n** [comment]
> Is r.external then still working?

I didn't even build it yet ;)   But I wouldn't except any functional change (except that it will require the GDAL (minor) version it was built with and not try any previous versions).

**Comment by jef-n** [comment]
> Is r.external then still working?

Any idea whether the tests cover r.external?

**Comment by hellik** [comment]
> > Is r.external then still working?
> 
> Any idea whether the tests cover r.external?

As there is no testsuite folder in the source (

**Comment by neteler** [comment]
> > Is r.external then still working?
> 
> Any idea whether the tests cover r.external?

I have just added a r.external testsuite in #2291

**Comment by neteler** [comment]
> > > Is r.external then still working?
> > 
> > 
> > Any idea whether the tests cover r.external?
> 
> I have just added a r.external testsuite in #2291

Merged and backported to 8.0 in 3a32af69e0dd8f127d7e59abe616bd8b0bdc19b7.

@jef-n if possible, please rebase your PR to incorporate the new test.

**Comment by neteler** [comment]
From the [log](https://github.com/OSGeo/grass/runs/5800288419?check_suite_focus=true) file:

windows-2019 build and tests
```
...
Running .\raster\r.external\testsuite\test_r_external.py...
Running .\raster\r.fill.stats\testsuite\test_r_fill_stats.py...
Running .\raster\r.geomorphon\testsuite\test_r_geom.py...
...
```

The new test `r.external` passed.

**Comment by hellik** [comment]
> From the [log](https://github.com/OSGeo/grass/runs/5800288419?check_suite_focus=true) file:
> 
> windows-2019 build and tests
> 
> ```
> ...
> Running .\raster\r.external\testsuite\test_r_external.py...
> Running .\raster\r.fill.stats\testsuite\test_r_fill_stats.py...
> Running .\raster\r.geomorphon\testsuite\test_r_geom.py...
> ...
> ```
> 
> The new test `r.external` passed.

should we merge?

**Comment by nilason** [comment]
Builds fine and the new tests succeeds on Mac. Looks good to me 👍 !

**Comment by neteler** [comment]
So, all we really have to do now is have the courage to merge this PR, right?
I suppose it should also be backported to 8.0.2?

**Comment by hellik** [comment]
> So, all we really have to do now is have the courage to merge this PR, right? I suppose it should also be backported to 8.0.2?

Yes to both.

**Comment by nilason** [comment]
> So, all we really have to do now is have the courage to merge this PR, right?

I need to emphasise that this is not my field of expertise. Someone might explain the advantages with hardcoding library linking info, but now I can't see any pros that overweight the contras (keep up with versions, support *all* platforms etc.).
I'd say definitely yes.

> I suppose it should also be backported to 8.0.2?

I personally believe it should be safe enough. The question is whether this is to be considered a bug -- lacking support for latest versions for all platforms should perhaps put this into that category.

**Comment by jef-n** [comment]
See also https://lists.osgeo.org/pipermail/grass-dev/2022-April/095640.html

**Comment by jef-n** [comment]
BTW: not windows specific

**Comment by wenzeslaus** [comment]
Maybe some user of GRASS driver for GDAL wants to test this. That is the only issue I can think of ([grass-dev Apr 12](https://lists.osgeo.org/pipermail/grass-dev/2022-April/095650.html)).

The Windows and Ubuntu tests are passing including v.in.ogr and r.external on Windows (visual check). This was submitted on Apr 4, Apr 7 on grass-dev, so on Apr 18 it will be two weeks since the initial submission which will give enough time for feedback. No response on the mailing list so far, so votes against this. I think we can merge it around Apr 18 (the coming Monday).

This has milestone 8.2.0, but also backport label. Do we want to be careful and change only 8.2 and continue with temporary fix in 8.0, i.e., no backport to 8.0?

> BTW: not windows specific

But the issue was not noticed on outside of Windows, no?

**Comment by nilason** [comment]
> But the issue was not noticed on outside of Windows, no?

We have #326,  there never was GDAL_DYNAMIC support for Mac.

**Comment by nilason** [comment]
> In a simplified view, this removes a lot of lines and simplifies others while keeping all automatic tests running and the feedback period passed. This is ready to be merged.

Agreed. 👍

**Comment by wenzeslaus** [comment]
Thanks to everyone involved, esp. to @jef-n for the change and to @neteler for the new tests.

**Comment by neteler** [comment]
@jef-n, all: do we want to have this PR backported to the upcoming GRASS 8.0.2?

**Comment by metzm** [comment]
Some explanation for this unusual dynamic linking: the reason was to avoid circular dependencies of GDAL and GRASS libs. Back then, GDAL needed GRASS (to build the GDAL-GRASS driver) and GRASS needed GDAL. For several years now, the GDAL-GRASS drivers (raster and vector) are no longer built with GDAL, instead the drivers are built as a separate GDAL-GRASS plugin. Thus GDAL no longer needs GRASS, the circular dependency is not an issue any more and this unusual linking in the GRASS raster lib can be safely removed.

Please backport!

**Comment by neteler** [comment]
Backport to relbranch80 done (for the upcoming GRASS 8.0.2).

**Comment by wenzeslaus** [comment]
One more comment from the mailing list on the removal of GDAL on-the-fly dynamic loading, specifically on the original motivation for the addition:

Q: Vaclav Petras:
> > ...I wanted to check the original motivation. Any ideas?...

A: [Glynn Clements on grass-dev, May 9 2022](https://lists.osgeo.org/pipermail/grass-dev/2022-May/095678.html):
> Dependencies. GDAL has lots of them. If libraster is linked directly
> against GDAL and one of the GDAL dependencies is missing or broken,
> GRASS will be almost completely non-functional.

> By using dlopen(), if there's an issue with GDAL it only matters if
> you try to use GDAL-linked (r.external) maps.

> This isn't an issue if you're getting GRASS (and everything it depends
> upon) via your distribution's package manager. It may be an issue for
> DIY builds.

**Pull request merged**
