### PR TITLE
GUI: fix ColumnSorterMixin regression

### PR DESCRIPTION
**Pull request by rohannallamadge**
---
#4277
---
just code changed from `ColumnSorterMixin(self, ncols)` to `ColumnSorterMixin.__init__(self, ncols)`

### CODE REVIEW

**Comment by echoix** [comment]
The second commit seems unrelated

**Comment by rohannallamadge** [comment]
yeah.. but in System description they have given new version  of all tools that's why I updated

**Comment by echoix** [comment]
> yeah.. but in System description they have given new version  of all tools that's why I updated

That was information to reproduce the bug or understand where it happens. And the place you changed is the documentation. We can really keep that part of the documentation updated at all times, as each new PR merged has a different revision, and would require a new PR right after each merge, and it wouldn't be up to date even for that. And it changes for each system, platform that runs it and library versions used.

So instead, we keep it updated once before releasing, or when we change the format of the information outputted, that isn't the case here.


Now knowing this, you can safely remove that second commit from this PR to keep it focused on the problem to fix.

**Review by petrasovaa — CHANGES_REQUESTED** [review]
I tested this in wxPython demo and we need this "dunder" call so please add everywhere
```
ColumnSorterMixin.__init__(self, ncols)  # noqa: PLC2801
```
to fix ruff complaining it.

**Comment by echoix** [comment]
What's that wxPython demo you used, so I know how to run it myself?

**Comment by echoix** [comment]
There's also the C2801 so Pylint itself can ignore it, not just the ruff implementation of it.

**Comment by petrasovaa** [comment]
> There's also the C2801 so Pylint itself can ignore it, not just the ruff implementation of it. (See #4309)

Right, @rohannallamadge please add that too:
```
... # noqa: PLC2801, C2801
```

**Comment by petrasovaa** [comment]
> What's that wxPython demo you used, so I know how to run it myself?

https://extras.wxpython.org/wxPython4/extras/4.2.1/

Sometimes it's a nice way to experiment to see whether a problem is in wxPython itself or in GRASS

**Review by petrasovaa — APPROVED** [review]

**Comment by echoix** [comment]
@rohannallamadge For your next PRs, make sure to do your work on a branch (instead of master), so you can have multiple PRs waiting without interfering.

(I know master isn't the default branch in your fork, there's main too, but it's a good practice for contributions in any project, not just here)

**Comment by rohannallamadge** [comment]
"Got it! Thank you for the feedback. I'll make sure to create a new branch for my next PRs
Will do!"

**Comment by neteler** [comment]
Please also assign the correct milestone before merging, thanks!

**Pull request merged**
