### PR TITLE
Fix flake8 pep8 errors

### PR DESCRIPTION
**Pull request by neteler**
This PR fixes around 600 PEP8 errors identified with `flake8` and selectively fixed with `autopep8`, in order to separate out the different errors and warnings into single commits for easier review.

### CODE REVIEW

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
The changes look good after reviewing the commits and also additionally the non-whitespace changes. I agree that the escape sequence problem needs more care. Open an issue for it.

This PR is missing the change of ignored messages in the corresponding .flake8 file. Just remove all you fixed.

https://github.com/OSGeo/grass/blob/master/lib/python/.flake8

I was thinking this could be done by Black to reduce number of all changing commits and also because some of the fixes will be different from autopep8. On the other hand, doing this ahead will reduce the size of the changes by Black.

**Comment by neteler** [comment]
@wenzeslaus Corresponding `lib/python/.flake8` is updated and some further issues fixed manually.

Once merged I'll open issue(s) for the remaining errors and warnings not addressed here.

**Review by wenzeslaus — APPROVED** [review]
Awesome! Happy to see better code and more checks in place. :rocket:

**Comment by neteler** [comment]
Quick question: backport or not?

**Comment by wenzeslaus** [comment]
No backport. This is not fixing a critical bug in behavior. It seems exactly like the thing not to backport.

**Pull request merged**
