### PR TITLE
wxGUI: Changes in Layer Manager tabs order and labels

### PR DESCRIPTION
**Pull request by lindakladivova**
wxGUI/LayerManager: Changed tab order (Modules are third) and Layers renamed to Display.

### CODE REVIEW

**Comment by mlennert** [comment]
As one can open more than one display, I would call the tab 'Displays'.

**Comment by petrasovaa** [comment]
> As one can open more than one display, I would call the tab 'Displays'.

I thought about that and I still feel Display is better, since it's more general (meaning displaying as a concept) and many people don't use multiple displays anyway. But I don't have strong opinion on it.

**Comment by wenzeslaus** [comment]
Anybody has opinions about naming the tab _Display_ versus _Displays_? The current name is _Layers_.

**Comment by neteler** [comment]
If possible, @lindakladivova : could you pls add a screenshot here illustrating your proposal? thx

**Comment by nilason** [comment]
To me, *Display* (as a verb) seems most appropriate.

**Comment by lindakladivova** [comment]
Here is the suggestion:

Screenshot from 2020-07-21 11-48-52

**Comment by neteler** [comment]
I like "Display" best.

**Comment by mlennert** [comment]
On 22/07/20 13:00, Markus Neteler wrote:
> I like "Display" best.
> 

That makes for a clear vote for 'Display', so let's not spend more time 
on this :-)

Moritz

**Pull request merged**
