### PR TITLE
wingrass: rename grass.py to grass8x.py

### PR DESCRIPTION
**Pull request by landam**
Extracted from #1921 in order to fix blocker (#1911)

### CODE REVIEW

**Comment by neteler** [comment]
There is apparently yet a glitch: still using Python27?

`
Run .github/workflows/test_simple.bat 'C:\OSGeo4W64\opt\grass\grass80.bat'

D:\a\grass\grass>set grass=C:\OSGeo4W64\opt\grass\grass80.bat 

D:\a\grass\grass>call C:\OSGeo4W64\opt\grass\grass80.bat --tmp-location EPSG:4326 --exec g.region res=0.1 -p 
Fatal Python error: initfsencoding: unable to load the file system codec
  File "C:\OSGEO4~1\apps\Python27\lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

Current thread 0x00001b40 (most recent call first):
Error: Process completed with exit code 1.
`

**Comment by hellik** [comment]
where do this log come from?

>C:\OSGeo4W64

we switched to OSGeo4W vers 2, there shouldn't be the suffix W64 anymore

**Comment by hellik** [comment]
>Maybe the CI wasn't updated?

or the related PR not yet merged? @ninsbl

**Comment by ninsbl** [comment]
> > Maybe the CI wasn't updated?
> 
> or the related PR not yet merged? @ninsbl

Indded, #1873 has not been merged yet. Ideally, #1921 gets merged first, and then https://github.com/jef-n/OSGeo4W/pull/3
And then #1873 can be adjusted to the two other, so we use just one and the same build recipe in both CI and packaging. That way we make sure that what gets shipped to the user is tested...

However, although I generally would think that running our unit tests with OSGeo4W builds is an advantage for both projects, I see that cross-dependencies and the need for coordination are a drawback of such a solution....

**Pull request closed without merging**
