### PR TITLE
Initial tests for v.random

### PR DESCRIPTION
**Pull request by JosefPudil**
1) Checking if number of points equals 100
2) Checking if all points are in the polygon boundary state
3) Checking if all points are in the polygon boundary state

### CODE REVIEW

**Comment by wenzeslaus** [comment]
@JosefPudil @landam Do you plan to follow up? If not, we can mark this good first issue and open this for anybody to finish it.

**Comment by SunveerSingh** [comment]
Hey There! I will be working on this!

**Comment by SunveerSingh** [comment]
@wenzeslaus Sorry for the delay, as far as I can understand from the previous comments,  please see the updated file here: https://github.com/SunveerSingh/GRASSTests/blob/master/test_v_random.py I am not on the branch so I can't create a pull request.  Please let me know if any changes or improvements are needed.

**Comment by wenzeslaus** [comment]
@SunveerSingh No big problem with the delay, now is the time to get really into it. However, please do create the branch. Being able to navigate the Git/GitHub workflow is important part of both contributing and GSoC. If you find it confusing or hard to understand, don't despair, many (most?) people do (at least initially, but not only initially). Nevertheless, most things have their reason and it is possible to navigate the workflow even without understanding it. Please see the [CONTRIBUTING.md](https://github.com/OSGeo/grass/blob/master/CONTRIBUTING.md) file.

In your case, since you are starting from this PR and branch which is not in your or the main repo, additional step is needed and that's getting code from some other fork. You will need to create the branch in a special way which is:

```sh
# Create a new branch based on master branch.
git checkout -b add-v_random-test master
# Fetch changes from ctu-geoforall-lab branch and merge them into your new branch.
# (This is the special step.)
git pull https://github.com/ctu-geoforall-lab/grass.git v_random
# (Now or later) Push the branch to your fork.
git push origin add-v_random-test
```

Once ready, or even little before that, open a new PR. If all goes well, it will show changes by you on top of code by JosefPudil.

**Comment by ninsbl** [comment]
Bumping up milestone as 8.0.1 is due in two days, while this has not been part of RC1 and there has not been activity for some time.

**Comment by wenzeslaus** [comment]
Replaced by #1464. Thanks @JosefPudil. Good start, but needed some more work. So closing this one. Contributions transferred to https://github.com/OSGeo/grass/commit/0f0b7f89bcfce198dbe0e16c8a66e803789380ec and acknowledged there.

**Pull request closed without merging**
