### PR TITLE
osgeo4w: build fixes and use proj 7 and gdal 3

### PR DESCRIPTION
**Pull request by jef-n**

### CODE REVIEW

**Comment by metzm** [comment]
proj 6 and gdal 3 are not yet supported, waiting for PR #118 to be merged and backported

**Comment by neteler** [comment]
#137 has been merged and forward-ported to master in a1d75c73d0ce2b9d60b0911b9e969607ebd01ce6

@jef-n Could you please rebase this PR accordingly?

**Comment by hellik** [comment]
@neteler citing here @metzm  

> proj 6 and gdal 3 are not yet supported, waiting for PR #118 to be merged and backported

is GRASS now proj 6 and gdal 3 ready?

#137 is now merged; is this PR now only about proj 6 and gdal 3?

**Comment by hellik** [comment]
see https://lists.osgeo.org/pipermail/grass-dev/2019-October/093434.html


* master: https://github.com/OSGeo/grass/commit/b32d8be38d123eba6bcc2c33f8b13e40a836a79a
* releasebranch_7_8: https://github.com/OSGeo/grass/commit/66b4ea2c0e6c4962b8abb2f1fa7b4551dfbe9d7f

should we now merge also this PR? or do we have to adapt OSGeo4W env first?

**Comment by jef-n** [comment]
> should we now merge also this PR? or do we have to adapt OSGeo4W env first?

Depends.  As it is it build with the nightlies of GDAL and PROJ - so it should work now #118 is merged.    It probably should be changed to use the regular GDAL & PROJ packages again when those are updated.

**Comment by neteler** [comment]
@jef-n ok, what do you recommend? RC1 today without this change or wait for this PR being merged and then RC1?

**Comment by jef-n** [comment]
> @jef-n ok, what do you recommend? RC1 today without this change or wait for this PR being merged and then RC1?

This change was meant to build the daily builds with the nightlies of GDAL and PROJ.  So no - no need to merge into the release branch.

**Comment by hellik** [comment]
At the moment, proj4x and gdal2x are still the default in OSGeo4W, right?

Any idea when the switch to proj6 and gdal3 as default will happen?

@jef-n so your suggestion is to keep upcoming winGRASS 7.8.1 with proj4/gdal2?

Why not with winGRASS 7.8.1 RC1 switch to  proj6/gdal3?

**Comment by neteler** [comment]
> But that doesn't factor in that GRASS is "only" a RC.

So far it is not. This is what I want to know: RC1 tonight or not yet?

> And GDAL and PROJ also both currently have RCs out - so it might make sense to wait for those. 

You suggest to start the GRASS GIS RC cylce only after that? I am not sure why this would be helpful to delay the GRASS GIS release but maybe I am overlooking something.
Again: I am talking about the source code release, not the winGRASS/OSGeo4W package here.

**Comment by metzm** [comment]
On Tue, Oct 29, 2019 at 6:02 PM Markus Neteler <notifications@github.com>
wrote:
>
> But that doesn't factor in that GRASS is "only" a RC.
>
> So far it is not. This is what I want to know: RC1 tonight or not yet?

IMHO, asap.

> And GDAL and PROJ also both currently have RCs out - so it might make
sense to wait for those.
>
> You suggest to start the GRASS GIS RC cylce only after that? I am not
sure why this would be helpful to delay the GRASS GIS release but maybe I
am overlooking something.
> Again: I am talking about the source code release, not the
winGRASS/OSGeo4W package here.

GRASS 7.8.1 is not dependent on the current RCs of GDAL and PROJ. PROJ 6
and GDAL 3 have already been released and GRASS 7.8.1 would be the first
GRASS release to support GDAL 3 + PROJ 6 (in addition to previous versions
of GDAL and PROJ). Thus I don't see a need for GRASS to wait for the
current RCs of GDAL and PROJ.

my2c

Markus M

**Comment by hellik** [comment]
lets try to get out of the confusion  ;-)

(1) OSGeo4W environment has to prepared that winGRASS will switch to proj6 and gdal3 

(2) GRASS source ( i.e. winGRASS build scripts) have to be adapted to an adapted (1)

OSGeo4W environment will be changed to be ready for (1) when new proj6 and gdal3 RC will be then official releases incorporated in  OSGeo4W. It's too much maintaining burden to offer an interim solution in OSGeo4W. 

Regarding (2) winGRASS 7.8.1 RC1 won't be available with proj6 and gdal3 support at the moment as OSGeo4W isn't yet ready, see (1), thus nothing to test the new capabilties in the windows side of the world, no chance to catch bugs etc. 

In all cases, if GRASS 7.8.1 RC1 will be tagged now, winGRASS build scripts have to be adapted for (1) anyway..

Will be then there a RC2 or RC3 or RC4 or RC5 if needed?

it's all about keeping the maintaining and release burden now!

anything unclear?  ;-)

**Comment by neteler** [comment]
> In all cases, if GRASS 7.8.1 RC1 will be tagged now, winGRASS build scripts have to be adapted for (1) anyway..

Here we are!

https://github.com/OSGeo/grass/releases/tag/7.8.1RC1

> Will be then there a RC2 or RC3 or RC4 or RC5 if needed?

Sure, as needed.

**Comment by metzm** [comment]
> lets try to get out of the confusion ;-)
> 
> (1) OSGeo4W environment has to prepared that winGRASS will switch to proj6 and gdal3
> 
[...]
> 
> In all cases, if GRASS 7.8.1 RC1 will be tagged now, winGRASS build scripts have to be adapted for (1) anyway..

I thought it would be easier to first include GRASS 7.8.1 (because it works also with GDAL 1/2 + PROJ 4/5), and later on switch to GDAL 3 + PROJ 6. If you switch to GDAL 3 + PROJ 6 first, you break the GRASS build until GRASS is updated to 7.8.1. But then I am not a OSGeo4W maintainer.

**Comment by neteler** [comment]
FYI: GRASS GIS 7.8.1 with support for Python 3, PROJ 6 and GDAL 3 has been released:

https://github.com/OSGeo/grass/releases/tag/7.8.1

**Comment by kikislater** [comment]
> FYI: GRASS GIS 7.8.1 with support for Python 3, PROJ 6 and GDAL 3 has been released:
> 
> https://github.com/OSGeo/grass/releases/tag/7.8.1

Why 7.8.1 is considered as stable ? v.import doesn't work for example : https://trac.osgeo.org/grass/ticket/3869

**Comment by metzm** [comment]
> Why 7.8.1 is considered as stable ? v.import doesn't work for example : https://trac.osgeo.org/grass/ticket/3869

According to ticket [3869](https://trac.osgeo.org/grass/ticket/3869), v.import does work, it just does not have all the options of v.in.ogr.
Originally, v.import was meant to be a simple vector import tool with only a few options to keep the user interface simple. If you want more control over the import process, use v.in.ogr.

**Comment by kikislater** [comment]
Yes but it was written : 

> v.import might not work as expected with proj 6+ and gdal 3+ in future releases of GRASS GIS

So if you have previous code working and update to 7.8.1, it breaks the workflow. So it partially works ... Could not be considered as stable or put message on release log like :  **modules break !**

**Comment by metzm** [comment]
> Yes but it was written :
> 
> > v.import might not work as expected with proj 6+ and gdal 3+ in future releases of GRASS GIS
> 
> So if you have previous code working and update to 7.8.1, it breaks the workflow. So it partially works ... Could not be considered as stable or put message on release log like : **modules break !**

It's the other way around: if you upgrade to GDAL 3 + PROJ 6, v.import of GRASS 7.6 is guaranteed to **not** work correctly. You need GRASS 7.8.1 if you want to use GRASS with GDAL 3 + PROJ 6.

Rephrasing your words: if you have previous code working and update to gdal 3 + proj 6, it breaks the workflow unless you update GRASS to 7.8.1.

**Comment by kikislater** [comment]
Makes sense but what happen to 7.8 documentation ? 

>  If the projection of the input does not match the projection of the location, the input is reprojected into the current location
https://grass.osgeo.org/grass78/manuals/v.import.html

**Comment by metzm** [comment]
> Makes sense but what happen to 7.8 documentation ?
> 
> > If the projection of the input does not match the projection of the location, the input is reprojected into the current location
> > https://grass.osgeo.org/grass78/manuals/v.import.html

This is still valid. If you want to use PROJ 6, you need GRASS 7.8.1. As before, for more control over the import and reprojection process, use v.in.ogr and v.proj instead of v.import. Regarding PROJ 6, it is worth to use projinfo to select an appropriate reprojection method.

**Comment by kikislater** [comment]
Ok thank you. As I know these limitations now it's ok for me but others could be in trouble regarding documentation and reprojection from this module

**Comment by neteler** [comment]
@hellik @landam what about this PR? Is it relevant for the upcoming 7.8.2?

**Comment by jef-n** [comment]
> @hellik @landam what about this PR? Is it relevant for the upcoming 7.8.2?

no.

**Comment by neteler** [comment]
Re: PROJ 7 support, see also #395

**Pull request closed without merging**
