### PR TITLE
libpython/temporal: fix t.rast.import module import input tarball file

### LINKED ISSUE #3581: [Bug] t.rast.import fails with ValueError
**Describe the bug**
`t.rast.import` fails to import space-time dataset created by `t.rast.export`.

**To Reproduce**

1. Download sample dataset: [sample.zip](https://github.com/OSGeo/grass/files/14955481/sample.zip) and unzip
2. Create new location (EPSG: 5514)
3. Run `t.rast.import in=~/Downloads/sample.tar.bz2 output=sample`

```py
Traceback (most recent call last):
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/scripts/t.rast.import", line 151, in <module>
    main()
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/scripts/t.rast.import", line 131, in main
    tgis.import_stds(
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/stds_import.py", line 583, in import_stds
    register_maps_in_space_time_dataset(
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/register.py", line 400, in register_maps_in_space_time_dataset
    assign_valid_time_to_map(
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/register.py", line 560, in assign_valid_time_to_map
    end_time = int(end)
               ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'file'
```

**Expected behavior**
Space-time dataset imported successfully. 

**System description (please complete the following information):**

- Operating System: Linux
- GRASS GIS version 8.4

### PR DESCRIPTION
**Pull request by tmszi**
Fixes #3581.

### CODE REVIEW

**Review by veroandreo — APPROVED** [review]
it works as expected :)

**Comment by echoix** [comment]
Is there a way to trigger the old bug in a test without a specific dataset (even better just function calls)?

**Comment by tmszi** [comment]
I'm a little bit confused with printing semantic label.

I modified temporal data [sample.zip](https://github.com/OSGeo/grass/files/14955481/sample.zip) semantic labels inside list.txt file as follows:

```
zaplava_180.5|1|1|S2_1
zaplava_180.6|11|11|S2_2
zaplava_180.7|21|21|S2_3
```

Importing temporal raster maps was successful:

```
GRASS newProject/PERMANENT:~ > t.rast.import in=/tmp/exp/strds_export.tar.bz2 output=sample --o
Checking validity of input file (size: 0.0 MB). Make take a while...
Extracting data...
WARNING: Raster map <zaplava_180.5> already exists and will be overwritten
Importing raster map <zaplava_180.5>...
 100%
Color table for raster map <zaplava_180.5> set to 'zaplava_180.5.color'
WARNING: Raster map <zaplava_180.6> already exists and will be overwritten
Importing raster map <zaplava_180.6>...
 100%
Color table for raster map <zaplava_180.6> set to 'zaplava_180.6.color'
WARNING: Raster map <zaplava_180.7> already exists and will be overwritten
Importing raster map <zaplava_180.7>...
 100%
Color table for raster map <zaplava_180.7> set to 'zaplava_180.7.color'
 100%
 100%
```

Checking semantic labels with `t.info` module was successful:

```
GRASS newProject/PERMANENT:~ > t.info sample 
 +-------------------- Space Time Raster Dataset -----------------------------+
 |                                                                            |
 +-------------------- Basic information -------------------------------------+
 | Id: ........................ sample@PERMANENT
 | Name: ...................... sample
 | Mapset: .................... PERMANENT
 | Creator: ................... tomas
 | Temporal type: ............. relative
 | Creation time: ............. 2024-04-13 19:43:08.895144
 | Modification time:.......... 2024-04-13 19:43:09.374256
 | Semantic type:.............. sum
 +-------------------- Relative time -----------------------------------------+
 | Start time:................. 1
 | End time:................... 21
 | Relative time unit:......... minutes
 | Granularity:................ 10
 | Temporal type of maps:...... point
 +-------------------- Spatial extent ----------------------------------------+
 | North:...................... 1.0
 | South:...................... 0.0
 | East:.. .................... 1.0
 | West:....................... 0.0
 | Top:........................ 0.0
 | Bottom:..................... 0.0
 +-------------------- Metadata information ----------------------------------+
 | Raster register table:...... raster_map_register_0b33293e385f48e5984c3ed1bd5f3793
 | North-South resolution min:. 1.0
 | North-South resolution max:. 1.0
 | East-west resolution min:... 1.0
 | East-west resolution max:... 1.0
 | Minimum value min:.......... None
 | Minimum value max:.......... None
 | Maximum value min:.......... None
 | Maximum value max:.......... None
 | Aggregation type:........... None
 | Number of semantic labels:.. 3
 | Semantic labels:............ S2_1,S2_2,S2_3
 | Number of registered maps:.. 3
 |
 | Title:
 | 
 | Description:
 | 
 | Command history:
 | # 2024-04-13 19:43:09 
 | t.rast.import in="/tmp/exp/strds_export.tar.bz2"
 |     output="sample" --o
 | 
 +----------------------------------------------------------------------------+
```

Checking individual raster map semantic label with `r.info` module was successful too:

```
GRASS newProject/PERMANENT:~ > r.info zaplava_180.5
 +----------------------------------------------------------------------------+
 | Map:      zaplava_180.5                  Date: Sat Apr 13 20:09:00 2024    |
 | Mapset:   PERMANENT                      Login of Creator: tomas           |
 | Project:  newProject                                                       |
 | DataBase: /home/tomas/grassdata                                            |
 | Title:                                                                     |
 | Timestamp: 1 minute                                                        |
 |----------------------------------------------------------------------------|
 |                                                                            |
 |   Type of Map:  raster               Number of Categories: 0               |
 |   Data Type:    FCELL                Semantic label: S2_1                  |
 |   Rows:         1                                                          |
 |   Columns:      1                                                          |
 |   Total Cells:  1                                                          |
 |        Projection: S-JTSK / Krovak East North                              |
 |            N:          1    S:          0   Res:     1                     |
 |            E:          1    W:          0   Res:     1                     |
 |   Range of data:    min = NULL  max = NULL                                 |
 |                                                                            |
 |   Data Description:                                                        |
 |    generated by r.in.gdal                                                  |
 |                                                                            |
 |   Comments:                                                                |
 |    r.in.gdal --overwrite input="zaplava_180.5.tif" output="zaplava_180.\   |
 |    5" memory=150 offset=0 num_digits=0                                     |
 |                                                                            |
 +----------------------------------------------------------------------------+
``` 

But checking individual raster map semantic label with `r.semantic.label` module doesn't print semantic label:

```
GRASS newProject/PERMANENT:~ > r.semantic.label zaplava_180.5 operation=print
WARNING: Metadata for semantic label <None> not found
```

**Comment by tmszi** [comment]
> Is there a way to trigger the old bug in a test without a specific dataset (even better just function calls)? I know it's not fun...

I can extend t.rast.import module tests by test of import temporal raster maps with semantic labels, and check them.

**Comment by tmszi** [comment]
> But checking individual raster map semantic label with `r.semantic.label` module **doesn't print semantic label:**

It is bug (method semantic_label argument is assigned to wrong parameter), I'm going to open related PR.

**Review by echoix — APPROVED** [review]

**Pull request merged**
