### PR TITLE
tools/mkhtml: fix src and src commits url in html addon module manual

### PR DESCRIPTION
**Pull request by tmszi**
Fix bug reported in the issue #979.

### CODE REVIEW

**Comment by neteler** [comment]
Tested in master, works as expected.

Tested also on relbranch78 but here I still get the trac link rather than the GitHub repo link. This may be interesting, too, since the addons are compiled on the grass.osgeo.org server using relbranch78.

**Comment by tmszi** [comment]
> Tested in master, works as expected.
> 
> Tested also on relbranch78 but here I still get the trac link rather than the GitHub repo link. This may be interesting, too, since the addons are compiled on the grass.osgeo.org server using relbranch78.

So that's interesting, I tested this patch on relbranch78 and works as expected, too.

Simple test:

```
# Instalation 
g.extension -i operation=add extension=r.green

cat .grass7/addons/docs/html/r.green.biomassfor.co2.html | tail -n 20

--><h2>SOURCE CODE</h2>
<p>Available at: <a href="https://github.com/OSGeo/grass-addons/tree/master/grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.co2">r.green.biomassfor.co2 source code</a> (<a href="https://github.com/OSGeo/grass-addons/commits/master/grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.co2">history</a>)</p>
<hr class="header">
<p>
<a href="index.html">Main index</a> |
<a href="raster.html">Raster index</a> |
<a href="topics.html">Topics index</a> |
<a href="keywords.html">Keywords index</a> |
<a href="graphical_index.html">Graphical index</a> |
<a href="full_index.html">Full index</a>
</p>
<p>
&copy; 2003-2020
<a href="http://grass.osgeo.org">GRASS Development Team</a>,
GRASS GIS 7.8.4dev Reference Manual
</p>

</div>
</body>
</html>
```

```
# Compilation only
g.extension -i operation=add extension=r.green

cat /tmp/grass7-tomas-23723/tmpg7i63fps/r.green/docs/html/r.green.biomassfor.co2.html | tail -n 20

--><h2>SOURCE CODE</h2>
<p>Available at: <a href="https://github.com/OSGeo/grass-addons/tree/master/grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.co2">r.green.biomassfor.co2 source code</a> (<a href="https://github.com/OSGeo/grass-addons/commits/master/grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.co2">history</a>)</p>
<hr class="header">
<p>
<a href="index.html">Main index</a> |
<a href="raster.html">Raster index</a> |
<a href="topics.html">Topics index</a> |
<a href="keywords.html">Keywords index</a> |
<a href="graphical_index.html">Graphical index</a> |
<a href="full_index.html">Full index</a>
</p>
<p>
&copy; 2003-2020
<a href="http://grass.osgeo.org">GRASS Development Team</a>,
GRASS GIS 7.8.4dev Reference Manual
</p>

</div>
</body>
</html>
```

**Comment by neteler** [comment]
Ah, maybe I had local leftovers here.

**Comment by neteler** [comment]
Thanks, I'll merge it and backport to get the online addons manual right.

**Comment by tmszi** [comment]
> Thanks, I'll merge it and backport to get the online addons manual right.

You are welcome. Alright Markus. Small note some basic functionality is included in this [PR,](https://github.com/OSGeo/grass/pull/683) after this [PR](https://github.com/OSGeo/grass/pull/683) will be merged, I will open new PR (with cosmetic code changes especially this [function](https://github.com/OSGeo/grass/pull/987/commits/055d8b48b81d520e79f73aa76bd4c300436f8c87#diff-58ae09416c2574f4eb2c0dbd6b0470d1R169)).

**Pull request merged**
