### PR TITLE
d.vect: label vertical alignment workaround

### LINKED ISSUE #2854: Incorrect label vertical alignment for certain font sizes
A row of vector points has labels shown next to them. Depending on the font size, some labels will be vertically shifted or all labels will be on the same line (as expected).
See screenshot with only one difference – for one row font size is set to 21px and for other – 22px. Vertical alignment should be identical for all letters but is different for the 21px case.
21px

### PR DESCRIPTION
**Pull request by marisn**
Although more fine-grained control over label placement would be better, this PR at least makes labelling to work as intended.
Fixes #2854

### CODE REVIEW

**Comment by nilason** [comment]
This is the output with Cairo:
map

**Comment by nilason** [comment]
Using:

```sh
#!/bin/sh

# nc_spm_full_v2alpha2

echo "1|629880|222510|a
2|629882|222510|b
3|629884|222510|c
4|629886|222510|d
5|629888|222510|e
6|629890|222510|f
7|629892|222510|g
8|629894|222510|h
9|629896|222510|i
10|629898|222510|1
11|629900|222510|2
12|629902|222510|3
13|629904|222510|4
14|629906|222510|5
15|629908|222510|6
16|629910|222510|7
17|629912|222510|8
18|629914|222510|9" | v.in.ascii input=- output=labelmap cat=1 x=2 y=3 --overwrite

g.region e=629916 w=629879 s=222508 n=222512 res=1
d.mon start=cairo output=map.png --overwrite

d.vect map=labelmap color=0:29:57:255 width=1 \
    attribute_column=str_1 label_bcolor=13:0:200:255 \
    label_size=21 \
    yref=bottom xref=left

d.mon stop=cairo
```

**Comment by marisn** [comment]
That's strange as your example gives me (as expected):
image

**Comment by nilason** [comment]
Made another attempt with this PR, results are better (must have failed to build this PR correctly before), but centring doesn't work well (here top + center):

map

and with increased scale (greater region, larger distance between points):

map2

Script used, see in details:

<details>

```bash
#!/bin/sh

# nc_spm_full_v2alpha2

g.region e=629916 w=629879 s=222508 n=222512 res=1

echo "1|629880|222510|a
2|629882|222510|b
3|629884|222510|c
4|629886|222510|d
5|629888|222510|e
6|629890|222510|f
7|629892|222510|g
8|629894|222510|h
9|629896|222510|i
10|629898|222510|1
11|629900|222510|2
12|629902|222510|3
13|629904|222510|4
14|629906|222510|5
15|629908|222510|6
16|629910|222510|7
17|629912|222510|8
18|629914|222510|9" | v.in.ascii input=- output=labelmap cat=1 x=2 y=3 --overwrite

d.mon start=cairo output=map.png --overwrite

d.vect map=labelmap color=0:29:57:255 width=1 \
    attribute_column=str_1 label_bcolor=13:0:200:255 \
    label_size=17 \
    yref=top xref=center

d.mon stop=cairo

g.region raster=basin@PERMANENT res=100

echo "1|629880|222510|a
2|630000|222510|b
3|631000|222510|c
4|632000|222510|d
5|633000|222510|e
6|634000|222510|f
7|635000|222510|g
8|636000|222510|h
9|637000|222510|i
10|638000|222510|1
11|639000|222510|2
12|640000|222510|3
13|641000|222510|4
14|642000|222510|5
15|643000|222510|6
16|644000|222510|7
17|644500|222510|8
18|645000|222510|9" | v.in.ascii input=- output=labelmap2 cat=1 x=2 y=3 --overwrite

d.mon start=cairo output=map2.png --overwrite

d.vect map=labelmap2 color=0:29:57:255 width=1 \
    attribute_column=str_1 label_bcolor=13:0:200:255 \
    label_size=17 \
    yref=top xref=center

d.mon stop=cairo
```

</details>

**Comment by marisn** [comment]
I didn't touch the horizontal alignment code. It also seems to be in a need for a solution. Still I do not know how it should be made as vertical shift is easy movement of point of reference up/down by size * magic constant, then for horizontal it wouldn't work like that as length of string must be taken into account.

Note – vertical alignment seems to work fine as all letters seem to be aligned on the same baseline (note – „g“ letter goes below the line, „a“ doesn't and „b“, „f“ are taller than „g“ or „a“).

**Comment by marisn** [comment]
@nilason can you, please, retest the PR if it is good now?

**Review by landam — APPROVED** [review]
I tested this PR (cairo 1.18). 

map_before

PR applied:

map

Letter "G" is slightly shifted. But still PR brings significant improvement.

**Comment by marisn** [comment]
> Letter "G" is slightly shifted. But still PR brings significant improvement.

@landam the "g" letter placement is intentional. Letters are aligned to baseline and not top or bottom. Note that "a", "c" and "e" are not as tall as "b", "d" and "f". And "g" does not jump up from its position as it goes below "a..f".

**Comment by landam** [comment]
To my knowledge there is no request for change. @marisn So feel free to merge.

**Review by nilason — APPROVED** [review]
This is certainly an improvement. I was hoping to get some time to explore a "a proper fix" as you mentioned in the comment, perhaps with some input from e.g. https://wiki.inkscape.org/wiki/Text_Rendering_Notes#HarfBuzz, but in vain.
Looks good to me!

**Comment by landam** [comment]
@marisn As you are marked as assignee, please consider merging this PR.

**Pull request merged**
