### PR TITLE
gunittest docs: fix broken links

### PR DESCRIPTION
**Pull request by neteler**
<strike>This PR expands the "[Analyzing quality of source code](https://grass.osgeo.org/grass79/manuals/libpython/gunittest_testing.html#analyzing-quality-of-source-code)" section in "Testing GRASS GIS source code and modules" document with information about our new [GitHub Actions](https://grass.osgeo.org/news/2020_06_28_github_actions/).</strike>

In addition, I fixed some outdated links.

Note that related to this, I got this Python error:

```
make sphinxdoclib
...
make[1]: Entering directory '/home/mneteler/software/grass_master/lib/python/docs'
SPHINXBUILD: Found <sphinx-build>
SPHINXAPIDOC: Found <sphinx-apidoc>
SPHINXBUILD: Using <sphinx-build>
GISRC=/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/demolocation/.grassrc79 GISBASE=/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu PATH="/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/bin:/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/bin:/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts:$PATH" PYTHONPATH="/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python:/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython:$PYTHONPATH" LD_LIBRARY_PATH="/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/bin:/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/bin:/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts:/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/lib:/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/lib:" LC_ALL=C LANG=C LANGUAGE=C sphinx-build -b html -d _build/doctrees   -c . src/ /home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/docs/html/libpython
Running Sphinx v2.2.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/mneteler/software/grass_master/lib/python/docs/conf.py", line 50, in <module>
    f.write(footer_tmpl.substitute(grass_version=grass_version, year=today.year))
TypeError: a bytes-like object is required, not 'str'

make[1]: *** [Makefile:72: libpythonhtml] Error 2
make[1]: Leaving directory '/home/mneteler/software/grass_master/lib/python/docs'
make: *** [include/Make/Sphinx.make:48: sphinxdoclib] Error 2
```

### CODE REVIEW

**Comment by petrasovaa** [comment]
This should help (untested):
```
diff --git a/lib/python/docs/conf.py b/lib/python/docs/conf.py
index 622cf3a54..3f801699b 100644
--- a/lib/python/docs/conf.py
+++ b/lib/python/docs/conf.py
@@ -46,7 +46,7 @@ grass_version = core.version()['version']
 today = date.today()
 
 copy("_templates/layout.html.template", "_templates/layout.html")
-with open("_templates/layout.html", "a+b") as f:
+with open("_templates/layout.html", "a+") as f:
     f.write(footer_tmpl.substitute(grass_version=grass_version, year=today.year))
     f.close()
```

**Comment by neteler** [comment]
Thanks, that fixes it.

**Comment by neteler** [comment]
Ok, I have dropped the new part.

**Comment by neteler** [comment]
I'll merge since the PR is rather trivial now.

**Pull request merged**
