### PR TITLE
d.vect.thematic: Do not show decimal places for ints

### PR DESCRIPTION
**Pull request by wenzeslaus**
Number of minimal decimal places is fixed to 2 in the legend generated by d.vect.thematic. This adds logic which changes the number of decimal places to 0 when the column type is integer (DB_C_TYPE_INT).

This does not let user decide the number, but it covers more cases than the current code and it prepares a way for making it parametrized in the future.

### CODE REVIEW

**Comment by cmbarton** [comment]
This will be a nice update if the module can be made to work with 8.4

**Comment by wenzeslaus** [comment]
The current CI checks are now running on this and the PR is now set to auto-merge when it passes the requirements. With our new system with required reviews, it needs an approving review from a maintainer.

In this new system, users and contributors without write access can help by leaving a reviews for whatever they feel qualified to judge, e.g. after testing the change.

**Comment by echoix** [comment]
Depending on how it was configured exactly, someone without write access can leave reviews, but they'll be gray instead of green, and won't "count" on the required reviews. However, I'm open to patch this and approve a PR if it is approved by such a person that would be a better reference than me, to unblock those rare cases. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#:~:text=If%20your%20repository,can%20be%20merged.

**Review by petrasovaa — APPROVED** [review]
Tested and it works

**Comment by wenzeslaus** [comment]
> ...someone without write access can leave reviews, but they'll be gray instead of green, and won't "count" on the required reviews. However, I'm open to patch this and approve a PR if it is approved by such a person that would be a better reference than me, to unblock those rare cases.

I think that should be our approach when applicable. We have a lot of skillful users/contributors/testers who can evaluate the functionality, sometimes even the code, so it would be great to have and use their input.

> Depending on how it was configured exactly...

As far as I can tell, that's the only configuration and that makes sense to me.

**Pull request merged**
