### PR TITLE
configure: update to autoconf 2.71

### PR DESCRIPTION
**Pull request by nilason**
Update GRASS configure to autoconf 2.71 (from present 2.69).

From autoconf 2.70 [announcement](https://lists.gnu.org/archive/html/autotools-announce/2020-12/msg00001.html):

> We are pleased to announce stable release 2.70 of GNU Autoconf.
> 
> This release includes eight years of development work since the
> previous release, 2.69.  Noteworthy changes include support for the
> 2011 revisions of the C and C++ standards, support for reproducible
> builds, improved support for cross-compilation, improved compatibility
> with current compilers and shell utilities, more efficient generated
> shell code, and many bug fixes.

([see more](https://lwn.net/Articles/834682/))

[Announcement of 2.71:](https://lists.gnu.org/archive/html/autotools-announce/2021-01/msg00000.html)
> We are pleased to announce stable release 2.71 of Autoconf.
> 
> 2.71 is a bugfix release, correcting several important compatibility
> problems and regressions discovered since the release of 2.70.  There
> are no new features.  Upgrading is recommended for all users of 2.70.
> Users of 2.69 or earlier should proceed with caution; please consult
> the NEWS file and/or the release announcement for 2.70 for details.

This is a smaller jump than the one from 2.13 to 2.69 (#1845), and (hopefully) avoids issues with patched distributions of autoconf, e.g. #2225 and #2280.

[autoconf 2.71 News](http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob;f=NEWS;h=f035e65e53b53857bbaafa66a24580ae4fabd916;hb=5ec29d5a4991e1fee322a48e7358e5bcd17c645c)

### CODE REVIEW

**Comment by metzm** [comment]
Current stable releases of e.g. Debian and Fedora come with autoconf 2.69. I suggest to wait with this PR until these two important Linux distros provide autoconf 2.71 in their latest stable releases.

**Comment by nilason** [comment]
> Current stable releases of e.g. Debian and Fedora come with autoconf 2.69. I suggest to wait with this PR until these two important Linux distros provide autoconf 2.71 in their latest stable releases.

This is not an urgent issue. I was foremost curious how much changes was needed to update and apparently there was not much. All the same, I tagged this to 8.4 and had no intention to suggest to backport it.

**Comment by neteler** [comment]
> Current stable releases of e.g. Debian and Fedora come with autoconf 2.69. I suggest to wait with this PR until these two important Linux distros provide autoconf 2.71 in their latest stable releases.

I just checked https://repology.org/project/autoconf/versions :

- Debian 11 (bullseye - official): autoconf 2.69
- Debian 12 (bookworm - in testing): autoconf 2.71
- Fedora 36 (official): autoconf 2.71
- Ubuntu 22.04 (testing):  autoconf 2.69
- Ubuntu 22.10 (testing):  autoconf 2.71

**Comment by a-detiste** [comment]
bookworm as been released

**Comment by landam** [comment]
@nilason Please can you rebase this PR?

**Comment by nilason** [comment]
> @nilason Please can you rebase this PR?

I will as soon as #2189 is merged. The two may conflict.

**Comment by marisn** [comment]
> > @nilason Please can you rebase this PR?
> 
> I will as soon as #2189 is merged. The two may conflict.

#2189 is stuck as requires @wenzeslaus approval to get merged. I'll be mostly off starting from the next week thus (unless someone else merges it), no action till the new year.

**Comment by marisn** [comment]
> If it's okey with you, I'll go ahead with the rebase (and possibly merge if so agreed).

Yes, feel free to do so. I'll manage with merging changes into #2189 (and, hopefully, one day be able to merge it too).

**Comment by nilason** [comment]
Rebased. Looks good overall, but Travis' Clang build fails. Seems unrelated to me... `clang --version` fails due to missing clang, just before configure...

**Comment by nilason** [comment]
> Rebased. Looks good overall, but Travis' Clang build fails. Seems unrelated to me... `clang --version` fails due to missing clang, just before configure...

There is a new Travis docker build, created in Dec 7.

**Comment by nilason** [comment]
Ahh, Travis is a good boy again.

**Comment by nilason** [comment]
According to https://repology.org/project/autoconf/versions `autoconf` version 2.71 is the default on following systems:
- Debian 12 'bookworm'
- Fedora 36
- Ubuntu 22.04 'jammy'

I believe the day has come to upgrade and merge this PR.

Note: `autoconf` (with this change, version 2.71) is only needed for (re-)generating the `configure` file, it is **not** needed for building. However, if there is any package system that regenerate the configure file as part of the building, it *might* cause problems, but I'm not aware of any such system.

Although the changes are small, it is preferable to merge this in good time before next release, to be able to test it properly.

**Review by landam — APPROVED** [review]

**Review by wenzeslaus — APPROVED** [review]
I can't really judge the details, but overall this looks hopeful and checks are passing. I like the use of `#error` instead of raw text `choke me` in the code.

**Comment by nilason** [comment]
@metzm, @neteler, others: any objection to merge this?

**Review by neteler — APPROVED** [review]
Thanks for the update!

**Comment by landam** [comment]
@nilason Please free to merge this PR (there are already three approvals)...

**Comment by echoix** [comment]
I had maybe one last question, but it got merged when writing the question.

Where the changes in i.cluster/global.h intended in this PR (to fix something), or was a merge/rebase artifact? I didn't read a mention of it in this thread

**Comment by nilason** [comment]
> Where the changes in i.cluster/global.h intended in this PR (to fix something), or was a merge/rebase artifact? I didn't read a mention of it in this thread

It was intended, obsolete configure tests/macros with 2.71.

**Comment by echoix** [comment]
Perfect then!

**Pull request merged**
