### PR TITLE
wxGUI: add r.buildvrt module into DevelopRasterMap toolbox

### LINKED ISSUE #2620: [Bug] r.buildvrt not visible in gui
**Describe the bug**
The r.buildvrt does not appear in the GUI Raster menu or tools tab. Launching from the command line works
**To Reproduce**

1. Go to Tools tab in main window 
2. Type buildvrt in Search window
3. No commands matching buildvrt found

**Expected behavior**
Expect to see gui link to r.buildvrt command

**Screenshots**

**System description (please complete the following information):**

- Operating System: Windwos 10 Enterprise
- GRASS GIS version8.2.0

g.version -rge
version=8.2.0
date=2022
revision=cafd69c05
build_date=2022-06-04
build_platform=x86_64-w64-mingw32
build_off_t_size=8
libgis_revision=cafd69c05
libgis_date=2022-06-03T13:27:06+00:00
proj=9.0.0
gdal=3.4.3
geos=3.10.2
sqlite=3.38.1

python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
4.1.1 msw (phoenix) wxWidgets 3.1.5 

**Additional context**

### PR DESCRIPTION
**Pull request by tmszi**
Fixes #2620.

### CODE REVIEW

**Review by neteler — APPROVED** [review]
Thanks!

**Comment by wenzeslaus** [comment]
Adding to menu sounds good, but isn't there a better home for this? In which way it is overlay? Isn't this more some data management?

**Comment by tmszi** [comment]
> Adding to menu sounds good, but isn't there a better home for this? In which way it is overlay? Isn't this more some data management?

I wasn't sure, I was deciding between DevelopRasterMap and OverlayRasters toolbox. I decided that when I looked at the manual page, the section [SEE ALSO](https://grass.osgeo.org/grass82/manuals/r.buildvrt.html#see-also) which contains r.patch which are part of the OverlayRasters toolbox.

**Comment by petrasovaa** [comment]
> > Adding to menu sounds good, but isn't there a better home for this? In which way it is overlay? Isn't this more some data management?
> 
> I wasn't sure, I was deciding between DevelopRasterMap and OverlayRasters toolbox. I decided that when I looked at the manual page, the section [SEE ALSO](https://grass.osgeo.org/grass82/manuals/r.buildvrt.html#see-also) which contains r.patch which are part of the OverlayRasters toolbox.

I think it should go under Develop Raster Map, after Tiling. It is doing a mosaic of tiles, so it's directly related to that. While r.patch can do a mosaic (and that's why it's linked from the man page), the reason why it's in Overlay rasters is its other usage - filling no data cells.

**Pull request merged**
