### PR TITLE
Changes done trac 2981

### PR DESCRIPTION
**Pull request by cvvergara**
@neteler 

Currently the weblate is out of sync, there are conflicts.
see [trac 2981](https://trac.osgeo.org/osgeo/ticket/2981)

### CODE REVIEW

**Comment by wenzeslaus** [comment]
While I don't know how Weblate is updated, I think what needs an update is the Weblate repo. This PR can be closed.

As I mentioned in [OSGeo Trac 2981#comment:21](https://trac.osgeo.org/osgeo/ticket/2981#comment:21), I don't see any changes in translations in the Weblate repo (in fact in the two repos linked there). The only differences are code (not translations). That needs to be updated possibly by rest to main of this (upstream) repository.

**Comment by HuidaeCho** [comment]
See https://github.com/OSGeo/grass/pull/3160. PRs from Weblate seem to be broken with no changes shown (detected?).

**Comment by cvvergara** [comment]
This was done after this PR
https://github.com/OSGeo/grass/pull/3160#issuecomment-1732219996

Please note that sometimes there are conflicts on the translations they might be as simple as:
```
<<<<<<< HEAD                                                                                                            
"PO-Revision-Date: 2023-08-23 07:08+0000\n"                                                                             
=======                                                                                                                 
"PO-Revision-Date: 2023-06-28 19:08+0000\n"                                                                             
>>>>>>> eeff31d386 (Translated using Weblate (German))  
```

or as complicated as, one translator translated a string and another one translated the same string, both are done on different commits, (if commits done by author)

Will close my PR

**Comment by cvvergara** [comment]
image

**Comment by wenzeslaus** [comment]
> or as complicated as, one translator translated a string and another one translated the same string, both are done on different commits, (if commits done by author)

Sounds like something which happens during the natural course of things. Any idea how to resolve or avoid these? ...assuming that they are actually a problem.

**Comment by robe2** [comment]
It's usually not a problem as long as you close pull requests promptly before you make further edits in the repo.  I think the issue with grass, is two fold

1) there wasn't an automatic hook set in place before to notify weblate when changes were made to the repo.  This was fixed

2) Weblate past pull request was being ignored

**Pull request closed without merging**
