### PR TITLE
r.coin: added tests for r.coin module

### PR DESCRIPTION
**Pull request by Shreshth-Malik**
The test parses the tabular output of `r.coin`, extracts relevant data, and compares it against expected results to ensure accurate calculate of category coincidences.

### CODE REVIEW

**Comment by Shreshth-Malik** [comment]
Are there any more tests that I can perform for this tool?

**Review by echoix — COMMENTED** [review]
I don't know if there is missing something. There is only one test, so testing with all flags and options might be hard to do in a unit test way.

Since you're using pytest, the their assert handling might be enough to not need having a string explaining when it doesn't match. But you don't need to change it, just to know in the future (unless the output wasn't clear enough when you tested it). 

Usually, what I consider makes a good test, is tests that you have confidence in to catch your bugs and future bugs. Tests that you have seen fail before, and that passes after. That means you know that the test isn't always passing even if it's not right. I usually like to check that the conditions that make the module fail are tested to fail, so that if ever it passes for no reason, it would be flagged in tests.

You don't need to do the same kind of test for all options. For example, I see that there is an `unit` argument, you might want to know that the module correctly accepts them, and rejects others.

But if you feel that what you have is enough, we can go with this for now

**Comment by echoix** [comment]
For now, the test doesn't run yet, because the file name doesn't match the pattern hardcoded in pyproject.toml. (It bothered me in another PR too).

Do you mind testing (locally maybe) if removing that line includes too much files? https://github.com/OSGeo/grass/blob/7e29f98e86c644696e35f504c8ae4d287e1745d3/pyproject.toml#L381

Otherwise, change it to match the pytest defaults like explained in
https://docs.pytest.org/en/latest/reference/reference.html#confval-python_files, but inside `tests` folder only. 
> By default, files matching `test_*.py` and `*_test.py` will be considered test modules.

**Comment by Shreshth-Malik** [comment]
@echoix So removing the line is resulting is a lot tests failing and messing up the build. So I placed my test in the `tests` folder with the right nomenclature. It is being included in the tests now but I am getting an error on line `run_command("g.region", n=3, s=0, e=3, w=0, res=1)` saying:
`grass.exceptions.CalledModuleError: Module run `g.region n=3 s=0 e=3 w=0 res=1` ended with an error.
The subprocess ended with a non-zero return code: 1.`

I tried calling `run_command` with Grass script context like `gs.run_command` but doesn't seem to work as well. Maybe there is something I am missing as the tests are passing locally.

I am planning to add tests for different units and see if the output consistently updates with changing the `units`.

**Comment by echoix** [comment]
@wenzeslaus do you have some guidance here? Is it a question of missing a session in pytest, since it is not a Python module, but a C one?

@Shreshth-Malik 
Is there any other tests that use a C module that runs with pytest that you could see how it gets called/set up?

**Comment by Shreshth-Malik** [comment]
Added config file to setup the environment like other tests I ran into. But I am triggering another error where the session is not passing onto the test file and in the line `gs.setup.init(project, env=os.environ.copy())` is not taking 2 arguments hence i can't pass `env` variable. I checked https://grass.osgeo.org/grass85/manuals/libpython/_modules/script/setup.html which gives an idea how to setup but in those examples `init` is taking the `project` and `env` variables successfully.

I will keep looking into it and try to see where it is going wrong.

**Comment by echoix** [comment]
@Shreshth-Malik I think this is working now, since #4784 got merged. We can see with code coverage that the new test got correctly run, and there are no failures. Do you still have local errors to solve, or is it ready to go? Was there anything else left to do in this PR currently marked as a draft?

**Review by echoix — APPROVED** [review]

**Pull request merged**
