### PR TITLE
CI (Python): Refine pytest workflow to address package compatibility issues

### PR DESCRIPTION
**Pull request by arohanajit**
Iimprove the stability and compatibility of pytest workflow, particularly focusing on issues encountered with newer Python versions and package dependencies.
Modified the package installation process to address compatibility issues with setuptools, wheel, and pip across different Python versions (3.9, 3.12, 3.13).
Attempted to resolve deprecation warnings related to pkg_resources by updating dependencies and modifying requirement files.
Adjusted the PYTHONWARNINGS environment variable to catch potential issues early in the CI process.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
I'm postponing running the CI here until we resolve (possibly off-list) what is @arohanajit's intention.

**Comment by echoix** [comment]
@wenzeslaus are you in contact with him in person, or you'd like for me to take the time sometime tomorrow?

**Comment by wenzeslaus** [comment]
I suggested @arohanajit to try one of the ResourceWarnings coming from Python code first. CI on @arohanajit's branch does not pass at this point. I'm not saying you can't have a look here.

**Comment by echoix** [comment]
That's a good idea. It's a good start. Lots of the warnings are hidden in the captured stderr of gunittest reports. But the easiest way to start is by using `ruff check --select SIM115`, and even `ruff check --select SIM115,FURB101,FURB103`. Fixing these will fix most of the resourcewarnings that originate from unclosed files (Python catched it and closed it).

But depending on his interests, he might want to try getting Pylint 3 passing. I have the CI ready, the config file ready since end of June/July (only missing new exclusions). In fact it was done before I introduced ruff here. I used ruff to help pass through some issues that could be fixed faster or automatically to increase the global quality and reduce the amount of issues to investigate with Pylint, that is way slower than the milliseconds ruff takes. Pylint handles more complex issues though, that aren't limited to static analysis. However, the work to do is a bit more unbounded, unguided. There are no auto fixes, and the direct link to the file in question is less evident (module name vs file path). All issues that prevent Pylint to pass are either to fix or add as an exclusion. There isn't a particular cause, it's very varied. So it's a different challenge, but maybe not a good first issue.

**Comment by echoix** [comment]
Is he interested in Python only, or CI, or C/C++ too? If it's CI, enabling (integrating) tools like cppcheck/flawfinder (respecting a reasonable resource usage w.r.t. the usefulness) might be a good challenge too.

**Comment by echoix** [comment]
Hi @arohanajit!
I'm glad to see you're interested in improving some CI and Python quality for GRASS here, but as you might have understood from off-list communications, this PR specifically isn't ready to be merged as is, will be closed unmerged. But, even so, I'll still take the time to review it so we can all learn (not just you) on what makes it not approved. I still invite you to try other PRs in the near future!


At a general level, I had some difficulty understanding what the problem referred to was, and how the PR changed it, or improved on it. The closest change that could be related to that is to install setuptools and wheel in the workflow. Since an issue didn't exist yet (and wasn't discussed), or the issue not explained, it was harder to know what you are talking about.
-> We need to be able to understand the issue one way or the other
-> The PR's code should be related to what the PR's description says
-> I like to understand the _why_ of a PR, when judging it

The PR description was well written 😀 but concerned 4 (slightly) unrelated topics 🙁
-> it's generally a good idea to have a PR concern a single topic.
-> it's makes reviewing easier, by having a single reviewer know enough on the entire PR to understand and approve. We aren't that good yet at having multiple complementary reviewers (except for code vs linguistic reviews in a same PR, we're getting the hang of it)

The PR seemed to contain some unintended changes, some formatting, others not.
-> it's better to try to have a small, clean diff before sending a PR. There's less to review, and it's clear what the changes are. (Note that it's not always possible to do so, for examples in PRs that intend to change formatting)
-> When addressing a problem, it's ok to leave out a change for another time if it isn't related. I often hate it as the file isn't as good as it could be, but then I think on future me 15 years from now digging a file's git history and not understanding why a certain line was changed with a commit message talking about a different subject. 

Creating a PR directly from your main branch is often prone to silly mixups in the process (like not understanding that updating your fork will also update the PR, not being able to have a second PR with separate changes from the same branch). It’s way easier to have 1 branch=1 PR when starting.

That's it for the form. It's not too bad for a first contribution.



Let's go technical now. 🤩 Let's forget the fact that some changes would've been in other separate PRs. Let's imagine that every change was made in a perfect PR and everything was understood perfectly and all.

https://github.com/OSGeo/grass/pull/4239/files#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL1
Removing the yaml triple dash at the top of the file. It is a feature of YAML files to signal the start of a document, most useful when having directives over it, or having multiple documents one after the other in the same stream. https://stackoverflow.com/questions/50788277/why-3-dashes-hyphen-in-yaml-file Our yaml linters suggest adding them if not there. It is not mandatory and in our file, it is still valid without it.
My decision would’ve been to keep the original line.


https://github.com/OSGeo/grass/pull/4239/files#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL30-L31
It’s seems the two comments providing context on these env vars were removed. If it isn’t problematic, it’s a good idea to keep it. I don’t see the improvement that it makes.


https://github.com/OSGeo/grass/pull/4239/files#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aR31

Changing PYTHONWARNINGS from always to error. It’s not bad as such, as it’s stricter, but it’s been only a week since we added this to see more warnings. We’re not ready for it yet, we still need to stabilize what we just disrupted. And it will error out even for things that wouldn’t be our fault or possible to solve (e.g. errors in PIP). I tried it the other week in a branch, it wasn’t ready either: https://github.com/echoix/grass/pull/199
I would’ve even considered a "downgrade" to « `default` if justified or bundled with Python’s dev mode, as it still includes all warnings without the ones ignored by default, but doesn’t print as much times.  https://docs.python.org/3/library/warnings.html#the-warnings-filter
-> might be accepted later when appropriate


https://github.com/OSGeo/grass/pull/4239/files#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL35-R34

Changing the action’s version pointed to. I assumed at first that you were thinking of pinning the dependencies to there exact versions (major.minor.patch), because it’s better. Yes it’s better for having the same version, but when compared to sliding tags (ie v4 or v4.1). With a less granular tag, what’s not good is that when the tag changes (by the action’s author), a workflow that used to work might not work anymore, even if we didn’t change anything. We can also think at cybersecurity (what if the new version is malicious?). Thing is, tags aren’t really immutable, we can force push, and that’s a way of having these « v4 » sliding tags. Since the design of GitHub Actions makes use of regular git ref for downloading actions (can for example be a [commit-ish](https://git-scm.com/docs/gitglossary#def_commit-ish) or [tree-ish](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftree-ishatree-ishalsotreeish)), using a tag v4.1.7 isn’t any better that using v4, it still has the same problems. So, the accepted convention for GitHub Actions is to specify the full commit digest of the tag. So, us having a hash there doesn’t mean that we were outdated. In fact, the comment afterwards is automatically kept updated by renovate PRs at the same time the commit hashes are updated. So, these changes are in fact decreasing the good practices here, I would’ve kept the old lines.


https://github.com/OSGeo/grass/pull/4239/files#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aR43-R46:

Installing/upgrading pip above where it was: Not really useful as such, as technically if ever we had a custom image or didn’t assume any software were installed in the runner, we might have needed to have the system dependencies by apt-get installed first (like Python) before running it.

Adding setuptools and wheel: This shouldn’t be needed, especially since we don’t use it ourselves, and pip should (as it would be the good thing to do, not what it really is doing) getting it when needed. Since the years that pyproject.toml is used (PEP517, PEP518, PEP621), projects should be defining what they need as a build system. So, there shouldn’t be any reason to have it, I don’t see what it solves as there wasn’t a problem in this workflow if I remember correctly. In fact, installing the wheel package from pip is discouraged, it shouldn’t be needed and needing to install it manually is a symptom of other problems. See the README on pypi or https://github.com/pypa/wheel?tab=readme-ov-file#historical-note. 

https://github.com/OSGeo/grass/pull/4239/files#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aR102
unrelated change. 


https://github.com/OSGeo/grass/pull/4239/files#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aR136
end of file changed. We tend to finish the files with a final newline. Mostly an Linux convention, comes handy when displaying multiple files in a same stream). Work on getting a editorconfig file set up at the repository’s root isn’t started yet, but I have one for grass-addons, just too many violations for now.



https://github.com/OSGeo/grass/pull/4239/files#diff-076aa247a1ac6862a2ca9b69f936f9fdb210a8cb2cb63a228e2b4d45219a7beaR44
seems to be a typo, a stuck keyboard, or a cat on a keyboard? 😆


So, that’s it for the technical part.

In any event, don’t take this as an attack, I’m only concerned on the code itself, not the person, and I truly believe in one of the Wikipedia’s guidelines saying « do not bite the newcomers ». @wenzeslaus seems to have taken care already of directing your interests on other parts where some help will be very valuable.

**Comment by arohanajit** [comment]
Thank @echoix for taking time to give such a detailed feedback! Apologies for late response as I was caught a bit with my coursework. Basically the pytest workflow failed when I forked this repo and ran it on my system. And I thought those were the errors @wenzeslaus was referring to when he mentioned I need to fix errors/warnings. I have also been following This was what I was getting:
image

Since then I has directed to me to much more relevant errors in the src code that I can invest my efforts into. I have also been following this discussion, and I just wanted to mention that although most of my work has been in Python, I am familiar with GCC/C++ (albeit only from perspective of leetcoding😅) and would open to exploring them as well

**Pull request closed without merging**
