### PR TITLE
Cross compilation

### PR DESCRIPTION
**Pull request by HuidaeCho**
Cross-compiling to MinGW cannot run g.parser.exe for generating HTML files. Currently, only Html.make ignores cross-compiling.

### CODE REVIEW

**Comment by hellik** [comment]
Could you point to this issue in the compilation log, e.g. in

https://wingrass.fsv.cvut.cz/grass79/x86_64/logs/log-r539a62a7d-45/

**Comment by HuidaeCho** [comment]
> Could you point to this issue in the compilation log, e.g. in
> 
> https://wingrass.fsv.cvut.cz/grass79/x86_64/logs/log-r539a62a7d-45/

I don't think those logs are from cross compilation. I found many references to /c/OSGeo4W64, /C/msys64/, and C:/msys64. If I'm not wrong, current official daily builds for Windows are built on Windows using OSGeo4W and MSYS2. They are not cross compiled. There are no relevant errors in those logs.

However, when you actually cross-compile, you cannot generate html files by running g.parser.exe or individual modules from Linux because these binaries are for a target architecture (e.g., Windows or x86_64-w64-mingw32). Actually, that is what Html.make is currently doing for the same reason; it empties the html target when cross-compiling.

**Comment by hellik** [comment]
Thanks for the clarification. 

Any idea how often cross-compilation is used?

**Comment by neteler** [comment]
(to me it looks ok)

**Comment by HuidaeCho** [comment]
> Thanks for the clarification.
> 
> Any idea how often cross-compilation is used?

Well... Hopefully, daily in the near future. I'm trying to use cross compilation over OSGeo4W/MSYS2 because make in MSYS2 is just too slow (https://github.com/msys2/MSYS2-packages/issues/138). It takes about an hour to compile GRASS vs. 6 minutes cross-compilation. Both on SSD. Cross-compilation works fine; I just need to figure out how to set it up properly when running it on Windows.

If you want to see the issues related to this commit, [error.log](https://idea.isnew.info/how-to-cross-compile-grass-gis-for-ms-windows/error.log) and [mymake.log](https://idea.isnew.info/how-to-cross-compile-grass-gis-for-ms-windows/mymake.log) (lines 24931, 37722, 37736, etc for Traceback for `No module named 'grass'`).

**Comment by HuidaeCho** [comment]
Just added one change to `configure` and `configure.in`, but `pkg-config` also needs to be configurable for cross compiling. In my case, `x86_64-w64-mingw32.shared-pkg-config` should be used. Maybe, through `--with-pkg-config` or `$PKG_CONFIG`?

One more... `WINDRES` in `include/Make/Grass.make` is hardcoded to `windres`, but I'm using `x86_64-w64-mingw32.shared-windres`.

**Comment by HuidaeCho** [comment]
Maybe, this is also related. Since `configure` overwrites `include/Make/Platform.make` and Doxyfile*, compiling host and target binaries requires running `configure` every time before `make`. Not a big deal, but annoying for cross-compiling.

**Comment by HuidaeCho** [comment]
https://autotools.io/pkgconfig/cross-compiling.html

**Comment by HuidaeCho** [comment]
Currently, `cd gui/wxpython; make` cannot generate XML files when cross compiling.

```bash
core/toolboxes.py:416: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  idx = items.getchildren().index(subtoolbox)
core/toolboxes.py:573: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  mItemChildren = moduleItem.getchildren()
core/toolboxes.py:575: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for node in moduleNode.getchildren():
r.in.gdal: Unable to fetch interface description for command '<r.in.gdal>'.

Details: <[Errno 2] No such file or directory: 'r.in.gdal': 'r.in.gdal'>
r.in.xyz: Unable to fetch interface description for command '<r.in.xyz>'.

Details: <[Errno 2] No such file or directory: 'r.in.xyz': 'r.in.xyz'>
```

**Comment by HuidaeCho** [comment]
**PR summary**
- `configure` and `configure.in`
  - `$PKG_CONFIG` support
  - `$WINDRES` support
  - Use `pwd` instead of `pwd -W` for cross compiling
- `include/Make/Grass.make`
  - Remove `WINDRES` (moved to `include/Make/Platform.make`)
- `include/Make/Platform.make`
  - Add `WINDRES`
    - Empty for non-MINGW
    - `windres` for MINGW without `$WINDRES`
    - `$WINDRES` for MINGW with `$WINDRES`
- `include/Make/GuiScript.make`
  - Don't try to generate HTML files when cross-compiling because we cannot run cross-compiled binaries
- `include/Make/Rules.make`
  - Don't use `g.echo.exe` and `;` when cross-compiling; Simply use `:`
- `gui/wxpython/Makefile` and `raster/r.colors/Makefile`
  - Don't try to execute cross-compiled modules.

**Comment by HuidaeCho** [comment]
I tested this PR for the past 3 days in daily cron. It's been successfully building daily builds for x86_64-pc-linux-gnu and x86_64-w64-mingw32.

**Pull request merged**
