### PR TITLE
r.in.poly: do not try to use stdin as input

### PR DESCRIPTION
**Pull request by infrastation**

### CODE REVIEW

**Comment by neteler** [comment]
fixes #1420

**Comment by metzm** [comment]
A better solution would be to write stdin input to a temp file, then open this temp file and proceed as before. See `v.in.ascii` as an example.

**Comment by infrastation** [comment]
Thank you for making this point. When a program input explicitly presents itself as a pipe (not a file), using a temporary file to emulate the pipe goes against the principle of least surprise. This exact "workaround" in other programs in the past had unexpectedly caused me magnetic disk bottlenecks or excess SSD wear or running out of tmpfs space and breaking things. The issue becomes more apparent when the amount of data starts to be in gigabytes. Although this plugin usually processes small files, perhaps it would be better to keep as many plugins on the safe side as possible. Does it make sense?

**Comment by infrastation** [comment]
Rebased on the latest master branch.

**Comment by infrastation** [comment]
Rebased on the latest master branch.

**Pull request closed without merging**
