### PR TITLE
manual: HTML updates in lib/db and db manual pages and README files

### PR DESCRIPTION
**Pull request by neteler**
This PR provides minor HTML fixes to `lib/db/` and `db/` manual related files:

- convert several `README` to `README.md`
- update selected broken URLs
- minor HTML fixes
- partially sync `grass-mysql.html` and `grass-mesql.html` incl. section order

Extra:
- avoid `<br>` tags within `<em> .. </em>` as this will not be properly converted to Markdown

### CODE REVIEW

**Comment by echoix** [comment]
Did you use prettier (like in superlinter) to find problematic/unparsable html?

**Comment by neteler** [comment]
> Did you use prettier (like in superlinter) to find problematic/unparsable html?

For markdown, I used:

`npx prettier --print-width 80 -w ': npx prettier --print-width 80 -w README.md`

on the various `README.md` files but not on HTML.

**Comment by echoix** [comment]
In the grass-addons, I used prettier and fixed the html parsing errors a while ago, but did not apply the formatting fixes, as it was way too disruptive. But many places the hrefs without quotes were flagged, or tags not in order.

**Comment by neteler** [comment]
I tried with `npx prettier` on the four HTML files and the result is pretty ugly (broken `</pre> tags and more). So I would submit this.

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
> I tried with `npx prettier` on the four HTML files and the result is pretty ugly (broken `</pre>` tags and more). So I did not submit these changes.

I made a quick run to see if there were some parsing errors that might be problematic when converting. Take a look at the 5 files that have red lines in https://github.com/echoix/grass/actions/runs/12001379426/job/33451802353?pr=303#step:4:8310

One is an decimal character entity missing its semicolon;
one is a link that the closing tag doesn't have the slash so the closing `</em>` is unexpected;
One is a figure not having a closing italic tag, so the closing div is unexpected;
The two others it's hard to understand with the lines shown, the context isn't big enough.

**Comment by neteler** [comment]
> One is an decimal character entity missing its semicolon; one is a link that the closing tag doesn't have the slash so the closing `\</em\>` is unexpected; One is a figure not having a closing italic tag, so the closing div is unexpected; 

This test looks good and useful to me: so it is informative yet it does not modify the entire HTML code.

The identified HTML errors might be fixed along with the submission of a new superlinter HTML linting PR (in case you plan that).

> The two others it's hard to understand with the lines shown, the context isn't big enough.

Concerning one of the linting errors: 
`t.rast.extract.html`: here the `<` in the example code section will need to be converted to `&lt;` as it seems to confuse superlinter as is.

**Comment by neteler** [comment]
(addressed in #4757)

**Comment by echoix** [comment]
> > One is an decimal character entity missing its semicolon; one is a link that the closing tag doesn't have the slash so the closing `\</em\>` is unexpected; One is a figure not having a closing italic tag, so the closing div is unexpected; 
> 
> 
> 
> This test looks good and useful to me: so it is informative yet it does not modify the entire HTML code.
> 

Problem is: they do. That's what all the warnings (in gray) are. I didn't find a way to get what I wanted for grass-addons, so I ended up disabling. 



> The identified HTML errors might be fixed along with the submission of a new superlinter HTML linting PR (in case you plan that).
>

Not for now. I'm hoping they get replaced by MD.


> 
> > The two others it's hard to understand with the lines shown, the context isn't big enough.
> 
> 
> 
> Concerning one of the linting errors: 
> 
> `t.rast.extract.html`: here the `<` in the example code section will need to be converted to `&lt;` as it seems to confuse superlinter as is.
> 
> 

:)

**Review by echoix — APPROVED** [review]

**Pull request merged**
