### PR TITLE
wxGUI/history: fix execute r/r3.mapcalc module command

### LINKED ISSUE #3304: [Bug] wxGUI/history: r/r3.mapcalc module command is not parsed correctly
**Describe the bug**
`r/r3.mapcalc` module command  is not parsed correctly when is executed from the History tab (page) tree.

**To Reproduce**

1. `r.mapcalc --overwrite expression="foo = 1"` or with expression param arg with single quotes successfully executed from the wxGUI Console and reran from the history tree (`r.mapcalc --overwrite expression="foo = 1"`), print error message **Unable to parse command 'r.mapcalc --overwrite expression="foo = 1"'**.
2. `r.mapcalc --overwrite expression="foo=1"` or with expression param arg with single quotes successfully executed from wxGUI Console and reran from the history tree (`r.mapcalc --overwrite expression="foo=1"` ), invoke `r.mapcalc` **module GUI** dialog but expression param arg contains double or single quotes and run module GUI dialog fails with error message 
```
(Thu Dec 14 05:32:52 2023)                                                      
r.mapcalc --overwrite expression="foo=1"                                       
syntax error
Parse error
ERROR: parse error
```
3. `r.mapcalc --overwrite "foo = 1"` or with expression arg with single quotes successfully executed from the wxGUI Console and reran from the history tree (`r.mapcalc --overwrite "foo = 1"`), print error message **Unable to parse command 'r.mapcalc --overwrite "foo = 1"'**.
4. `r.mapcalc` without parameters and arguments successfully executed from wxGUI Console invoke `r.mapcalc` **wxGUI dialog** which write to the history tree following command `r.mapcalc --overwrite expression=foo = 1` and reran command from the history tree, print error message **Unable to parse command 'r.mapcalc --overwrite expression=foo1 = 1'**.

**Expected behavior**
`r/r3.mapcalc` module command  should be parsed correctly when is executed from the History tab (page) tree.

**System description:**

- Operating System: all
- GRASS GIS version: 8.4.dev

```
GRASS nc_basic_spm_grass7/PERMANENT:~ > python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.11.6 (main, Dec  2 2023, 19:38:08) [GCC 13.2.1 20230826]
4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
```

### PR DESCRIPTION
**Pull request by tmszi**
Fixes #3304.

### CODE REVIEW

**Comment by tmszi** [comment]
Rebase and resolve conflicts https://github.com/OSGeo/grass/commit/86a9609fc820bb9a633549c8ab4a375653c9687b

**Review by petrasovaa — CHANGES_REQUESTED** [review]
Looks like using minus causes some problems for the parsing:
```
r.mapcalc "test = a - b"
```
and then using partial parameter name like:
```
r.mapcalc expr="test = a"
```
is failing too, but that's probably harder to address.
It may be better to put the parsing function elsewhere, maybe core.utils?

**Comment by tmszi** [comment]
> r.mapcalc expr="test = a"



> Looks like using minus causes some problems for the parsing:
> 
> ```
> r.mapcalc "test = a - b"
> ```
> 
> and then using partial parameter name like:
> 
> ```
> r.mapcalc expr="test = a"
> ```
> 
> is failing too, but that's probably harder to address. It may be better to put the parsing function elsewhere, maybe core.utils?

Thanks for catching that. Fixed with https://github.com/OSGeo/grass/pull/3305/commits/c64ab82184b35285bd9e5e20581608178d2abf47.

**Review by petrasovaa — APPROVED** [review]
Works great!
The only thing is it won't parse correctly the shortened variations of 'expression' parser enables (except 'expr'), so that's a limitation I would just accept for now.

**Comment by tmszi** [comment]
> Works great! The only thing is it won't parse correctly the shortened variations of 'expression' parser enables (except 'expr'), so that's a limitation I would just accept for now.

I forgot that it is possible to use a shortened version of the `r.mapcalc` expression parameter (`e|ex|exp|expr|expre|expres|express|expressi|expressio|expression`), because I always used `expression` or `expr` param name, I fixed it with https://github.com/OSGeo/grass/pull/3305/commits/db6a00c747da8a9537ba541b3cccba6a2e5e4f71.

**Comment by petrasovaa** [comment]
> > Works great! The only thing is it won't parse correctly the shortened variations of 'expression' parser enables (except 'expr'), so that's a limitation I would just accept for now.
> 
> I forgot that it is possible to use a shortened version of the `r.mapcalc` module `expression` parameter (`e|ex|exp|expr|expre|expres|express|expressi|expressio|expression`), because I always used `expression` or `expr` param name, I fixed it with [db6a00c](https://github.com/OSGeo/grass/commit/db6a00c747da8a9537ba541b3cccba6a2e5e4f71).

I am wondering, would this be a problem in case you use something like:
```
r.mapcalc exp="test = a + e"
r.mapcalc exp="test = a + exp(5)"
```

**Comment by tmszi** [comment]
> I am wondering, would this be a problem in case you use something like:

It works as expected. However, I can add it to the func doc test.

**Pull request merged**
