### PR TITLE
libproj: fix crs modification with PROJ6+

### PR DESCRIPTION
**Pull request by metzm**
fix crs modification with PROJ6+
fix usage of over switch in [r|v].proj

### CODE REVIEW

**Comment by neteler** [comment]
Would a change also here be required?

https://github.com/OSGeo/grass/blob/53eda832018485b0d02f94755c8cca9c499c528d/general/g.region/printwindow.c#L558

**Comment by metzm** [comment]
> Would a change be necessary here as well?
> 
> https://github.com/OSGeo/grass/blob/53eda832018485b0d02f94755c8cca9c499c528d/general/g.region/printwindow.c#L558

Yes, thanks for the hint!
This "over" switch can be used to disable the default wrapping to [-180, 180] which is useful if data cover the datum border. This switch can only be used with PROJ syntax. I have no idea yet how to disable this longitude wrapping when using WKT or authority:code to construct a transformation pipeline.

**Comment by neteler** [comment]
Maybe @rouault has a hint here?

**Comment by rouault** [comment]
> I have no idea yet how to disable this longitude wrapping when using WKT or authority:code to construct a transformation pipeline.

There's no way unfortunately. If you need +over functionality, you're back to old PROJ.4 strings and their limitations

**Comment by metzm** [comment]
> > I have no idea yet how to disable this longitude wrapping when using WKT or authority:code to construct a transformation pipeline.
> 
> There's no way unfortunately. If you need +over functionality, you're back to old PROJ.4 strings and their limitations

We need the +over functionality for lines and polygons crossing the datum border. A workaround would be to get the PROJ pipeline with `projinfo -o PROJ -s ... -t ...`, insert the +over switch at the correct place and use this modified pipeline for transformation.

**Comment by rouault** [comment]
> A workaround would be to get the PROJ pipeline with `projinfo -o PROJ -s ... -t ...`, insert the +over switch at the correct place and use this modified pipeline for transformation.

Sounds good

**Comment by metzm** [comment]
> > A workaround would be to get the PROJ pipeline with `projinfo -o PROJ -s ... -t ...`, insert the +over switch at the correct place and use this modified pipeline for transformation.
> 
> Sounds good

I wonder how many users of a software package using PROJ for coordinate transformations understand PROJ pipelines and are able to insert the +over switch at the correct place. Granted that the software package allows users to provide custom PROJ pipelines.

**Pull request merged**
