### PR TITLE
v.db.join: Add exclude_columns= option

### PR DESCRIPTION
**Pull request by HuidaeCho**
This PR adds exclude_columns= option to exclude certain columns from other table (e.g., cat).

### CODE REVIEW

**Comment by HuidaeCho** [comment]
BTW, overwriting `cat` is dangerous in general. If other table is the attribute table of another vector, we should exclude `cat` automatically?

**Review by wenzeslaus — APPROVED** [review]
Looks good. I'm for merging this as is and fixing the cat column issue separately.

**Comment by landam** [comment]
@HuidaeCho Are you going to merge this PR?

**Comment by HuidaeCho** [comment]
> @HuidaeCho Are you going to merge this PR?

Yes. Doing it now. Thanks for the reminder!

**Pull request merged**
