### PR TITLE
Add GitHub Action to build, run tests, and Python static code analysis

### PR DESCRIPTION
**Pull request by wenzeslaus**
The PR includes:
* CI workflow with:
  - A build job which is not parallelized and is meant for clear & relatively fast check of compilation and building in general. (Duplicating what is running on Travis.)
  - A test job which of course needs to build, but the main focus is to run tests, so the compilation is parallelized (depending on nproc) and thus potentially less readable. This runs the whole test suite. (You need to run it locally to see the actual error, but you can see which tests are failing.)
* Static code analysis/Code quality check using Flake8 with separate tests for lib/python, gui/wxpython, scripts and temporal directories.
  - lib/python uses configuration which ignores code in testsuite directories and ignores a lot of errors.
  - The other directories use the default settings and the failure is ignored. (Neither is an ideal solution, but we can see and change it based on whatever is more advantageous for getting it fixed.)

Test job requires at least 50% success rate (using the new `--min-success` flag). There is now 45% of tests failing. Test uses nc_spm_full_v2alpha2 location from fatra.cnr.ncsu.edu for tests (that's also something to be improved).

Helper files placed to .github/workflows.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
You can see the actions running here:

https://github.com/wenzeslaus/grass/actions

**Comment by wenzeslaus** [comment]
The checks/actions/workflows/jobs execute on each PR and commit.

**Comment by landam** [comment]
@wenzeslaus Any idea what to do with

```

Run cd scripts
./v.db.droprow/v.db.droprow.py:18:1: E265 block comment should start with '# '
#%module
^
```
?

See eg. https://github.com/wenzeslaus/grass/runs/598192172?check_suite_focus=true

**Comment by wenzeslaus** [comment]
> @wenzeslaus Any idea what to do with ...`E265 block comment should start with '# '`?

Yes, the parser should be modified to allow for `# %` besides `#%` and the comments should be changed. I checked the code quickly in the past and I didn't see any apparent issues with that.

An alternative, basically [what you had to do so far](https://github.com/wenzeslaus/r.example.plus/blob/master/.github/workflows/linting.yml#L25), is to ignore the warning. However, why to break an [explicit guideline form PEP8](https://www.python.org/dev/peps/pep-0008/#block-comments)?

**Comment by neteler** [comment]
Just to say: this is really cool!!

**Pull request merged**
