### PR TITLE
v.db.join: Use case insensitive comparison for columns

### PR DESCRIPTION
**Pull request by wenzeslaus**
Since SQL is case insensitive, adding a new column to a table needs to use case insensitive
comparison with the existing columns.

Additionally, use fully qualified map name to get the 'found in more than one mapset' message
only once.

### CODE REVIEW

**Review by ninsbl — APPROVED** [review]
This is a valid workaround. I still think a more thorough fix would be to use quoted idetifiers (see [Trac 3071](https://trac.osgeo.org/grass/ticket/3071)). Instead of using backend dependent quoting, standard SQL compliant double quotes could be used. That would laso solve quite common issues with keywords, f.ex.. But that is a different issue and would have to be applied all over the place. One may start with modules like this however...

**Comment by wenzeslaus** [comment]
> This is a valid workaround.

I think it is _the solution_ within the current logic, or am I missing something?

> I still think a more thorough fix would be to use quoted idetifiers (see [Trac 3071](https://trac.osgeo.org/grass/ticket/3071)).

Some users might be surprised by the need to exactly type the case of column name in some contexts (parameter is column name) while in some others you would still be free to do whatever you want (parameters like where). However, I think I would be for this change anyway.

**Comment by wenzeslaus** [comment]
> This is a valid workaround. I still think a more thorough fix would be to use quoted idetifiers (see [Trac 3071](https://trac.osgeo.org/grass/ticket/3071)). Instead of using backend dependent quoting, standard SQL compliant double quotes could be used. That would laso solve quite common issues with keywords, f.ex.. But that is a different issue and would have to be applied all over the place. One may start with modules like this however...

Perhaps a CS/CE oriented GSoC topic? Do you want to add the idea to the list?

**Comment by nilason** [comment]
Shall this be backported to 7.8.6?

**Comment by landam** [comment]
> Yes, done so

Thanks! :-)

**Pull request merged**
