### PR TITLE
refactor: display driver in r_raster.c fixing duplicateExpression warning

### PR DESCRIPTION
**Pull request by Sharansrj567**
This pull request addresses a duplicateExpression warning identified by cppcheck in the lib/display/r_raster.c file related to the use of Cairo_Driver. The modifications aim to improve code clarity by refactoring redundant conditions in the Cairo_Driver logic.

**Reasons:**
- **Redundancy:** The same function (Cairo_Driver()) is called in both the true and false branches of the conditional operator (? :), making the conditional check unnecessary.
- **Code Readability:** The structure of the code might be confusing due to the extra conditional check.

**Context:**
These lines have not been touched for 16 years, and the conditional compilation includes or excludes Cairo_Driver() based on the availability of Cairo during GRASS build. If Cairo is available, it serves as the fallback driver; otherwise, the PNG driver is used.

**Testing:**
Manual testing has been performed to ensure that the behavior of the Cairo_Driver function remains unchanged. The modified code has undergone style checks using clang-format to maintain standard formatting.

### CODE REVIEW

**Comment by echoix** [comment]
Unless other commits are hidden, blaming these lines show that it has been 16 years since these lines were touched.


For some GRASS reviewer:
Just to make sure about the current and future behavior:
- Before: there is a conditional compilation directive to include or not `Cairo_Driver()` in a chain of ifs that choose a driver for the `drv` command. If GRASS is built with Cairo, Cairo is the fallback driver, or else it is the PNG driver. 
- After: the `Cairo_Driver()` is the fallback driver if GRASS is configured to build with Cairo, in the other case, we use PNG driver.

So that means that the PNG is always available when building, am I right? (There isn't any way to configure without png).

**Comment by nilason** [comment]
I believe the logic of the code is correct as it is. It depends on the value of the environmental variable `GRASS_RENDER_IMMEDIATE` (see [Display drivers](https://grass.osgeo.org/grass83/manuals/displaydrivers.html)). It may be eg: `default` which leads to using Cairo if available. If Cairo is not available, it will default to `PNG_Driver`.

[Cairo DISPLAY DRIVER](https://grass.osgeo.org/grass83/manuals/cairodriver.html):
> The Cairo driver is used for GRASS display commands by default if available, otherwise [PNG driver](https://grass.osgeo.org/grass83/manuals/pngdriver.html) is used.

This case seems to me to be a false positive.

**Comment by nilason** [comment]
> I believe the logic of the code is correct as it is. It depends on the value of the environmental variable `GRASS_RENDER_IMMEDIATE` (see [Display drivers](https://grass.osgeo.org/grass83/manuals/displaydrivers.html)). It may be eg: `default` which leads to using Cairo if available. If Cairo is not available, it will default to `PNG_Driver`.
> 
> [Cairo DISPLAY DRIVER](https://grass.osgeo.org/grass83/manuals/cairodriver.html):
> 
> > The Cairo driver is used for GRASS display commands by default if available, otherwise [PNG driver](https://grass.osgeo.org/grass83/manuals/pngdriver.html) is used.
> 
> This case seems to me to be a false positive.

Scratch that. This is the end-result of this PR too. The only difference is that now it is clearer that the code should expect a value `cairo`.

**Review by nilason — APPROVED** [review]

**Comment by nilason** [comment]
@Sharansrj567 Thanks for your contribution!

**Pull request merged**
