### PR TITLE
fix: remove unused wxwidgets compilation configuration option

### PR DESCRIPTION
**Pull request by sisco0**
The configuration option wxwidget has been removed

Refs: #2578

### CODE REVIEW

**Comment by nilason** [comment]
This looks fine by me. `--with-wxwidgets` is indeed a dead-end configure option.

Just a small note: no need to change the `macosx/ReadMe.md` file at this point, it is in all totally outdated (as noted at the top of the file).

Thanks @sisco0 !

**Comment by ojwb** [comment]
I reported #2578 and @sisco0 asked me to check this patch works as expected, and it does.  Thanks.

I did a quick grep in the tree to look for lingering references and I wonder if these can be removed too:

```
diff --git a/.github/workflows/osgeo4w.yml b/.github/workflows/osgeo4w.yml
index e645585d..4db5f0da 100644
--- a/.github/workflows/osgeo4w.yml
+++ b/.github/workflows/osgeo4w.yml
@@ -39,7 +39,7 @@ jobs:
           $exe = 'osgeo4w-setup.exe'
           $url = 'http://download.osgeo.org/osgeo4w/v2/' + $exe
           (New-Object System.Net.WebClient).DownloadFile($url, $exe)
-          Start-Process ('.\'+$exe) -ArgumentList '-A -g -k -q -s http://download.osgeo.org/osgeo4w/v2/ -P proj-devel,gdal-devel,geos-devel,libtiff-devel,libpng-devel,pdal-devel,netcdf-devel,cairo-devel,fftw,freetype-devel,gdal-ecw,gdal-mrsid,liblas-devel,libxdr,libpq-devel,pdcurses,python3-matplotlib,python3-numpy,python3-ply,python3-pywin32,python3-six,python3-wxpython,regex-devel,wxwidgets-devel,zstd-devel' -Wait
+          Start-Process ('.\'+$exe) -ArgumentList '-A -g -k -q -s http://download.osgeo.org/osgeo4w/v2/ -P proj-devel,gdal-devel,geos-devel,libtiff-devel,libpng-devel,pdal-devel,netcdf-devel,cairo-devel,fftw,freetype-devel,gdal-ecw,gdal-mrsid,liblas-devel,libxdr,libpq-devel,pdcurses,python3-matplotlib,python3-numpy,python3-ply,python3-pywin32,python3-six,python3-wxpython,regex-devel,zstd-devel' -Wait
 
       - name: Compile GRASS GIS
         run: D:\msys64\usr\bin\bash.exe -l (''+(Get-Location)+'\.github\workflows\build_osgeo4w.sh') (Get-Location)
diff --git a/.travis/linux.install.sh b/.travis/linux.install.sh
index 64022804..ffdbebcb 100755
--- a/.travis/linux.install.sh
+++ b/.travis/linux.install.sh
@@ -26,7 +26,6 @@ sudo apt-get install --no-install-recommends \
         libreadline-dev \
         libsqlite3-dev \
         libtiff-dev \
-        libwxgtk3.0-gtk3-dev \
         libxmu-dev \
         libzstd-dev \
         python3 \
diff --git a/Vagrantfile b/Vagrantfile
index 0a47b641..16499ba3 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -63,7 +63,6 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
       "proj-bin",
       "libreadline-dev",
       "libsqlite3-dev",
-      "libwxgtk3.0-gtk3-dev",
       "libxmu-dev",
       "python3",
       "python3-wxgtk4.0",
```

First hunk is dropping `wxwidgets-devel`, which I'm less sure about as I'm not familiar with whatever package system that is.

I'm much more confident about the `libwxgtk3.0-gtk3-dev` dependencies as I co-maintain those packages in Debian.

**Comment by sisco0** [comment]
The recommendations given by @ojwb have been considered and the PR has been moved to Review state.

**Review by nilason — APPROVED** [review]
Thanks!

Regarding the macos/ReadMe.md file, I'd prefer to keep its history untouched. Apart from being converted from rtf to md format, it's content was last modified in 2009! Rather a historical document, waiting for a major rewrite...

**Review by neteler — APPROVED** [review]
Locally compiled with success, GUI works as expected.

I'd suggest to backport it to G8.2

**Comment by sisco0** [comment]
> Thanks!
> 
> Regarding the macos/ReadMe.md file, I'd prefer to keep its history untouched. Apart from being converted from rtf to md format, it's content was last modified in 2009! Rather a historical document, waiting for a major rewrite...

I got to provide with a last commit, which currently reverts the changes under the `macos` folder. Could you kindly take a look and see if it matches the expectations? **Have a great day!**

**Comment by nilason** [comment]
Merged and backported to 8.2.
Thank you @sisco0 !

**Pull request merged**
