### PR TITLE
i18n: fix duplicate messsages in po files

### PR DESCRIPTION
**Pull request by neteler**
This PR deduplicates the message files (currently the compilation is broken), apparently introduced in #4710 .

~~I used the following command (inspired by @HuidaeCho in https://github.com/OSGeo/grass/pull/1396#issuecomment-782987864):~~

Edit: keeping the commented cruft in the PO files:

```
for i in $(ls grass*.po); do
    msguniq --use-first ${i} > $i.tmp
    rm -f ${i}
    mv $i.tmp ${i}
done
```

### CODE REVIEW

**Comment by echoix** [comment]
It seems a lot of deletions (40k vs 20 (unit) ish additions). Has a spot check been made to be sure we aren't losing too much work?

**Comment by neteler** [comment]
Only comments have been removed. Again, I am following @HuidaeCho's advice (see reference above).

**Comment by echoix** [comment]
Would a full collection of new strings be appropriate? We never got it updated since I worked on fixing the python strings that formatted before calling gettext (INT003 and all)

**Comment by neteler** [comment]
Yes, but probably in a new PR. 
The related server cronjobs are broken at time which I would like to see running again asap.

**Comment by neteler** [comment]
While I don't fully agree I have now reverted it and only deduplicated in 7e596dc33bacdd185a71f802880a15d72f78d425 to speed up merging of this PR.

@echoix please review.

**Review by echoix — APPROVED** [review]
I checked them all. There were the two duplicates in russian, that have different translations, and there is in spanish and italian that the strings aren't translated to the same contents, but for spanish for example, that same string is also for 2 other source strings, and only one is fuzzy.

So, its fine for me to potentially degrade 2-6 strings for all languages.

**Comment by neteler** [comment]
Thanks for the thorough review!

**Comment by echoix** [comment]
You disabled auto-merge?

**Comment by neteler** [comment]
I accidentally activated it, the deactivated it again since it will not run due to the current Travis CI bug.

**Comment by neteler** [comment]
This PR deduplicates the message files (currently the compilation is broken, apparently introduced in #4710), using

```
for i in $(ls grass*.po); do
    msguniq --use-first ${i} > $i.tmp
    rm -f ${i}
    mv $i.tmp ${i}
done
```

**Pull request merged**
