### PR TITLE
limit viewshed horizontally by specifying two angles

### PR DESCRIPTION
**Pull request by petrasovaa**

### CODE REVIEW

**Comment by petrasovaa** [comment]
Can't get to trac right now, so commenting here. This is already updated patch from what is here: https://trac.osgeo.org/grass/ticket/3926
so it should work, I tested it.

**Comment by metzm** [comment]
I can confirm, it works fine.
Just one comment: the code uses atan2() which is costly (takes computational time). Can you build in a test if the limitation is really needed? If not, don't even test, avoiding atan2(). Something like
`if (abs(minAngle - maxAngle) != 360) ...`

**Comment by petrasovaa** [comment]
Right. To avoid any float comparison, it's checked outside depending if user requested the direction limit.

**Comment by metzm** [comment]
Looks good to me, ready to be merged.

**Pull request merged**
